### ISSUE TITLE
Error in PIP.

### ISSUE THREAD

**Issue by filipemd** [hydralauncher/hydra#100]
```
ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
ERROR: No matching distribution found for libtorrent
```

Using Intel MacOS Sonoma.

**Comment by zamitto** [comment]
are you using Python 3.9 as stated by the README file?

**Comment by hydralauncher** [comment]
Which Python version you on?

**Comment by filipemd** [comment]
I'm using Python 3.12.

**Comment by brunog2** [comment]
Same here. Any updates?

**Comment by zamitto** [comment]
Please, try with Python 3.9, as specified in the README

**Comment by filipemd** [comment]
How do I install Python 3.9?

**Comment by brunog2** [comment]
I can confirm that installing Python 3.9 solves the problem.

**Comment by zamitto** [comment]
I'm closing the issue as @brunog2 confirmed the solution, if you have any problems even after installing Python 3.9 @filipemd, feel free to open it again
