### ISSUE TITLE
[BUG] Portuguese in friends tab

### ISSUE THREAD

**Issue by steeepaaaan** [hydralauncher/hydra#1002]
### Describe the bug

Portuguese in friends tab

### Steps to Reproduce

1.click friends button
1.Portuguese next to friend code

### Expected behavior

translate it

### Additional information and data

![Snímek obrazovky 2024-09-21 181600](https://github.com/user-attachments/assets/cd739050-12ea-46dd-ad92-f5b4505f06d8)

### Operating System

windows 11 

### Hydra Version

2.1.6

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by dogemanttv** [comment]
+1

**Comment by zamitto** [comment]
Thanks! 
The translated text will be available on 2.1.7
