### ISSUE TITLE
. JSON download URL's

### ISSUE THREAD

**Issue by BOBLO123** [hydralauncher/hydra#1003]
can someone please give me a list of download urls for hydra, no matter how many times i re-install or use a dif version of hydra, it only ever give me 0xEMPRESS and KaOsKrew download urls, and i dont know how to make a .json download url. can someone please help

**Comment by KratozZ12** [comment]
https://hydralinks.cloud

**Comment by BOBLO123** [comment]
thank you

**Comment by kaioznny** [comment]
pq n consigo usar url json?

**Comment by KratozZ12** [comment]
a que te refieres ? @kaioznny

**Comment by kaioznny** [comment]
o codigo n funciona

**Comment by KratozZ12** [comment]
como estas usando el codigo ? (https://raw.githubusercontent.com/KekitU/rutracker-hydra-links/main/all_categories.json)

**Comment by SnUsOeDoW** [comment]
https://hydralinks.cloud/sources/tinyrepacks.json
https://hydralinks.cloud/sources/kaoskrew.json
https://hydralinks.cloud/sources/fitgirl.json
https://hydralinks.cloud/sources/empress.json
https://hydralinks.cloud/sources/dodi.json
https://hydralinks.cloud/sources/atop-games.json
https://hydralinks.cloud/sources/steamrip.json
https://hydralinks.cloud/sources/gog.json
https://hydralinks.cloud/sources/onlinefix.json
https://hydralinks.cloud/sources/xatab.json
https://raw.githubusercontent.com/KekitU/rutracker-hydra-links/main/all_categories.json
