### ISSUE TITLE
[BUG] Visual artifacts when GPU acceleration is on

### ISSUE THREAD

**Issue by lockieluke** [hydralauncher/hydra#1004]
### Describe the bug

![{CE89DFDA-B0CF-4967-AFE1-FFE9497FF4CB}](https://github.com/user-attachments/assets/4ba6b76c-ede6-49ac-9569-f38fc913d8c3)

### Steps to Reproduce

1. Launch Hydra on Windows 11

### Expected behavior

No visual artifacts when GPU acceleration is explicitly turned off by flag `--disable-gpu`

### Additional information and data

[info.txt](https://github.com/user-attachments/files/17086031/info.txt)

### Operating System

Windows 11

### Hydra Version

v2.1.6

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by lockieluke** [comment]
I tried changing graphics settings and make Hydra use my iGPU(7800x3D) instead of the 4080 Super and the visual artifacts are no longer present

**Comment by mikeydoom** [comment]
Are you using the latest Nvidia drivers?

**Comment by lockieluke** [comment]
Yes, I just reinstalled Windows and that fixed it, I think Rectify11 broke my installation
