### ISSUE TITLE
No download available

### ISSUE THREAD

**Issue by vektiscc** [hydralauncher/hydra#1006]
Most of the games in my catalog have a “No download available” line, that’s how it should be, and no one has found a repack for such games or do I have some kind of problem? I’m just not sure that it was difficult to find repacks for example cs:source or cs1.6

Or, for example, GoW Ragnarok, repacks of this game are already available on the Internet. I see that on the page in the Hydra application there is a counter of active players and downloads, and they are clearly bigger than zero, but I still do not have any repacks available in the app

![image](https://github.com/user-attachments/assets/52d27cb8-6f4d-49fd-8ebe-e6e3045d1d5c)

**Comment by mikeydoom** [comment]
Add all the sources from here 

https://hydralinks.cloud/
