### ISSUE TITLE
[BUG] Não esta contabilizando o tempo de game 

### ISSUE THREAD

**Issue by Pudk** [hydralauncher/hydra#1007]
### Describe the bug

Se eu baixo o game pel opropio hydra e coloco ele pra ser executavel ele conta o tempo de game normalmente, porem se eu baixo por fora e coloco o executavel no hydra ele não calcula o tempo de game
![imagem_2024-09-22_133340989](https://github.com/user-attachments/assets/0c644065-39f9-4250-af6e-d068c03ec97a)

### Steps to Reproduce

Estou bem longe no game e n contabilizou nada kkk

### Additional information and data

![imagem_2024-09-22_133952767](https://github.com/user-attachments/assets/92e18774-579e-4615-8a6f-0f928e44f77d)

### Operating System

windows

### Hydra Version

2.1.6

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by Pudk** [comment]
Acabei de baixar a versão 2.1.7 e quando fui iniciar o game esta contabilizando normalmente ou seja acho q arrumado ? mesmo não intencionalmente kkkk

**Comment by JackEnx** [comment]
the time count depends on the selected .excel of the game, if you choose the .exe of the launcher the time is not counted.
