### ISSUE TITLE
Install Hydra-1.1.0.Setup.exe on win7

### ISSUE THREAD

**Issue by josev-marques** [hydralauncher/hydra#101]
I downloaded the .exe file onto my notebook and encountered this error shown in the image. I haven't found a solution online. Is the launcher compatible with Windows 7? Is there anything I can do to install the launcher?

![hydra error](https://github.com/hydralauncher/hydra/assets/65729149/aac2bcb4-d0fb-4f4b-b5d6-85a530f3d6f4)

The image says:

Hydra.exe - Entry Point Not Found
The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll.

**Comment by FabioZumbi12** [comment]
Vi que vc é br... tentou os procedimentos desse video? 
https://www.youtube.com/watch?v=BWBWAYdcX2U

**Comment by zamitto** [comment]
Hydra requires Windows 10 at least.

**Comment by Martimsleite23** [comment]
![Captura de Ecrã (122)](https://github.com/hydralauncher/hydra/assets/171244473/124b9c55-9bb1-496f-a696-9eb3c1dc86c0)
 oq faço
