### ISSUE TITLE
[BUG] Write a title for your bug

### ISSUE THREAD

**Issue by PhaelRD** [hydralauncher/hydra#1010]
### Describe the bug

Pagina inicial e de login se encontram vazias

### Steps to Reproduce

Entrar na pagina de inicio ou tentar fazer login

### Additional information and data

**CAPTURAS**

![Captura de tela 2024-09-22 184126](https://github.com/user-attachments/assets/6d6b90da-474a-446d-8681-50d7642b32c5)
![Captura de tela 2024-09-22 184215](https://github.com/user-attachments/assets/156b7263-115a-4698-819c-75791c4147e1)

**LOGS**

[info.txt](https://github.com/user-attachments/files/17091384/info.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17091385/pythoninstance.txt)
[error.txt](https://github.com/user-attachments/files/17091386/error.txt)

### Operating System

Windows 11

### Hydra Version

2.1.6

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Could you update to 2.1.7 and test it again?

By the way, do you use TIM as your internet provider in Brazil?

**Comment by PhaelRD** [comment]
> Could you update to 2.1.7 and test it again?
It's working normally now
> By the way, do you use TIM as your internet provider in Brazil?
Yes, I use Tim as a provider

**Comment by zamitto** [comment]
> > Could you update to 2.1.7 and test it again?
> It's working normally now
> 
> 
> > By the way, do you use TIM as your internet provider in Brazil?
> Yes, I use Tim as a provider
> 
> 

Yeah, for some reason TIM was blocking connection to our backend

**Comment by zamitto** [comment]
Could you send screenshots?

**Comment by PhaelRD** [comment]
> Você poderia enviar capturas de tela?
simply when I click on enter the captcha unchecks it and does not enter the account
![Captura de tela 2024-09-25 142410](https://github.com/user-attachments/assets/10b3d318-c026-4ff8-958e-095cb2351c4b)
![Captura de tela 2024-09-25 142422](https://github.com/user-attachments/assets/7ea3508f-5be9-4364-b6c1-fda0366f336b)

**Comment by PhaelRD** [comment]
> @PhaelRD, você tem certeza de que seu nome de usuário foi digitado exatamente assim? Ele diferencia maiúsculas de minúsculas

I have, I tried to create another account too and I couldn't log in

**Comment by zamitto** [comment]
> > @PhaelRD, você tem certeza de que seu nome de usuário foi digitado exatamente assim? Ele diferencia maiúsculas de minúsculas
> 
> I have, I tried to create another account too and I couldn't log in

I just checked the database, your username is "phael" (all lowercase).

But did you got any errors while trying to create a new account?

**Comment by PhaelRD** [comment]
> > > @PhaelRD, você tem certeza de que seu nome de usuário foi digitado exatamente assim? Ele diferencia maiúsculas de minúsculas
> > 
> > 
> > Eu tenho, tentei criar outra conta também e não consegui logar
> 
> Acabei de verificar o banco de dados, seu nome de usuário é "phael" (tudo em letras minúsculas).
> 
> Mas você encontrou algum erro ao tentar criar uma nova conta?

Even using lowercase letters I can't log in, I created a new account with "Phael" as the username and I couldn't log in either.

**Comment by PhaelRD** [comment]
fixed
