### ISSUE TITLE
hidra nao mostra nenhum game para baixar

### ISSUE THREAD

**Issue by jothathedark** [hydralauncher/hydra#1013]
### Describe the bug

desde que eu baixei a versao 2.1.5 o hidra nao mostra nada e fica sem nenhuma opção de jogos nem nada sequer, e tbm não adianta tentar colocar os URLs, eu copio no hidra e clico para validar, mas de nada acontece, não faço ideia do que possa ser.

### Steps to Reproduce

1. executo hidra como administrador
2. hidra inicia em branco sem qualquer tipo de opção de donwload

### Additional information and data

.

### Operating System

windows 10

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
@jothathedark,
1) Close Hydra
2) Delete hydra.db, located at "%appdata%/hydra"
3) Open Hydra and add your links again
