### ISSUE TITLE
[BUG] HowlongtoBeat not working

### ISSUE THREAD

**Issue by Sarthak-Saini265** [hydralauncher/hydra#1014]
### Describe the bug

I cannot see Howlongtobeat stats on any game, whenever I open a game page it shows it briefly but then it goes away. I have enabled app access through the Firewall too.
OS: Windows 11

### Steps to Reproduce

1. Open any game
2. You just see the system requirements and stats

### Additional information and data

![ss](https://github.com/user-attachments/assets/8c75001d-14ca-4570-b2c0-4f569c71c975)

### Operating System

Windows 11

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
HLTB removed the integration we used to get their information. So we removed it from our UI, at least for now

**Comment by zamitto** [comment]
HLTB will be working again on next release
