### ISSUE TITLE
[URGENT] telegram atualizou suas políticas de privacidade, o aplicativo não é mais seguro para comunicação de pessoas e usuários envolvidos nesse projeto. Telegram updated their privacy policy, the app isn't more secure for users and developers of this project.

### ISSUE THREAD

**Issue by MrDraxs** [hydralauncher/hydra#1016]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/38ab3de5-b9f2-4dd5-8b3f-e53169a28dd6)
https://telegram.org/privacy/br
https://www.youtube.com/embed/cOIaEa7dhoU

### Describe the solution you'd like

mude o applicativo usado para comunicação.

Change the app used for communication.

### Describe alternatives you've considered

prefereables(descentalized)
https://www.0xchat.com/ (end to end encryption)
https://simplex.chat/ (end to end encryption)
https://matrix.org/ (end to end encryption)
not preferables(centralized)
https://signal.org/ (end to end encryption)

**Comment by pedropinto0** [comment]
eu gosto de camarão

**Comment by NameLord** [comment]
> 😐 Sensacionalismo midiático, já que sempre esteve nos termos de uso do Telegram a possibilidade de informar para autoridades o número de telefone e IP mediante ordem judicial.
> 
> 😐 Media sensationalism, since it’s always been in Telegram’s terms of service that they can provide phone numbers and IP addresses to authorities with a court order.

This is because of scammers using telegram to talk. from Nigeria/India/Pakistan and so on...
