### ISSUE TITLE
[BUG] Нет доступных загрузок

### ISSUE THREAD

**Issue by DEVxKIS** [hydralauncher/hydra#1018]
### Describe the bug

Только что установил лаунчер, но не одну игру невозможно скачать по причине "Нет Доступных Загрузок"
Скриншот прикладываю

### Steps to Reproduce

1 Установить Лаунчер  (Последняя версия на сегодняшнюю дату)
2 открыть каталог
3 увидеть "нет доступных загрузок"

### Additional information and data

![image](https://github.com/user-attachments/assets/2294cf47-a320-4bed-9376-2c9a8cfa490e)

### Operating System

WIn 10

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
You need to add your own sources of download.
If you need help finding them, you can join the community discord server. They have a russian chat so you can ask for help there (https://discord.gg/hydralaunchercommunity)

**Comment by H0pZik** [comment]
в настройках надо открыть источники загрузки и добавить ссылки от сюда https://hydralinks.cloud/

**Comment by SkAAAtS** [comment]
> в настройках надо открыть источники загрузки и добавить ссылки от сюда https://hydralinks.cloud/
А что если я копирую, вставляю в лаунчере, а он никак не реагирует? Я даже не могу прожать проверить

**Comment by SkAAAtS** [comment]
> > в настройках надо открыть источники загрузки и добавить ссылки от сюда https://hydralinks.cloud/
> > А что если я копирую, вставляю в лаунчере, а он никак не реагирует? Я даже не могу прожать проверить
Анекдот, но вечером всё заработало, я ничего не делал

**Comment by 0shuri** [comment]
Sorry, I don't know English, so I'll write through a translator. I have a problem with the game Horizon Zero Dawn. I downloaded it from Hydra Launcher. I tried to download all versions from each repack but to no avail. The game gives the message "Critical error", I tried all the methods that were on Russian YouTube, and also to no avail. I use Hydra Launcher on version 3.0.8 I think. Help me please...
![IMG_20250114_095205](https://github.com/user-attachments/assets/567cb4ef-03df-4b61-888f-ac5df5ef4bad)
![Screenshot_2025-01-14-09-54-33-422_com google android googlequicksearchbox](https://github.com/user-attachments/assets/101d6443-9d00-4024-8e41-4853c8612a83)

**Comment by Duxloqpoc** [comment]
Здравствуйте всем я хотел бы узнать почему нет загрузок на некоторые игры,но при этом ссылки с hydralinks все добавлены.

**Comment by ZefIrPlay** [comment]
А что делать если для программ нет источников загрузок, а для игр есть в Гидре?

**Comment by egor832f** [comment]
а что делать если при нажатии проверить ничего не происходить

**Comment by kex1tu** [comment]
> а что делать если при нажатии проверить ничего не происходить

перезапусти или подожди, у меня сработало, мб двойной клик на проверить тоже поможет
