### ISSUE TITLE
Скачивание с маленькой скоростью

### ISSUE THREAD

**Issue by ksen1xdrink** [hydralauncher/hydra#1019]
### Describe the bug

Качает с разной но маленькой скоростью как и на старых, так и на новых версиях, от 30 килобайт и максимум до 1.8 мегабайт 

### Steps to Reproduce

.

### Expected behavior

Помогите пожалуйста с ошибкой

### Additional information and data

.

### Operating System

Windows 11

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by BonBuason** [comment]
maybe you have a slow SSD ?

**Comment by ksen1xdrink** [comment]
No

**Comment by BonBuason** [comment]
then maybe there is not enough seed

**Comment by JackEnx** [comment]
The download speed depends entirely on the file you are downloading.
