### ISSUE TITLE
Does not open games blocked in the region

### ISSUE THREAD

**Issue by galpspan** [hydralauncher/hydra#102]
I live in a region where titanfall 2, fallout 4, helldivers, borderlands, etc are blocked.

And when trying to open these games in the launcher it just returns to the window back.

**Comment by gabriel7419** [comment]
Have you tried to disconnect your computer from the internet before launching the game?
You can also try to use a VPN and connect to another country to try to bypass the blockade.

**Comment by galpspan** [comment]
> You can also try to use a VPN and connect to another country to try to bypass the blockade.

I can open games with vpn, I hope to be able to open games without regional difficulties later on

**Comment by Niximkk** [comment]
not an hydra issue i guess

**Comment by hydralauncher** [comment]
Not an Hydra issue at all. Closing this.
