### ISSUE TITLE
[BUG] import button does not work in hydra launcher

### ISSUE THREAD

**Issue by DollinXD** [hydralauncher/hydra#1022]
### Describe the bug

I'm trying to add a download source for the hydra launcher, but when I put the link to the valid .json file, and click on import, nothing happens

### Steps to Reproduce

1. Settings
2. Download Sources
3. add source
4. put the link and verify
5. import does not work

### Expected behavior

The download source imported

### Additional information and data

![image](https://github.com/user-attachments/assets/211fd06d-0a1f-4d09-8f8f-9d240c72adb7)

[hydra.zip](https://github.com/user-attachments/files/17148138/hydra.zip)

### Operating System

Windows 10

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Quick fix:

1. Close Hydra
2. Delete hydra.db, located at "%appdata%/hydra"
3. Open Hydra again
4. Adds your sources

**Comment by DollinXD** [comment]
tks bro
