### ISSUE TITLE
[BUG] Window Side Decorations are on by default.

### ISSUE THREAD

**Issue by sabbateus** [hydralauncher/hydra#1023]
### Describe the bug

Window Side Decorations are on by default on version 2.1.1 and higher. As far as I know there is no way to turn them off.

### Steps to Reproduce

Launch any version of hydra-launcher higher than 2.0.9.

### Expected behavior

Setting or --flag to turn them on/off on Windows/Linux.

### Additional information and data

I am using .AppImage for now, since AUR is out-of-date.
https://aur.archlinux.org/packages/hydra-launcher-bin

### Operating System

CachyOS | Hyprland

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Could you upload a screenshot for more context?

**Comment by sabbateus** [comment]
Sure. Here are some screenshots.
As you can see, on the v.2.0.3 window decorations were off by default. So I had no problems with them.
But starting with v.2.1.1 everything changed, including the main font and window decorations.
I guess there is a way to support user-based setting or --flag to turn them off.
![2 0 3](https://github.com/user-attachments/assets/7c9bc7e2-e909-438e-aeb7-e3fcef084a71)
![2 1 1](https://github.com/user-attachments/assets/db98b5c6-d4bd-4e3b-9445-811575733f08)

**Comment by sabbateus** [comment]
Fixed on version 3.0.2.

Closing this issue
