### ISSUE TITLE
[BUG] traduzir jogo

### ISSUE THREAD

**Issue by felipemartins346** [hydralauncher/hydra#1038]
### Describe the bug

Traduzir NEXT ORDER, todos os arquivos abrem com codificação estranha

### Steps to Reproduce

Acessar pasta do jogo > caminho até onde está o idioma > abrir com bloco de notas > todo codificado

### Expected behavior

Arquivo todos estão com codificação

### Additional information and data

![image](https://github.com/user-attachments/assets/6d3cd237-d8bd-4c95-89df-a9246cdddb00)

### Operating System

Win11

### Hydra Version

Ultima

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
As stated when opening a new issue, we don't provide any support regarding the games you download.
You can look for help in the discord server managed by the community: https://discord.gg/hydralaunchercommunity
