### ISSUE TITLE
[BUG] I AM FREAKING TRYING TO UPDATE THE FREAKING LAUNCHER BUT I FREAKING CANT!!

### ISSUE THREAD

**Issue by Blazindude365** [hydralauncher/hydra#1041]
### Describe the bug

when i was trying to intall v2.1.7, IN THE FFREAKING MIDDLE OF THE DOWNLOAD BAR, AN FREAKING ERROR APPEARED AND OH BOY, DID I JUST GOT SCAMMED!?

### Steps to Reproduce

1. go to hydra ( make sure that the version of the launcher is older than v2.1.7 )
2. click on play on any game
3.  update to v2.1.7

### Expected behavior

i want to play zeepkist but i cant

### Additional information and data

i dont have any more iformation about the bug

### Operating System

windows 11

### Hydra Version

older than v2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by NameLord** [comment]
What the freaking way is happening here ? need more info.
