### ISSUE TITLE
[BUG] Real Debrid api token

### ISSUE THREAD

**Issue by darkjezza** [hydralauncher/hydra#1042]
### Describe the bug

the api token is not working

### Steps to Reproduce

copy the api token into box click save get a error

### Expected behavior

should save and no error

### Additional information and data

![Screenshot 2024-10-06 012042](https://github.com/user-attachments/assets/5c9838e2-0ed8-4b1d-b11b-085af9c535f6)

### Operating System

windows 11

### Hydra Version

v2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by darkjezza** [comment]
i put the real debrid token in the database but i think real debrid is broken atm games are not downloading

**Comment by JackEnx** [comment]
Sorry for the delay, could you please let me know if the problem persists?

**Comment by darkjezza** [comment]
> Sorry for the delay, could you please let me know if the problem persists?

problem still there

**Comment by JackEnx** [comment]
the logs report that the token provided is not valid, we have not had other people reporting anything similar, how did you obtain your token?

**Comment by darkjezza** [comment]
https://real-debrid.com/apitoken

**Comment by darkjezza** [comment]
i can confirm its working now

**Comment by PeterKevyn** [comment]
![Image](https://github.com/user-attachments/assets/c0181fac-ac19-4de2-bbf5-719f1c3c3c6e)

Ola estou com problema para ativar o token do Real-Debrid, ja estou tentando faz um tempo, uso o sistema linux Zorin os, estou com o hrydra na versão 3.2.3, instalado com o AppImage. No inicio a chave salvou, mas quando fui fazer download ele não iniciou, tentei mudar o token, mas sempre aparece a mensagem de api invalido, e quando reinicio o Hydra sempre retorna para o primeiro api que coloquei, por favor peço ajuda.
