### ISSUE TITLE
This has a Trojan.Malpack. Do not download!!!

### ISSUE THREAD

**Issue by Aagi19** [hydralauncher/hydra#1045]
### Describe the bug

Downloaded this from GitHub yesterday and immediately after installing someone from Brazil hacked into my account. When I scanned vor viruses it said I had a Trojan.Malpack

### Steps to Reproduce

Just downloading and installing 

### Additional information and data

Already given all the info, don't have any screenshots.

### Operating System

Windows 11

### Hydra Version

v2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Hydra exists since around March 2024.
No one has been infected from running Hydra
all the code is open source here, lots of people have checked and confirmed it is safe.

If you really got hacked, I hope you recover your accounts, but it wasn't because of Hydra

**Comment by thegrannychaseroperation** [comment]
> Enters on Hydra's GitHub containing the whole source code behind the software
> "Downloaded this from GitHub yesterday and immediately after installing someone from Brazil hacked into my account. When I scanned vor viruses it said I had a Trojan.Malpack"
