### ISSUE TITLE
Verified downloads

### ISSUE THREAD

**Issue by FernandoPazCavalcante** [hydralauncher/hydra#105]
It would be nice to have a "verified" label in the download options.
A verified download may consist of the download source being checked for viruses, availability, and reliability.

**Comment by hydralauncher** [comment]
Verified by whom?

**Comment by FernandoPazCavalcante** [comment]
> Verified by whom?

There may be a dedicated server to check the downloads that appear available.

Or, a solution that I think is even better. To decentralize this validation, downloads could have some feedback from users who download, and the platform curator could analyze this feedback and add a flag or label for downloads validated by the community.

This would simplify the platform for those with limited knowledge of torrenting or who don't know how to use torrents.

**Comment by hydralauncher** [comment]
Sorry, not doing this. Anything that requires human/manual intervention won't happen anytime soon.
Closing this for now.
