### ISSUE TITLE
[BUG] Не могу добавить ссылку в настройках 

### ISSUE THREAD

**Issue by H0pZik** [hydralauncher/hydra#1051]
### Describe the bug

когда нажимаю кнопку импортировать ничего не происходит. 

### Steps to Reproduce

1) зайти в настройки
2) открыть вкладку источники загрузки
3) вставить ссылку (пример: https://hydralinks.cloud/sources/steamrip.json)
4) увидеть что ничего не происходит

### Expected behavior

добавится ссылка

### Additional information and data

https://github.com/user-attachments/assets/611794df-d7f0-400b-8078-035b57c0fb1b

Sorry it's not in English, I don't speak it well

### Operating System

Windows 10

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
You could use Google Translate next time, no problem.
Please, try the following:

1. Close Hydra
2. Go to %appdata% and delete "hydra" and "hydralauncher" folder
3. Open Hydra again and try to import you download sources

**Comment by H0pZik** [comment]
Thank you, it helped

**Comment by mbTheCoolMan** [comment]
а где  %appdata%??? я не могу найти эту папку

**Comment by zamitto** [comment]
> а где  %appdata%??? я не могу найти эту папку 

Press Windows + R
Type %appdata%
Press Enter

**Comment by AlbertEc22** [comment]
I deleted both folders from appdata, but in the end it just came out of the account and I couldn't log in to it, I had to turn on ulta, but after all the actions, it didn't work out in the ioga to specify the source for downloading, just endless waiting

**Comment by AlbertEc22** [comment]
> You could use Google Translate next time, no problem. Please, try the following:
> 
> 1. Close Hydra
> 2. Go to %appdata% and delete "hydra" and "hydralauncher" folder
> 3. Open Hydra again and try to import you download sources

I deleted both folders from appdata, but in the end it just came out of the account and I couldn't log in to it, I had to turn on ulta, but after all the actions, it didn't work out in the ioga to specify the source for downloading, just endless waiting

**Comment by zloyglaz** [comment]
> You could use Google Translate next time, no problem. Please, try the following:
> 
> 1. Close Hydra
> 2. Go to %appdata% and delete "hydra" and "hy

I tried to do it, does'nt have any effect
