### ISSUE TITLE
i cant download any game

### ISSUE THREAD

**Issue by florexrx** [hydralauncher/hydra#1052]
### Describe the bug

I can't download any game, in all of them it appears that there are no download options
![image](https://github.com/user-attachments/assets/d3014659-56cb-4427-8081-42fa87eb22e2)

### Steps to Reproduce

just start the app

### Additional information and data

C:\Users\3070\AppData\Roaming\hydra

### Operating System

W11

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by DiegoAATrevisan** [comment]
## Hi, i'm having the exact same problem.
![image](https://github.com/user-attachments/assets/37542342-f899-4ab3-a929-5091e417e945)

**Comment by zamitto** [comment]
Definitively not a bug. If you search in other issues you will find answers.
But you need to add sources of download to have downloads available. Hydra does not provide any download by its own.

If you need further help, you can join the community discord server (https://discord.gg/hydralaunchercommunity)
