### ISSUE TITLE
[INQUIRY]

### ISSUE THREAD

**Issue by hornyalcoholic** [hydralauncher/hydra#1055]
### Is your feature request related to a problem? Please describe.

Well yes and no, I got logged out randomly for no reason out of my Hydra account but I can't seem to remember the username I chose, all I know is that the Display name was Leonardo & this is my code to friend me; 95pboovy
I don't care about resetting my password but how the hell do I get to know which username I chose at registration???

### Describe the solution you'd like

I guess a way to know your original username you chose

**Comment by zamitto** [comment]
Please, send an email to support@hydralauncher.gg with the information you wrote here and any other that you remember.
We will answer you by email.
