### ISSUE TITLE
[BUG] no download

### ISSUE THREAD

**Issue by ereh7** [hydralauncher/hydra#1060]
### Describe the bug

Minhas fontes de download nao funcionam para baixar nenhum jogo

### Steps to Reproduce

.

### Additional information and data

.

### Operating System

win 11

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by Elps013** [comment]
i too having problem

**Comment by Elps013** [comment]
![image](https://github.com/user-attachments/assets/9f5ab9d5-165e-4341-bcc8-b859b072f4cd)

**Comment by Murchh** [comment]
Me too
