### ISSUE TITLE
[BUG] no download

### ISSUE THREAD

**Issue by d12egojnr** [hydralauncher/hydra#1061]
### Describe the bug

depois da atualização V2.1.7, os links de direcionamento de downloads não aparecem, antes de atualizar estava tudo normal, baixando os arquivos tudo certinho, agora que atualizou quando vai nos arquivos dos jogos aparece que não tem downloads disponível, mas isso para todos os jogos do catalogo.

### Steps to Reproduce

.

### Additional information and data

.

### Operating System

Windows 10

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by kurosketch** [comment]
Existe alguma melhor forma para aumentar a velocidade dos Downloads?

**Comment by zamitto** [comment]
@d12egojnr did you add sources of download?

**Comment by d12egojnr** [comment]
no

**Comment by zamitto** [comment]
> no
> 

So there is no download for Hydra to list.
You need to add sources of download.
You can search in the other dozens of issues that already asked that. Or you can also join the discord community server, there are always lots of people there asking for help and helping each other
discord.gg/hydralaunchercommunity
