### ISSUE TITLE
не можу пограти в ФС 22

### ISSUE THREAD

**Issue by Roman1526** [hydralauncher/hydra#1066]
### Describe the bug

потрібен пароль до гри 

### Steps to Reproduce

не має паролів до гри FS 22

### Expected behavior

добавте паролі до ігор

### Additional information and data

![Знімок екрана 2024-10-15 212004](https://github.com/user-attachments/assets/a398445f-0d8b-42a1-aafe-e761a10766df)
![Знімок екрана 2024-10-15 212024](https://github.com/user-attachments/assets/d644449d-41c1-4ec5-9b67-1fa84ce13442)

### Operating System

Windows 11

### Hydra Version

https://github.com/hydralauncher/hydra/releases/download/v2.1.7/hydralauncher-2.1.7-setup.exe

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by GEkXD3** [comment]
Может стоит на английском писать блять?

**Comment by JackEnx** [comment]
we do not support what is downloaded by hydra, you can try to find some hydra community that can help you
