### ISSUE TITLE
[BUG] Write a title for your bug

### ISSUE THREAD

**Issue by Alysoon3443** [hydralauncher/hydra#1067]
### Describe the bug

não aparece dowloads nos jogos, todos os jogos sem download

### Steps to Reproduce

abro o programa, jogos sem download 

### Expected behavior

não 

### Additional information and data

.

### Operating System

windows 10 pro 

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Hydra does not offer download options by itself. You need to add your download sources.
You can search about it in other issues (as there are countless of them talking about the same matter).
You can also join the community discord server and read their FAQ or ask for help there (discord.gg/hydralaunchercommunity)
