### ISSUE TITLE
White screen on launch

### ISSUE THREAD

**Issue by sanirdz** [hydralauncher/hydra#107]
When I launch the application I get stuck with the following white screen:
![image](https://github.com/hydralauncher/hydra/assets/21080423/a39da261-3e3a-446a-8412-d2602ea29a73)

Release 1.1.0
Windows 11

logs attached:
[error.log](https://github.com/hydralauncher/hydra/files/15155988/error.log)
[info.log](https://github.com/hydralauncher/hydra/files/15155989/info.log)

**Comment by zamitto** [comment]
known issue, will be fixed on next release

**Comment by hydralauncher** [comment]
This has been fixed.
