### ISSUE TITLE
[BUG] several links from the "Hydra community links" doesn't work

### ISSUE THREAD

**Issue by Lemon4ik-bit** [hydralauncher/hydra#1072]
### Describe the bug

I go to the settings. Next to the download sources, add the source. All links work except "DODI" (https://hydralinks.cloud/sources/dodi.json) link and "KaOsKrew" (https://hydralinks.cloud/sources/kaoskrew.json) link.
When I insert these links and click on the "check" button, nothing happens.

### Steps to Reproduce

1. Open Hydra launcher
2. Go to settings
3. Go to "download sources"
4. Click on "add source"
5. insert the URL (https://hydralinks.cloud/sources/dodi.json) or (https://hydralinks.cloud/sources/kaoskrew.json)
6. click on "validate"
7. Nothing happend

### Expected behavior

all links work except "DODI"  (https://hydralinks.cloud/sources/dodi.json) and "KaOsKrew" (https://hydralinks.cloud/sources/kaoskrew.json)

### Additional information and data

https://github.com/user-attachments/assets/8ff7454f-80a5-46b2-92bc-3a754457d32a

I took the link from your site "Hydra community links" (https://hydralinks.cloud/)

### Operating System

Windows 11

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
This looks like their jsons have some error.
You need to wait for the provider of the jsons to identify the error and fix it.

**Comment by Lemon4ik-bit** [comment]
Now all working. Thanks

**Comment by jose18232** [comment]
hola quisiera poder jugar gta 5 online atra vez de la plata forma hydra? alguien que me ayude porfavor
