### ISSUE TITLE
[BUG] Problem with account registration and login

### ISSUE THREAD

**Issue by Hanzo000-ma** [hydralauncher/hydra#1080]
### Describe the bug

I tried to log into my account, it didn't work, I tried to create a new one, it doesn't work, it just stays on the registration window and nothing changes

### Steps to Reproduce

1. Click on log in
2. Click register or log in

### Expected behavior

log in to your account

### Additional information and data

------------

### Operating System

Windows 10

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by taufox** [comment]
Im having the same problem on Windows 11 23H2, Hydra Version 2.1.7

**Comment by zamitto** [comment]
We passed through some issues with our api. Should be fixed by now.
Could you try again?

**Comment by taufox** [comment]
> We passed through some issues with our api. Should be fixed by now. Could you try again?

I tried once and didnt work, i uninstalled and deleted everything about Hydra and tried again and it worked, Ty
Maybe some file would not let you connect to the auth servers so watch out for that.

**Comment by zamitto** [comment]
Probably not the case

**Comment by DosX-dev** [comment]
Same problem

**Comment by UserLavaDev** [comment]
Now is version v.3.1.5 "Spectre".It still has the some problem
