### ISSUE TITLE
[BUG] Bug na Criação da conta

### ISSUE THREAD

**Issue by igorcharlie103** [hydralauncher/hydra#1083]
### Describe the bug

Não consigo criar uma conta!

### Steps to Reproduce

Crio uma conta e depois tento logar com ela! Fala que o user ou a senha está incorreta depois eu tento usar a senha de recuperação e fala q a conta n existe!

### Expected behavior

Esperava logar normalmente! Ou que a conta realmente fosse criada!

### Additional information and data

Em "error.txt": [2024-10-15 14:55:42.407] [error] (main)            Error: Error: net::ERR_SOCKET_NOT_CONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)
[2024-10-15 14:55:42.410] [error]                   Unhandled rejection Error: net::ERR_SOCKET_NOT_CONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:114482)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)

### Operating System

Windows 10

### Hydra Version

v2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by CoohCooh** [comment]
o hydra está sendo atualizado e possivelmente sai uma nova versão com novas funcionalidades e correções

**Comment by zamitto** [comment]
@igorcharlie103 consegue enviar um email para support@hydralauncher.gg com o nome de usuário e nome de exibição que você está escolhendo?
Prints seriam bem vindos também.

**Comment by BanneMax** [comment]
Estou com o mesmo problema do criador do tópico.
O meu problema começou após a atualização para o 3.0, ao pagar a mensalidade para salvar em nuvem, após isso minha conta deslogou e não consegui logar novamente.
Ao tentar entrar em contato com o suporte via e-mail, minha mensagem é bloqueada, acho que por suspeita de spam, mas não sei com certeza.
![image](https://github.com/user-attachments/assets/fe271b84-60c8-4fde-99a2-19b6c5d68522)

**Comment by zamitto** [comment]
@BanneMax support@hydralauncher.gg
