### ISSUE TITLE
[BUG] Can't add download fonts

### ISSUE THREAD

**Issue by laetemn** [hydralauncher/hydra#1084]
### Describe the bug

When i try to add the download fonts it simply dont add.
When i click in validate when i put this link https://hydralinks.cloud/sources/fitgirl.json nothing happen after it.

### Steps to Reproduce

1. Download or copy fonts;
2. Try to add a new download font.

### Additional information and data

![bugh](https://github.com/user-attachments/assets/c3e799f9-3431-4839-bf4c-8b3579e9ccd0)

### Operating System

Windows 10 Pro 22H2

### Hydra Version

v2.1.7 "Leviticus"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by TrasAzar** [comment]
1. Completely close Hydra, end the activity in the task manager, and then uninstall Hydra from your PC.
2. Then search for "%appdata%" in that folder, look for Hydra and Hydra launcher, and delete these folders from your computer.
3. After that, just install Hydra again and it will be working normally.

**Comment by laetemn** [comment]
> 1. Completely close Hydra, end the activity in the task manager, and then uninstall Hydra from your PC.
> 
>     2. Then search for "%appdata%" in that folder, look for Hydra and Hydra launcher, and delete these folders from your computer.
> 
>     3. After that, just install Hydra again and it will be working normally.

It worked perfectly.
THANK YOU!!!
