### ISSUE TITLE
[BUG] fifa 24 não tem download

### ISSUE THREAD

**Issue by victortm007** [hydralauncher/hydra#1085]
### Describe the bug

o download do fifa 24 não aparece, baixei todas as fontes e não tem, entretanto tem 4 mil downloads

### Steps to Reproduce

.

### Additional information and data

![{B36CA349-8D40-4D55-B1BB-6BDF732BAF67}](https://github.com/user-attachments/assets/cdcda0a3-052e-4542-92ff-12938cfc2f9e)
![{7D1FB09D-28DA-4067-BA16-B8B568A1BDD2}](https://github.com/user-attachments/assets/b2197e61-6ff1-4aac-b270-1b90e91448ac)

### Operating System

windows 11

### Hydra Version

now

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by CoohCooh** [comment]
não quer dizer que o jogo está aparecendo no hydra que ele ja está crackeado

**Comment by CoohCooh** [comment]
o hydra é so um launcher aonde reune as jogos, então depende de outras pessoas para crackear os jogos, como a empress, dodi e etc

**Comment by victortm007** [comment]
Já tem 4 mil downloads

Em ter., 22 de out. de 2024 4:25 PM, CoohCooh ***@***.***>
escreveu:

**Comment by JackEnx** [comment]
sources are not hydra's responsibility.
