### ISSUE TITLE
[BUG] Can't create account

### ISSUE THREAD

**Issue by BaldCult** [hydralauncher/hydra#1093]
### Describe the bug

I enter all the information needed then I click create account then confirm for the pin but then it just prompts me to enter the info again.

I also get no error code or anything saying i've done something wrong, so im confused.

### Steps to Reproduce

1. Click sign in
2. signup
3. enter info as needed
4. click create account
5. confirm the pin
6. then it just leads back to the page to enter account info with my account info already put in

### Additional information and data

![Screenshot 2024-10-22 201527](https://github.com/user-attachments/assets/3b003094-0d7d-4feb-940c-20ddb235044d)

### Operating System

Windows 11

### Hydra Version

V3.0.0

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
We found the problem and it has been fixed. You can try to create your account again!

**Comment by Gainsy228** [comment]
Добрый день. Скачал гидра лаунчер, но не могу создать аккаунт, после пин кода, который надо сохранить, перекидывает обратно на создание аккаунта и так постоянно
