### ISSUE TITLE
Bug tela branca 

### ISSUE THREAD

**Issue by strakapoia** [hydralauncher/hydra#110]
Após um tempo com o programa minimizado e baixando, quando você voltar para o programa ele fica bugado nessa tela branca do print anexado, não sei se o download continua em segundo plano, mas a tela não volta ao normal só se fechar e abrir de novo.

![Screenshot_50](https://github.com/hydralauncher/hydra/assets/75393709/8741d37c-2889-4e71-8bec-f769a36ee4c8)

**Comment by aluisiocomiran** [comment]
Também estou com o mesmo problema, porém a tela branca fica desde o inicio. Não consigo visualizar nada.

**Comment by mobius1qwe** [comment]
duplicate #107

**Comment by zamitto** [comment]
known issue, will be fixed on next release
and yes, the download is not paused or stopped while the screen is blank

**Comment by drakteel** [comment]
Eu fecho o hydra no "X" e clico duas vezes nele ali no canto da barra de tarefas... ele volta ao normal

**Comment by hydralauncher** [comment]
This has been fixed.
