### ISSUE TITLE
[BUG] Why payout is on Brazilian?

### ISSUE THREAD

**Issue by GEkXD3** [hydralauncher/hydra#1101]
### Describe the bug

Not completely bug but...
When I want to buy cloud saves, Hydra redirects me to Brazilian site. I don't know Brazilian, but I want cloud saves....

### Steps to Reproduce

1. Go to https://checkout.hydralauncher.gg/
2. See Brazilian language

### Expected behavior

I expect this site have at least english or Deutsch

### Additional information and data

![image](https://github.com/user-attachments/assets/8d1c0b1d-b295-4424-bcf3-c5c39a176844)

### Operating System

(Doesn't matter)

### Hydra Version

Any version that has cloud saves

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by HelmXGaming** [comment]
Hydra is a Brazilian owned program due to the more light laws on programs like this. Unknown on if you can buy the subscription if you live outside brazil at the moment

**Comment by HelmXGaming** [comment]
[zamitto](https://github.com/zamitto) did reply on a similar post stating that PayPal payment should be coming soon once fully integrated so should actually be possible to subscribe in the US depending on if a CPF requirement will stay or not

**Comment by Mathhsss** [comment]
LOL, brazil is the home of hydra bro

**Comment by HelmXGaming** [comment]
@Mathhsss Well duh, ain't no way a program like this would last against the US government. Anything here making piracy openly easier gets nuked fast.

**Comment by itxtoledo** [comment]
they need to setup a company in georgia (1% of tax) and receive payments using international payments or just accept bitcoin via lightning network.

**Comment by HelmXGaming** [comment]
Bitcoin would probably be difficult to do with subscriptions. Maybe having
bundled months like 1 month, 3 months, 6 months and 12 months.

**Comment by zamitto** [comment]
Checkout page is now translated to EN, ES and RU
Only Pix (brazilian payment method) requires CPF (brazilian social number). Paypal only requires email
