### ISSUE TITLE
[BUG] In-app updater does not respect user install preferences

### ISSUE THREAD

**Issue by MigProPlayer** [hydralauncher/hydra#1103]
### Describe the bug

After updating via the in-app updater from 2.1.7 to 3.0.1 (not sure if it also happens with 3.0.0 or when updating directly from github), there are now two separate entries in the "Uninstall or change a program" section of the control panel
![image](https://github.com/user-attachments/assets/6e341bfb-439e-4334-93fc-6d63cbf542e0)
and in the Installed apps section of the settings app
![image](https://github.com/user-attachments/assets/95813641-354b-4428-a1ca-411682095215)
as seen in the screenshots above, the two entries have different versions and sizes.

As I was drafting this report, I noticed that indeed there are two different Hydras installed. One in C:\Program Files\Hydra (which is where it is supposed to be installed), and in %localappdata%\Programs\Hydra (which I guess is the new/updated version)
There are also two Hydra shortcuts in the Start Menu, which leads me to believe that the in-app updater always does a per-user installation, instead of respecting the user's preferences (which in my case was a shared/machine-wide installation).

### Steps to Reproduce

1. Install Hydra as a Shared install
2. Update using the in-app updater
3. Notice that there are now two different Hydras installed, one in the current user (Local AppData) and the other in Program Files

### Expected behavior

The in-app updater follows the user preferences defined in the first install.

### Additional information and data

Could not find up-to-date or relevant logs.

### Operating System

Windows 11 Pro

### Hydra Version

2.1.7/3.0.1

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Thanks for the report, I will investigate it

**Comment by ruizlenato** [comment]
Same Here, My hydra was originally installed in the C:\Program Files\Hydra folder, after the 3.0.1 update it was installed again but in the C:\Users\USER\AppData\Local\Programs\Hydra folder.

![image](https://github.com/user-attachments/assets/2570dc49-b6ef-4c05-bde5-b1336b2fcad2)
![image](https://github.com/user-attachments/assets/3b3ddc3a-f57b-4922-a03a-77b8d6cec9aa)

**Comment by zamitto** [comment]
Silent install on auto update will be removed. Seems to be a bug/limitation on the auto update library. So by prompting the user when auto updating, this should not happen anymore

**Comment by zamitto** [comment]
Solved in lastest version by not using the silent install on auto update
