### ISSUE TITLE
[BUG] "Sign in to see achievements" overlay covers unwanted content

### ISSUE THREAD

**Issue by MigProPlayer** [hydralauncher/hydra#1104]
### Describe the bug

https://github.com/user-attachments/assets/a92e70a3-6278-4f77-82f4-d3ed53b321d5

Bug is demonstrated in the video above.

When not logged in to Hydra, on a game's page that has achievement support the "Sign in to see achievements" overlay that covers the achievement section covers the **Add to library/Play** and **Open download options/Options** buttons and the bar that holds them

### Steps to Reproduce

1. Make sure you're not logged in to Hydra
2. Find a game that supports achievements
3. Open the game's details page
4. Scroll down and see that the "Sign in to see achievements" overlay blocks the Add to library/Play and Open download options/Options (depending on whether the game is added to the library or not) buttons and their bar

### Expected behavior

Overlay does not cover the buttons and the bar

### Additional information and data

Visual bug. Logs not needed

### Operating System

Windows 11 Pro

### Hydra Version

3.0.1

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Thanks, this one will be fixed by today's update
