### ISSUE TITLE
[BUG] não aparece nenhuma opção de download

### ISSUE THREAD

**Issue by rCruzzx** [hydralauncher/hydra#1114]
### Describe the bug

nenhum jogo aparece opções de download

### Steps to Reproduce

1 abri o hydra
2 nenhum jogo tem downloads
![imagem_2024-10-23_233601708](https://github.com/user-attachments/assets/b5a14463-410f-44bf-af65-f5860819715a)

### Expected behavior

encontrar jogos com opções de download

### Additional information and data

![imagem_2024-10-23_233722210](https://github.com/user-attachments/assets/500b4f98-0b26-4de2-8df3-6013402485ec)

### Operating System

windows 11

### Hydra Version

3.0.2

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by Shisuiicaro** [comment]
Você adicionou as fontes?

**Comment by Joao-oliveiraf** [comment]
> Onde eu encontro essas fontes?

https://www.reddit.com/r/hydralauncher/comments/1dmivyc/no_sources/
