### ISSUE TITLE
[BUG] Não consigo criar atalho na área de trabalho através do Hydra

### ISSUE THREAD

**Issue by adelorn08** [hydralauncher/hydra#1122]
### Describe the bug

Depois de selecionar o caminho do executável, eu clico em "Criar atalho na área de trabalho" ocorre o erro do anexo
![Captura de tela 2024-10-24 160428](https://github.com/user-attachments/assets/227856ed-45b4-4155-8ace-9b37eaeffef5)

Isso está acontecendo com todos os jogos no qual eu tento criar o atalho na área de trabalho através do Hydra.

### Steps to Reproduce

1. Vá em um jogo baixado na biblioteca e clique em "Gerenciar"
2. Adicione o caminho do arquivo executável do jogo
3. Clique em "Criar atalho da área de trabalho"
4. ![Captura de tela 2024-10-24 160428](https://github.com/user-attachments/assets/7c37dfed-6468-4e19-b449-7159e574ebba)

### Additional information and data

[error.txt](https://github.com/user-attachments/files/17512027/error.txt)
[info.old.txt](https://github.com/user-attachments/files/17512028/info.old.txt)
[info.txt](https://github.com/user-attachments/files/17512030/info.txt)
[logs.txt](https://github.com/user-attachments/files/17512032/logs.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17512033/pythoninstance.txt)
[achievements.txt](https://github.com/user-attachments/files/17512034/achievements.txt)

### Operating System

Windows 11

### Hydra Version

3.0.2

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Will be fixed in 3.0.3 (release in a few minutes)
