### ISSUE TITLE
[REQUEST] achievements in-game overlay 

### ISSUE THREAD

**Issue by Realm-Drifter** [hydralauncher/hydra#1126]
### Is your feature request related to a problem? Please describe.

whenever i get an achievement when i'm in a game, i just hear the sound and i have to alt-tab to the desktop to see it or to hydra itself

### Describe the solution you'd like

is it possible to have the achievements pop while in game, like an in-game overlay?

**Comment by JackEnx** [comment]
currently the notification information works in borderless, but not in fullscreen, there are some technical issues that prevent us from doing it this way, this is something we will fix soon, for now you can choose to play in borderless.

**Comment by Realm-Drifter** [comment]
@JackEnx 
alright borderless it is
thanks, dude
