### ISSUE TITLE
[REQUEST] Conquistas de jogos novos não disponíveis no hydra.

### ISSUE THREAD

**Issue by xjeandiasx** [hydralauncher/hydra#1134]
### Is your feature request related to a problem? Please describe.

Atualizar lista de conquistas no hydra, jogos que foram lançados a pouco tempo e que tem conquistas na steam, não estão disponíveis no Hydra Launcher.

Exemplo:

- Prim
- Age of history 3 
- Fear the spotlight (esse está com as conquistas desatualizadas)

Entre muito outros.

### Describe the solution you'd like

Atualizar lista de conquistas disponíveis em jogos lançados recentemente.

**Comment by zamitto** [comment]
Updated!
