### ISSUE TITLE
[BUG] Achievements de Silent Hill 2 Remake não funcionam

### ISSUE THREAD

**Issue by Alceu7** [hydralauncher/hydra#1135]
### Describe the bug

As conquistas de Silent Hill 2 estão presentes no Hydra, porém não funcionam.

### Steps to Reproduce

Tentei quatro repacks diferentes e tentei mudar as propriedades do arquivo (vi que algumas pessoas tiveram problemas na steam rodando o jogo como administrador). Já no Resident Evil 2 Remake funcionou perfeitamente. Alguém poderia me esclarecer se há algo pra fazer ou se estão planejando um update?

### Additional information and data

Testado nas versões 3.0.0, 3.0.2 e 3.0.3

### Operating System

Windows 11

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by MadWritter** [comment]
Nem todos os jogos comprados no hydra tem como efetuar monitoramento de achievements, mas se quer mesmo notificações pra vários jogos, recomendo dar uma olhada em como usar o Achievements Watcher

**Comment by zamitto** [comment]
Silent Hill 2 Remake does not generate the achievements files natively.
Even Achievement Watcher wouldn't be able to get achievements from SH2.

But, some users have made it possible for SH2 to generate theses files. I'd recommend you to talk to the community and see what they did to make it work

**Comment by LucGomes007** [comment]
Eu tambem sofro de problemas com as conquistas, em alguns jogos simplesmente nao sao desbloqueadas as conquistas, como gta sa ou cuphead, ja tentei diversas formas para consertar mais nenhuma funcionou, alguem sabe algum metodo q pode resolver?
