### ISSUE TITLE
[BUG] No game time on game page

### ISSUE THREAD

**Issue by samlach2222** [hydralauncher/hydra#1138]
### Describe the bug

I'm french and in a game page, I don't have my game time and the last played period.

### Steps to Reproduce

1. In a french environment, click a game
2. Look at the time
3. See missing time

### Additional information and data

![image](https://github.com/user-attachments/assets/acbd3d21-41e8-43ff-984a-c0b69fb9676c)

### Operating System

Windows 11

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Hydra needs to know the .exe file of your game to count your playtime. You can do this by going to the game Options screen and selecting and executable:

![image](https://github.com/user-attachments/assets/fecbd299-0097-4333-aa7c-0ad66ed19da2)

![image](https://github.com/user-attachments/assets/de390e36-5112-429e-857c-a021d9a53981)

**Comment by samlach2222** [comment]
But I have the same issue with games that have exe file 
![Uploading image.png…]()

**Comment by zamitto** [comment]
Oh! Could you do a small test and set the language to English?
It is probably a bug in the French translation that I already fixed and will be in the next release.

**Comment by samlach2222** [comment]
the bug is only in french translation and fixed in the latest version.
Thank you
