### ISSUE TITLE
[BUG] There are no games

### ISSUE THREAD

**Issue by Andruha656** [hydralauncher/hydra#1140]
### Describe the bug

There are just nothing here. Just nothing.

### Steps to Reproduce

Just downloaded and launched.

### Expected behavior

There are no any games in launcher.

### Additional information and data

![image](https://github.com/user-attachments/assets/413640e1-1963-4db9-8b62-8d4a119b1d78)

### Operating System

Windows 10

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
This is a bug that for some reason happens in some installations. But it can be easily fixed by:

1. Close Hydra
2. Go to `%appdata%` and delete `hydra` and `hydralauncher` folders
3. Open Hydra again
