### ISSUE TITLE
NÃO TEM download DISPONIVEL

### ISSUE THREAD

**Issue by X3X315** [hydralauncher/hydra#1142]
### Describe the bug

aPAGOU TODOS OS download DISPONIVEIS

### Steps to Reproduce

NENHUM

### Additional information and data

NADA ATEM

### Operating System

WINDOWS 10

### Hydra Version

3.0.3.

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Your problem is listed in our [Frequently Asked Question](https://github.com/hydralauncher/hydra/wiki/FAQ).
