### ISSUE TITLE
[BUG] Jogo não consta como jogado

### ISSUE THREAD

**Issue by bernardofernandezz** [hydralauncher/hydra#1143]
### Describe the bug

Fiz o modo historia completo do jogo e ao entrar no meu perfil, ele consta como se eu não tivesse conquistas e nenhuma hora jogada. 
![{21BAD8F0-C2E2-4E70-9869-D49109DB5442}](https://github.com/user-attachments/assets/8b87d456-1ae7-449c-a534-9fe84539252f)

### Steps to Reproduce

No response

### Expected behavior

No response

### Additional information and data

No response

### Operating System

Windows 11

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Did you select the game executable? To Hydra count your playtime you need to select the game executable.

About the achievements. Not all sources of games generate the files that register you achievements. And some games require you to also select the game executable to find the possible achievements files

**Comment by bernardofernandezz** [comment]
Após a instalação do jogo, eu vou no local onde foi baixado, extraio e executo pelo arquivo executável do jogo. Porém, ao entrar no hydra ele não consta essse tempo jogado.

Sobre as conquistas, eu verifiquei e este jogo tem suporte a conquistas. Até recebi algumas durante o jogo, consigo visualiza-las, mas é como se ao inspecionar meu perfil esse tempo e conquistas de jogo fosssem "apagadas"

**Comment by zamitto** [comment]
@bernardofernandezz você tem a assinatura do Hydra Cloud? As conquistas só aparecem no seu perfil com a assinatura.
E para constar o tempo do jogo, é necessário adicionar o executável do jogo nas configurações do jogo. Exemplo:

![image](https://github.com/user-attachments/assets/9a379df6-48cb-432a-9c11-7ba8df349da7)
![image](https://github.com/user-attachments/assets/5601caf3-2404-4dec-8b03-58b46abd71ce)



De qualquer forma, se preferir você pode entrar em contato pelo chat em help.hydralauncher.gg. Por lá as respostas são mais rápidas.

**Comment by bernardofernandezz** [comment]
Tenho a assinatura sim.

Sobre a adição do executável nas configurações do jogo, não tinha adicionado ele ainda, irei fazer isto. Obrigado!

**Comment by zamitto** [comment]
Certo!
Sobre as conquistas do Miles Morales, vale também ver com outros usuários da comunidade a partir de qual download eles conseguiram as conquistas.
