### ISSUE TITLE
[BUG] My launcher isn't loading

### ISSUE THREAD

**Issue by Austin2701** [hydralauncher/hydra#1144]
### Describe the bug

My launcher isn't loading, as if i had no connection to internet or something
I tried downloading older versions and re-installing the new one, but nothing worked

![image](https://github.com/user-attachments/assets/173a894f-7d74-4593-9cb1-4ab9f3598dfc)

### Steps to Reproduce

just downloaded the app and nothing else

### Additional information and data

![image](https://github.com/user-attachments/assets/8ca836aa-72e0-47d5-b3fa-c9227d965bb6)
[error.txt](https://github.com/user-attachments/files/17531777/error.txt)
[info.txt](https://github.com/user-attachments/files/17531785/info.txt)

### Operating System

windows 10

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
This is a bug that for some reason happens in some installations. But it can be easily fixed by:

1. Close Hydra
2. Go to %appdata% and delete hydra and hydralauncher folders
3. Open Hydra again

**Comment by Austin2701** [comment]
It worked! thx
