### ISSUE TITLE
[BUG] Incorrect Game Title Matching

### ISSUE THREAD

**Issue by ZeDarkAdam** [hydralauncher/hydra#1148]
### Describe the bug

I have encountered an issue with the Hydra Launcher regarding the matching of game titles from the JSON file with existing entries in the application. Specifically, when the game title "Sally Face | RePack" is parsed, it incorrectly matches to the entry for "Sally" instead of "Sally face."

This mismatch could lead to confusion for users searching for specific games, as it does not accurately reflect the intended title. I believe that the title matching logic needs to account for full title recognition, especially when dealing with multi-word titles.

### Steps to Reproduce

add source https://raw.githubusercontent.com/ZeDarkAdam/hydra_links_igruha/refs/heads/main/hydra_links_igruha.json

check "Sally Face | RePack" is matched to "Sally."

### Expected behavior

The entry "Sally Face | RePack" should match to "Sally face" instead of "Sally."

### Additional information and data

![image](https://github.com/user-attachments/assets/de121ff0-6355-4872-884d-13b79f27a71b)
![image](https://github.com/user-attachments/assets/54b55409-d744-47a0-85b2-66dc3070ead2)

### Operating System

Windows 11

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Your problem is listed in our [Frequently Asked Question](https://github.com/hydralauncher/hydra/wiki/FAQ).
