### ISSUE TITLE
[BUG] Can't download any game 

### ISSUE THREAD

**Issue by Rooklyn0** [hydralauncher/hydra#1149]
### Describe the bug

U can't donwload any games, it just says "No download available" on any game 
No matter what i do this keeps happening

### Steps to Reproduce

Install hydra 3.0.3 and open it

### Expected behavior

The games should be downloadable

### Additional information and data

![Hydra_HPBoBztqSS](https://github.com/user-attachments/assets/5764d28e-e718-4326-a95d-e6e1f8d19b3a)
C:\Users\Myuser\AppData\Local\Programs\Hydra

### Operating System

Windows 11

### Hydra Version

V3.0.3 "Skyscraper"

### Before opening this Issue

- [x] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Your problem is listed in our [Frequently Asked Question](https://github.com/hydralauncher/hydra/wiki/FAQ). 
We created it recently, but we recommending to always read the FAQ before opening a new issue.

**Comment by Rooklyn0** [comment]
> Your problem is listed in our [Frequently Asked Question](https://github.com/hydralauncher/hydra/wiki/FAQ). We created it recently, but we recommending to always read the FAQ before opening a new issue.

Ohhh, sorry and thanks for help, everything works now
