### ISSUE TITLE
[BUG] Can't see Fallout 3 achievements

### ISSUE THREAD

**Issue by Alceu7** [hydralauncher/hydra#1150]
### Describe the bug

I can see achievements in Fallout New Vegas, but they doesn't exist in Fallout 3. Is there any fix for this? 

### Steps to Reproduce

. 

### Additional information and data

![20241027_104034](https://github.com/user-attachments/assets/1cd140b1-73cf-45e8-a0ad-d98993295be3)
![20241027_104007](https://github.com/user-attachments/assets/0cb92918-2d81-4d9e-bdde-03f45ba778eb)

### Operating System

Windows 11

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Yes, because Fallout 3 has no achievements on Steam
