### ISSUE TITLE
Can't download any games

### ISSUE THREAD

**Issue by Caciocavall** [hydralauncher/hydra#1152]
### Describe the bug

I tried the method in FAQs to resolve it but nothing happened (erased hydra and hydralauncher on %appdata% and the restarted hydra), i tried also to unistall and download every version available but every single version wuold not let me add any community link, simply i cannot validate them. Look like the button to validate is bugged. All happened after i downloaded god of war, before that was functioning,

### Steps to Reproduce

1. Go to settings
2. Download sources
3. insert link from community links
4. validate
5. see error (cannot validate)

### Expected behavior

I was expecting that the links wuold be auto installed in the hydra launched as installed from setup.

### Additional information and data

%appdata%/hydra

### Operating System

windows 10

### Hydra Version

3.03

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Please, do not download older versions as some of them can corrupt your local database (versions before 2.1.0 iirc).

Please, follow the steps on FAQ again (sonwe can be sure you database is not corrupted), and after trying to import your sources, upload your logs here. That way we can try to debug what's happening.

**Comment by zamitto** [comment]
Please, do not download older versions as some of them can corrupt your local database (versions before 2.1.0 iirc).

Please, follow the steps on FAQ again (sonwe can be sure you database is not corrupted), and after trying to import your sources, upload your logs here. That way we can try to debug what's happening.

**Comment by vrad1sh** [comment]
You can use this site. Just push button "Install on Hydra" and install all json files. It works :)

https://hydralinks.cloud/
![image](https://github.com/user-attachments/assets/adf8b030-e94e-449f-894e-af019b7ecfd2)
