### ISSUE TITLE
[REQUEST] Auto-extracting archives

### ISSUE THREAD

**Issue by CMAULTOP** [hydralauncher/hydra#1157]
### Is your feature request related to a problem? Please describe.

Perhaps this is too complicated an idea, but I would like to automatically unpack zip, rar and other archives after installation

### Describe the solution you'd like

Place the install button, make the unzip button and the archive will be automatically unpacked to the same folder where the archive is located. It is also possible to make the install steam fix button if there is another archive in the folder where the archive was downloaded with the name repair, fix and others. If a password is requested, what can be done either every time a window with a password request from the archive or immediately set a password for certain download sources (and immediately shove the password into json with hydra link)

the translation is clumsy, I used a translator :)

**Comment by JackEnx** [comment]
duplicated #748, we only download what is placed by the user like any torrent client, any external operation is the user's responsibility.
