### ISSUE TITLE
[BUG] playtime not tracked on linux

### ISSUE THREAD

**Issue by hannahcool** [hydralauncher/hydra#1162]
### Describe the bug

My playtime is not tracked when I play hydra games on Linux. When I play them on Windows, however, it does track it.

### Steps to Reproduce

1) install game on linux computer
2) play game
3) playtime is not tracked

### Expected behavior

Tracked playtime

### Additional information and data

![Screenshot from 2024-10-28 20-50-59](https://github.com/user-attachments/assets/c52d761d-ff36-44e4-bad6-9a6d1d8802fc)
It might just be a problem with wine idk

### Operating System

Arch Linux

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JarEXE** [comment]
+1 for this. I have tried launching games with various WINE prefixes, WINE templates, and programs, in various locations, but Hydra never seems to be able to keep track of my playtime or last played time. 

If there's any additional configs or information needed that could be of assistance, I'll do my best to provide. 

System: Fedora 41
