### ISSUE TITLE
[BUG] No sources for download games, requires a json file

### ISSUE THREAD

**Issue by AleksHeyman** [hydralauncher/hydra#1165]
### Describe the bug

When opening any game in the catalog it says “no downloads available”
I don't understand where to find the json file to add it to the download sources in the settings

### Steps to Reproduce

1. Open Hydra
2. Check any game in Catalog

### Expected behavior

Appearance of download sources

### Additional information and data

![Снимок экрана 2024-10-29 194915](https://github.com/user-attachments/assets/7bc32a70-d09e-487f-b0ff-e78341589b49)
![Снимок экрана 2024-10-29 1949311](https://github.com/user-attachments/assets/8c8b70c8-a967-474a-a05e-1e98caf3719d)
[achievements.txt](https://github.com/user-attachments/files/17560464/achievements.txt)
[error.txt](https://github.com/user-attachments/files/17560467/error.txt)
[info.txt](https://github.com/user-attachments/files/17560468/info.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17560469/pythoninstance.txt)

### Operating System

Windows

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Expat228** [comment]
I have exactly the same problem.

**Comment by C4RNEIRO** [comment]
Tambem estou com o mesmo erro.

**Comment by vrad1sh** [comment]
You can use this site. Just push button "Install on Hydra" and install all json files. It works :)

https://hydralinks.cloud/
![image](https://github.com/user-attachments/assets/b6f1c477-140d-406a-83ef-d905b6d5de73)

**Comment by C4RNEIRO** [comment]
https://www.youtube.com/watch?v=XIg9GEjCvhY 

solução do problema ai.
