### ISSUE TITLE
[BUG] Update 3.0.4 causing my pc to lag the heck out while updating

### ISSUE THREAD

**Issue by alpet032** [hydralauncher/hydra#1169]
### Describe the bug

I just had a 3.0.3 update installed today on my pc which is gone great without any issues. now when im trying to update it to 3.0.4 my pc just lags the hell out and i cant even use it properly. pc config - 14700k, 64gb ddr5, rtx 4070. sorry for the russian language on the screenshot, didn't have time to switch the language. this screenshot with a 100% usage is for my OS ssd, where it is NOT supposed to install or even interact with because it is supposed to be installed on a completely separate ssd

### Steps to Reproduce

trying to update 3.0.3 to 3.0.4

### Additional information and data

![image](https://github.com/user-attachments/assets/04a06b8e-0cd3-491d-abb3-e4b4cd1d1ad1)

### Operating System

windows 11

### Hydra Version

3.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Does your CPU gets back to normal if you close Hydra? There's absolutely nothing that we changed between 3.0.3 and 3.0.4 that could increase CPU use. 
Does the issue persists if you restart Hydra? Does it stays at high use even after a few seconds?

**Comment by alpet032** [comment]
cpu is always on normal usage, its my OS ssd im talking about. and yes, i did left it to do it things for about 5-7 minutes and its appeared to be stuck on infinite loading, utilizing my system ssd at 100% usage and 2000ms of response time. but when i completely deleted the old version and installed the 3.0.4, it gone absolutely normal like it was when i installed version 3.0.3.

**Comment by zamitto** [comment]
Ok, so it is back to normal again?
We will try to investigate what happened, anyway

**Comment by alpet032** [comment]
sorry for not answering if you waited me to, i was on my work hours. i can maybe show it on discord what is happening when i try to do this kind of update, if you need it

**Comment by alpet032** [comment]
well, i think i found the problem whilist was trying to recreate this bug. and it came up to me that i caused this all by myself actually...
so, im sorry to bother you any longer :D
the whole problem is, that the launcher installer can not understand the situation if there any foreigh files\folders that the installer did not put there and it kinda stalls itself in this moment and all system recources becomes unresponsive.
if i do clear installation then update without adding any files or folders in the root hydra folder, it goes completely fine without any issues.
so issue resolved and thank you for motivating me to investigate it, i guess :D
