### ISSUE TITLE
[BUG] deleted my game file like wtf

### ISSUE THREAD

**Issue by ChargedX5** [hydralauncher/hydra#1176]
### Describe the bug

I closed the damn app, I opened it again and as usual it did not resume till I reinstalled the app, I tried to resume my download instead it deleted ALL MY PROGRESS, I waited 4 days for cyberpunk to download 98gb on my VERY limited internet plan just to get deleted..F YOU, learnt my lesson will be gladly going back to using torrents like utorrent...enjoy your crap

### Steps to Reproduce

pause your download and exit the app..open it and try and resume the download and boom...all your savings used to by the bandwidth for the game all gone cause they decided to delete my 98gb worth of files thanks a lot

### Expected behavior

deletes game files

### Additional information and data

m

### Operating System

windows 11

### Hydra Version

3.0.4 skyscraper

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Encryption-c08** [comment]
if you were downloading it from a server and not torrenting then thats why, you cannot close the app while downloading from a server.
