### ISSUE TITLE
Opções de Download inexistentes

### ISSUE THREAD

**Issue by Kazbonfim** [hydralauncher/hydra#1179]
### Describe the bug

Já têm um tempo que isso ocorre, nenhum jogo pesquisado, que eu tenha baixado antes pela ferramenta, aparece depois de um tempo com suas opções de download - um exemplo é o título GTA: San Andreas, e GTAIV.

![image](https://github.com/user-attachments/assets/9b72b0fa-c67f-4030-9f26-dec48d1f797f)

### Steps to Reproduce

Usando versão portátil

### Expected behavior

Jogos com links válidos, deveriam aparecer como disponíveis para Download 

### Additional information and data

Nada a relatar

### Operating System

W11

### Hydra Version

3.0.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Hachi-R** [comment]
hi @Kazbonfim, first install download fonts if you don't have them yet

if this behavior persists, follow the steps below

press `win + r` and paste this line `%appdata%/hydra/`

press enter and it will open a directory, close hydra from system tray or task manager and delete the hydra.db file in the directory

reopen hydra and install download fonts

**Comment by VoidSeeder** [comment]
Hi @Hachi-R!
Where can I find "download fonts"?

**Comment by VoidSeeder** [comment]
Okay, thank you very much for the information!
But what has changed? Why was this not necessary before and now it is?
When I did the first installation I didn't have to include these files.

**Comment by Kazbonfim** [comment]
> Hi @Hachi-R! Where can I find "download fonts" files to install?

Here, i've found a good source, just decode that
aHR0cHM6Ly9oeWRyYWxpbmtzLmNsb3VkLw==

**Comment by Kazbonfim** [comment]
> hi @Kazbonfim, first install download fonts if you don't have them yet
> 
> if this behavior persists, follow the steps below
> 
> press `win + r` and paste this line `%appdata%/hydra/`
> 
> press enter and it will open a directory, close hydra from system tray or task manager and delete the hydra.db file in the directory
> 
> reopen hydra and install download fonts

Worked! Thanks 💖🔥

**Comment by Kazbonfim** [comment]
> hi @Kazbonfim, first install download fonts if you don't have them yet
> 
> if this behavior persists, follow the steps below
> 
> press win + r and paste this line %appdata%/hydra/
> 
> press enter and it will open a directory, close hydra from system tray or task manager and delete the hydra.db file in the directory
> 
> reopen hydra and install download fonts

Worked, thanks! 🔥💖

**Comment by VoidSeeder** [comment]
> > Hi @Hachi-R! Where can I find "download fonts" files to install?
> 
> Here, i've found a good source, just decode that aHR0cHM6Ly9oeWRyYWxpbmtzLmNsb3VkLw==

Opa, valew demais, meu aliado!
