### ISSUE TITLE
[BUG] the directory doesnt work and more v3.0.4

### ISSUE THREAD

**Issue by MAROS-kek** [hydralauncher/hydra#1191]
### Describe the bug

does not show pictures of buttons to simply download the game, searching for the game is also without results

### Steps to Reproduce

1) the directory doesnt work
 2) surprise me button doesnt work
 3) the login button also doesnt work 

### Expected behavior

what should i do to fix this or if this is a hydra server failure then please fix it

### Additional information and data

![Снимок экрана (1)](https://github.com/user-attachments/assets/2f0b0b83-1034-47a8-8fff-e83161f5d697)
I have an old laptop acer

### Operating System

10windows

### Hydra Version

hydralauncher-3.0.4-setup.exe

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Follow the steps on the FAQ for a clean install. 
Your installation got corrupted for some reason

**Comment by MAROS-kek** [comment]
Oh my god, sorry to bother you, I understand completely, thank you

**Comment by zamitto** [comment]
No problem! Glad it is working now
