### ISSUE TITLE
[BUG] I can't install games

### ISSUE THREAD

**Issue by sqfoll** [hydralauncher/hydra#1192]
### Describe the bug

I can’t download anything on all the game icons it says: There are no installation options available, I tried to switch to another version and updated Hydra Launcher, it didn’t help.

### Steps to Reproduce

I don't know how to get this bug

### Additional information and data

![image](https://github.com/user-attachments/assets/1e11a065-f2e6-419e-8333-395b5d5d391c)

### Operating System

Windows 10

### Hydra Version

3.0.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Pazdikan** [comment]
Did you add sources?
Settings -> Download sources

**Comment by zamitto** [comment]
Did you read the FAQ?

**Comment by sqfoll** [comment]
Where can I find sources?

**Comment by MrDraxs** [comment]
> Where can I find sources?

https://hydralinks.cloud/sources
