### ISSUE TITLE
[BUG] Write a title for your bug

### ISSUE THREAD

**Issue by STUMP02** [hydralauncher/hydra#1195]
### Describe the bug

the same problem on version 3.0.4, I tried a lot, they advised me to install version 1.2.1, but it's nowhere to be found, I just didn't find it, I tried different games, different repacks, nothing helps, the download just lasts 10,000 years, and then stops at 0, and all this in order to do, when it is fixed, the same problem that I had in version 1.3.1, then I installed 1.2.1 and it helped, and then I deleted the hydra launcher from the PC, installed it again, and here it is again

### Steps to Reproduce

go to the catalog section, select any game, click download, select the repack and the game does not load

### Additional information and data

![{DA6193D1-09CB-4BF9-9D05-6FDBE9B0AF45}](https://github.com/user-attachments/assets/93a7b0e4-cbf0-4982-9c24-532231267a5a)

### Operating System

Windows 11

### Hydra Version

3.0.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
What's the download directory that you chose? Any chance it needs admin permission to write?

**Comment by STUMP02** [comment]
it really helped, thanks a lot, everything works and loads
