### ISSUE TITLE
[BUG] Write a title for your bug No download available

### ISSUE THREAD

**Issue by sagemcom09** [hydralauncher/hydra#1198]
### Describe the bug

Download options are not displayed (No download available)

### Steps to Reproduce

1 open hydra
2 there is no download option

### Additional information and data

<img width="951" alt="Capturar" src="https://github.com/user-attachments/assets/e1e70ff8-d147-4256-a946-93f66b80a23d">

### Operating System

windows 10

### Hydra Version

v3.0.4 - "Skyscraper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).
