### ISSUE TITLE
[BUG] Missing Achievements On Some Game Pages

### ISSUE THREAD

**Issue by Psyonix343** [hydralauncher/hydra#1201]
### Describe the bug

There are some games I've come across that have their achievements missing on the main page of the game as if the game didn't come out with them.

### Steps to Reproduce

Lookup games such as; Neva, Europa, Lego Harry Potter Collection.

### Expected behavior

Seeing your achievements on the game page.

### Additional information and data

![Screenshot_1](https://github.com/user-attachments/assets/e8bcb001-abb2-443a-8d64-a56b0cdbb330)
![Screenshot_2](https://github.com/user-attachments/assets/c628acfd-5654-4da6-84f8-7dc121c4b2f3)

### Operating System

Windows 10

### Hydra Version

v3.0.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Thanks for the report!
We are finishing implementing automatic updates on the achievements. Soon this problem should no longer happen
I will manually update the games you listed in the next couple hours.

**Comment by zamitto** [comment]
Done
