### ISSUE TITLE
respond to emails!!

### ISSUE THREAD

**Issue by arman0091** [hydralauncher/hydra#1209]
### Describe the bug

hey i forgot my account's password and i emailed "support@hydralauncher.com" and got no respond its almost 1 week!

### Steps to Reproduce

.

### Additional information and data

aa

### Operating System

11

### Hydra Version

3.0.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Please, reply to the same email you sent before. We will look into it with priority

**Comment by zamitto** [comment]
Oh, you sent to the worng email 

It is support@hydralauncher.gg

**Comment by arman0091** [comment]
sent ty
