### ISSUE TITLE
[BUG] Can`t find steam game

### ISSUE THREAD

**Issue by NataliaAgapova** [hydralauncher/hydra#1210]
### Describe the bug

When I try to search the catalogue for Wild Indigo Ranch (https://store.steampowered.com/app/1751350/Wild_Indigo_Ranch/), it's not in the search list.
![image](https://github.com/user-attachments/assets/81cf535a-215a-4385-bad1-51e1530cc237)

 Even if I enter only one word, still no. 
![image](https://github.com/user-attachments/assets/e5468fa7-8eb8-4f10-9f2d-78585dda273f)

### Steps to Reproduce

1. Enter in the search field "Wild Indigo Ranch"
2. Make sure that game is available in steam.

### Expected behavior

Find a game by full title in first position.

### Additional information and data

no

### Operating System

windows 10

### Hydra Version

3.05, but in previos version too

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Arthurmqz** [comment]
This isn’t a bug. Before downloading games, you need to provide a download source link in the settings. You can check the step-by-step guide in the documentation on Discord. Also, you can find some links at https://hydralinks.cloud/

**Comment by zamitto** [comment]
It looks like the title of this game was "Don't Die In The West" when the game page was first available on Steam.
I will update the game name on our database as soon as possible

**Comment by NataliaAgapova** [comment]
> It looks like the title of this game was "Don't Die In The West" when the game page was first available on Steam. I will update the game name on our database as soon as possible

Thank you! Yes, i checked, they changed the name of the game right before release.
