### ISSUE TITLE
[REQUEST] Fontes de Download ? 

### ISSUE THREAD

**Issue by Breninhoow** [hydralauncher/hydra#1211]
### Is your feature request related to a problem? Please describe.

Estou tentando baixar jogos, mais está sem fontes de downloads
![Captura de tela 2024-11-07 084151](https://github.com/user-attachments/assets/d94f68a6-0013-4142-ac42-4cf007644ccc)

### Describe the solution you'd like

Links com fontes de downloads confiavéis

**Comment by flygab** [comment]
Yes, I have the same problem and json files are not checked

**Comment by JackEnx** [comment]
#1151

**Comment by lucianohjds** [comment]
sim, tenho esse problema os links nao sao validados

**Comment by jvitor32** [comment]
o meu tabem links nao validao
