### ISSUE TITLE
[REQUEST] Bring back old achievement notifications

### ISSUE THREAD

**Issue by Psyonix343** [hydralauncher/hydra#1213]
### Is your feature request related to a problem? Please describe.

Please bring back the old achievement notification style or if possible have the choice between the 2 without having to downgrade versions. The windows/game bar notification style is very ugly and takes up a lot more of my screen.

### Describe the solution you'd like

Bring back old achievement notification.

### Describe alternatives you've considered

I switched to Hydra for my achievement notifications and tracking simply due to how it was handled and loving it so far until the windows notification update. I moved away from Achievement Watcher as they use the same style of notification.

**Comment by zamitto** [comment]
The first one (which I much preferred) had some compatibility issues and was causing a black box for some users. 
We are working on a much better solution that hopefully will work for everyone using Windows (for Linux we don't have a solution yet)

**Comment by Psyonix343** [comment]
Understood, thanks for the insight and the replies to my other tickets as well, appreciate the work you do. <3
