### ISSUE TITLE
[BUG] hydra doesn't load

### ISSUE THREAD

**Issue by ZLOYkitaeza** [hydralauncher/hydra#1234]
### Describe the bug

![image (1)](https://github.com/user-attachments/assets/2490e023-bc0c-44f4-85ef-48076c549815)
![image](https://github.com/user-attachments/assets/63600b88-d740-478f-9eab-08005ab84869)
hydra just doesn't load and I can't register and download games and things like that and I tried to say old versions but they also give the same error
гидра просто не грузит и я не могу зарегистрироваться и скачать игры и тому подобные вещи и пытался сказать старые версии но они тоже выдают такую же ошибку 
wrote English with translation

### Steps to Reproduce

.

### Additional information and data

![image](https://github.com/user-attachments/assets/45b379be-4591-4d1e-9c26-35c5dd08d497)
this computer/documents/hydra

### Operating System

Win10

### Hydra Version

v3.0.5 "Skyscaper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by ZLOYkitaeza** [comment]
"zloxdobro" my discord if anyone wants to help a lot with all this
"zloxdobro" мой дискорд если кто то хочет сильно помочь со всем этим

**Comment by Hachi-R** [comment]
hi @ZLOYkitaeza , pls close the launcher in system tray and delete this folder `%appdata%/hydra`

reopen the launcher again, if this doesnt work you can reply me

**Comment by daztyyoff** [comment]
> hi @ZLOYkitaeza , pls close the launcher in system tray and delete this folder `%appdata%/hydra`
> 
> reopen the launcher again, if this doesnt work you can reply me

working, thx.
