### ISSUE TITLE
The hydra doesn't give me download options ;[

### ISSUE THREAD

**Issue by DariZzZ-CM** [hydralauncher/hydra#1235]
### It doesn't give me download options

It doesn't give me options to download the games I want, I don't know if it's just me or what, or there isn't one because it's very recent or my Windows security is active but it still lets me download it, or rather run it, too. I use 360 ​​Total Security but I turned it off and I don't know if that's it.thank you sou much

![Captura de pantalla 2024-11-16 225810](https://github.com/user-attachments/assets/a2955397-8018-47b3-96d0-828b6f05c506)

### Steps to Reproduce

1: it doesn't appear, when I enter the game and what is added to the library it doesn't let me download

2: When I enter the games catalog and select one, it doesn't tell me to download or anything and next to it it tells me that there are still no downloads available 

3.I don't know what to do pls help

### Expected behavior

I was hoping to be able to download the games without it telling me that there are still no downloads available.I don't know if it is because the version is very recent or they are making fixes,I will be attentive to what happens if you answer me, I even have my steam open, yes, that's it and no,thank you sou much.

### Additional information and data

There is this route but it doesn't show me much either

![Captura de pantalla 2024-11-16 230844](https://github.com/user-attachments/assets/9ebce74c-9735-4e2b-b303-5e311638c771)

in the other one that is not with the %appdata% executable if it shows me more

![Captura de pantalla 2024-11-16 232439](https://github.com/user-attachments/assets/9ee522e0-097f-44f2-bb21-a4787e7634e3)

### Operating System

windows 11 home

### Hydra Version

3.05 the neww or the last "Skyscraper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by ZakitheBig** [comment]
Have you tried adding the repositories?
https://hydralinks.cloud/

**Comment by JackEnx** [comment]
please, read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ) or search in the closed issues before open a issue.
