### ISSUE TITLE
[BUG] no downloads available

### ISSUE THREAD

**Issue by NaviTDost** [hydralauncher/hydra#1240]
### Describe the bug

i cant downloads games it says no downolads available

### Steps to Reproduce

go to the game page

### Expected behavior

i think they will help me and i will be able to play my favorite games

### Additional information and data

help please

### Operating System

windows 10 pro

### Hydra Version

v3.0.5"Skycraper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).
