### ISSUE TITLE
[REQUEST] Games patch notes

### ISSUE THREAD

**Issue by guibzo** [hydralauncher/hydra#1241]
### Is your feature request related to a problem? Please describe.

Seeing game updates

### Describe the solution you'd like

I would like that such as in Steam, the game patch notes are added to the game screen.
It would make it easier than having to go to the game or steam page to see related patch notes and etc.

**Comment by Hachi-R** [comment]
we cant guarantee or expect the download versions to match the ones on steam, so the patch notes in game page might end up causing more confusion than helping
