### ISSUE TITLE
[BUG] The app isn't loading anything

### ISSUE THREAD

**Issue by calielian** [hydralauncher/hydra#1243]
### Describe the bug

The app doesn't show anything. My profile is not found, it just doesn't show anything. And yes, I disabled the firewall for Hydra.

### Steps to Reproduce

Just open the app

### Additional information and data

![issue](https://github.com/user-attachments/assets/07f564bb-6638-4bbf-8b39-b972814e45d3)

### Operating System

Windows 10

### Hydra Version

3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
we performed an API optimization that required a downtime.
