### ISSUE TITLE
my hydra is bugged

### ISSUE THREAD

**Issue by RYAN40028922** [hydralauncher/hydra#1244]
### Describe the bug

My hydra went offline and I can't solve it. I've tried uninstalling, closing, checking my internet but nothing worked.

### Steps to Reproduce

I clicked on "surprise me" and then my hydra couldn't search, I thought it was my internet, so I went to check and it wasn't. I've tried closing the program, ending the task and reinstalling hydra but it didn't help at all. The catalog didn't show any games and only the selection screen remained. When I reinstalled it wouldn't let me log in, and I'm still trying to solve it.
![Captura de tela 2024-11-19 182758](https://github.com/user-attachments/assets/de0a9c7e-c5b6-44ac-a06a-6a8344fcc5b6)

### Expected behavior

I was hoping to be able to search for other games (and log in again)

### Additional information and data

[info.txt](https://github.com/user-attachments/files/17821727/info.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17821728/pythoninstance.txt)
[error.txt](https://github.com/user-attachments/files/17821729/error.txt)

### Operating System

windows 10

### Hydra Version

v3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
we performed an API optimization that required a downtime.
