### ISSUE TITLE
[BUG] Download keep "downloading metadata" and thats it

### ISSUE THREAD

**Issue by toofastforboo** [hydralauncher/hydra#1245]
### Describe the bug

i cant install hotline miami 2 cuz it keep saying downloading metadata and the download dont go up

### Steps to Reproduce

i just installed the download sources, clicked to download and it just doesn't work
im using the latest version
i opened an execution in the firewall, disabled Windows Defender
reinstalled
run as administrator and nothing works

### Expected behavior

the download should work and complete after a while via torrent but it doesn't happen

### Additional information and data

![image](https://github.com/user-attachments/assets/892b086c-7e4e-4269-8b98-5594b1cf525b)

### Operating System

windows 10

### Hydra Version

3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
go to %appdata%/hydra/logs and send the file pythoninstance.txt

**Comment by toofastforboo** [comment]
[pythoninstance.txt](https://github.com/user-attachments/files/17837464/pythoninstance.txt)

**Comment by JackEnx** [comment]
all torrent you try to download is the same, and this torrent has no seeds: 
![image](https://github.com/user-attachments/assets/db8000df-5d5c-4086-881d-c863b84d848c)
please, try other torrent and check if works.
