### ISSUE TITLE
[REQUEST] Parâmetros de inicialização pros jogos

### ISSUE THREAD

**Issue by x02mateus** [hydralauncher/hydra#1247]
### Is your feature request related to a problem? Please describe.

O problema relacionado a sugestão é principalmente para jogar mods não-standalone (mods que usam a Goldsrc, mas não dependem do Half-Life 1 em si, que funcionam sozinho sem o EXE/arquivos do jogo original) de Half-Life. Isso é fácil utilizando params, e se não me engano, é a única forma possível de fazer isso (com parâmetros de inicialização).

O Half-Life 1 mesmo quando você adiciona os arquivos do mod baixado na pasta do jogo, não é possível inicializar eles pelo hl.exe (executável do jogo), já que isso faria o Half-Life 1 ser inicializado.

A solução é pra isso, é iniciar o Half-Life com o parâmetro -game cstrike (exemplo pro CS 1.6), porém, não é possível já que o Hydra não permite fazer isso diretamente no programa e o Windows não permite escrever parâmetros diretamente no EXE, obrigando o usuário a fazer um atalho que inicia o executável com os parâmetros e isso desencadeia em outro problema, se você colocar o atalho na opção de executável do jogo no Hydra, ele contará o tempo de jogo que você passa com o .ink aberto e não com o "hl.exe".

![image](https://github.com/user-attachments/assets/f01b11d2-de0c-48ed-a4b8-5bdf43911bfe)
![image](https://github.com/user-attachments/assets/ccf977cf-4645-4cd2-826c-5c2fa5eea0c0)

### Describe the solution you'd like

Adicionar uma opção de parâmetros de inicialização nas configurações do jogo, estilo a da Steam.
Exemplo:
![image](https://github.com/user-attachments/assets/015c5f21-22f9-4963-adfd-21f00d51d8ce)

**Comment by JackEnx** [comment]
duplicated  #914

**Comment by x02mateus** [comment]
ok
