### ISSUE TITLE
[BUG] No downloads available for all games

### ISSUE THREAD

**Issue by Leeoo-H** [hydralauncher/hydra#1248]
### Describe the bug

Hi! So, i just installed the launcher and it's saying that there are no download options for any game, even though i can look and see hundreds of thousands of downloads were made, i tried reinstalling, but that didnt work, i tried installing a previous Hydra version and updating and it didnt work, and like i dont know what to do to fix it so any help would be greatly appreciated

### Steps to Reproduce

1: i installed the hydra launcher through the "hydralauncher-3.0.5-setup.exe" file, 2: i followed the instalation process, 3: no download options appear

### Expected behavior

i expected that the download options wouldve appeared lol

### Additional information and data

![Captura de tela 2024-11-20 165102](https://github.com/user-attachments/assets/303ecc58-12eb-4fe4-b67e-8969d6a05e1d)
](url)

### Operating System

Windows 11

### Hydra Version

Hydra 3.0.5 "Skyscraper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).
