### ISSUE TITLE
[REQUEST] Feature question

### ISSUE THREAD

**Issue by L1nker2** [hydralauncher/hydra#1253]
### Is your feature request related to a problem? Please describe.

Good afternoon, development team. I have two questions for you.
First question: Do you plan to create the ability to filter and sort games by genre and other parameters?
Second question: Do you plan to introduce a feature of a bigpicture like in Steam for playing on a gamepad?

### Describe the solution you'd like

filter and sort games by genre and other parameters
feature of a bigpicture

**Comment by zamitto** [comment]
1. Yes
2. It is a complex feature and not a top priority right now. But probably in the future

**Comment by L1nker2** [comment]
thanks for the feedback. your project is very cool, don't abandon it =)
