### ISSUE TITLE
[BUG] Endless downloading of metadata | Бесконечная загрузка метаданных

### ISSUE THREAD

**Issue by Arktika-Tech** [hydralauncher/hydra#1256]
### Describe the bug

I wanted to download Fishing: North Atlantic - Enhanced Edition from KaOsKrew, but nothing happens beyond “loading metadata”. Help me decide, I will be glad :)                                                                                                                                 Sorry for my English

Хотел скачать Fishing: North Atlantic - Enhanced Edition от KaOsKrew, но дальше "загрузка метаданных" ничего не происходит. Помогите решить буду рад :)

### Steps to Reproduce

1) Open Hydra Launcher | Открыть Hydra Launcher
2) Start downloading the game | Начать загружать игру
3) Endless downloading of metadata | Бесконечная загрузка метаданных

### Expected behavior

The download should work and complete after some time via torrent.

Загрузка должна работать и завершиться через некоторое время через торрент.

### Additional information and data

![1](https://github.com/user-attachments/assets/bcabcf70-5304-496e-a541-fd6fd83aa432)
![2](https://github.com/user-attachments/assets/324b941b-4223-4256-9753-993b01e39707)

### Operating System

Windows 11

### Hydra Version

v3.0.5 "Skyscraper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Hachi-R** [comment]
this download is probably old and not seeded anymore

**Comment by Hachi-R** [comment]
as i said, this isnt a hydra issue, its most likely that download doesnt have seeders anymore

> This is most likely due to loading. I restarted Hydra and nothing changed. :) Started downloading the halyard 2021, it is downloading.

as i said, this isnt a hydra issue, its most likely that download doesnt have seeders anymore

**Comment by OneWay52z** [comment]
> Скорее всего, это из-за загрузки. Я перезапустил Гидру и ничего не изменилось. :) Начал качать фал 2021, качается.

Привет, знаю писал ты в прошлом году но можешь пожалуйста рассказать получилось ли у тебя это пофиксить?

Hi, I know you wrote this last year, but can you please tell me if you managed to fix this?
