### ISSUE TITLE
[BUG] Hydra Launcher v3.0.5 não inicia no Windows: "Failed to get 'documents' path"

### ISSUE THREAD

**Issue by tiagoassun** [hydralauncher/hydra#1258]
### Describe the bug

O Hydra Launcher não inicia corretamente e não exibe sua interface gráfica. O programa é executado em segundo plano, mas não abre como esperado. Utilizei o Git Bash no Windows 10 para executar o programa, e o log apresentou o seguinte erro:

`Unhandled Error: Failed to get 'documents' path
at getDocumentsPath (file:///E:/Games/Hydra/resources/app.asar/out/main/index.js:1979:22)
at file:///E:/Games/Hydra/resources/app.asar/out/main/index.js:2006:19
at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
at async node:electron/js2c/browser_init:2:125779
at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:138:5)
`

### Steps to Reproduce

1. Instale o Hydra Launcher v3.0.5 ("Skyscraper") no Windows 10.

2. Abra o Git Bash e navegue até o diretório de instalação utilizando:
`cd /e/Games/Hydra`

3. Tente iniciar o programa com o seguinte comando:
`./Hydra.exe --no-sandbox --verbose > hydra_log.txt 2>&1`

4. Verifique se o programa está sendo executado em segundo plano com:
`ps aux | grep Hydra`
- O comando confirma que o processo está em execução:
`362 332 362 27448 pty1 197609 20:46:37 /e/Games/Hydra/Hydra`

5. Verifique o arquivo de log gerado com:
`cat hydra_log.txt`
- O arquivo apresenta o seguinte erro:
`Unhandled Error: Failed to get 'documents' path
at getDocumentsPath (file:///E:/Games/Hydra/resources/app.asar/out/main/index.js:1979:22)
at file:///E:/Games/Hydra/resources/app.asar/out/main/index.js:2006:19
at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
at async node:electron/js2c/browser_init:2:125779
at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:138:5)
`

### Expected behavior

O Hydra Launcher deveria abrir normalmente e exibir sua interface gráfica sem apresentar erros.

### Additional information and data

**Diretório de instalação:** E:/Games/Hydra

**Arquivos presentes na pasta resources:**
- app.asar
- app-update.yml
- elevate.exe
- windows.vbs

**Comandos executados no Git Bash:**
1. Iniciar o programa:
`./Hydra.exe --no-sandbox --verbose > hydra_log.txt 2>&1`

2. Verificar o processo:
`ps aux | grep Hydra`
- Saída:
`362 332 362 27448 pty1 197609 20:46:37 /e/Games/Hydra/Hydra`

3. Verificar o log:
`cat hydra_log.txt`
- Saída do log:
`Unhandled Error: Failed to get 'documents' path
at getDocumentsPath (file:///E:/Games/Hydra/resources/app.asar/out/main/index.js:1979:22)
at file:///E:/Games/Hydra/resources/app.asar/out/main/index.js:2006:19
at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
at async node:electron/js2c/browser_init:2:125779
at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:138:5)
`

### Operating System

Nome do sistema operacional:               Microsoft Windows 10 Pro
Versão do sistema operacional:             10.0.19045 N/A compilação 19045

### Hydra Version

v3.0.5 - "Skyscraper"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Os logs dizem que sua pasta "Meus Documentos" do Windows não foi encontrada.
Poderia realizar o seguinte teste e nos dizer o resultado:
1. Apertar Windows + R
2. Digitar "documents" e apertar Enter

**Comment by tiagoassun** [comment]
Bom dia, @zamitto 

Digitei aqui, e aparece como a pasta existe sim. Abriu a janela normal.

![Captura de tela 2024-11-27 084058](https://github.com/user-attachments/assets/ed585e81-ec17-4e40-90e9-f61bd94e6387)

**Comment by tiagoassun** [comment]
Hi @Hachi-R 

Yes, the launcher icon appears in the Windows task manager.

![Captura de tela 2024-11-27 084309](https://github.com/user-attachments/assets/e592a341-8fcf-4ecb-b10c-e2370158c980)

I have attached the files "error.txt" and "logs.txt" for your review.
**Files**:
- [error.txt](https://github.com/user-attachments/files/17933756/error.txt)
- [logs.txt](https://github.com/user-attachments/files/17933757/logs.txt)

**Comment by tiagoassun** [comment]
Bom dia, @zamitto 

Depois do que vc falou sobre a pasta documentos, e eu ver que ela axiste e o Hydra não conseguir acessar. Achei que poderia ser alguma coisa de acesso não permitido ou coisa assim.

Então fui na pasta Documentos, e redirecionei ela pra outro local. Antes estava em "C:\Users\tiago\Documents" e agora está em "D:\OneDrive\Documentos", e isso resolveu o problema:
![Captura de tela 2024-11-27 085113](https://github.com/user-attachments/assets/e781c850-276e-462d-bf22-fecd2d28c816)

Voltou a abrir normalmente até o momento:
![Captura de tela 2024-11-27 085311](https://github.com/user-attachments/assets/e89cd56c-5425-4b2f-9977-0c63461144e6)

Não sei se foi alguma atualização do Windows que tornou, do nada, essa pasta Documentos dentro da pasta do meu usuario como restrita ou algo assim. Enfim, vlw!

**Comment by tiagoassun** [comment]
Problema solucionando alterando o local da pasta Documentos para um local no qual o Hydra consegue acessar.

**Comment by Hachi-R** [comment]
> Problema solucionando alterando o local da pasta Documentos para um local no qual o Hydra consegue acessar.

isso ocorre por conta do backup automático do one drive

**Comment by shirowoor** [comment]
@tiagoassun 

Opa, estou com mesmo erro, e fui nessa pasta apertei com botão direito e acessei propriedades, mas não consigo editar o local de acesso, a foto da pasta e diferente da sua também

**Comment by wallacerenan** [comment]
Para quem está com o problema é só reinstalar o OneDrive

**Comment by Gaabsqxy** [comment]
Instalei o OneDrive e voltou a funcionar
