### ISSUE TITLE
Erro em exibir o playtime/games na biblioteca

### ISSUE THREAD

**Issue by aglairvta** [hydralauncher/hydra#1259]
### Describe the bug

1. Erro ao exibir o playtime
Estou na versão Linux (.deb, 3.0.5). Instalo algum jogo, índico o caminho do executável, porém ao abrir não contabiliza as horas jogadas e nem indica que o jogo foi iniciado, exibindo a mensagem padrão “Você ainda não jogou X”. O jogo funciona normalmente.

---

2. Erro ao exibir games na biblioteca do perfil
Além disso, também estou com problema com os jogos presentes na biblioteca visível no meu perfil. Na seção da esquerda, exibe os jogos baixados, todos os quais já foram iniciados pela plataforma. No entanto, apenas 2 deles aparecem na biblioteca do perfil à direita.

### Steps to Reproduce

1. Instale um jogo
2. Indexe o executável em “Gerenciar“
3. Inicie o jogo

> Ocorre dos games não contabilizarem as horas jogadas, nem aparecerem no total na biblioteca do seu perfil.

### Expected behavior

- Horas dos jogos contabilizadas e exibidas na plataforma.
- Todos os jogos adicionados na seção de biblioteca presentes no meu perfil.

### Additional information and data

![1](https://github.com/user-attachments/assets/785dcb06-a440-4236-b522-6358c78cc1fb)

![2](https://github.com/user-attachments/assets/f1159077-9d35-4f1a-a374-9aae21b71b0a)

### Operating System

Linux Mint

### Hydra Version

3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
Qual o meu que você está utilizando para executar os jogos? lutris ou alguma outra plataforma? 
Sobre a biblioteca, se um jogo não é executado, um evento de execução do mesmo não ocorre, esse evento é necessario para que esta informação seja salva e exibida em perfil.

**Comment by aglairvta** [comment]
Eu estou rodando direto pelo wine, pois executar o game nunca foi um problema através deste. Agora com seu comentário vou testar com lutris/outros pra ver no que resulta. Obrigada pela resposta rápida.

**Comment by JackEnx** [comment]
A pergunta sobre plataforma é mais por questões de a depender de onde, o processo do jogo é executado de forma diferente no sistema, por hora o hydra ainda não tem suporte para rodar wine, alguns jogos requerem a utilização de alguns extras como winetrick e algumas dlls, um melhor suporte ao wine é algo planjeado futuramente.

**Comment by aglairvta** [comment]
Agradeço pelo esclarecimento.
