### ISSUE TITLE
Missing icon for discord (bug)

### ISSUE THREAD

**Issue by Rebecchi06** [hydralauncher/hydra#1260]
### Describe the bug

ok i just installed the 3.0.5 skycraper version and all the games in the plataform come with the donwload disabilited, reading de FAQ and forums i figured out that i need it to configure myself some downloads sourses from the community on discord, but my hydra version dont have the discord simbol for me to reach the community discord and after search a lot i coudnt finf the discord channel.
someone can please help me?
![Hydra_bug](https://github.com/user-attachments/assets/5fc4977f-bd8b-4f10-a454-24ef256d21d4)

### Steps to Reproduce

donwload version of hydra, [hydralauncher-3.0.5-setup.exe](https://github.com/hydralauncher/hydra/releases/download/v3.0.5/hydralauncher-3.0.5-setup.exe).
try to find the hiperlink of the discord.

### Expected behavior

on previous versions, have the icon for discord

### Additional information and data

![Hydra_bug](https://github.com/user-attachments/assets/0aecb43b-633e-448f-88e5-0dbe1368bddc)

### Operating System

windows 10

### Hydra Version

3.0.5-setup.exe

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by phgodoy** [comment]
can i fix this ?

**Comment by zamitto** [comment]
We don't have an official discord server. The discord server you are talking about is a community discord (created and managed by the community).
Others users have already posted the link in some issues
