### ISSUE TITLE
[Issue] i'm having a problem with my account and i loss my account

### ISSUE THREAD

**Issue by cafezin987** [hydralauncher/hydra#1266]
### Describe the bug

i had a account named cafezin987, but i tried my password and pin of recuperaton but it didn't work, so i losed my account and i created a new account if i can recover my account i can prove that i am the owner of the account

### Steps to Reproduce

i enter the hydra launcher, put my username and password or pin and doesn't work...

### Expected behavior

i expected that i was going to enter my account and play the lost in play

### Additional information and data

![imagem_2024-11-30_192859847](https://github.com/user-attachments/assets/524ebb17-57b1-4dc6-a15e-1d07fd51740b)
location of the files^
                              |

### Operating System

Windows 10

### Hydra Version

3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment]
for account recovery contact support@hydralauncher.gg
