### ISSUE TITLE
[BUG] The launcher is flickering and displaying graphical glitches.

### ISSUE THREAD

**Issue by jose0013** [hydralauncher/hydra#1272]
### Describe the bug

My Hydra launcher is experiencing a bug that I can't quite identify. Whenever I interact with it, the launcher flickers a lot, disappearing and reappearing completely. It seems to be a graphical glitch that's only happening with this application. Does anyone know what it might be or how to fix it?

### Steps to Reproduce

Just opening the launcher causes the issue. As soon as I open it, graphical errors start, and the entire launcher begins flickering.

### Additional information and data

https://github.com/user-attachments/assets/8c4e2cad-b9bd-483f-8f06-a7cc736ad7f6

https://github.com/user-attachments/assets/aee484cc-72e0-4014-b388-802eac84e965

### Operating System

Windows 11

### Hydra Version

3.0.6-portable

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by jose0013** [comment]
I activated g-sync but also restored the settings in my nvidia control panel, then it went back to normal.

**Comment by Lapokoshmala** [comment]
It's simple.
go to shortcut properties and type --disable-gpu-compositing, it should say "C:\Program Files\Hydra\Hydra.exe" --disable-gpu-compositing.
This option will be better than disabling MPO, because without MPO you won't have g-sync in many games.
You should write --disable-gpu-compositing in the “object” field.

**Comment by Nefarius1908** [comment]
tell me in more detail where to write --disable-gpu-compositing, otherwise I don't understand
