### ISSUE TITLE
[BUG] Can't login

### ISSUE THREAD

**Issue by n1ckSn1ckS** [hydralauncher/hydra#1278]
### Describe the bug

I had to uninstall and install again the launcher and now I can't login because I don't remember my username just my e-mail used.
Sent e-mail for support@hydralauncher.gg but it doesn't work it says that the address couldn't be found, or is unable to receive mail.

### Steps to Reproduce

Open the app, try to logon

### Additional information and data

<html>
<body>

Address not found
--
Your message wasn't delivered to support@hydralauncher.gg because the address couldn't be found, or is unable to receive mail.

</body>
</html>

### Operating System

Win11

### Hydra Version

3.0.6

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
That's odd. We've just received an email asking for support from users. Could you try again today? Maybe using another email provider if possible?

**Comment by n1ckSn1ckS** [comment]
I've tried with my gmail... Tried again today and worked. Solved the problem with the login too.
Thank you
