### ISSUE TITLE
Change game executable location

### ISSUE THREAD

**Issue by RlrMatoso** [hydralauncher/hydra#130]
I accidentaly set the location of the executable of one of my games to the installer instead of the game, so when I click play it tries to install.
An option to change the path to the game's executable would be extremely helpfull.

**Comment by zamitto** [comment]
It is a planned feature (#118)

Until this feature is implemented, an alternative option to solve your problem would be: remove the game from your library and then add it again. It will ask you to choose an .exe location and you could set the right one

**Comment by zamitto** [comment]
In 2.0 we added a new window which gives you this possibility
