### ISSUE TITLE
[REQUEST] Add the "Categories" menu to the Catalogue

### ISSUE THREAD

**Issue by gordaoescolas** [hydralauncher/hydra#1310]
### Is your feature request related to a problem? Please describe.

Not a problem, but it would be nice to add a game type filter to increase discoveries

### Describe the solution you'd like

A menu that would filter game categories (like racing, action, adventure, etc.)

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implement a game type filter in the catalogue page to allow users to filter games by category. This includes adding a new dropdown menu for selecting game types, updating the API call to include the selected filter, and modifying the UI to display the filter options.

You can review changes in this commit: https://github.com/wwqwq2313/hydralauncher-hydra-1310/commit/15ddf53ce7a1ccd5967f612f89017134d2673603.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by JackEnx** [comment]
This feature is planned for the next update on the 23rd.

**Comment by zamitto** [comment]
Done in 3.1.0
