### ISSUE TITLE
Processo extranho

### ISSUE THREAD

**Issue by retlAairtlA** [hydralauncher/hydra#132]
por algum motivo isso acontece comigo, o hydra ele abre um processo chamado tasklist e logo em seguida ele fecha  e depois abre e fecha infinitamente, pra mim n aparece nada no windows mas no gerenciador de tarefas fica uma doideira abrindo e fechando processo, as vezes ele começa a lagar o windows por conta desse processo
![Screenshot_242](https://github.com/hydralauncher/hydra/assets/61324721/c9687e9b-3754-4b88-870a-ede95c94cef8)
![Screenshot_246](https://github.com/hydralauncher/hydra/assets/61324721/518eef8d-c270-47ed-853b-a7effc10fb82)
![Screenshot_247](https://github.com/hydralauncher/hydra/assets/61324721/116bffdb-d431-4a6e-b112-27347d1dbf3f)

**Comment by mendeel** [comment]
Mestre, tasklist e conhost são processos do Windows e são a forma que o sistema executa as tarefas que o programa faz.

**Comment by 0LostConnection** [comment]
> Mestre, tasklist e conhost são processos do Windows e são a forma que o sistema executa as tarefas que o programa faz. O Hydra não está batendo lá na porta deles pra fazer algo, creio que tem relação com o fato do app ser em Electron e utilizar NodeJS por trás.

Continuando o que o @mendeel disse, o programa "Tasklist" apenas lista os processos ativos no momento de execução dele, nada de mais. O Hydra deve utilizar as informações geradas desse programa para alguma função interna.

**Comment by zamitto** [comment]
1. We ask to write the issues in English, there are a lot of non portuguese speakers that come to the repository
2. Yes, @0LostConnection is right, in the current release version we use tasklist to keep tracking of playtime.
3. The high cpu usage is already solved, we replaced the use of tasklist.exe with a faster version, using less CPU. This you will be in the next release

Closing this issue
