### ISSUE TITLE
[BUG] Hydra launcher stopped working in Russia

### ISSUE THREAD

**Issue by Nik-coderere** [hydralauncher/hydra#1328]
### Describe the bug

![Снимок экрана 2024-12-24 151634](https://github.com/user-attachments/assets/2cbd1127-5961-45c8-84eb-55201398885d)
The catalog, search bar, and download sources do not work in Russia.

### Steps to Reproduce

https://github.com/user-attachments/assets/9592984e-b71a-43e9-acd0-ea25dbdc2e70

### Additional information and data

I do not know what to do.
![Снимок экрана 2024-12-24 152348](https://github.com/user-attachments/assets/dc09b310-2881-4006-a7bf-255a0f57bb13)

### Operating System

Windows 11

### Hydra Version

3.1.2

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by Hawpeg** [comment]
Думаешь все таки нас заблокировали? Та же проблема.

**Comment by Nik-coderere** [comment]
Hawpeg скорее всего

**Comment by Hawpeg** [comment]
Nik-coderere В старой версии каталог все еще работает поэтому вряд ли(

**Comment by Nik-coderere** [comment]
Hawpeg этот каталог не работает из за стима скорее всего

**Comment by Hawpeg** [comment]
Nik-coderere Описание к уже добавленным играм сейчас подгружаются из стима (?) поэтому вряд ли

**Comment by thamiresb19** [comment]
same here in Brazil :(

**Comment by Hawpeg** [comment]
Nik-coderere Кст да, очень может быть тут же в changelog'e писалось что категории добавляли

**Comment by Nik-coderere** [comment]
thamiresb19 созываем разрабов чтоб решали эту хрень или делали версию со старым каталогом

**Comment by Hachi-R** [comment]
apparently cloudflare pages is blocking russia, we will fix it asap

**Comment by Nik-coderere** [comment]
Hachi-R fix this problem as soon as possible, otherwise it is impossible to use the hydra launcher in Russia

**Comment by Hawpeg** [comment]
and in Belarus, too(

**Comment by thamiresb19** [comment]
> thamiresb19 созываем разрабов чтоб решали эту хрень или делали версию со старым каталогом

thank you <3

**Comment by Nik-coderere** [comment]
Hawpeg это везде где есть запрещенные игры скорее всего

**Comment by Hawpeg** [comment]
Ну что? У меня заработало. (What's up? I got it working)

**Comment by Nik-coderere** [comment]
Hawpeg можно закрывать разработчики молодцы
