### ISSUE TITLE
Relatively high CPU usage on low-end PC

### ISSUE THREAD

**Issue by Chapadin** [hydralauncher/hydra#133]
I noticed a relatively high use of the processor and RAM when Hydra is inactive, that is, without making any downloads.
I have a laptop with Core I3 1115G4 and Intel IGPU, I know it's not one of the best PCs nowadays, but it's what I have at the moment.
Sorry for my English, I'm using Google Translate because I'm BR.

![Captura de tela 2024-04-30 140305](https://github.com/hydralauncher/hydra/assets/147850373/881b6f8a-7299-4fef-b7c5-3a290e61d513)

![image](https://github.com/hydralauncher/hydra/assets/147850373/89d3a49e-0eea-4ca3-863d-c2898facbd1f)

**Comment by hydralauncher** [comment]
Thanks for reporting this issue. This is a bug that was introduced in v1.1.0, which has been already fixed and will be available in the next update:
https://github.com/users/hydralauncher/projects/1?pane=issue&itemId=61396364

Feel free to follow our Roadmap board. I'll keep this issue open as a duplicate.

**Comment by Renkoto** [comment]
> Thanks for reporting this issue. This is a bug that was introduced in v1.1.0, which has been already fixed and will be available in the next update: https://github.com/users/hydralauncher/projects/1?pane=issue&itemId=61396364
> 
> Feel free to follow our Roadmap board. I'll keep this issue open as a duplicate.

Hell, for a moment I had been scared and i was thinking that my PC was infected with a cryptominer because I also noticed that.
(Using Linux and the bug also happens there btw).

**Comment by mehfius** [comment]
![image](https://github.com/hydralauncher/hydra/assets/7073758/8d441cf3-83e9-4840-b3d7-c42217d3ca72)
High use cpu. Doing nothing.  Intel  i9 12 gen

**Comment by zamitto** [comment]
Since 1.2.0 the CPU usage has been improved by a lot. Closing this issue
