### ISSUE TITLE
[BUG] Pin inválido ao tentar redefinir senha

### ISSUE THREAD

**Issue by choraproteupai** [hydralauncher/hydra#1331]
### Describe the bug

quando vou redefinir a minha senha, o pin que me foi enviado no cadastro consta como inválido

### Steps to Reproduce

Eu entro na opção de entrar pelo pin, preencho as informações como login, senha nova e quando ponho o pin consta como inválido

### Expected behavior

,

### Additional information and data

![image](https://github.com/user-attachments/assets/999679f6-d71a-4eaa-ab38-9be92884a77a)

### Operating System

Windows 11

### Hydra Version

v3.0.8

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment]
Envie um email para support@hydralauncher.gg com o seu nome de usuario e qualquer outra informaçao que voce tenha da sua conta
