### ISSUE TITLE
acho que é um falso positivo

### ISSUE THREAD

**Issue by GGabrielCross** [hydralauncher/hydra#134]
Verifiquei no virustotal, mas não acho que seria um vírus

![Captura de tela 2024-04-30 150930](https://github.com/hydralauncher/hydra/assets/168583247/c567a62c-1223-4048-9043-adbc6eac7919)

**Comment by Chapadin** [comment]
É um falso positivo
O chrome e o Windows Defender bloquearam o hydra e excluiu o EXE do setup.
Eu consegui instalar o o Hydra Launcher no meu PC sem problemas
A única coisa que me deixou confuso foi que o setup não criou um Atalho na Área de Trabalho.
Caso ocorra com você também, o EXE do Hydra está em Appdata Local

**Comment by hydralauncher** [comment]
Closing this.
