### ISSUE TITLE
Please, add download games not only from the Torents

### ISSUE THREAD

**Issue by ogled** [hydralauncher/hydra#1346]
### Is your feature request related to a problem? Please describe.

I can't download games from torrents due to ISP restrictions 

### Describe the solution you'd like

Add the ability to download games from other places, for example, from telegram channel - Notorgames

**Comment by Pazdikan** [comment]
There's real debrid support and torbox on the way.

You can download the games yourself and add the exe in the launcher. I don't think a lot of people would want downloading games from telegram channels lol
