### ISSUE TITLE
Abnormal GPU Usage

### ISSUE THREAD

**Issue by Fgrtheaks** [hydralauncher/hydra#135]
When using the program I noticed that the GPU is at 12%, and it is an RTX 3050, I realized that the problem was corrected but I wanted to pass this on.

**Comment by hydralauncher** [comment]
Could you attach a screenshot or such? Was Hydra idling? Wast it running on the background? Please explain a little bit further.

**Comment by Fgrtheaks** [comment]
I noticed that this abnormal GPU consumption only occurs when the program is open, when I minimize consumption it stays at 4% or 5%.

**Comment by Fgrtheaks** [comment]
![Uploading Imagem do WhatsApp de 2024-05-01 à(s) 00.00.13_67b85667.jpg…]()

**Comment by Fgrtheaks** [comment]
![Imagem do WhatsApp de 2024-05-01 à(s) 00 00 13_67b85667](https://github.com/hydralauncher/hydra/assets/168587187/8698d1da-b4e2-4cca-9729-5c101ff49ee6)

**Comment by zamitto** [comment]
Could you provide a screenshot like this one? The one you sent tell us nothing about much Hydra specifically is using. It tells the total use all your processes.

![image](https://github.com/hydralauncher/hydra/assets/167933696/c535aeaf-3ff1-480f-b5c5-58998d5c2cff)

**Comment by Spillernatt** [comment]
My one has been using a little bit more without downloading anything too, is it normal? I got a RTX 3070 //I7-10th // 32gb 2666mhz ram

**_Not downloading_**
![image](https://github.com/hydralauncher/hydra/assets/63877530/c4d064fa-d467-4748-932a-f0cf6574d7b4)

_**Downloading**_
![image](https://github.com/hydralauncher/hydra/assets/63877530/b41cba5b-398e-4700-9acc-316b096a7c09)

**Comment by thegrannychaseroperation** [comment]
Solved in 2.0. Please open a new one if that's still an issue.
