### ISSUE TITLE
Add Addons

### ISSUE THREAD

**Issue by PedroBrantes** [hydralauncher/hydra#138]
As Hydra is an indexer, just like Stremio, it could support add-ons made by the community in order to optimize usage and facilitate development.

**Comment by zamitto** [comment]
Done in 2.0

**Comment by PedroBrantes** [comment]
> Done in 2.0

I didn't find it in the release notes

**Comment by zamitto** [comment]
We didn't call it add-ons, but the downloads sources achieve almost the same goal. The community can create its own files with lists of downloads and you can import them into your Hydra
