### ISSUE TITLE
small add to library bug

### ISSUE THREAD

**Issue by nunera** [hydralauncher/hydra#141]
This isn't a big deal but whenever you click add to library and click cancel, it adds the game to the library even though no executable is assigned to it. Not sure if this is intended or not.

**Comment by DanielRios549** [comment]
I would like an option to add to library even without an executable assigned, I know this bug does that, but what I mean is add to library and do not change the button to "Play" until an executable has been assigned.

**Comment by zamitto** [comment]
In 2.0 we reworked these actions. So this should be solved by now
