### ISSUE TITLE
Extremly low download speeds

### ISSUE THREAD

**Issue by maxiwee69** [hydralauncher/hydra#149]
When I download anything using the launcher its significantly slower that if i would download the torrent manually

**Comment by hydralauncher** [comment]
I hope you are aware that different torrents will have different download speeds. Having this said, I will assume that you compared the speed in between the very same torrent file in the two bittorrent clients, is that correct? If so, provide me more info about the number of seeds/peers in both clients and the download speed as well.

**Comment by maxiwee69** [comment]
I am indeed aware of that, i chose the torrent from fitgirl repacks for resident evil 4 and it says it has like 60 peers and 40 seeds, speed is around 2.5mb/s however if i am using qbittorrent i have like 15mb/s

**Comment by maxiwee69** [comment]
Ok so after a reboot it was completely fixed and I have the same download speeds as always
