### ISSUE TITLE
tem seedbox, vpn ou é realmente o torrent puro????

### ISSUE THREAD

**Issue by ghost** [hydralauncher/hydra#157]
é bom esconder o ip, gostaria de saber para instalar de forma segura.

**Comment by zamitto** [comment]
Please, keep discussions here in English.
Right now, Hydra downloads with direct torrents.
There are collaborators working to investigate ways to improve this feature

**Comment by hydralauncher** [comment]
It behaves just like any torrent client, no VPN, no proxy.
