### ISSUE TITLE
Add trailer and screenshots to game details

### ISSUE THREAD

**Issue by hydralauncher** [hydralauncher/hydra#158]

**Comment by Mkdantas** [comment]
Hi, can i contribute to this?
if so, what should be the source of the trailer and screenshots? do you use a specific CDN?

**Comment by zamitto** [comment]
Hey @Mkdantas! Actually this issue has already been taken, it's just not assigned yet to the contributor

**Comment by hydralauncher** [comment]
@GamesTocaBoca you can indeed respond to this

**Comment by hydralauncher** [comment]
@Mkdantas we haven't got any updates on this. Do you still wanna pick it up?
Also, please join our Discord server an grab the Collaborator role

**Comment by Mkdantas** [comment]
I do want it, 
what should be the source of the trailer and screenshots? do you use a specific CDN?

**Comment by hydralauncher** [comment]
@Mkdantas I highly recommend you to join the Discord so we can discuss it better. But yes, we can fetch the URLs from Steam's CDN which is provided by the `gameDetails` on the `game-details` page.

**Comment by zamitto** [comment]
@Mkdantas the discord is https://discord.com/invite/hydralauncher

**Comment by Mkdantas** [comment]
Thank you I will be working on this issue this weekend
