### ISSUE TITLE
Hydra doesn't open after install

### ISSUE THREAD

**Issue by Luixxxxxxx** [hydralauncher/hydra#159]
I disabled antivirus, install the hydra, and after nothing open, i tried open for the shortcut, and for the fold, and failed.

**Comment by zamitto** [comment]
Did any error message show up? Does it show in the process list?

**Comment by jaodeda** [comment]
I have the same problem, when installing version 1.1.0 my Hydra does not open, but I tried installing the previous version 1.0.1 and it opens normally

**Comment by Luixxxxxxx** [comment]
@jaodeda how do u install games in 1.0.1?

**Comment by Luixxxxxxx** [comment]
@zamitto any messages

**Comment by zamitto** [comment]
@Luixxxxxxx, not 100% sure, but this might be a known bug that will be fixed in the next release.
You can try to download the 1.0.1 as @jaodeda said.

**Comment by Luixxxxxxx** [comment]
@zamitto i downloaded the 1.0.1 and can't install games, only elden ring appears, and i search, don't works

![image](https://github.com/hydralauncher/hydra/assets/168689737/39c566b3-f16c-44a8-a087-96d4ebd17b9e)

**Comment by jaodeda** [comment]
> @jaodeda how do u install games in 1.0.1?

I still haven't found a way to solve this, I can just open it but cant install games, I tried updating Hydra directly through the program and still, when I update, it stops opening again

**Comment by zamitto** [comment]
Could you try to add the -no-sandbox option and run the 1.1.0 again?

![image-1.png](https://github.com/hydralauncher/hydra/assets/167933696/63d6f3d4-55a2-45ea-844c-636409f638c8)

**Comment by Luixxxxxxx** [comment]
@zamitto i tried -no-sandbox in 1.1, and works, ty bro

**Comment by Tobi719** [comment]
![20240502_152343](https://github.com/hydralauncher/hydra/assets/168771685/cbeeeb34-7f7d-417e-bcf2-98af43b806c2)
Someone help me, this error started appearing a few hours ago. Whenever I start hydra through setup, this error appears and I can't log in, I've already tried to solve it and I couldn't. If anyone can help me, I would be grateful.

**Comment by Peter3-1** [comment]
> Could you try to add the -no-sandbox option and run the 1.1.0 again?
> 
> ![image-1.png](https://private-user-images.githubusercontent.com/167933696/327379725-63d6f3d4-55a2-45ea-844c-636409f638c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3ODM1OTgsIm5iZiI6MTcxNDc4MzI5OCwicGF0aCI6Ii8xNjc5MzM2OTYvMzI3Mzc5NzI1LTYzZDZmM2Q0LTU1YTItNDVlYS04NDRjLTYzNjQwOWY2MzhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwMDQxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODFlNmZiYzM1MGNmNWE2NzUwODQ2MzQ4ZDE0ZGJlYTllZDVhNmFkMTc1NDQ5NWNmOTc3NGM4NThiYWI4ZWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bYK5ivWms0aikA4zj6Z_VtTzjJpV8zd8PlkzXwP-U8s)

thx bro, i had the same problem and this worked

**Comment by hydralauncher** [comment]
This has been (most likely) solved with the migration to electron-builder.
