### ISSUE TITLE
Trocar caminho do executavel do jogo

### ISSUE THREAD

**Issue by jmorcatti** [hydralauncher/hydra#160]
Um dica de um problema que tive, apertando em jogar selecionei o laucher errado, por ser minha primeira vez utilizando uma plataforma dessa.
Não encontrei uma opção para editar o caminho do executavel do botão jogar.
Seria uma dica para facilitar o uso.

Parabens pelo projeto, experiencia de primeiro usuario com software parecidos.

**Comment by zamitto** [comment]
Mesmo que o projeto seja brasileiro, pedimos pra todas as issues serem escritas em ingles.
Obrigado pelo comentário! Essa feature está planejada (#118) e deve ser disponibilizada nas próximas versões
