### ISSUE TITLE
[REQUEST] Add the option to colaborate with sources to download Games

### ISSUE THREAD

**Issue by gabriel7419** [hydralauncher/hydra#167]
Hello!

Searching for some specific games on the platform, I noticed some of them missing. Games like Total War: Rome II don't have any source to download from. Allowing users to collaborate with extra sources for games that don't have any way to download from the launcher will make the community more engaged in the project.

Of course, there would be some serious security questions since there are a lot of malicious torrents. To address this, we could implement a system like the Community Notes on X, where notes need to be approved by other users before appearing.

It is my suggestion, and I'm always open to more suggestions to make it possible. Thank you.

**Comment by thegrannychaseroperation** [comment]
This feature has been added in 2.0.
