### ISSUE TITLE
Jogos em outro idioma

### ISSUE THREAD

**Issue by henriquewilkee** [hydralauncher/hydra#175]
Bom dia, como sei o idioma do jogo que estou baixando? Baixei o Farming Simulator 22 e ele era apenas russo, não descobri como trocar o idioma, existem várias opções de downloads, mas n sei se alguma delas é sobre idioma

**Comment by zamitto** [comment]
I recommend you to join our discord server and ask your question on the support channel as this is a question not directly related to Hydra features.
