### ISSUE TITLE
[REQUEST] Melhorias no launcher

### ISSUE THREAD

**Issue by rackertp** [hydralauncher/hydra#185]
Bom dia, gostei muito do launcher, estão de parabéns.

Acredito que as seguintes melhorias ajudariam bastante os utilizadores, facilitando assim o manuseio,

1. Favoritar os jogos, pois já me ocorreu de passar por um jogo, não querer instalar no momento, e esquecer completamente o jogo.
2. Um executável melhorado. Pois após executar o setup, não me é criado o executável, tenho de ir na pasta AppData para buscar o executável.
3. A opção instalar, não desativa após instalar o jogo. De momento, tenho o jogo instalado, consigo jogar pelo launcher, mas a opção de instalar ainda continua ativada.

Grato pelo vosso tempo e um ótimo trabalho,

**Comment by hydralauncher** [comment]
Different topics, different issues. Please keep a single topic per issue. Closing this for now.
