### ISSUE TITLE
Arch package support?

### ISSUE THREAD

**Issue by HakaishinShwet** [hydralauncher/hydra#186]
It would be awesome if someone maintain arch package with which we can directly install and update over time rather than building ourself

**Comment by fhilipecrash** [comment]
There is already a package being maintained, here is the [link](https://aur.archlinux.org/packages/hydra-launcher) if you want to download it.
Let me know if you face problems with this package

**Comment by HakaishinShwet** [comment]
@fhilipecrash thanks dev :-))

**Comment by fhilipecrash** [comment]
> @fhilipecrash thanks dev :-))

You're welcome, the [link](https://aur.archlinux.org/packages/hydra-launcher-bin) is now different, I had to create a new package to add the -bin prefix

**Comment by DjallenDias** [comment]
> There is already a package being maintained, here is the [link](https://aur.archlinux.org/packages/hydra-launcher) if you want to download it. Let me know if you face problems with this package

I'm having issues on Manjaro Linux. When I open Hydra, a window with the app's logo appears. In this window, it shows that it's checking for updates or says it's updating, then it says it will restart the app. This cycle repeats, and from what I've seen in the system monitor, it keeps spawning more processes of itself

**Comment by zamitto** [comment]
> > There is already a package being maintained, here is the [link](https://aur.archlinux.org/packages/hydra-launcher) if you want to download it. Let me know if you face problems with this package
> 
> I'm having issues on Manjaro Linux. When I open Hydra, a window with the app's logo appears. In this window, it shows that it's checking for updates or says it's updating, then it says it will restart the app. This cycle repeats, and from what I've seen in the system monitor, it keeps spawning more processes of itself

This window was removed in update 2.0
This problem was one of the reasons we removed it and changed the auto update notification.
Could you try uninstalling your current version and downloading the latest release?

**Comment by DjallenDias** [comment]
> This window was removed in update 2.0 This problem was one of the reasons we removed it and changed the auto update notification. Could you try uninstalling your current version and downloading the latest release?

Hydra in AUR is at version 1.2.4, so I think I'll need to build the app, and I don't know how to do this.

**Comment by mrh-ofici** [comment]
> > This window was removed in update 2.0 This problem was one of the reasons we removed it and changed the auto update notification. Could you try uninstalling your current version and downloading the latest release?
> 
> Hydra in AUR is at version 1.2.4, so I think I'll need to build the app, and I don't know how to do this.

do you achieved?
i am with the same problem and when i try to use the appimage it not do downloads among other bugs that happen

**Comment by DjallenDias** [comment]
> do you achieved? i am with the same problem and when i try to use the appimage it not do downloads among other bugs that happen
> 
> i am using garuda linux with hyprland

I've installed the appimage version and everything is okay, it can download and install the games with wine, but not every game run
