### ISSUE TITLE
[REQUEST] Real Debrid Support

### ISSUE THREAD

**Issue by JoseLuizFranco** [hydralauncher/hydra#196]
Real Debrid or other Debrid providers may be a great security addition.

**Comment by zamitto** [comment]
This is in development. Can't say when, but I'll try to comment here to update you when we release a version with Debrid support

**Comment by JoseLuizFranco** [comment]
Great to know, will keep an eye on it. Thanks

**Comment by hydralauncher** [comment]
Closing this since Real Debrid has been implemented on the main branch.
