### ISSUE TITLE
Replace electron with Tauri

### ISSUE THREAD

**Issue by NoelJacob** [hydralauncher/hydra#202]
I could make a pull request, if it's ok.

**Comment by hydralauncher** [comment]
It's okay.

**Comment by pedrosantayana** [comment]
Using Tauri/Rust instead of Electron, we could use libtorrent bindings for Rust and abandon the Python ones.

**Comment by IBorgesDev** [comment]
Wails its a great idea as well.

**Comment by NoelJacob** [comment]
To do it the backend aka `src/main` will be needed to made into Rust. Around 3K LOC. I can do it when I'm free soon.

We could do it in other ways like compiling `src/main` into a nodejs embedded exe and calling `src/render` in a webview but that would be a hassle to develop and maintain.

**Comment by zamitto** [comment]
Buddy, there is absolutely no reason to migrate all this code to another stack.
Electron works just fine.
If you want to collaborate in other features or talk about the project, feel free to join our Discord server

**Comment by IBorgesDev** [comment]
> Buddy, there is absolutely no reason to migrate all this code to another stack.
> Electron works just fine.
> If you want to collaborate in other features or talk about the project, feel free to join our Discord server 

chubby explained that the memory problem was related to the search system, sqlite limitations, i agree, changing to another stack wont fix the problem entirely.

**Comment by NoelJacob** [comment]
>  Electron works just fine.

Well, that's why I asked if it's [ok](https://github.com/hydralauncher/hydra/issues/202#issuecomment-2094824966) first 🙂

**Comment by hydralauncher** [comment]
@NoelJacob I said that it was okay to open a pull request, and it is indeed fine. We can go through the pros and cons of the implementation, but I don't really think that it's viable to refactor the whole Hydra codebase right now, specially the scrapers.
But let me know what you think.
