### ISSUE TITLE
Antivirus desinstala o launcher toda vez

### ISSUE THREAD

**Issue by rafraleo** [hydralauncher/hydra#208]
Não consigo instalar o launcher porque o Avira sempre coloca todos os arquivos em quarentena e trava, pedindo pra reiniciar o pc. Quando reinicio, ele não deixa eu tirar os arqvuios de quarentena, dizendo "não foi possivel restaurar os items". Ja instalei com o Avira desligado, mas aí quando reinicia o pc ele liga e faz a mesma coisa. 

Tem alguma forma de instalar e fazer o antivirus deixar ele no PC?

**Comment by Spillernatt** [comment]
Todos os antivírus vão dar como se o Hydra fosse nocivo pro computador, você precisa manualmente colocar ele como confiável, nao sei como é o seu antivírus, mas tem uma [pagina sobre a quarentena no site oficial](https://support.avira.com/hc/en-us/articles/360003070838-Restore-or-delete-quarantined-files).

**Comment by darkjontex** [comment]
Uma dica que posso deixar é você desativar o antivirus totalmente, fazer a instalação do Hydra Launcher e colocar a pasta do Hydra como diretório de excessão em seu antivirus. Todo antivirus tem essa opção e possibilidade.
Tutorial exemplo para o Microsoft Windows Defender, porém todos os antivirus tem algo similar:
[Tutorial oficial da Microsoft](https://answers.microsoft.com/pt-br/windows/forum/all/windows-10-adicionar-exce%C3%A7%C3%B5es-no-windows/71ebebbd-4e94-40fa-98d5-8308b4ad5a4f)

O diretório padrão de instalação do Hydra Launcher no Windows é:
`
"X:\Users\"_**NOME DO SEU USUÁRIO**_"\AppData\Local\hydra"`

**Comment by hydralauncher** [comment]
Not much that we can do about it. Closing this.
