### ISSUE TITLE
White screen when downloading a game and leaving the hydra minimized

### ISSUE THREAD

**Issue by IBorgesDev** [hydralauncher/hydra#209]
Sometimes when u open the launcher and leave a game downloading there and start doing something else, the launcher goes full blank.

![image](https://github.com/hydralauncher/hydra/assets/142950797/8043c96f-a43c-49d0-8ab1-7dce38130e0e)

downloading btw
![image](https://github.com/hydralauncher/hydra/assets/142950797/178c33d7-3658-40d4-a73a-03b4d75cc9f1)

**Comment by hydralauncher** [comment]
This has been fixed.
