### ISSUE TITLE
[REQUEST] Add option to manage game files

### ISSUE THREAD

**Issue by Spillernatt** [hydralauncher/hydra#220]
While using Hydra i noticed we have options such as Instal and play, but what if i wanted to uninstal and/or manage the game files quickly? It seems a simple thing but for people like me that instal and uninstal games quickly to try out more games it's important. 
**_Loving Hydra so far!! go team!_**

**Comment by zamitto** [comment]
In 2.0 we added a new window which gives you this possibility
