### ISSUE TITLE
[BUG] Game image not loading properly

### ISSUE THREAD

**Issue by Spillernatt** [hydralauncher/hydra#223]
Anyone has seen this bug with other titles? Is it because there's no image regarding the game or something like that?

https://open.hydralauncher.site/?p=WyIzODY3MTAiLCJzdGVhbSIsIkMlM0ElNUNyYWZ0IiwicHQtQlIiXQ%3D%3D

![image](https://github.com/hydralauncher/hydra/assets/63877530/bdb945ad-5304-423f-9fbe-508b32d14762)

**Comment by hydralauncher** [comment]
This game has a header (https://cdn.cloudflare.steamstatic.com/steam/apps/386710/header.jpg), but seems to lack both logo and hero (which are the images displayed on the game details).
https://cdn.cloudflare.steamstatic.com/steam/apps/386710/library_hero.jpg
https://cdn.cloudflare.steamstatic.com/steam/apps/386710/logo.png
