### ISSUE TITLE
'startGameDownload': TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by mrtom31** [hydralauncher/hydra#229]
When I try to download any game:
```
Error occurred in handler for 'startGameDownload': TypeError: Cannot read properties of undefined (reading 'id')
    at getSteamGameIconUrl (file:///home/thomas/hydra/out/main/index-NFpcPGOw.js:65:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startGameDownload (file:///home/thomas/hydra/out/main/index-NFpcPGOw.js:826:45)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:77963)
```

**Comment by JakeMartinezz** [comment]
Probably you forgot to edit your .env
Happened to me as well.

**Comment by mrtom31** [comment]
I filled `.env` but maybe with wrong values:
-  `MAIN_VITE_STEAMGRIDDB_API_KEY=` I put my steam API KEY
-  `MAIN_VITE_ONLINEFIX_USERNAME=` steam username
-  `MAIN_VITE_ONLINEFIX_PASSWORD=` steam password
-  `MAIN_VITE_SENTRY_DSN=` React js sentry dns
-  `RENDERER_VITE_SENTRY_DSN=` same value as above

I tried with and without " ".

**Comment by Chr1s0Blood** [comment]
Hey dude. I had this problem yesterday with the "getSteamGameIconUrl" function. It is caused by the lack of steamgriddb api key in the .env and you have to restart the application with "yarn dev" to work.

**Comment by Chr1s0Blood** [comment]
> I filled `.env` but maybe with wrong values:
> 
> * `MAIN_VITE_STEAMGRIDDB_API_KEY=` I put my steam API KEY
> * `MAIN_VITE_ONLINEFIX_USERNAME=` steam username
> * `MAIN_VITE_ONLINEFIX_PASSWORD=` steam password
> * `MAIN_VITE_SENTRY_DSN=` React js sentry dns
> * `RENDERER_VITE_SENTRY_DSN=` same value as above
> 
> I tried with and without " ".

"MAIN_VITE_ONLINEFIX_*" It's not about steam

**Comment by Chr1s0Blood** [comment]
https://www.steamgriddb.com/

Create an account on this site and generate an API KEY

Copy the API KEY and put it on .env in MAIN_VITE_STEAMGRIDDB_API_KEY

**Comment by mrtom31** [comment]
Thanks that was it. I put steam API key (20e to get a game and then a key) instead of steamgriddb.
