### ISSUE TITLE
"HowLongToBeat" feature not working

### ISSUE THREAD

**Issue by Dredgun** [hydralauncher/hydra#233]
The image i just submited show that the feature "HowLongToBeat" is not working properly on my windows 11 laptop. i do not know if it is due to the version of currently im suing or not, but everything else is working just fine.

![image](https://github.com/hydralauncher/hydra/assets/169204216/d5a24afc-4dc6-4486-bec6-8e7b8f40e036)

**Comment by jrgf** [comment]
Seems to be a problem with axios to fetch de data from HowLongToBeat. Can you try closing the app and open it again?

**Comment by Dredgun** [comment]
yeah i just tried to do that and even with the same game as you. did not work sadly

![image](https://github.com/hydralauncher/hydra/assets/169204216/ceb089d7-b602-4413-9905-29debf461b3b)

**Comment by Dredgun** [comment]
yup it all checks out fine 

![image](https://github.com/hydralauncher/hydra/assets/169204216/63a0a4cc-d0ae-44fd-843c-2bf850c6c2a7)

**Comment by BRVN01** [comment]
I have the same problem.

**Comment by hydralauncher** [comment]
It's a known bug on 1.1.0. Will be patched on next release.

**Comment by Dredgun** [comment]
appreciate you and your work
