### ISSUE TITLE
[BUG] Botão de adicionar à biblioteca

### ISSUE THREAD

**Issue by silv4b** [hydralauncher/hydra#240]
[BUG] Ao clicar no botão de adicionar à biblioteca, a janela para seleção de pasta, abre normalmente, porém, caso a mesma seja fechada (sem que uma pasta seja selecionada), os botões mudam 
De:
![image](https://github.com/hydralauncher/hydra/assets/17997794/5b6ce3d5-414c-415f-873f-44c7b3a6b4c6)
Para:
![image](https://github.com/hydralauncher/hydra/assets/17997794/6fc80e4e-7dcc-4289-b6f2-5e4ab459d350)
Sem que nenhum jogo tenha sido baixado ou selecionado.

Passo a passo:
1. Página do jogo, acessado a partir do botão de sugestões.
![image](https://github.com/hydralauncher/hydra/assets/17997794/757be112-dd6b-4915-844a-2ecfb16a12de)
2. Pasta do SO aberta para seleção. Cliquei em "cancelar":
![image](https://github.com/hydralauncher/hydra/assets/17997794/0a0d02fe-456c-465c-a708-800dba792079)
3. Botões alterados:
![image](https://github.com/hydralauncher/hydra/assets/17997794/754e1bd8-6417-49cb-9449-b36ef9dae46f)

É isso!

**Comment by zamitto** [comment]
In 2.0 we reworked this actions and this should not be an issue anymore
