### ISSUE TITLE
I can't open launcher after installing

### ISSUE THREAD

**Issue by Dominhoco** [hydralauncher/hydra#245]
After downloading and installing the launcher, it does not start in any way. Does anyone know any way to resolve this? (I don't have any antivirus active on my PC)

**Comment by jaodeda** [comment]
Yeah, try this
![try this](https://github.com/hydralauncher/hydra/assets/168692183/e91ddc16-d7e2-4130-8986-9aca9e708c4a)

**Comment by zamitto** [comment]
Please, see releases page and download new update. This issue has been fixed
