### ISSUE TITLE
Trava após alguns segundo aberto

### ISSUE THREAD

**Issue by AbraaoRocha** [hydralauncher/hydra#250]
Após alguns segundos aberto, o aplicativo simplesmente trava, e é não consigo utilizar.

SO: Windows 11

**Comment by MateusOK** [comment]
Também estou com o mesmo problema, uso o Windows 10

**Comment by zamitto** [comment]
Do you have on going downloads or a fresh install?

**Comment by tiagovribas** [comment]
> Do you have on going downloads or a fresh install?

got the same problem on win10, didnt have any on going downloads

**Comment by zamitto** [comment]
Please, see releases page and download new update
