### ISSUE TITLE
Reconfigurar jogo instalado

### ISSUE THREAD

**Issue by ramonpego** [hydralauncher/hydra#251]
Baixei um jogo e na hora de instalar o cliente Hydra abriu o gerenciador de arquivos para que eu selecione o executavel do jogo.
Porem eu escolhi o executável errado e agora ele salvou esse arquivo e não consigo trocar, mesmo desinstalando o jogo quando baixo de novo ele ja volta com isso configurado. 
Tem algum lugar que eu consiga alterar isto ?

**Comment by darkjontex** [comment]
Tem. É que no momento não tem um menu de contexto para ficar claro o que cada item faz. Vai ser melhoria para o Hydra Launcher em algum momento.
Enquanto não tem, você pode remover o jogo da biblioteca (isso apenas tira ele da sua lista).
E a opção adicionar jogo a biblioteca vai estar habilitado. Clique em adicionar jogo e escolha o exe do seu computador.
Veja:

![image](https://github.com/hydralauncher/hydra/assets/8375650/47fab69e-1ae9-41d2-ae5e-29b3a254d1fd)

Isso serve para qualquer jogo, inclusive se não for baixado pelo Hydra Launcher. Se selecionar um exe ou arquivo errado, basta fazer isso que resolve.

**Comment by ramonpego** [comment]
Muito Obrigado
