### ISSUE TITLE
Launcher não reconhece o jogo mais

### ISSUE THREAD

**Issue by Gabriel-mb** [hydralauncher/hydra#252]
Quando eu seleciono a opção de remover o instalador do jogo, o launcher só esqueceu onde o jogo estava instalado e deu a opção de instalar novamente e não permitiu selecionar o local de instalação do jogo.

**Comment by darkjontex** [comment]
Esse erro é estranho, teria algum passo a passo de como fez para ter esse problema?

De todo modo, você pode limpar o cache do Hydra Launcher, isso certamente vai resolver, porém você vai ter que configurar sua lista de jogos novamente, porque ela também vai ser perdida (não vai desinstalar jogo nem nada, apenas não vai ter os jogos listados).

Para fazer a limpeza de cache faça isso:
- Abra seu Explorer ou Windows+R e digite: `**%appdata%** `

- Procure a pasta Hydra, entre na pasta e delete todos os arquivos dentro desta pasta.

Importante o **Hydra Launcher** não estar rodando quando for fazer isso, se não você não vai conseguir deletar todos os arquivos de cache desta pasta por estarem em uso.

Depois é executar o **Hydra Launcher**, buscar o jogo que quer adicionar e clicar em **adicionar à biblioteca** e escolher o executável do jogo onde esta instalado e pronto.

**Comment by Gabriel-mb** [comment]
Então, ao baixar ele nos da a opção de instalar o jogo que ao clicar, te leva para o .exe do instalador. Depois de instalado, se você for na pagina de downloads e clicar em remover instalador, a opção de jogar some e aparece somente remover ou ver opções de download. Clicando em remover, resolve o problema e a opção de selecionar o local do jogo aparece novamente.

![Screenshot_1](https://github.com/hydralauncher/hydra/assets/91752665/3b150d24-107d-4f76-bb40-eedfa8ff7045)
![Screenshot_2](https://github.com/hydralauncher/hydra/assets/91752665/989a4f31-be4f-418b-b5f0-af99d72059f5)
![Screenshot_3](https://github.com/hydralauncher/hydra/assets/91752665/6e290cda-9430-477e-a8d4-2aa8cdfceeed)

**Comment by darkjontex** [comment]
Entendi. Esse comportamento deve ser corrigido com a melhoria do menu de contexto que a equipe do Hydra esta atuando.
Não fica claro para o usuário o que cada opção faz e como reverter. Mas que bom que resolveu o problema.

**Comment by zamitto** [comment]
This should be fixed since 2.0, as we added a new window to update the game executable and reworked all this screen
