### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Raqnick** [hydralauncher/hydra#258]
When I click on the game profile it tries to open, but closes
**To Reproduce**

1. Go to 'Catalogue'
2. Click on 'God of War'
3. See error

Game's profile is expected to open

**Additional context**

- OS: Windows 11
- Hydra Version:1.1.0
- Additional information and context of your problem:

https://github.com/hydralauncher/hydra/assets/95162518/806d8504-8190-453b-ac10-2072eefe5877

**Comment by tester1356** [comment]
the same problem with other games, maybe it's due to the load on the servers or something like that

**Comment by Raqnick** [comment]
> the same problem with other games, maybe it's due to the load on the servers or something like that

I'm not sure, because the issue still persists, but other games like Outer Wilds works

**Comment by iHelops** [comment]
This bug occurs if the game is not available in your Steam region. Enabling VPN may solve the issue. Check this issue: https://github.com/hydralauncher/hydra/issues/259

**Comment by zamitto** [comment]
Please, see releases page and download new update
