### ISSUE TITLE
The game page does not open

### ISSUE THREAD

**Issue by tester1356** [hydralauncher/hydra#259]
**Describe the bug**
When you click on the game page, it either does not open or opens after several clicks

**To Reproduce**
open any game page

**Screenshots**

**Additional context**
the error no results found appears for a moment
- OS: win10
- Hydra Version: 1.1.0

**Comment by TaPO4eg3D** [comment]
try enabling VPN if torrent trackers are banned in your country

**Comment by meaningg** [comment]
Same thing.
Even if i use VPN some game pages doesn't open, for example "Total war warhammer 2"

**Comment by tester1356** [comment]
> try enabling VPN if torrent trackers are banned in your country

Even with VPN this dont working, game page opens and disappears at the same moment

**Comment by tester1356** [comment]
> > try enabling VPN if torrent trackers are banned in your country
> 
> Even with VPN this dont working, game page opens and disappears at the same moment

with vpn game page opens, but looks like that
![image](https://github.com/hydralauncher/hydra/assets/169451148/bd4293d5-0019-4186-9ca2-e44a79997b64)

**Comment by avalage** [comment]
same issue even with VPN

**Comment by SxNine** [comment]
It's the same for me.
From the "Catalog" section, any page with the game opens properly, but if you try to open the page with the game using the search, the page opens and closes instantly.

**Comment by kotenok2000** [comment]
It happens to Quantum Break

**Comment by katsukibtw** [comment]
I just discovered that if the game you want to open is not available in your region on steam, then the game page in hydra will not open either. This happens because the game data is fetched directly from the steam page without any proxy. The problem can be solved by using vpn, but it is better to just add a proxy directly to the game data request

**Comment by tester1356** [comment]
> I just discovered that if the game you want to open is not available in your region on steam, then the game page in hydra will not open either. This happens because the game data is fetched directly from the steam page without any proxy. The problem can be solved by using vpn, but it is better to just add a proxy directly to the game data request

you a genius

**Comment by tester1356** [comment]
> I just discovered that if the game you want to open is not available in your region on steam, then the game page in hydra will not open either. This happens because the game data is fetched directly from the steam page without any proxy. The problem can be solved by using vpn, but it is better to just add a proxy directly to the game data request

i switched steam account, but this dont work even with serbian account

**Comment by UnKitsune** [comment]
> > I just discovered that if the game you want to open is not available in your region on steam, then the game page in hydra will not open either. This happens because the game data is fetched directly from the steam page without any proxy. The problem can be solved by using vpn, but it is better to just add a proxy directly to the game data request
> 
> i switched steam account, but this dont work even with serbian account

It doesn’t matter what account you have on Steam, the request does not go through it, but directly, so this needs to be done by Hydra developers.

**Comment by tester1356** [comment]
> It doesn’t matter what account you have on Steam, the request does not go through it, but directly, so this needs to be done by Hydra developers.

that is, we need to wait for the patch?

**Comment by UnKitsune** [comment]
> > It doesn’t matter what account you have on Steam, the request does not go through it, but directly, so this needs to be done by Hydra developers.
> 
> that is, we need to wait for the patch?

It looks like it. And no one knows how long it will take.

**Comment by bloodtoha** [comment]
> I just discovered that if the game you want to open is not available in your region on steam, then the game page in hydra will not open either. This happens because the game data is fetched directly from the steam page without any proxy. The problem can be solved by using vpn, but it is better to just add a proxy directly to the game data request

and why does he take data from steam at all? And how do I add a proxy there and will it affect the download?

**Comment by kotenok2000** [comment]
Unfortunately steamdb isn't used in 1.1.0

**Comment by tester1356** [comment]
> Unfortunately steamdb isn't used in 1.1.0

I noticed this too, but then it becomes generally unclear why this error appears

**Comment by alcoartist** [comment]
Same here, page not showing. No vpn. Ghost Recon: Wildlands. Game is not available officially in my region.

**Comment by tester1356** [comment]
> Same here, page not showing. No vpn. Ghost Recon: Wildlands. Game is not available officially in my region.

it doesn't matter if the game is available, it's Hydra's own fault

**Comment by igor-kurenkov** [comment]
Same problem. Game page won't open from search

**Comment by Planeptunia** [comment]
Have a problem with a game Atomic Heart, on trying to open just goes back to catalogue, game not officially available in steam

**Comment by Nx0Ri** [comment]
happens to cyberpunk 2077

**Comment by zamitto** [comment]
Please, see releases page and download new update
