### ISSUE TITLE
[BUG] hydra wont open without crashing instantly

### ISSUE THREAD

**Issue by skyer1a** [hydralauncher/hydra#266]
**Describe the bug**
hydra just crashes entirely and i cant open it properly.
its able to open for about 5 seconds but as soon as i tab out or click something within the launcher, it just crashes.

**To Reproduce**
idk, just open hydra launcher on the latest version of windows 11

**Expected behavior**
i expected hydra to launch normally and just work but i cant do anything on it at all.

**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/144589136/e8fc7b0d-4ae2-487e-9d6e-5bb2508203ab)

**Additional context**

- OS: Windows 11
- Hydra Version: 1.1.0

**Comment by skyer1a** [comment]
kinda disappointed with this because it doesnt work at all :/

**Comment by Momo26r** [comment]
+1

**Comment by Nightcoder777** [comment]
+1

**Comment by levenimeux** [comment]
I have the same problem.

**Comment by tiagovribas** [comment]
+1
OS: Windows 10
Hydra Version: 1.1.0

**Comment by zamitto** [comment]
Are all of you with fresh installs?
Or did someone already had Hydra installed and this behaviour started recently?

**Comment by skyer1a** [comment]
I’m on a fresh install, I’ve never ever had hydra installed before. Also I
have done several fresh installs and had the same issue

**Comment by MaKeSter333** [comment]
+1
Hydra version 1.1.0
Windows 11

**Comment by zamitto** [comment]
Even with this message saying that the program isn't responding, could you try leave it open for a few minutes? 
The UI is probably freezing because of a heavy torrent being processed during the scrapping, if you get past this torrent, you should be fine afterwards.

**Comment by lucassfernando** [comment]
+1
Hydra 1.1.0
Windows 10

**Comment by skyer1a** [comment]
Nope. Literally as soon as I installed it after the initial setup file, it
froze up after opening and it just does that now. No torrents, nothing.
Also the app isn’t optimised at all, which could be why it’s crashing so
much.

**Comment by andriy8800555355** [comment]
+1 
But, after X seconds he start work good

**Comment by levenimeux** [comment]
After a few freezes, the program is working properly.

**Comment by zamitto** [comment]
Please, see releases page and download new update
