### ISSUE TITLE
[BUG] what is the password for the downloaded archives

### ISSUE THREAD

**Issue by Tarrlay** [hydralauncher/hydra#268]
I'm just not very smart and please tell me what the password is

**Comment by ChristoferMendes** [comment]
try online-fix.me

**Comment by HOLKus** [comment]
It would be nice to add this information to the description

**Comment by Tarrlay** [comment]
when downloading the game, I have an offer to open an archive that is password-protected and I do not know what to do with it

**Comment by ChristoferMendes** [comment]
> when downloading the game, I have an offer to open an archive that is password-protected and I do not know what to do with it

Try typing online-fix.me on the password. It is the password required for some repacks

**Comment by Tarrlay** [comment]
Bro, you have no idea how much you helped me, thank you so much!!!
> 
> Try typing **online-fix.me** on the password. It is the password required for some repacks

**Comment by Enot52dig** [comment]
help me download ride 5 from hydra launcher and I don't know the password
![Снимок экрана 2024-11-04 134201](https://github.com/user-attachments/assets/b42588a9-e491-4f81-b37b-e0ffc5df3635)

**Comment by Enot52dig** [comment]
![Снимок экрана 2024-11-04 135217](https://github.com/user-attachments/assets/a854aece-54ee-4670-8dbf-f53a45e748a1)
This?

**Comment by Tarrlay** [comment]
any of this
