### ISSUE TITLE
[BUG] low perfomance

### ISSUE THREAD

**Issue by delyfss4796** [hydralauncher/hydra#274]
Hydra first 2 minutes uses more CPU than minecraft, intellij idea and discord combined

- OS: Manjaro Linux 23.1.4 Vulcan x86_64 
- Hydra Version: last

**Comment by brezzgg** [comment]
+1
- windows 11
- last

**Comment by lumenpearson** [comment]
Maybe it's due to using Electron - quite heavy framework in the project, maybe changing to Tauri fixed the problem. But again, this requires almost complete redesign of the hydra project + there are some plugins and accesses to system api that are available on Electron, not on the same Tauri. Tough case.

**Comment by lumenpearson** [comment]
+1

- macos 12.6.2
- last

**Comment by zamitto** [comment]
Actually, Electron is not the cause
We are aware of the high use of CPU and it has already been fixed. We are soon releasing the next version with these improvements

**Comment by zamitto** [comment]
Just to be more specific, the main cause was the way Hydra was watching process to count the playtime of games.
I will keep this issue open until we release the next version and confirm the CPU usage is at expected levels

**Comment by Enigma1309** [comment]
how should i fix this?
which branch should i pull to install it manually before release?

**Comment by obaidabit** [comment]
+1

- OS: Windows 10 22H2
- Hydra Version: Latest

**Comment by bredd10** [comment]
+1 
![image](https://github.com/hydralauncher/hydra/assets/169592859/9bbb15fd-3946-4f08-a743-5f77264f90e5)
Os windows 10
1.1.0

**Comment by Gustik** [comment]
+1
Windows 10.0.19045.4291
Hydra Version: 1.1.0

**Comment by mehfius** [comment]
+1
Windows 11 
Hydra Version: 1.1.0
0 Download 0 Upload

![image](https://github.com/hydralauncher/hydra/assets/7073758/96140d89-7ce7-4e3f-a1bd-611d1187571a)

**Comment by zamitto** [comment]
Please, see releases page and download new update
