### ISSUE TITLE
[REQUEST] Savegame synchronization via cloud

### ISSUE THREAD

**Issue by mekx** [hydralauncher/hydra#275]
Is there a plan to implement synchronization functionality for local save files to the cloud?

Suggestion: Add integration with a popular cloud storage service, such as Google Drive, and provide the option to select the local save folder (or somehow integrate the local path into the game profile, including variables such as %appdata%, %userprofile%, etc.).

Goal: Preserve game progress during reinstallation and synchronize it across multiple devices.

It would involve more than just savegame sync; probably more data, such as settings, can be stored in the user's Google Drive.

**Comment by Adamih** [comment]
It will probably take a while until the team launches some paid cloud service (if it ever happens). In the meantime, I had an idea. I will explore using the peer-to-peer file-sharing client Syncthing for this purpose. It will need manual configuration to sync save-file folders across games and devices. I will also try this myself later and see how it goes.

**Comment by thegrannychaseroperation** [comment]
Temporarily closing this since we won't be creating applications in Google (to sync with Drive, for instance). Might move into a different topic of discussion in the future, but not doing it for now.
