### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GameOtako** [hydralauncher/hydra#281]
**Describe the bug**
Не открывают иконки с играми, где находятся торрент, есть видео.
They do not open icons with games, where there are torrent files, there are videos.

Uploading BUG.mp4…

- OS: [Windows 10]
- Hydra Version: 1.1.0

**Comment by GameOtako** [comment]
> **Describe the bug** Не открываются иконки с играми, где находятся торрент, есть видео. They do not open icons with games, where there are torrent files, there are videos.
> 
> Uploading BUG.mp4…
> 
> * OS: [Windows 10]
> * Hydra Version: 1.1.0

**Comment by squidsdev** [comment]
You don't seem to have uploaded the video.

**Comment by GameOtako** [comment]
It doesn't want to load :(. Link to the YouTube video - https://youtu.be/dR7sueEsu1o С

**Comment by hydralauncher** [comment]
@GameOtako in which country is this? Seems like Steam's restricting you.

**Comment by GameOtako** [comment]
I am in Russia.

**Comment by GameOtako** [comment]
I turned off Steam completely, the problem remains

**Comment by zamitto** [comment]
Hydra gets game info from public Steam pages. If a game is not available in your region, currently, the game page will not load. We will fix this in the future, so at least the download options show corrctly

**Comment by KawaiNeSenpai** [comment]
> I turned off Steam completely, the problem remains

Впн включай.

**Comment by zamitto** [comment]
Please, see releases page and download new update
