### ISSUE TITLE
[BUG] problema na instalação

### ISSUE THREAD

**Issue by johnsparda** [hydralauncher/hydra#284]
well i installed  Hydra and it was a little bit lagged so i unistalled it but coudn't delete the files because they were in use, wich they were not. 
now i found a way to delete said files and tryed reeinstalling Hydra and the instalation aways faills and tells me to check the log and this is what apears in the log.

11752> 2024-05-04 09:05:00> Program: Starting Squirrel Updater: --install .
11752> 2024-05-04 09:05:00> Program: Starting install, writing to C:\Users\conta\AppData\Local\SquirrelTemp
11752> 2024-05-04 09:05:00> Program: About to install to: C:\Users\conta\AppData\Local\Discord
11752> 2024-05-04 09:05:00> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
11752> 2024-05-04 09:05:00> CheckForUpdateImpl: Reading RELEASES file from C:\Users\conta\AppData\Local\SquirrelTemp
11752> 2024-05-04 09:05:00> CheckForUpdateImpl: Remote version 1.0.9144 differs from local 
11752> 2024-05-04 09:05:00> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
11752> 2024-05-04 09:05:00> ApplyReleasesImpl: Writing files to app directory: C:\Users\conta\AppData\Local\Discord\app-1.0.9144
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\chrome_200_percent.pak to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\chrome_200_percent.pak
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\d3dcompiler_47.dll to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\d3dcompiler_47.dll
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\app.ico to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\app.ico
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\chrome_100_percent.pak to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\chrome_100_percent.pak
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\Discord.exe to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\Discord.exe
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\Discord.exe.sig to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\Discord.exe.sig
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\ffmpeg.dll to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\ffmpeg.dll
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\icudtl.dat to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\icudtl.dat
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\installer.db to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\installer.db
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\libEGL.dll to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\libEGL.dll
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\libGLESv2.dll to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\libGLESv2.dll
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\resources.pak to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\resources.pak
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\snapshot_blob.bin to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\snapshot_blob.bin
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\v8_context_snapshot.bin to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\v8_context_snapshot.bin
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\vk_swiftshader_icd.json to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\vk_swiftshader_icd.json
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\updater.node to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\updater.node
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\vk_swiftshader.dll to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\vk_swiftshader.dll
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Moving file C:\Users\conta\AppData\Local\Discord\app-1.0.9144\lib\net45\vulkan-1.dll to C:\Users\conta\AppData\Local\Discord\app-1.0.9144\vulkan-1.dll
11752> 2024-05-04 09:05:02> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\conta\AppData\Local\Discord\app-1.0.9144\Discord.exe]
11752> 2024-05-04 09:05:02> Utility: Process Started: C:\Users\conta\AppData\Local\Discord\app-1.0.9144\Discord.exe --squirrel-install 1.0.9144, pid 9908
11752> 2024-05-04 09:05:03> Utility: Received exitcode 0 from process C:\Users\conta\AppData\Local\Discord\app-1.0.9144\Discord.exe
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: ran C:\Users\conta\AppData\Local\Discord\app-1.0.9144\Discord.exe, pid 12564
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: Starting fixPinnedExecutables
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9144
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\conta\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: O acesso ao caminho 'C:\Users\conta\AppData\Roaming\Microsoft\Windows\Start Menu\Programas' foi negado.
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   em System.IO.FileSystemEnumerableIterator`1.MoveNext()
   em System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   em System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   em System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   em Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion)
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: Updating shortcut C:\Users\conta\OneDrive\Ambiente de Trabalho\Discord.lnk
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: Fixing up tray icons
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9144
11752> 2024-05-04 09:05:03> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9144

**Comment by johnsparda** [comment]
bom eu instalei o hydra a tava tendo umas dificuldades pra usar ai desinstalei mas resolvi reinstalar e ai apresentou um erro e mostrou isso no log

**Comment by zamitto** [comment]
Please, see releases page and download new update

**Comment by johnsparda** [comment]
obrigado
*João Pedro Costa Pinho*


Em ter., 14 de mai. de 2024 às 14:20, Zamitto ***@***.***>
escreveu:
