### ISSUE TITLE
[BUG] O launcher fica todo branco do nada

### ISSUE THREAD

**Issue by Lenhards** [hydralauncher/hydra#285]
I was downloading a game and the launcher got all white. restarting the launcher fixed it, but gets white again after a few minutes

![2024-05-11](https://github.com/hydralauncher/hydra/assets/169458403/cfc516f2-fc4a-452a-9be5-d2e83b5a733d)

**Comment by LoriaLawrenceZ** [comment]
O meu mn, tenta escreve em inglês, acho que vaifacilitar pros cara que desenvolvem 👍 
Qualquer coisa tu me chama se tu quiser ajuda pra meter um inglesinho

**Comment by Lenhards** [comment]
Tinham vários comentários em português então achei q era de boa falar em português agora eu coloquei em inglês, valeu mano

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hydralauncher** [comment]
This has been fixed.
