### ISSUE TITLE
[REQUEST] Add new site for install (with online)

### ISSUE THREAD

**Issue by Spacy80893** [hydralauncher/hydra#286]
site: https://freetp.org/
viruses were not found as long as my friends and I downloaded multiplayer fixes from the site
the site has very frequent game updates!
If you add this site, the library of your games will be even more !
Repacks of games on the site are very high quality and do not lag!
I hope you like the idea.

**Comment by whyttt6** [comment]
ещкерееее

**Comment by TesterHere06** [comment]
It usually takes stuff already from online-fix.me, but yeah sometimes there are new things. Overall I think there should be user-directed torrent sources in the launcher

**Comment by Spacy80893** [comment]
I and my friends are ready to provide sites from which you can take repacks

**Comment by Listum** [comment]
@TesterHere06 
> user-directed torrent sources 

That's impossible, otherwise you'd just have to manually write code to parsing games and stuff

**Comment by Listum** [comment]
Пиздец ты конечно англичанин

**Comment by Spacy80893** [comment]
> Пиздец ты конечно англичанин

да я че ебу как пиздеть на пендосятине я через переводчик ебашил

**Comment by Spacyaa** [comment]
Realistically when will you add freetp.org repacks already?

**Comment by Gleb2372372** [comment]
> Реально, когда вы уже добавите репаки freetp.org?

Хз когда разраби время найдут или просто не хотят.

**Comment by zamitto** [comment]
This can be done by the community since version 2.0

**Comment by Gleb2372372** [comment]
Кто-то нашел json файл free-tp?

**Comment by Gleb2372372** [comment]
![image](https://github.com/hydralauncher/hydra/assets/76180186/52dd5ce5-0768-433e-84f5-b52f96e8e83a)
Я написал разработчику сайта чтобы сделал json файл сайта.

**Comment by Spacyaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/76180186/342193848-52dd5ce5-0768-433e-84f5-b52f96e8e83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk5ODAsIm5iZiI6MTcxOTI3OTY4MCwicGF0aCI6Ii83NjE4MDE4Ni8zNDIxOTM4NDgtNTJkZDVjZTUtMDc2OC00MzNlLTg0ZjUtYjUyZjk2ZThlODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmMzNjIwZmJlNTdhZmE0ZGNhYzA3MWIxMDBhNGIyNzNiYzVjNzgyZDA3MjU4N2Y3ZGJiN2FmMWVjYTI2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFjRiGkaDcmmhziZ4LxG5BzyxnVZpc8NGlARW1_FtSs) Я написал разработчику чтобы сделал json файл сайта.

бро а можешь объяснить для чего этот json файл и как его достать

**Comment by Gleb2372372** [comment]
> > ![image](https://private-user-images.githubusercontent.com/76180186/342193848-52dd5ce5-0768-433e-84f5-b52f96e8e83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk5ODAsIm5iZiI6MTcxOTI3OTY4MCwicGF0aCI6Ii83NjE4MDE4Ni8zNDIxOTM4NDgtNTJkZDVjZTUtMDc2OC00MzNlLTg0ZjUtYjUyZjk2ZThlODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmMzNjIwZmJlNTdhZmE0ZGNhYzA3MWIxMDBhNGIyNzNiYzVjNzgyZDA3MjU4N2Y3ZGJiN2FmMWVjYTI2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFjRiGkaDcmmhziZ4LxG5BzyxnVZpc8NGlARW1_FtSs) Я написал разработчику чтобы сделал json файл сайта.
> 
> бро а можешь объяснить для чего этот json файл и как его достать

Ну смотри это сборник всего что есть на сайте и у каждого раздела есть своя ссылка, а там просто все отсортировано. Чтобы его найти можешь посмотреть тутор https://ru.stackoverflow.com/q/1173444/600672

**Comment by Spacyaa** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/76180186/342193848-52dd5ce5-0768-433e-84f5-b52f96e8e83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk5ODAsIm5iZiI6MTcxOTI3OTY4MCwicGF0aCI6Ii83NjE4MDE4Ni8zNDIxOTM4NDgtNTJkZDVjZTUtMDc2OC00MzNlLTg0ZjUtYjUyZjk2ZThlODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmMzNjIwZmJlNTdhZmE0ZGNhYzA3MWIxMDBhNGIyNzNiYzVjNzgyZDA3MjU4N2Y3ZGJiN2FmMWVjYTI2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFjRiGkaDcmmhziZ4LxG5BzyxnVZpc8NGlARW1_FtSs) Я написал разработчику чтобы сделал json файл сайта.
> > 
> > 
> > бро а можешь объяснить для чего этот json файл и как его достать
> 
> Ну смотри это сборник всего что есть на сайте и у каждого раздела есть своя ссылка, а там просто все отсортировано. Чтобы его найти можешь посмотреть тутор https://ru.stackoverflow.com/q/1173444/600672

все понял спасибо

**Comment by Spacyaa** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/76180186/342193848-52dd5ce5-0768-433e-84f5-b52f96e8e83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk5ODAsIm5iZiI6MTcxOTI3OTY4MCwicGF0aCI6Ii83NjE4MDE4Ni8zNDIxOTM4NDgtNTJkZDVjZTUtMDc2OC00MzNlLTg0ZjUtYjUyZjk2ZThlODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmMzNjIwZmJlNTdhZmE0ZGNhYzA3MWIxMDBhNGIyNzNiYzVjNzgyZDA3MjU4N2Y3ZGJiN2FmMWVjYTI2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFjRiGkaDcmmhziZ4LxG5BzyxnVZpc8NGlARW1_FtSs) Я написал разработчику чтобы сделал json файл сайта.
> > 
> > 
> > бро а можешь объяснить для чего этот json файл и как его достать
> 
> Ну смотри это сборник всего что есть на сайте и у каждого раздела есть своя ссылка, а там просто все отсортировано. Чтобы его найти можешь посмотреть тутор https://ru.stackoverflow.com/q/1173444/600672

и если сможешь получить ссылку на json файл то скинь мне пожалуйста

**Comment by Gleb2372372** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/76180186/342193848-52dd5ce5-0768-433e-84f5-b52f96e8e83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNzk5ODAsIm5iZiI6MTcxOTI3OTY4MCwicGF0aCI6Ii83NjE4MDE4Ni8zNDIxOTM4NDgtNTJkZDVjZTUtMDc2OC00MzNlLTg0ZjUtYjUyZjk2ZThlODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAxNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmMzNjIwZmJlNTdhZmE0ZGNhYzA3MWIxMDBhNGIyNzNiYzVjNzgyZDA3MjU4N2Y3ZGJiN2FmMWVjYTI2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFjRiGkaDcmmhziZ4LxG5BzyxnVZpc8NGlARW1_FtSs) Я написал разработчику чтобы сделал json файл сайта.
> > > 
> > > 
> > > бро а можешь объяснить для чего этот json файл и как его достать
> > 
> > 
> > Ну смотри это сборник всего что есть на сайте и у каждого раздела есть своя ссылка, а там просто все отсортировано. Чтобы его найти можешь посмотреть тутор https://ru.stackoverflow.com/q/1173444/600672
> 
> и если сможешь получить ссылку на json файл то скинь мне пожалуйста

Я попробую но ето может сделать только создатель сайта.

**Comment by BadKiko** [comment]
Сделал список
Там 1700 игр, пропаршенные с FreeTp некоторых может не быть но это редкость если чего то нет просто Issue откройте гляну, добавлю.

https://github.com/BadKiko/freetp-hydra-link/

**Comment by Spacy80893** [comment]
> Сделал список Там 1700 игр, пропаршенные с FreeTp некоторых может не быть но это редкость если чего то нет просто Issue откройте гляну, добавлю.
> 
> https://github.com/BadKiko/freetp-hydra-link/

ЛЕГЕНДА

**Comment by ARTEMIOBRO** [comment]
> Сделал список Там 1700 игр, пропаршенные с FreeTp некоторых может не быть но это редкость если чего то нет просто Issue откройте гляну, добавлю.
> 
> https://github.com/BadKiko/freetp-hydra-link/

REPO нету(

**Comment by FreePhoenix888** [comment]
@Role-Play237 а что тебе пионер ответил?

**Comment by Listum** [comment]
@BadKiko Когда допиленный SOFL?

**Comment by BadKiko** [comment]
> > Сделал список Там 1700 игр, пропаршенные с FreeTp некоторых может не быть но это редкость если чего то нет просто Issue откройте гляну, добавлю.
> > 
> > https://github.com/BadKiko/freetp-hydra-link/
> 
> REPO нету(
> 

Да, давно не обновлял, над бы GitHub Actions прикрутить, сделаю на днях

**Comment by BadKiko** [comment]
> @BadKiko Когда допиленный SOFL?
> 
> 

Работаю над ним, надеюсь до конца месяца смогу выкинуть в альфа релиз 😁

**Comment by BadKiko** [comment]
> > Сделал список Там 1700 игр, пропаршенные с FreeTp некоторых может не быть но это редкость если чего то нет просто Issue откройте гляну, добавлю.
> > https://github.com/BadKiko/freetp-hydra-link/
> 
> REPO нету(

Обновил список от 07.06.25

**Comment by FreePhoenix888** [comment]
@BadKiko может быть какой-нибудь Github Action который реагирует на github action?
```
name: Issue Title Filter

on:
  issues:
    types: [opened, edited]

jobs:
  filter-title:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.title && startsWith(github.event.issue.title, '[Deploy]')
    steps:
      - name: Echo matched title
        run: echo "Issue title matched: ${{ github.event.issue.title }}"

```
+ выставить ему ещё кулдаун что бы ребята не флудили таким ишью
