### ISSUE TITLE
Update from the menu

### ISSUE THREAD

**Issue by KawaiNeSenpai** [hydralauncher/hydra#289]
**Is your feature request related to a problem? Please describe.**
No, it's a suggestion for improvement

**Describe the solution you'd like**
Add a tab to update the program itself from it.

**Describe alternatives you've considered**
Forced update at program startup.

**Comment by aleks1timiya** [comment]
How can I update?

**Comment by zamitto** [comment]
In 2.0 we added a discrete message under the app main header that shows when a update is available
