### ISSUE TITLE
Program shortcut

### ISSUE THREAD

**Issue by KawaiNeSenpai** [hydralauncher/hydra#290]
**Is your feature request related to a problem? Please describe.**
Maybe I'm the only one who didn't get the label. I haven't seen any complaints.

**Describe the solution you'd like**
Creating a shortcut to the program on the desktop during installation.

**Describe alternatives you've considered**
When installing, add the option to check the boxes
1) Create a shortcut on the desktop
2) Add the program to Start Menu.
3) Open the program at system startup.

**Additional context**
Ability to find a program when using "Search"
I had to make a shortcut to the desktop myself.

<details>
 
![image_2024-05-11_18-50-39](https://github.com/hydralauncher/hydra/assets/60895366/8f657294-9409-4b2d-9953-7b609106ed79)

</details>

**Comment by zamitto** [comment]
This is a bug in the current version. And will the fixed with the next release

**Comment by hydralauncher** [comment]
This has been fixed.
