### ISSUE TITLE
[BUG] The problem with hanging

### ISSUE THREAD

**Issue by PlugManYT** [hydralauncher/hydra#291]
**Describe the bug**
5 seconds after launching the launcher, it does not respond. I reinstalled it three times and restarted Windows
![image](https://github.com/hydralauncher/hydra/assets/136507921/41d0f476-2ac8-404b-830e-54feefc57d7c)

- OS: [Windows 11]
- Hydra Version: 1.1.0

**Comment by KawaiNeSenpai** [comment]
Когда у тебя прога зависает ничего не нажимай просто и жди. не нажимай ничего в нем. если ты нажал и появилось это окно. то прога не отвиснет!

**Comment by KWolf94** [comment]
Every 10 seconds, the program freezes with the same error and becomes unusable. We are currently waiting for a solution to this issue.

**Comment by cmndude** [comment]
I'm having same issue

**Comment by zamitto** [comment]
Please, see releases page and download new update
