### ISSUE TITLE
[REQUEST] Running with Windows

### ISSUE THREAD

**Issue by PlugManYT** [hydralauncher/hydra#293]
Could you make it possible in the settings to launch the hydra when Windows starts💛

**Comment by ClementNerma** [comment]
In the meantime, you can create a shortcut to the software and put it in `C:\Users\<your username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`. This will start the program when you login ;)

**Comment by zamitto** [comment]
It will be possible in the next update
