### ISSUE TITLE
[BUG] The name of the repack does not fit into the block

### ISSUE THREAD

**Issue by Scheffio** [hydralauncher/hydra#297]
**Describe the bug**
The name of the repack does not fit into the block

**To Reproduce**

1. Go to 'Home' menu
2. Type "Kimetsu" in search field
3. Open "Demon Slayer -Kimetsu no Yaiba-..." game
4. Click "Open download options"
5. 2nd repack name doesn't fit into the block

**Expected behavior**
 The name of the repack does fit into the block

**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/45427871/1b898a4a-9e54-4e1a-a479-4d03468deb48)

**Additional context**

- OS: Windows 11
- Hydra Version: v1.1.0 "Exodus"

**Comment by mohannadzidan** [comment]
Working on a fix
