### ISSUE TITLE
[REQUEST] add games that are not automatically paired in the catalog

### ISSUE THREAD

**Issue by vyacheslavsem** [hydralauncher/hydra#298]
an interesting idea is to add games that are not automatically paired in the catalog. for example, put them in the "suggestions" and let the volunteers add links to repacks with their hands for free (links must be verified by the community)

-----------------next, just my thoughts, the main idea has already been expressed-----------------

You can become a volunteer via chat upon request. you can make a small button "suggest \ add a game" there to add the name of the game, a description from the store (steam or other sources) and a link to the repack. the volunteer checks the link and description, if the link is malicious (by the decision of the volunteer or by the decision of the community), then either refuse to add the game, or the volunteer himself is looking for a more reliable source. It is better to mark such games that they are added by the community.

or you can do without volunteers, and for example, once a week to collect all the offers, highlight them in a separate tab and people will vote for the game and the link to it.

As the solution to the problem of suggestion-mess, there may be included a simple basic account system for volunteers for stats and votes

**Comment by JackEnx** [comment]
all download links are the responsibility of the community.
