### ISSUE TITLE
[REQUEST] launch options for each game

### ISSUE THREAD

**Issue by School-account-10** [hydralauncher/hydra#302]
like the feature in steam that lets users put a launch option 
ive tried using the shortcut method but it did not really work 
and i've also tried using batscripts which worked but it can't be used by hydra because it does not accept Bat files

**Comment by lockieluke** [comment]
currently you can create a shortcut linked to the batch script but playtime wouldn't work as batch scripts run in a detached process

**Comment by JackEnx** [comment]
closing to keep a more detailed issue with the problem, #444
