### ISSUE TITLE
[REQUEST] Add support for Torrent-Igruha games and repacks 

### ISSUE THREAD

**Issue by m4fz** [hydralauncher/hydra#310]
**Describe the solution you'd like**
Considering that https://itorrents-igruha.org/ has a shit ton of games it would be great to see these repacks get added to all of the other ones, that's it.

**Comment by KeyZenD** [comment]
site with stillers in repacks. not reccomend.

**Comment by luvvvdev** [comment]
лучше https://byruthub.org/

**Comment by KMozor** [comment]
No!!!! It's got viruses, watch YouTube.

**Comment by m4fz** [comment]
Never got any viruses from it, and i got some shit before, so i'm careful with this type of stuff on any site i use

**Comment by JackEnx** [comment]
all download links are the responsibility of the community.
