### ISSUE TITLE
[BUG] Hydra doesn't open some game's tab, only opens a tab to close it instantly

### ISSUE THREAD

**Issue by yanchernyavsky** [hydralauncher/hydra#317]
**Hydra doesn't open some game's tab, only opens a tab to close it instantly**
So, as the title says, my Hydra client refuses to open some game's "window" or tab, clicking on any game results in it loading as intended but shutting itself down when loaded.

https://github.com/hydralauncher/hydra/assets/39568103/69fbe56f-2c3f-48bb-90e2-ae4f232e0895

**Comment by zamitto** [comment]
Hydra currently uses info from the Steam page of the game. If the game is not available in your country, this bug happens.
We are trying to fix this.
For now, you can try to use a VPN to access the game page once. And after the first time, the game page will be cached and a VPN will not be needed anymore for that game
