### ISSUE TITLE
[REQUEST] Add a Notice Footer for Resource-Intensive Data Scraping

### ISSUE THREAD

**Issue by MrAndroPC** [hydralauncher/hydra#320]
We've been using the program and noticed that during data scraping, there's a significant uptick in resource consumption. To mitigate any confusion or concern from users, could we consider adding a "footer" notification that simply states, "Data scraping in progress, increased consumption of PC resources." or something similar? This way, users will be aware of the process and its resource implications without feeling left in the dark.

**Comment by Ghastly2001** [comment]
I'll ensure that the notification is displayed appropriately and is styled in a non-intrusive manner. Additionally, I'll provide an option for users to dismiss the notification if they prefer.

**Comment by MrAndroPC** [comment]
> I'll ensure that the notification is displayed appropriately and is styled in a non-intrusive manner. Additionally, I'll provide an option for users to dismiss the notification if they prefer.

Since there is no more so crucial impact, i don't think if this banner actually needed. But maybe i wrong.

**Comment by zamitto** [comment]
Closing as Hydra does not have this feature anymore
