### ISSUE TITLE
Suggestion to add a new tracker

### ISSUE THREAD

**Issue by Listum** [hydralauncher/hydra#329]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I suggest you add another tracker with games and online fixes **[freetp.org](https://freetp.org/)**, its russian, but it's natively clear how to install

**Describe alternatives you've considered**
**[online-fix](https://online-fix.me/)**?

**Additional context**

**Comment by Spacy80893** [comment]
bro I already wrote this idea a couple days ago🔥

**Comment by Listum** [comment]
#286

**Comment by JackEnx** [comment]
duplicated #286
