### ISSUE TITLE
[BUG] Hydra freezes in loading the "getHowLongToBeat" function

### ISSUE THREAD

**Issue by harshil21** [hydralauncher/hydra#330]
**Describe the bug**

The hydra launcher sometimes freezes while loading the how long to beat section.

**To Reproduce**

1. Go to any game page
2. Scroll through the page
3. The launcher freezes sometimes, with the dialog "Hydra is not responding" shown.

**Expected behavior**
The launcher should work fine without this bug and without consuming a lot of CPU and memory.

**Additional context**

- OS: Ubuntu 23.10
- Hydra Version: 1.1.0
- Additional information and context of your problem:
This is the traceback in the terminal:
```
Error occurred in handler for 'getHowLongToBeat': TypeError: Cannot read properties of null (reading 'children')
    at /usr/lib/hydra-launcher/resources/app.asar/.webpack/main/index.js:2:4777503
    at Generator.next (<anonymous>)
    at o (/usr/lib/hydra-launcher/resources/app.asar/.webpack/main/index.js:2:4776418)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by hydralauncher** [comment]
Fixed.
