### ISSUE TITLE
Stuck on AMD RYZEN. [BUG]

### ISSUE THREAD

**Issue by AgroTazer** [hydralauncher/hydra#333]
The application freezes when launched on an AMD RYZEN processor. I ask you to fix this problem.

**Comment by AgroTazer** [comment]
The application freezes when launched on an AMD RYZEN processor. I ask you to fix this problem.

**Comment by GGabrielCross** [comment]
same thing here

**Comment by MizuKumi** [comment]
The same thing on ryzen 5 3500u.

**Comment by zamitto** [comment]
Please, see releases page and download new update
