### ISSUE TITLE
[REQUEST] make a Mac/Ios launcher pls

### ISSUE THREAD

**Issue by tavinnnnnnnnnnnnnnn** [hydralauncher/hydra#334]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zamitto** [comment]
Mac users wont be able to play the games they would download with Hydra. There is no point on releasing a mac build

**Comment by JackEnx** [comment]
duplicated  #300
