### ISSUE TITLE
Another game on Raft page

### ISSUE THREAD

**Issue by onlive1337** [hydralauncher/hydra#343]
Describe the bug
On the raft page we can see another game, name: Super Raft Boat Together 

To Reproduce
Just search Raft and click Open Download options

![image](https://github.com/hydralauncher/hydra/assets/102153021/ad6e3252-ae50-40bb-9a09-f84180950210)

**Comment by JackEnx** [comment]
This is not a bug, it is a side effect of the automatic way we index games

**Comment by JackEnx** [comment]
This is not a bug, it is a side effect of the automatic way we index games
