### ISSUE TITLE
[BUG] App keep crashing on Fedora 40

### ISSUE THREAD

**Issue by 0NegrY0** [hydralauncher/hydra#344]
**Describe the bug**
After start the app it crashes after a small period of time.

**To Reproduce**

1. Open the app
2. Wait for a small period of time
3. See error

**Expected behavior**
The app should work normally

**Additional context**
- OS: Fedora Linux 40 (Gnome-Wayland)
- Hydra Version: 1.1.0
- combined.log:

{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Download button not found","method":"getNewRepacksFromXatab"}
{"level":"error","message":"Download button not found","method":"getNewRepacksFromXatab"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27802/abaddon-princess-of-the-decay/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29184/ad-infinitum/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28244/afterdream/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27718/airborne-ranger/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27970/alice-escaped/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29382/alone-in-the-dark/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29353/alpha-protocol/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26817/alt-frequencies/"}
{"level":"error","message":"Cannot read properties of null (reading 'href')","method":"getGOGGame","url":"https://freegogpcgames.com/3254/ancestors-legacy-special-edition/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28792/anodyne/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29633/arcade-tycoon-simulation-game/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28126/arena-renovation/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27737/ariels-daily-grind/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29642/asterix-obelix-slap-them-all-2/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29251/as-dusk-falls/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27902/axe-cop/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27749/a-long-journey-to-an-uncertain-end/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27741/a-maiden-astrologer-divines-the-future/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28938/a-night-at-the-watermill/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28685/a-tale-of-two-kingdoms/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29277/a-void-hope/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28476/a-whisper-in-the-twilight-chapter-one/"}
{"level":"error","message":"Cannot read properties of null (reading 'href')","method":"getGOGGame","url":"https://freegogpcgames.com/6723/bad-dream-fever/"}
{"level":"error","message":"Cannot read properties of null (reading 'href')","method":"getGOGGame","url":"https://freegogpcgames.com/1894/1-baldurs-gate-siege-of-dragonspear/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28754/ballance/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29158/bandle-tale-a-league-of-legends-story/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28266/bang-on-balls-chronicles/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27528/batora-lost-haven/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29058/batsugun/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26819/before-i-forget/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26434/before-we-leave/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26646/belial-red-unrated/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27827/betrayer/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28234/beyond-two-souls/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29165/bilkins-folly/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29325/black-forest/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26468/blade-assault/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28498/boiling-point-road-to-hell/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26301/boom-blaster/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28763/booze-masters-freezing-moonshine/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29686/boti-byteland-overclocked/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27678/bread-fred/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27732/breakout-recharged/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28320/brigand-gold/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27794/bucket-knight/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26700/buddy-simulator-1984/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28264/burnhouse-lane/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/27815/bus-driver-simulator/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29077/bus-world/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29222/canine/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28687/cats-hidden-in-bali/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29406/cats-hidden-in-georgia/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28689/cats-hidden-in-italy/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/28693/cats-hidden-in-paris/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29323/cavern-of-dreams/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/29644/chihiro-himukai-always-walks-away/"}
{"level":"error","message":"Cannot read properties of null (reading 'content')","method":"getGOGGame","url":"https://freegogpcgames.com/26481/chronicon-complete/"}

**Comment by zamitto** [comment]
Please, see releases page and download new update
