### ISSUE TITLE
[BUG] Write downloading metadata

### ISSUE THREAD

**Issue by Meline900** [hydralauncher/hydra#345]
Я сам на русском напишу. Я захотел скачать stray но после 41% hydra пишет downloading metadata

![Снимок экрана 2024-05-13 223451](https://github.com/hydralauncher/hydra/assets/79465817/92818fc2-f9ec-40d9-b365-1fc5d53eb305)
Как это исправить.
На заранее спасибо.

**Comment by JackEnx** [comment]
please in english

**Comment by Meline900** [comment]
> пожалуйста, на английском
I'll write it in Russian myself. I wanted to download stray but after 41% hydra says downloading metadata.
How to fix it.
Thanks in advance.

**Comment by JackEnx** [comment]
we have a new version (https://github.com/hydralauncher/hydra/releases/tag/v1.2.1) this version have a break point, you need to uninstall the 1.1.0 and download the new version

**Comment by Urahara-Blade** [comment]
@JackEnx can you please download version 1.2.1 again?

**Comment by JackEnx** [comment]
@Urahara-Blade version 1.2.1 has been removed, I recommend using the latest version, you can find the download links in the closed issues

**Comment by Urahara-Blade** [comment]
takes a very long time to load. how to deal with this problem?


Сб, 3 авг. 2024 г. в 05:04, JackEnx ***@***.***>:

**Comment by JackEnx** [comment]
what load? you mean download? if yes, it is how torrent works, you can try to use real debrid but it's a paid service.
