### ISSUE TITLE
[BUG] Repack downloading isn't working in Russia :o

### ISSUE THREAD

**Issue by K1LL3RPUNCH** [hydralauncher/hydra#353]
**Describe the bug**

**To Reproduce**

1. Go to 'Russia'
2. Click on 'Fallout 4'
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

- OS: Every OS
- Hydra Version: latest
- Additional information and context of your problem:

Not every games, just from those companies who doesn't sell them in Russia since SVO

https://youtu.be/D7Bp8fhFZk4

**Comment by leoxyeo** [comment]
Russia isn't allowed to do anithing since SVO lol   _:D_

**Comment by K1LL3RPUNCH** [comment]
> Russia isn't allowed to do anything since SVO lol _:D_

Это был вопрос не тебе, хрюшка.

**Comment by leoxyeo** [comment]
> > Russia isn't allowed to do anything since SVO lol _:D_
> 
> Это был вопрос не тебе, хрюшка.

blyad suka vodka? XD

**Comment by xxDRV** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Russia'
> 2. Click on 'Fallout 4'
> 3. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> 
> * OS: Every OS
> * Hydra Version: latest
> * Additional information and context of your problem:
> 
> Not every games, just from those companies who doesn't sell them in Russia since SVO
> 
> https://youtu.be/D7Bp8fhFZk4

Enable VPN, begin download, disable VPN

**Comment by ruth3n** [comment]
To my knowledge, this issue is unlikely to be a bug with Hydra. Hydra gets repacks from websites from the Megathread, therefore, I suggest using the VPN as previously mentioned.

**Comment by zamitto** [comment]
Please, see releases page and use new update.
