### ISSUE TITLE
[BUG] Bugs that really hinder my experience

### ISSUE THREAD

**Issue by GGabrielCross** [hydralauncher/hydra#356]
**Describe the bug**
1- Excessive use of processing power even with the program closed, having to close it through the task manager to be able to finish it.
2- The application freezes several times during use (I use a ryzen processor).

**To Reproduce**
1- Close the app and see it on the task manager
2- Just using it

**Expected behavior**
1- Have a button in the settings to disable background use
2- Don't Freeze LOL

**Screenshots**
1-     

https://github.com/hydralauncher/hydra/assets/168583247/bcae4e70-b48b-4e78-b688-5d53da9aa671

2- 

https://github.com/hydralauncher/hydra/assets/168583247/2cb5607d-6744-4105-a1e7-b2025445c3d2

**Additional context**

- OS: Windows 11 Enterprise 😔
- Hydra Version: 1.1.0

**Comment by GGabrielCross** [comment]
20% of my processor don't help me 😅😅

**Comment by zamitto** [comment]
Knowns issues. Fix on next update

**Comment by zamitto** [comment]
Please, see releases page for new update

**Comment by GGabrielCross** [comment]
Thanks👍👍
