### ISSUE TITLE
[REQUEST] Russification of the launcher and website

### ISSUE THREAD

**Issue by ghost** [hydralauncher/hydra#365]
Hello, I suggest adding Russian and Ukrainian languages. Both on the website and in the launcher.
Why?
Because I believe that in such regions your resource will be in demand.

**Comment by zamitto** [comment]
It's already added in the launcher on the lastest release

**Comment by aleks1timiya** [comment]
![image](https://github.com/hydralauncher/hydra/assets/149929281/52eaf3ac-6a07-4654-bf29-5754e9a79564)

**Comment by zamitto** [comment]
You are not running the latest release

**Comment by aleks1timiya** [comment]
How can I update?

**Comment by zamitto** [comment]
https://github.com/hydralauncher/hydra/releases

**Comment by KMozor** [comment]
Hmm, I today installed on Windows the latest version and Russian language I did not observe there
Can somehow through the config to fix it?

**Comment by zamitto** [comment]
Is your OS configure with russian language? Hydra should get the default language of your OS and use it.
Anyway, the next update should have a language selector

**Comment by KMozor** [comment]
Yes, my OS is completely in Russian, anyway, I'll wait for the language selection item

**Comment by aleks1timiya** [comment]
Да , русификация отличная, но сайт на португальском и английском.

**Comment by piradata** [comment]
strange, if the OS is in ru the language should have been detected automatically here:

![image](https://github.com/hydralauncher/hydra/assets/16529503/4b0a8ff5-61e2-4323-947a-9fffa4e03fca)

where `@locales` are

![image](https://github.com/hydralauncher/hydra/assets/16529503/00667a72-d305-4649-ba56-e42bc5994ea9)

**Comment by piradata** [comment]
addedlanguage selector menu to solve this
