### ISSUE TITLE
[BUG] Missing icon of the game in library

### ISSUE THREAD

**Issue by Dima2002iq** [hydralauncher/hydra#366]
**Describe the bug**
In my library i have a game that missing its icon. 

**Steps to reproduce**
Just downloaded random game and it doesn't have its icon :)

**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/46673893/95dcfbde-c1a8-4137-8b5e-a36818e92802)

**Additional context**

- OS: Windows 10
- Hydra Version: 1.2.0

**Comment by piradata** [comment]
it just really does not have an icon. maybe a default icon to be used in this case as fallback? i suggest the pepe meme :)

**Comment by Dima2002iq** [comment]
Well, if default icon will be added then this issue can be closed, I suppose.

**Comment by piradata** [comment]
someone need to open a PR for this tho
