### ISSUE TITLE
[BUG] Don't launch WIN10

### ISSUE THREAD

**Issue by Roma15228** [hydralauncher/hydra#367]
When starting app, his closed

- OS: [Windows 10]
- Hydra Version: 1.2.0

**Comment by johwconst** [comment]
Could you provide more information about the error? If possible, get the Windows error reports.

**Comment by Roma15228** [comment]
After starting the program, it closes before it can show the window. How can I record logs?

> Could you provide more information about the error? If possible, get the Windows error reports.

**Comment by johwconst** [comment]
Vice can use the "Windows Events Viewer"

**Comment by Roma15228** [comment]
> You can use the "Windows Events Viewer"

There are no entries for the Hydra app

**Comment by zamitto** [comment]
Just to be sure, the only installed version is 1.2.0?

**Comment by zamitto** [comment]
Could yiu try to use debugtron to try to debug and get some logs?
https://github.com/pd4d10/debugtron

Hydra has no telemetry anymore and is 100% anonymous, it is a little hard to know what might be happening

**Comment by Roma15228** [comment]
i get infinity error gpu
![изображение](https://github.com/hydralauncher/hydra/assets/60067543/a8e20a6e-56ba-4af9-b7bf-1bab8ef5d901)

**Comment by Roma15228** [comment]
> Could yiu try to use debugtron to try to debug and get some logs? https://github.com/pd4d10/debugtron
> 
> Hydra has no telemetry anymore and is 100% anonymous, it is a little hard to know what might be happening

**Comment by JackEnx** [comment]
please, try this: https://github.com/hydralauncher/hydra/issues/386#issuecomment-2113337422

**Comment by zamitto** [comment]
Issue should be fixed in last version
Closing as 2 weeks with no update from OP
