### ISSUE TITLE
[BUG] DOWNLOAD FREEZING

### ISSUE THREAD

**Issue by ImUnlimited** [hydralauncher/hydra#368]
**Describe the bug**
Download's freezing while downloading and if I try to cancel and download again it doesn't start.

**To Reproduce The First Freeze**

1. Start downloading Horizon Zero Dawn by FitGirl
2. It just freezes for me...

**To Reproduce The Second Freeze**

1. Start downloading something
2. Cancel it
3. Try downloading it again

**Expected behavior**
Download not freezing

Uploading sem título.mp4…

**Screenshots**

**Additional context**

- OS: Windows 11
- Hydra Version: 1.1.0
- Additional information and context of your problem:

**Comment by zamitto** [comment]
Could you download the latest version from the releases page and try again?

**Comment by ImUnlimited** [comment]
> Could you download the latest version from the releases page and try again?

Of course. But I have a question, why dont you guys implement an auto updater system since your application is made on electron and it's open source? It is easy to implement, just a suggestion.

**Comment by zamitto** [comment]
Sorry to take so long to answer. Since 1.2.0 there is an auto update system. And in 2.0 we reworked it as it was causing problems before.
So it should be working good right now.
If you still have problems, feel to to reopen this issue or open a new one
