### ISSUE TITLE
[REQUEST] search is limited by 12 games. Please add pagination like in main page.

### ISSUE THREAD

**Issue by kotenok2000** [hydralauncher/hydra#369]
**Describe the bug**
When i run search hydra finds only 12 games.
**To Reproduce**

1. search for a game called "the fall"  https://store.steampowered.com/app/290770/The_Fall/
2. Hydra can't find it.
**Expected behavior**
hydra displays full search result list.
**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/8822292/e19fedbe-a03c-4572-a6f0-276979a812e9)
**Additional context**

- OS: Windows 11
- Hydra Version: 1.2.0
- Additional information and context of your problem:

**Comment by piradata** [comment]
its is more like a feature actally, to add pagination on the seach as we have in the main page

**Comment by henriqueleite42** [comment]
Related: #361

**Comment by zamitto** [comment]
We reworked the search feature. It will now prioritize games with exact name you search and popular games
