### ISSUE TITLE
[REQUEST] Downloadqueue

### ISSUE THREAD

**Issue by MrAndroPC** [hydralauncher/hydra#372]
While issue 99 requests for simultaneous downloading, i think queue fits better for torrents, since we still need to manually install games. So, imo, queue fits better, cuz we notification for download completion, and user can install game and free up disk space for next games in queue (if there is lack of disk space). And its probably quite simpler to implement.

**Comment by Vadimus666** [comment]
This is good idea !

**Comment by zamitto** [comment]
Planned for next release

**Comment by zamitto** [comment]
Feature done in v2.0
