### ISSUE TITLE
[BUG] Wrong game download source

### ISSUE THREAD

**Issue by Spillernatt** [hydralauncher/hydra#374]
**Describe the bug**
I came across Supermarket Simulator and the download source from Fitgirl seems to be mistaken (downloads a completely different game)

**To Reproduce**
Head to the game page and press download 

**Expected behavior**
The source to the game should not be there if the source itself doesnt have the game

**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/63877530/e2df7a0b-e2e8-4217-9d95-195f7c0ef2b4)

**Additional context**

- OS: [Windows 11]
- Hydra Version: v1.2 💕

**Comment by zamitto** [comment]
It is something we can't do much, as Hydra matches the repacks with the game name, so stuff like your report will eventually happen. We have nothing to directly match a repack to the actual game. So we do this by the game title
