### ISSUE TITLE
[BUG] Hydra not opening on windows 10

### ISSUE THREAD

**Issue by Kalidher1** [hydralauncher/hydra#376]
When i click to open it, it opens on the taskbar and before making a windows, closes automatically

- OS: [Windows 10]
- Hydra Version: 1.2.0

**Comment by JackEnx** [comment]
could you do this? https://github.com/hydralauncher/hydra/issues/386#issuecomment-2112476995

**Comment by JackEnx** [comment]
plase, try this soluction: https://github.com/hydralauncher/hydra/issues/386#issuecomment-2113337422, and tell me if it works or not

**Comment by Kalidher1** [comment]
It worked :3
