### ISSUE TITLE
[BUG] O HYDRA EXECUTA MAIS FECHA EM SEGUIDA

### ISSUE THREAD

**Issue by rebeccasilv** [hydralauncher/hydra#377]
Oi gente, estou enfrentando  problemas para executar o Hydra no meu PC, eu utilizo o Windows 10 e estou usando a versão do Hydra 1.2.0 entretanto este bug também acontecia na versão anterior.
O programa simplesmente não abre, parece que esta sendo fechado por um programa secundário porém eu não tenho nenhum antivírus, através de alguns comentários eu acessei o Windows event  
![Design sem nome](https://github.com/hydralauncher/hydra/assets/143093609/eb22d8bf-e99a-45fa-8085-ded5a0a490d5)}

Podem me ajudar?

**Comment by KMozor** [comment]
Please write in English

**Comment by MacielzX321** [comment]
Hi everyone, I'm having trouble running Hydra on my PC. I'm using Windows 10 and Hydra version 1.2.0, but this bug also occurred in the previous version.
The program simply doesn't open; it seems to be closed by a secondary program, but I don't have any antivirus software. Based on some comments, I accessed the Windows Event Viewer to investigate further, but I'm not sure how to proceed. Any suggestions on what might be causing this issue or how to fix it?

**Comment by zamitto** [comment]
Did you uninstalled version 1.1.0?

**Comment by peixotojeff** [comment]
I have the same problem. I never have install hydra and after install doesn't open.

**Comment by JackEnx** [comment]
please, try this https://github.com/hydralauncher/hydra/issues/386#issuecomment-2112476995 and put your log

**Comment by BodepretoCRVG** [comment]
Clica com botão direito no icone d Hydra, vai em propiedades, aí na opção destino é só completar com assim, dar um espaço e cola isso aqui --no-sandbox

**Comment by peixotojeff** [comment]
work
