### ISSUE TITLE
[ REQUEST ] It should show if the game can be played multiplayer.

### ISSUE THREAD

**Issue by eovinicius** [hydralauncher/hydra#379]
It should show if the game can be played multiplayer on the game's details page.

**Comment by M1SHKAFREDE** [comment]
If there's OnlineFix, there's multiplayer.

**Comment by Maatarashiii** [comment]
> If there's OnlineFix, there's multiplayer.

Do you mean if there is OnlineFix? That is, is it possible to somehow see through the launcher that the repack has OnlineFix, or can it be installed additionally through some website?

**Comment by zamitto** [comment]
This feature is under development (there's a PR for review but we didn't have enough time to test and review it)

**Comment by M1SHKAFREDE** [comment]
> > If there's OnlineFix, there's multiplayer.
> 
> Do you mean if there is OnlineFix? That is, is it possible to somehow see through the launcher that the repack has OnlineFix, or can it be installed additionally through some website?

No, if the torrent repack says "online fix" then you need to download it, then it will be with multiplayer
