### ISSUE TITLE
[BUG] Wrong package name on deb package

### ISSUE THREAD

**Issue by DanielRios549** [hydralauncher/hydra#381]
**Describe the bug**
The correct package name is `hydra-launcher`, the new version (1.2.0) is set to `hydra` only. It conflits with a existent package on Ubuntu 22.04 called `hydra` (something to deal with network I think)

**To Reproduce**
Download the 1.2.0 .deb version and try to install.

**Expected behavior**
The package name should be `hydra-launcher`.

**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/11152535/9a452a30-1121-47e1-9026-d92c7ab97981)

**Additional context**

- OS: KDE Neon 5.27 (based on Ubuntu 22.04)
- Hydra Version: 1.2.0

**Comment by JackEnx** [comment]
we completely changed the build and we say on download of 1.2.0 to uninstall the previous version.

![image](https://github.com/hydralauncher/hydra/assets/167036558/88d88b53-2f09-4f7b-bc58-1323b24a1e64)

**Comment by Valentin3832** [comment]
bruh, i got the same issue

**Comment by DanielRios549** [comment]
@JackEnx OK, uninstall previous Hydra versions before installing the new one, but the package name is still wrong, `hydra` already exists on Ubuntu 22.04, it should be `hydra-launcher` instead

**Comment by yzee4** [comment]
To resolve this, go to the bin folder where the Hydra utility is installed, delete 'hydra-launcher' and change 'hydra' to 'hydra launcher'. So when you call it in the terminal it will run normally.

In the next update I believe this will be resolved and by default it will become 'hydra-launcher' again.



NOTE: Sorry for the bad English, I'm using Google Translate
