### ISSUE TITLE
[BUG] hydra closes quickly after opening

### ISSUE THREAD

**Issue by MacielzX321** [hydralauncher/hydra#386]
**Describe the bug**
Launcher não abre

**To Reproduce**

3. See error

**Expected behavior**

**Screenshots**
N/a

**Additional context**

- OS: Windows 11
- Hydra Version: 1.2.0
- Additional information and context of your problem: o launcher não abre, instalei tudo certo porém ele está com esse bug

**Comment by JackEnx** [comment]
first: english. 
second: insufficient information.

**Comment by MacielzX321** [comment]
The launcher has a bug where it opens and closes quickly. Do I need to add any commands in the properties, or is there another way to solve this?

**Comment by JackEnx** [comment]
did you uninstall 1.1.0?

**Comment by MacielzX321** [comment]
> did you uninstall 1.1.0?

Yes, I followed all the provided steps.

**Comment by MacielzX321** [comment]
In the previous version, a code was used in the executable address "--no-sandbox".

**Comment by JackEnx** [comment]
can you download debugtron, it's a program that shows the log of electron application, you can download from here:

https://github.com/pd4d10/debugtron/releases/tag/v0.5.0

execute debugtron with admistrador level and open hydra, this will show the error log.

**Comment by MacielzX321** [comment]
![image_2024-05-15_105243736](https://github.com/hydralauncher/hydra/assets/169906708/4cba963a-8238-4730-9358-239353890f98)


the error

**Comment by JackEnx** [comment]
please, to confirm the version, can you: 
1: right click on the hydra shortcut, 
2: properties, 
3: open on the local file button,

after this  on the base folder find the hydra.exe.

1: right click on the hydra.exe,
2: properties,
3: details page, send a print that show the hydra version

**Comment by MacielzX321** [comment]
![image_2024-05-15_134405381](https://github.com/hydralauncher/hydra/assets/169906708/b216ec17-3c04-4552-984b-81fd1d5a9bba)

**Comment by JackEnx** [comment]
could you manually select and open this hydra.exe file in debugtron?

**Comment by MacielzX321** [comment]
like this ? 
![image_2024-05-15_140211339](https://github.com/hydralauncher/hydra/assets/169906708/b937a45f-0476-4910-b86d-d9248055d332)

**Comment by DanieeLDev** [comment]
Same error

Debugtron:
![image](https://github.com/hydralauncher/hydra/assets/100256330/cef6a774-78c3-44c7-97b7-53a302ca86c0)

Details: 
![image](https://github.com/hydralauncher/hydra/assets/100256330/cba52db5-ab5f-49ac-8a4a-61c38d046863)

I noticed that version 1.0.1 opens the launcher, but the search systems and nothing involving them don't work, it shows Elden Ring as the first game, and only loads it in the application.

1.0.1:
![image](https://github.com/hydralauncher/hydra/assets/100256330/ae1a9863-2588-4244-be5e-02a2fcd15944)

since 1.1.0 it doesn't work
I hope I was able to provide more details

**Comment by JackEnx** [comment]
maybe i found a solucion, try to put --no-sandbox on hydra.exe, and say me if work or not

![image](https://github.com/hydralauncher/hydra/assets/167036558/02a9d1d6-2010-4a2d-9c54-fd0bb3cd5232)

**Comment by MacielzX321** [comment]
![image](https://github.com/hydralauncher/hydra/assets/169906708/9d710f54-83bb-40ff-818c-98e165d3294b)

**Comment by MacielzX321** [comment]
Thanks mate, if more people with this problem show up, I'll try to help as well.

**Comment by DanieeLDev** [comment]
It worked.
![image](https://github.com/hydralauncher/hydra/assets/100256330/65767c07-044a-44b3-81ba-0325889e3353)

Thx JackEnx!!

**Comment by rebeccasilv** [comment]
Thank you for your help, I was able to execute❤️❤️🌼👾

**Comment by JotaEfi** [comment]
I had this issue when put " --no-sandbox" in the directory.
![Screenshot_5](https://github.com/hydralauncher/hydra/assets/114100777/ac0863c3-a500-4235-9007-9b24e0e8b07c)

**Comment by JackEnx** [comment]
> I had this issue when put " --no-sandbox" in the directory. ![Screenshot_5](https://private-user-images.githubusercontent.com/114100777/331021099-ac0863c3-a500-4235-9007-9b24e0e8b07c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzEyMDcsIm5iZiI6MTcxNTgzMDkwNywicGF0aCI6Ii8xMTQxMDA3NzcvMzMxMDIxMDk5LWFjMDg2M2MzLWE1MDAtNDIzNS05MDA3LTliMjRlMGU4YjA3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwMzQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjQxNWE3YmNlM2U5ZDExNTMwYjlmNTg0ZDIxMGQ3NmYxZDMzMTFkNTY4ZDVlNTA5N2ZkMTBmYmIxMmUyNTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VdoQSpCYTr3KKPGXAU7qbAsV3ZntARckY5FsO8PaZdk)

this is other error, fixed in a new version: https://github.com/hydralauncher/hydra/releases

**Comment by Ghastzs** [comment]
Even after putting "--in-sandbox" in my hydra directory, it keeps giving white screen and obviously closing, basically "-in-sandbox" doesn't work for me (i tried in version 1.2.1, but even then it didn't work ) (i've searched several forums, but everyone said to put the --in-sandbox, but no one talks if it happens to go wrong)

**Comment by JackEnx** [comment]
is "--no-sandbox"

**Comment by Ghastzs** [comment]
sorry, I typed wrong, I put "-in-sandbox" before

**Comment by Ghastzs** [comment]
sorry, I typed wrong, I put "--no-sandbox" before

**Comment by Ghastzs** [comment]
sorry, I typed wrong, I put "--no-sandbox" before, it simply doesn't work for me

**Comment by YouteeM** [comment]
> can you download debugtron, it's a program that shows the log of electron application, you can download from here:
> 
> https://github.com/pd4d10/debugtron/releases/tag/v0.5.0
> 
> execute debugtron with admistrador level and open hydra, this will show the error log.

Thanks, I just installed the app with this software.

**Comment by zamitto** [comment]
Is this still an issue in version 2.0.2?
Feel free to reopen this if you still have problems
