### ISSUE TITLE
[BUG] Hydra downloads zips with password on it without giving the password

### ISSUE THREAD

**Issue by SometX** [hydralauncher/hydra#389]
I decided to download "Just Shapes & Beats" from Hydra Launcher, and encountered an issue. The downloaded archive is locked with password and I have no idea what the password is.

How to recreate this bug:
1) Search "Just Shapes & Beats" in Hydra Launcher
2) Download it
3) Press "Install" button
4) ???
5) Profit!
![image](https://github.com/hydralauncher/hydra/assets/162831873/cf78d12b-5f09-423f-88e7-417dcc6bdf48)

**Comment by ChristoferMendes** [comment]
#268

**Comment by JackEnx** [comment]
If you are using version 1.2.0, you will be informed of the password when you start the download.
