### ISSUE TITLE
Gostaria de saber se é comigo que o hydra está com virus quanto eu tento baixa-lo???

### ISSUE THREAD

**Issue by Otako1304** [hydralauncher/hydra#390]
![Captura de tela 2024-05-15 142454](https://github.com/hydralauncher/hydra/assets/169933500/a980103e-c7ef-465c-9c2a-aff25c09fa86)

- OS: [Windows 11]
- Hydra Version:1.1.0
- Additional information and context of your problem:Quando fui baixar o Hydra meu anti virus apitou e me alertou de trojan

**Comment by JackEnx** [comment]
download the new version: https://github.com/hydralauncher/hydra/releases/tag/v1.2.0

**Comment by Otako1304** [comment]
vc consegue me explicar como foi que teve virus a atualização passada

**Comment by JackEnx** [comment]
wrong question, you should prove where there is a virus in the code, if you don't know what you're talking about, don't say
