### ISSUE TITLE
How to uninstall the 1.1.0 Hydra Setup?

### ISSUE THREAD

**Issue by VitMM2000** [hydralauncher/hydra#391]
It says i need permission to uninstall

**Comment by pabermod** [comment]
Delete folder C:\Users\YOURUSER\AppData\Local\Programs\Hydra

**Comment by VitMM2000** [comment]
the folder are in C:\Users\my user
and when i trie to delete, apears i need adminpermission to execute this action

**Comment by whocastr** [comment]
just give the permission
