### ISSUE TITLE
[REQUEST] Addition of Direct Download Games(non-torrent) option

### ISSUE THREAD

**Issue by LasthopeBR** [hydralauncher/hydra#393]
A "Direct Download Games (non-torrent)" feature would open up a wider range of download options without the constant need for a VPN. It would utilize a background program like the open-source JDownloader to download files. This would also bring to the catalog games that are not available in official stores or torrents, providing a way to attract an user looking for older or specific games like "The Sims 2" or "Need for Speed Carbon."

Currently, the MegaThread on Reddit 'r/piracy' has several safe options for Direct Download Games that could be implemented in the Hydra launcher

The feature could be implemented by integrating a background download manager like JDownloader into the hydra.

**Comment by JackEnx** [comment]
Hydra supports some direct download links, you can also choose to use real debrid.
