### ISSUE TITLE
[BUG] Missing information on Game Page

### ISSUE THREAD

**Issue by joao-fernandes-fra** [hydralauncher/hydra#398]
### Describe the bug

When we open the game from the download page link the page opens with missing information

### Steps to Reproduce

1. Open downloads tab
2.Click on the title link to go to the game page
3.Get redirected to the page with missing information

### Expected behavior

Open regular game page

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/127697493/85ae496c-ebea-46d9-9213-07335b632b9b)

### Operating System

Win11

### Hydra Version

v1.2.0 

### Additional Information

Upon the first attempt to download the game my defender got triggered, so some file for the launcher might be missing, if that's the case i'm closing the issue, but is a little bug I noticed while monitoring my downloads.

**Comment by JackEnx** [comment]
read the #317
