### ISSUE TITLE
[BUG] JavaScript Error

### ISSUE THREAD

**Issue by DarkBroShow** [hydralauncher/hydra#399]
### Describe the bug

![изображение_2024-05-16_044634982](https://github.com/hydralauncher/hydra/assets/91475204/b5e40296-0c58-4f09-8c61-f9ec0fb408b0)

### Steps to Reproduce

Just launch the app

### Expected behavior

No errors  ¯\_(ツ)_/¯

### Operating System

Windows 10

### Hydra Version

1.2.0

**Comment by zamitto** [comment]
Thank you, we are investigating it

**Comment by berrbtw** [comment]
same

**Comment by bakin666** [comment]
same on win 11

**Comment by Tal0na** [comment]
same

**Comment by JackEnx** [comment]
fixed on #400
