### ISSUE TITLE
[BUG] ERRO JAVASCRIPT

### ISSUE THREAD

**Issue by BodepretoCRVG** [hydralauncher/hydra#401]
### Describe the bug

Hydra starts, but then this error occurs

### Steps to Reproduce

Hydra starts, but then this error occurs

### Expected behavior

Hydra starts, but then this error occurs

### Screenshots

![Sem título](https://github.com/hydralauncher/hydra/assets/169961668/39e7a7fa-9a5c-4233-bc3a-a864c48ddd3f)

### Operating System

Windows 10

### Hydra Version

1.2.0

**Comment by MatheusCequete** [comment]
I have the same problem :(

**Comment by zamitto** [comment]
A hotfix is on the way

**Comment by JackEnx** [comment]
fixed on #400
