### ISSUE TITLE
[BUG] settings in UI dont keep values when changing panes

### ISSUE THREAD

**Issue by piradata** [hydralauncher/hydra#403]
### Describe the bug

The usersettings ui is resetted when changing panes, although the values are saved.

The correct values are shown if if i change from settings to oyther thing in the sidebar and go back. video below show this behavior

### Steps to Reproduce

https://github.com/hydralauncher/hydra/assets/16529503/2803b5b7-049d-41fd-aaf9-72dfe7ee6b22

### Expected behavior

Should keep the current settings when changing setting pane

### Screenshots

Video above

### Operating System

Windows

### Hydra Version

1.2.0 (main actually, tried to fix but am too dumb sowrry)

**Comment by piradata** [comment]
@zamitto do you have any idea why this happens? can take a look miself later but need a hint, i'm not too familiar with node/react/electron myself, played more with ruby, python, rust and kotlin

**Comment by zamitto** [comment]
I will take a look into it later, thanks!

Can I ask just to, next time, you record a video from the main branch or release version, without modified code. 
Your video has your feature of language change, this might mix things up, as this is not merged yet.

**Comment by piradata** [comment]
yeaa, sorry @zamitto , I noticed the bug while I was testing the feature, but happens with and without it, as the checkbox are also resetted

**Comment by piradata** [comment]
someone fixed this on main already, can close
