### ISSUE TITLE
[BUG] не могу установить 

### ISSUE THREAD

**Issue by DeFix0** [hydralauncher/hydra#404]
### Describe the bug

Дело проходит: так после того как я скачал exe файл, я попытался установить его, всё было нормально до тех пор пока не закончилась установка в конце установки приложение просто вылетело, и так всё время происходило, я пытался повторить ещё пару раз это действие и каждый раз при установке в конце предложение вылетало и не устанавливалась, если честно я уже не знаю в чем может быть проблема.

### Steps to Reproduce

Посмотрите ошибку.

### Expected behavior

исправление ошибки и помощи по установке.

### Operating System

Windows 11

### Hydra Version

1.2.1

**Comment by wiz30** [comment]
Hydra isn't responsible for any outsourced executables. The goal is to provide you the file

**Comment by JackEnx** [comment]
english, please.
