### ISSUE TITLE
[REQUEST] Possibility to choose Debrid/Torrent on download modal

### ISSUE THREAD

**Issue by mithunnivas** [hydralauncher/hydra#410]
### Is your feature request related to a problem? Please describe.

Currently on clicking the download option, it automatically starts downloading. Only after it starts it says if it downloads using debrid or torrent or direct. 

### Describe the solution you'd like

Can you give a menu like option for every game where we can choose if we want to download using debrid or torrent or direct download?

**Comment by zamitto** [comment]
This feature will be available on next update!

**Comment by mithunnivas** [comment]
> This feature will be available on next update!

I am a c# dev, let me know if you need any help
