### ISSUE TITLE
[BUG] Very slow download speed

### ISSUE THREAD

**Issue by comisha** [hydralauncher/hydra#414]
### Describe the bug

When loading games, the speed jumps up and down to 100 kb/s

### Steps to Reproduce

-

### Expected behavior

Help from knowledgeable people

### Screenshots

![Снимок экрана 2024-05-16 185045](https://github.com/hydralauncher/hydra/assets/170023568/5259b644-d7bc-4481-b7d1-1960a161727a)

### Operating System

Windows 11

### Hydra Version

1.2.1

### Additional Information

If it helps, then I'm downloading Red Dead Redemption II.

**Comment by JackEnx** [comment]
BitTorrent system is literally explained in the readme.

**Comment by comisha** [comment]
> Система BitTorrent буквально описана в файле readme.

What does it mean? I'm very bad at reading
