### ISSUE TITLE
[REQUEST] Reset adress of games .exe

### ISSUE THREAD

**Issue by RogefeS** [hydralauncher/hydra#416]
### Is your feature request related to a problem? Please describe.

I had put wrong addres of a game .exe in a game and dont found how to remake or undo this.

### Describe the solution you'd like

A place in configurations to manage the options of the games like the address, see how much space comsume in disk, what server was choosen to dowwnload, redownload, delete just options, save, downloaded pack or entire game.

**Comment by wansleynery** [comment]
Hey, @RogefeS.

Have You tried the option **Remove from library**? It removes the game from your library and allows You to put again the correct path of your game.

<img width="296" alt="image" src="https://github.com/hydralauncher/hydra/assets/42624198/f80a61ba-e62f-4dc0-a4bb-8a715b444052">

**Comment by zamitto** [comment]
In 2.0 we added a new window which gives you this possibility
