### ISSUE TITLE
[BUG]  Does someone knows what that means ?

### ISSUE THREAD

**Issue by GGabrielCross** [hydralauncher/hydra#420]
### Describe the bug

I open the program, and later, apeared a tab saying: "A JavaScript error occurred in the main process"

### Steps to Reproduce

Open the program and wait, i think

### Expected behavior

Not show that

### Screenshots

![Captura de tela 2024-05-16 184417](https://github.com/hydralauncher/hydra/assets/168583247/bb3331e8-356f-4e11-9642-6b8ae6a8f498)

### Operating System

Windows 11

### Hydra Version

1.2.0

**Comment by zamitto** [comment]
It is fixed on 1.2.1. Your installation should auto update on the next launch.
But you can manual install from the releases page. No need to uninstall the current one
