### ISSUE TITLE
[REQUEST] Remove Game from Library via Right-Click

### ISSUE THREAD

**Issue by morninjer** [hydralauncher/hydra#421]
### Is your feature request related to a problem? Please describe.

Currently, removing games from the library requires navigating through several menus, which can be time-consuming. This can be inconvenient for users who want to quickly manage their game library.

### Describe the solution you'd like

I would like to have the ability to remove games from the library by right-clicking on them. This would streamline the process and make it faster. Additionally, it would be beneficial to include other actions in the right-click context menu, such as uninstalling and reinstalling games. This would enhance the overall user experience by providing more convenient options for managing the game library.

**Comment by zamitto** [comment]
In 2.0 we added a new window which gives you this option
