### ISSUE TITLE
[REQUEST] DISPONIBILIZAÇÃO DA SENHA DE DESCOMPACTAÇÃO

### ISSUE THREAD

**Issue by thahmmyresz** [hydralauncher/hydra#425]
### Is your feature request related to a problem? Please describe.

Embora todos as novas atualizações sejam ótimas, tive um problema e pensei que poderia ser disponibilizado a senha de descompactação. Baixei o Mortal Kombat XL e antes do download foi disponibilizado uma senha que até então copiei, mas pela demora da finalização tive que desligar o computador e perdi a senha. Tentei de todas as maneiras mas não consegui a senha novamente e isso poderia ser disponibilizado fora a parte em algum recurso para não sofrermos posteriormente.

### Describe the solution you'd like

Uma aba para acessar a senha disponibilizada

**Comment by SamFontainha** [comment]
English please, and the password of descompactation are available always you want install if you don't click in don't show again, the password is online-fix.me
