### ISSUE TITLE
[BUG] Hydra is downloading an outdated version of Content Warning

### ISSUE THREAD

**Issue by AirFryerDaVolkswaggen** [hydralauncher/hydra#427]
### Describe the bug

In the launcher, Hydra downloads Content Warning thru online-fix, but in the official online-fix website the download version for Content Warning is 1.15.a while the version that Hydra downloads in the laucher is 1.9.b, which means Hydra is downloading an outdated version of Content Warning.

### Steps to Reproduce

1. Download Content Warning Thru Hydra and check the version on the file
2. Check the version for Content Warning in the official online-fix website

### Expected behavior

Content Warning running on a outdated version when downloaded from Hydra.

### Screenshots

Online-Fix:

![OnlineFix_ContentWarning](https://github.com/hydralauncher/hydra/assets/170132086/9e201316-88d2-4a6c-8fb2-21f2c60b2844)

Hydra Launcher:

![HydraLaucher_ContentWarning_Date](https://github.com/hydralauncher/hydra/assets/170132086/c5fb0ac7-9688-441c-a257-00d916238fb7)
![HydraLauncher_ContentWarning_VersionDownload](https://github.com/hydralauncher/hydra/assets/170132086/9d918e7c-e92e-4bb9-a349-b5b7374e1590)

### Operating System

Windows 10

### Hydra Version

1.2.1

**Comment by zamitto** [comment]
It is fixed in the last Hydra version (if the repacker release a new version this behaviour might happen again, but we will soon fix this for once)
