### ISSUE TITLE
Watch_Dogs, Watch_Dogs 2, 3d gta trilogy and some other games

### ISSUE THREAD

**Issue by NightHairen** [hydralauncher/hydra#428]
WD and WD2 do not have download buttons, although hacked versions of these games have long been on the Internet 
3D GTA trilogy (original, not deffective edition) just does not appear in the search
not only these games has that issue. The Forest, Source engine games, and... I don't know how many other games have this issue

**Comment by JackEnx** [comment]
I'm going to assume you didn't read the README
