### ISSUE TITLE
[REQUEST] PCGamingWiki 

### ISSUE THREAD

**Issue by LCS-M4D** [hydralauncher/hydra#429]
### Is your feature request related to a problem? Please describe.

If support can be added to the website https://www.pcgamingwiki.com/
It contains several tutorials and fixes for games

### Describe the solution you'd like

If support can be added to the website https://www.pcgamingwiki.com/
It contains several tutorials and fixes for games

**Comment by JackEnx** [comment]
please, when opening an issue, state in detail what you want, how it should be implemented, and alternatives
