### ISSUE TITLE
[REQUEST] 

### ISSUE THREAD

**Issue by bylbulator** [hydralauncher/hydra#431]
### Is your feature request related to a problem? Please describe.

I am told that my internet is 50 mbps, but in Hydra it is 110 kb
![111](https://github.com/hydralauncher/hydra/assets/170174022/a7de6d22-854d-4701-a811-f88740d1cffc)
![image](https://github.com/hydralauncher/hydra/assets/170174022/41ff3e71-f183-487d-9ff2-24e48294dbce)

### Describe the solution you'd like

i need my internet 5mbps

### Describe alternatives you've considered

none

**Comment by JackEnx** [comment]
just read the README
