### ISSUE TITLE
[BUG] Trojan.Win32.Generic

### ISSUE THREAD

**Issue by jurandy007** [hydralauncher/hydra#434]
### Describe the bug

The antivirus detects PDM:Trojan.Win32.Generic when running Hydra. Is there something wrong with this, or is it a false positive?

### Steps to Reproduce

1 - Install Kasperspy Premium
2 - Execute Hydra.exe

### Expected behavior

The antivirus detects PDM:Trojan.Win32.Generic when running Hydra.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/738929/7c90edc1-0d5c-4f57-a56c-396f29d9e711)

### Operating System

Windows 11 Pro 23H2  22631.3593

### Hydra Version

1.2.2

**Comment by LasthopeBR** [comment]
It's very likely to be a false positive

![image](https://github.com/hydralauncher/hydra/assets/40614287/5262b984-e8b4-4980-b788-a9af60ab8db5)

link virustotal 1.2.0: https://www.virustotal.com/gui/file/4bd9024e465b7b5382bedfa60255d89cc3b540eaddf97a89e87995eb99f5343a

![image](https://github.com/hydralauncher/hydra/assets/40614287/cc86175e-c9dd-4e42-b741-ffc31d0e4b8a)

link virustotal 1.2.2: https://www.virustotal.com/gui/file/b407890733078a58c8a1af80794266f958ac0dc93e943ff799e4136b0baf509a

**Comment by marcosmaia** [comment]
E Virus Kasperspy  tenhos varios hacks ele nuca me deu falso positivo.

**Comment by JackEnx** [comment]
> E Virus Kasperspy tenhos varios hacks ele nuca me deu falso positivo.

vou nem me dar o trabalho de responder em inglês, você tem literalmente TODO codigo fonte aqui, se não sabe o que está fazendo, saia do github

**Comment by jurandy007** [comment]
> It's very likely to be a false positive
> 
> ![image](https://private-user-images.githubusercontent.com/40614287/331808545-5262b984-e8b4-4980-b788-a9af60ab8db5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDc3NTAsIm5iZiI6MTcxNjI0NzQ1MCwicGF0aCI6Ii80MDYxNDI4Ny8zMzE4MDg1NDUtNTI2MmI5ODQtZThiNC00OTgwLWI3ODgtYTlhZjYwYWI4ZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIzMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMmRmZmJmOTg1ZWZmMjQ1ZGY3Yzg3Yzk3YzNiZDFjZTMxOTJlMTUxY2MyNjBmMzRiYzZlZDQ0YzM4YzE1NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xjxSfMu_BWStUMwtxLIE00xr4TJCfrYqSCuxYj_cgjo)
> 
> link virustotal 1.2.0: https://www.virustotal.com/gui/file/4bd9024e465b7b5382bedfa60255d89cc3b540eaddf97a89e87995eb99f5343a
> 
> ![image](https://private-user-images.githubusercontent.com/40614287/331808692-cc86175e-c9dd-4e42-b741-ffc31d0e4b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDc3NTAsIm5iZiI6MTcxNjI0NzQ1MCwicGF0aCI6Ii80MDYxNDI4Ny8zMzE4MDg2OTItY2M4NjE3NWUtYzlkZC00ZTQyLWI3NDEtZmZjMzFkMGU0YjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIzMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNTlmMTJhZmNhYzRmMDA1N2VlNWQ3N2VlMTg1ZjJiYWFiYTI2ZGIzMGM2MDYyZjQ2OWJlM2RlM2Y3MTBjZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cIflQzaAmcVcgLB2LiYBWondD8uZ3EovrWHk2r1X880)
> 
> link virustotal 1.2.2: https://www.virustotal.com/gui/file/b407890733078a58c8a1af80794266f958ac0dc93e943ff799e4136b0baf509a

I understand, thank you for clarifying my doubt.
