### ISSUE TITLE
[REQUEST] Suggest options for evaluation.

### ISSUE THREAD

**Issue by JurandyRafael** [hydralauncher/hydra#435]
### Is your feature request related to a problem? Please describe.

When I see a game without download options, I think I have already seen it or know where to find the torrent, it's just not on Hydra.

### Describe the solution you'd like

A solution would be to provide a 'Suggest Source' button. This way, the user could suggest some sources they find (reliable torrent links) for the developer to evaluate and decide which links to add to the game or not."

**Comment by JackEnx** [comment]
all download sources is entering responsibility of the community.
