### ISSUE TITLE
[BUG] Error in the download

### ISSUE THREAD

**Issue by brun0lct** [hydralauncher/hydra#436]
### Describe the bug

when i try to download any game happens an error with the JavaScript, that started after i downloaded the 1.2.1 and 1.2.2 and i'm using the real debrid. 

### Steps to Reproduce

1. Download any game
2. During the process, the problems happens

### Expected behavior

Conclude the download of the game for i could install it on my pc

### Screenshots

![error 4](https://github.com/hydralauncher/hydra/assets/110179491/1e1b9bd6-0ec2-4d86-9f4a-1b7ee2c6404f)
![error 3](https://github.com/hydralauncher/hydra/assets/110179491/7686ee92-d912-406f-9c22-04f556bda2ac)
![error 2](https://github.com/hydralauncher/hydra/assets/110179491/3ac0dcf1-d792-46fb-b8f9-e841bebe32b6)
![error](https://github.com/hydralauncher/hydra/assets/110179491/ed1b685e-55c7-4b4a-97a4-00ad22fac832)

### Operating System

Windows 10

### Hydra Version

1.2.2 and 1.2.1

**Comment by zamitto** [comment]
@brun0lct is it still an issue in 2.1.7?
If so, could you upload logs after updating to 2.1.7?

**Comment by JackEnx** [comment]
long time no response, if the problem still exists, open the issue again.
