### ISSUE TITLE
[REQUEST] Alan Wake 2 is not showing

### ISSUE THREAD

**Issue by whocastr** [hydralauncher/hydra#446]
### Is your feature request related to a problem? Please describe.

no.

### Describe the solution you'd like

https://dodi-repacks.site/alan-wake-2/
https://fitgirl-repacks.site/alan-wake-2/

### Describe alternatives you've considered

why this game isn't showing in hydra?

**Comment by thegrannychaseroperation** [comment]
Only Steam library for now.
