### ISSUE TITLE
[BUG] Download error

### ISSUE THREAD

**Issue by Morgan2421** [hydralauncher/hydra#450]
### Describe the bug

downloading metadata the error is such that the download stands on this notification and does not move windows 10 anymore

### Steps to Reproduce

1 click install the game 2 after the notification comes out where the download speed is shown it says download metadata

### Expected behavior

downloading metadata the error is such that the download stands on this notification and does not move windows 10 anymore

### Screenshots

I can't send screenshots

### Operating System

windows 10

### Hydra Version

the latest version

### Additional Information

downloading metadata the error is such that the download stands on this notification and does not move windows 10 anymore

**Comment by zamitto** [comment]
Is it still and issue? If so, could you upload your logs after updating to 2.1.4?

**Comment by JackEnx** [comment]
long time without response, if the problem persists, open the issue again and report the problem
