### ISSUE TITLE
Como coloca o Hydra em português? 

### ISSUE THREAD

**Issue by Gravisk** [hydralauncher/hydra#452]
### Describe the bug

Meu hydra baixa em ingês e não consigo colocar em português, tem como mudar a lingua?

### Steps to Reproduce

1. Baixo o Hydra
2. Ele só abre em inglês
3. Teria como me ajudar a colocar em português?

### Expected behavior

Meu hydra baixa em inglês e não consigo colocar em português, tem como mudar a língua?

### Operating System

Windows 10

### Hydra Version

1.2.2

**Comment by DaniHRE** [comment]
Amigo... Dica sincera, aprender um pouco de inglês iria de ajudar muito, em diversos fatores.

**Comment by whocastr** [comment]
acho que o hydra deteca a linguagem do pc, o seu pc tá em pt-br?

**Comment by whocastr** [comment]
![image](https://github.com/hydralauncher/hydra/assets/63364180/8aa7c951-3c1e-43ac-b4d5-2a15e035610d)

**Comment by Rafael-Floriano** [comment]
Pelo que eu entendi o @whocastr está certo, o Hydra deveria detectar o idioma do seu computador... porém fazendo uns testes aqui na minha máquina o Hydra não detectou que o meu PC está em português (Fiz a troca da linguagem do computador de inglês para português):

![image](https://github.com/hydralauncher/hydra/assets/93800616/7420ad1d-4b37-4f5b-b918-9b2d183c17af)


Porém se eu rodar o código fonte do projeto pelo script de desenvolvimento com "yarn dev" o Hydra identifica que o meu computador está em português:

![image](https://github.com/hydralauncher/hydra/assets/93800616/dc03b3f0-a8f0-40b5-8cc0-8b8c0ce4e7c9)

**Comment by zamitto** [comment]
On next release we will add the option to change language
