### ISSUE TITLE
[BUG]  Download seeds

### ISSUE THREAD

**Issue by falseranker** [hydralauncher/hydra#453]
### Describe the bug

When i try to download something it shows that has 7 peers and 4 seeds (exemple from ghost of tsushima) and then comes back to 0 and proceeds to download nothing. I tried to download several games and different seeds and it all does the same bug

### Steps to Reproduce

1. Download something
2. Starts to downloading the meta and does nothing

### Expected behavior

Just donwload everything normaly

### Operating System

Windows 10

### Hydra Version

1.2.2

### Additional Information

Quando tento baixar algo ele mostra que tem 7 peers and 4 seeds (exemplo do ghost of tsushima que estou tentando baixar) e depois volta para 0 e não baixa nada. Tentei baixar vários jogos e  de sites diferentes e dá tudo o mesmo bug

**Comment by llLuckyll** [comment]
O meu está com o mesmo erro segue imagem 
![Uploading 17217759193234926128099244707338.jpg…]()

**Comment by HugoLopes1706** [comment]
i got the same problem, i try i lot, and i'm using the latest version.

**Comment by JackEnx** [comment]
Could you please let me know if the problem persists?

**Comment by HugoLopes1706** [comment]
No, thanks, is fixed.

Em dom., 27 de out. de 2024 14:23, JackEnx ***@***.***>
escreveu:
