### ISSUE TITLE
[REQUEST] The game "Super Bunny man" is not on Hydra's catalogue

### ISSUE THREAD

**Issue by AirFryerDaVolkswaggen** [hydralauncher/hydra#457]
### Is your feature request related to a problem? Please describe.

There as games on hydra that show up in the search bar even tho there are no download options for them. That is not the case for Super Bunny Man, which doesn't even show up if you look it up on the search bat. The game already has a download on online fix so it would be nice for it to be added to hydra.

### Describe the solution you'd like

add Super Bunny Man to Hydra which already has a download on onlinefix

**Comment by JackEnx** [comment]
we don't add the games on hydra.
