### ISSUE TITLE
erro stean

### ISSUE THREAD

**Issue by edsonassishl** [hydralauncher/hydra#459]
### Describe the bug

No jogog the las of us, quando tento iniciar o game da errro que tem que instala o steam_api64.dll

### Steps to Reproduce

na hora de iniciar o jogo

### Expected behavior

Jogo rodasse normamente 

### Operating System

windows 11

### Hydra Version

1.2.2

**Comment by zamitto** [comment]
Please, join telegram group and ask on the support channel
Closing as this issue is not related directly to Hydra
