### ISSUE TITLE
[BUG] Error during initialization: ERROR: sound bank failed to load cmn_root.polish. You have a build problem. 

### ISSUE THREAD

**Issue by Zateraa** [hydralauncher/hydra#460]
### Describe the bug

Boa noite, baixei o BO2 pelo hydra e depois de instalar a linguagem em ingles o jogo nao abre e sempre da esse problema, Error during initialization:
ERROR: sound bank failed to load cmn_root.polish. You have a build problem., gostaria de saber como resolver

### Steps to Reproduce

eu tento abrir o jogo e da o erro

### Expected behavior

que o jogo abrisse 

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/170278159/58d3e9f5-34ab-475b-ae3e-ffbcf2f5e8e0)

### Operating System

WIN10

### Hydra Version

1.2.2

**Comment by zamitto** [comment]
This issue is not directly related to Hydra.
Please, ask for help on the support channel in our Telegram
