### ISSUE TITLE
[BUG] A aba de downloads simplesmente esta em branco().

### ISSUE THREAD

**Issue by jgpc12** [hydralauncher/hydra#462]
### Describe the bug

literalmente isso que esta escrito, n sei se é somente no meu computador

### Steps to Reproduce

só clicar em downloads, embaixo do catalogo

### Expected behavior

queria que voltasse ao normal

### Screenshots

![Capturar](https://github.com/hydralauncher/hydra/assets/65517209/46037940-6ccc-4aa6-b9d6-2821dcb50acb)

### Operating System

windows 10

### Hydra Version

1.2.2

### Additional Information

se fechar e reabrir pela barra de tarefas ele reseta, mas a aba ainda n funciona

**Comment by Infraction7** [comment]
wut? 💀
