### ISSUE TITLE
[BUG] Erro ao tentar fazer download de algum jogo

### ISSUE THREAD

**Issue by Leonard-salles** [hydralauncher/hydra#464]
### Describe the bug

quando tento fazer downloadd de algum jogo na versao 1.2.2, me é reporta um erro de instalação do hydra
![erro-install-hydra](https://github.com/hydralauncher/hydra/assets/95556347/83a2e12a-e946-456b-8fd5-4350d5b0d8e3)

### Steps to Reproduce

1- escolha um 

### Expected behavior

Esperava que o download fosse feito com sucesso

### Screenshots

![erro-install-hydra](https://github.com/hydralauncher/hydra/assets/95556347/eb93239e-f451-4b3e-ae9a-92f258da17ef)
![erro-install-hydra2](https://github.com/hydralauncher/hydra/assets/95556347/b63bb5cf-0b2a-4fb2-92d3-8951899480fb)

### Operating System

window 10

### Hydra Version

1.2.2

**Comment by zamitto** [comment]
When you selected the Elden Ring .exe file you probably selected the Hydra installer instead of the game .exe.

You can remove the game from library and then add it again, selection the correct .exe file
