### ISSUE TITLE
[BUG]  Nao esta abrindo!

### ISSUE THREAD

**Issue by TTVMarech4** [hydralauncher/hydra#473]
### Describe the bug

o hydra na primeira versao abre mas não aparecem nenhum jogo para download, mas quando eu desinstalo  a primeira versao e instalo a mais atual mesmo com anti virus e tudo mais desligado ele instala normalmente mas quando vou abrir não abre. não aparece nenhuma mensgem de erro ou algo do tipo, simplismente aparece uma borda tranparende como se fosse do laucher e some e o laucher nao funciona
![image](https://github.com/hydralauncher/hydra/assets/170399017/3870739b-bc12-4789-805c-ccd046dad2ef)

### Steps to Reproduce

.

### Expected behavior

.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/170399017/cb2146ea-be9d-4420-b225-bdbc7c1ed3c7)

### Operating System

windows 11 ghost spectre

### Hydra Version

1.2.2

### Additional Information

.

**Comment by DaniloHub123** [comment]
verifica se ele está em segundo plano antes de desistala, depois instala a mais recente

**Comment by zamitto** [comment]
Please, install the last update 1.2.3. It fixes this bug on ghost spectre
