### ISSUE TITLE
[REQUEST] Adding lutris support

### ISSUE THREAD

**Issue by FarParticul** [hydralauncher/hydra#474]
### Is your feature request related to a problem? Please describe.

No, it's not.

### Describe the solution you'd like

I would like to make it so that there is support for lutris in the launcher itself in gnu/linux distributions. This would create some convenience in installing and running games.

### Describe alternatives you've considered

Haven't looked into it yet

**Comment by scrlkx** [comment]
Related to #438, #279 and #299. We do have a pull request that aims to allow us to run games using Lutris itself but Linux is not having a good amount of attention by the maintainers.

**Comment by scrlkx** [comment]
To be honest we should aim to allow running games going straight to Wine or Proton but as we can't even fix the games installation I don't it happening.

**Comment by FarParticul** [comment]
> To be honest we should aim to allow running games going straight to Wine or Proton but as we can't even fix the games installation (#304) probably not gonna happen soon.

So it's cool if from the program itself will be run, but it will be more convenient through lutris which has a lot of settings and support for other emulators (I know that wine/proton is not an emulator). I'll close this request then, thanks for the reply!
