### ISSUE TITLE
[BUG] The Hydra is not updating.

### ISSUE THREAD

**Issue by PlugManYT** [hydralauncher/hydra#475]
### Describe the bug

Hydra is not updating. I received a notification that Hydra 1.2.2 has been downloaded and will update itself when I close it. An update was released two days ago and Hydra is not being updated. Hydra 1.2.1 has not updated itself either. I had to tear down the program and download it again

### Steps to Reproduce

._.

### Expected behavior

Hydra will be automatically updated.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/136507921/10f5e0f5-a8f8-429d-9436-fd97bf4ceb57)
![image](https://github.com/hydralauncher/hydra/assets/136507921/950d88f9-7f89-419d-abc7-c513aea5e1ed)

### Operating System

Windows 11

### Hydra Version

1.2.1

**Comment by oSxpreme** [comment]
Unfortunately I have the same issue ://

**Comment by zamitto** [comment]
Could you try this:

Go to C:\Users\YOUR_USER_NAME\AppData\Local and if delete any `hydra` or `hydra-updater` or `hydralauncher-updater` folder that remained

This should force the auto updater to download the update again

**Comment by oSxpreme** [comment]
I'm sorry for the late reply. 
That seemed to have solved my issue, but would that mean I'd have to do that everytime an update comes out?

**Comment by zamitto** [comment]
No, you shouldn't need to do it again, only this time.

I'm not 100% sure why this happens, but one reason could be that we changed the package name (and consequently the installation folder) on version 1.2.3 to fix a conflict for linux users.
And unfortunately, it seems to have caused update conflicts for some users.
