### ISSUE TITLE
[BUG] Wrong progress status

### ISSUE THREAD

**Issue by zrtsky** [hydralauncher/hydra#478]
### Describe the bug

Wrong file size shown in progress info on download page, downloaded more then original file size

### Steps to Reproduce

1. Start download new game  
2. Go to downloads page
3. Check the file size on downladed size

### Expected behavior

Expected correct file size

### Screenshots

![Screenshot (1)](https://github.com/hydralauncher/hydra/assets/42916643/01d15ff3-4f35-4a1d-a833-955c01aab5eb)

### Operating System

Windows 11

### Hydra Version

1.2.2

**Comment by zamitto** [comment]
This should be fixed now
