### ISSUE TITLE
[REQUEST] Add a option: Friend List, If a friend of yours enters a game on Hydra, it will appear that your friend has entered the game in the corner of the screen, you will be able to enter their game to play.

### ISSUE THREAD

**Issue by DaniloHub123** [hydralauncher/hydra#479]
### Is your feature request related to a problem? Please describe.

Fix problems.

### Describe the solution you'd like

Pls add this

### Describe alternatives you've considered
![2](https://github.com/hydralauncher/hydra/assets/170479243/4bbabca6-0a51-4d07-a0d4-ebdc3f6b3571)

You can join on your friend 
![3](https://github.com/hydralauncher/hydra/assets/170479243/668ce565-b5ed-4668-ab58-6afe4c450b7d)

### Additional context

Friend List

**Comment by Panetina** [comment]
Second to this. 
Maybe the joining their game will be hard as it only downloads from repacks and those still use Steam to play online cracked games, but still a list of friend and just see who plays what would be cool.

**Comment by zamitto** [comment]
We added friends in 2.1.0. We will improve this features over time
