### ISSUE TITLE
um jogo (bopl battle) tem senha nao sei o que fazer[BUG] 

### ISSUE THREAD

**Issue by Laurojjj** [hydralauncher/hydra#480]
### Describe the bug

abaixei o jogo (pelo server do onlinefix) e quando clico para instalar ele abre a pasta nele tem um arquivo .zip que precisa de um codigo

### Steps to Reproduce

simplesmente abaixe normalmente (pelo serve do onlinefix) e clique instalar ele vai te levar pra uma pasta com o .zip do jogo voce tenta abrir e ele pede senha

### Expected behavior

só queria jogar com meus amigos ):

### Screenshots

![Captura de tela 2024-05-21 223148](https://github.com/hydralauncher/hydra/assets/98439502/a2913830-00e3-4875-a4cf-3d016fa05b6e)
![Captura de tela 2024-05-21 223212](https://github.com/hydralauncher/hydra/assets/98439502/92742766-7059-463e-a41a-24ae31821000)
![Captura de tela 2024-05-21 223221](https://github.com/hydralauncher/hydra/assets/98439502/951f3ad1-cfe7-4624-9c8f-f40a8c2c9e04)

![Captura de tela 2024-05-21 223346](https://github.com/hydralauncher/hydra/asset
![Captura de tela 2024-05-21 223300](https://github.com/hydralauncher/hydra/assets/98439502/430b51ee-7043-496c-bd08-9597192fc070)

![Captura de tela 2024-05-21 223326](https://github.com/hydralauncher/hydra/assets/98439502/c4dcfc8c-2ae8-42ef-b5d0-2b4e2493fc2a)
s/98439502/9245c2d8-f46a-4254-9f2c-a5bd737cd331)
![Captura de tela 2024-05-21 223310](https://github.com/hydralauncher/hydra/assets/98439502/864b6ea1-b7ff-443b-a39e-bf0b5b783a27)

### Operating System

windows 11

### Hydra Version

1.2.3 ´´exodus´´

**Comment by Laurojjj** [comment]
galera me desculpa, fui ver se alguem a mais teve isso e achei um cara falando que a senha é: online-fix.me 
testei e funcionou

**Comment by zamitto** [comment]
meu irmao em cristo tem um print que tu mesmo botou nessa issue que diz exatamente que a senha é online-fix.me
Cara, tu nào leu nem o que tu botou na issue não?
Enfim, que bom que conseguiu se achar ai e bom proveito do jogo, fechando a issue pq ta resolvido ja
