### ISSUE TITLE
[REQUEST]  Change installation folder Path after install a Game

### ISSUE THREAD

**Issue by joaolucaswork** [hydralauncher/hydra#484]
### Is your feature request related to a problem? Please describe.

When I  try to move a game from original download location, I receive a error: "Windows cannot find  ".../path/file/",.

![Screenshot 2024-05-22 094654](https://github.com/hydralauncher/hydra/assets/19161299/5190e524-fc3c-48e8-92f9-00b7873bd331)

### Describe the solution you'd like

A good solution would be to imitate the behavior when downloading the game for the first time, where a window to select folder or file opens and I can choose a new location.

**Comment by keuwey** [comment]
I have been facing the same problem. There is still no option to change the game's installation or play path if you move the folder to another location. It would be perfect if this option could be added to the games page.

**Comment by DaniloHub123** [comment]
Real

**Comment by zamitto** [comment]
In 2.0 you can select a new executable for your games
