### ISSUE TITLE
[BUG] hydralauncher_1.2.3_amd64.deb missing icon

### ISSUE THREAD

**Issue by nerun** [hydralauncher/hydra#485]
### Describe the bug

After installation of `hydralauncher_1.2.3_amd64.deb` there's no icon! Nor in Menu, nor after open in task bar.

### Steps to Reproduce

Just open the menu. Hydra has no icon.

### Expected behavior

There should be an icon.

### Screenshots

![hydraicon](https://github.com/hydralauncher/hydra/assets/3987342/85624182-6d9a-4e4d-bc5b-bd8ced65f228)

### Operating System

Linux Mint 21.3

### Hydra Version

1.2.3

**Comment by nerun** [comment]
Version 1.2.4 has the same issue.

**Comment by nerun** [comment]
# Hot to fix
File: `/usr/share/applications/hydralauncher.desktop`

```
[Desktop Entry]
Name=Hydra
Exec=/opt/Hydra/hydralauncher %U
Terminal=false
Type=Application
Icon=hydralauncher
StartupWMClass=Hydra
Comment=Hydra
Categories=Utility;
```
Change to:
```
[Desktop Entry]
Name=Hydra
Exec=/opt/Hydra/hydralauncher %U
Terminal=false
Type=Application
Icon=/usr/share/icons/hicolor/0x0/apps/hydralauncher.png
StartupWMClass=Hydra
Comment=Hydra
Categories=Utility;
```

**Comment by nerun** [comment]
Agora que vi que vocês são brasileiros.

**Comment by nerun** [comment]
Criei um changelog.gz decente também: [changelog.gz](https://github.com/hydralauncher/hydra/files/15441276/changelog.gz)

**Comment by zamitto** [comment]
Even though the project is maintained by brazilians, we ask to keep issues and pr's in English, as there are a lot of users who are not Portuguese speakers

**Comment by nerun** [comment]
Also, hydra launcher icon must be moved to folder 512x512, since it is the right size:
* From: `/usr/share/icons/hicolor/0x0/apps/hydralauncher.png`
* To: `/usr/share/icons/hicolor/512x512/apps/hydralauncher.png`

**Comment by nerun** [comment]
In `/usr/share/applications/hydralauncher.desktop`, would be better change category from utility to game:

```
Categories=Utility;
```

to:

```
Categories=Game;
```
