### ISSUE TITLE
Versão 1.2.3 já não abre maximizado [BUG] 

### ISSUE THREAD

**Issue by henriquesommitz** [hydralauncher/hydra#492]
### Describe the bug

Primeiro de tudo, parabéns pela criação do Hydra. 
BUG: 
Com o atalho do Hydra configurado para abrir maximizado nas propriedades, sempre deu certo, mas a atualização 1.2.3 adicionou uma nova tela, que acredito ser de carregamento, com a imagem da Hydra. Agora esta tela nova com o símbolo da hydra é a única que é alterada com as configurações de maximização nas propriedades, mas quando a tela inicial do programa aparece ela muda para o modo janela, mesmo estando configurado para abrir maximizado. Desde já agradeço!

### Steps to Reproduce

Dois cliques no atalho do Hydra

### Expected behavior

Abrir no modo maximizado conforme as configurações feitas nas propriedades do atalho e não no modo janela.

### Operating System

Windows 10

### Hydra Version

1.2.6

### Additional Information

Me parece que as propriedades do .exe estão vinculadas agora a tela de carregamento, que por sua vez abre o programa em si. Pois a tela inicial com a imagem do hydra acata todas as configurações de inicialização feitas nas propriedades:
- Iniciar no modo janela
- Iniciar Maximizado
- Iniciar Minimizado
Mas somente essa tela de carregamento que acata essas configurações, pois quando o programa em si abre ele muda automaticamente para o modo Janela desobedecendo a configuração de abrir Maximizado das propriedades.

**Comment by zamitto** [comment]
1.2.6? 
Antes de tudo, confirma que é a 1.2.3 por favor que ta instalada ai
A última versão que lançamos é 1.2.3

**Comment by henriquesommitz** [comment]
Desculpe
É a 1.2.3 que tenho agora, digitei errado

**Comment by deividsilco** [comment]
Olá a todos, baixei a ultimas versões do launcher 1.2.3 e x.x.4 e ambos não abrem antes mesmo de disponibilizarem a x.x.4 eu estava tentando iniciar ele mas nada acontecia e quando vi a x.x.4 logo fui baixar e tentar usar e mesmo assim sem sucesso rs, mais alguem com esse problema ?
