### ISSUE TITLE
Ferramentas Úteis [REQUEST] 

### ISSUE THREAD

**Issue by henriquesommitz** [hydralauncher/hydra#493]
### Is your feature request related to a problem? Please describe.

Aqui vão minhas sugestões:
- Incluir jogos à biblioteca sem ter que instalar
- Adicionar jogos à uma lista de favoritos
- Pesquisar por gênero como: Horror, Adventure, Thriller, etc.
- Pesquisar por tipo: RPG, FPS, MMO, MOBA, etc.
- Opção de ocultar jogos que não tem download disponível.
- Poder filtrar o catálogo por gênero, estilo de jogo ou até mesmo pela inicial, pois a forma atual de navegar no catálogo é bem disfuncional.
- Fazer a busca aceitar palavras chaves como: horror, zombies, tiro. Ao invés de aceitar somente palavras específicas.
- Melhorar a busca, pois se digitamos o nome de um game inteiro com apenas uma letra errada o Hydra já não reconhece.

### Describe the solution you'd like

Parabéns pela criação do Hydra.

### Additional context

Poderia fazer uma extensão do Hydra para o Playnite. Seria demais.

**Comment by TheGman1102** [comment]
Excelente, colocou tudo que precisa ser adicionado urgentemente, eu to tentando chegar no final do catálogo faz uns 4/5 dias, do nada da uma tela branca. Ia ajudar muito pesquisa por ordem alfabética.

**Comment by daguerpedro** [comment]
Acho legal

**Comment by thegrannychaseroperation** [comment]
Please create one issue per topic, otherwise it will be impossible to track it. Thanks.
