### ISSUE TITLE
Lasted version not launch[BUG] 

### ISSUE THREAD

**Issue by deividsilco** [hydralauncher/hydra#495]
### Describe the bug

Hello everyone, I downloaded the latest versions of the launcher 1.2.3 and x.x.4 and both didn't open before they even made x.x.4 available. I was trying to start it but nothing happened and when I saw x.x.4 I immediately went to download it and try to use it and it still did without success lol, anyone else having this problem?

### Steps to Reproduce

after download de most recent exe, nothing happend when click up then

### Expected behavior

nothing happend

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by zamitto** [comment]
The installer didn't run? Or it installs but the program does not open after installing?
It just does not open? No log error? Nothing?
