### ISSUE TITLE
[SOLICITAÇÃO]Reativar a reprodução dos vídeos de trailer automático como era antes.

### ISSUE THREAD

**Issue by Maxuell123** [hydralauncher/hydra#496]
### Is your feature request related to a problem? Please describe.

Antes os vídeos de trailer dos jogo já reproduzia automaticamente isso facilitava ver o vídeo do jogo em vez de toda vez ter que apertar o play, ai deis a versão 1.2.3 isso parou de acontecer

### Describe the solution you'd like

Reativar a reprodução dos vídeos de trailer automático

### Describe alternatives you've considered

Reativar a reprodução dos vídeos de trailer automático

### Additional context

Reativar a reprodução dos vídeos de trailer automático

**Comment by zamitto** [comment]
It divides opinions. It was initially with auto play on to mimic steam. But, Hydra's game page is a the same page to download the game and to access your catalogue and hit the play button.
It was not convenient to auto play the videos every single time you wanted to launch the game from Hydra. So we decided it was better no disable the auto play
