### ISSUE TITLE
[BUG]  Versão 1.2.4 já não abre maximizado

### ISSUE THREAD

**Issue by henriquesommitz** [hydralauncher/hydra#497]
### Describe the bug

BUG:
Com o atalho do Hydra configurado para abrir maximizado nas propriedades, sempre deu certo, mas a atualização 1.2.4 adicionou uma nova tela, que acredito ser de carregamento, com a imagem da Hydra. Agora esta tela nova com o símbolo da hydra é a única que é alterada com as configurações de maximização nas propriedades, mas quando a tela inicial do programa aparece ela muda para o modo janela, mesmo estando configurado para abrir maximizado. 

Me parece que as propriedades do .exe estão vinculadas agora à tela de carregamento, que por sua vez abre o programa em si. Pois a tela inicial com a imagem do hydra acata todas as configurações de inicialização feitas nas propriedades:

- Iniciar no modo janela
- Iniciar Maximizado
- Iniciar Minimizado

Mas somente essa tela de carregamento que acata essas configurações, pois quando o programa em si abre ele muda automaticamente para o modo Janela desobedecendo a configuração de abrir Maximizado das propriedades.

### Steps to Reproduce

Dois cliques no atalho do Hydra

### Expected behavior

Abrir no modo maximizado conforme as configurações feitas nas propriedades do atalho e não no modo janela.

### Operating System

Windows 10

### Hydra Version

1.2.4

### Additional Information

Desde já agradeço!

**Comment by zamitto** [comment]
Fixed in #504
