### ISSUE TITLE
[BUG]  Problema de SEGURANÇA!

### ISSUE THREAD

**Issue by henriquesommitz** [hydralauncher/hydra#498]
### Describe the bug

Após eu reportar um bug hoje o Hydra 1.2.3 desinstalou sozinho do meu computador, não sei se foi feito de forma remota ou não, mas isso é bem invasivo, vocês não acham?

### Steps to Reproduce

Reiniciei o o computador

### Expected behavior

Hydra estar instalado normal, mas não estava, foi completamente desinstalado do meu computador sem meu consentimento.

### Screenshots

Foi feita somente a desinstalação e exclusão dos arquivos, a versão 4 não foi instalada, mas a questão aqui é mais a desinstalação sem permissão do usuário.

### Operating System

Windows 10

### Hydra Version

1.2.4

### Additional Information

Isso é uma questão de segurança. Ninguém deve desinstalar o programa se não o próprio usuário.

**Comment by zamitto** [comment]
Cara, tem absolutamente nenhuma possibilidade de a gente desinstalar algo do seu computador, código fonte ta ai pra tu analisar.
Provavelmente foi um bug no auto update que desinstalou a versão atual e nao conseguiu instalar a nova

**Comment by henriquesommitz** [comment]
Tudo bem. Acredito em você. Acabei de instalar a versão 1.2.4, mas segue com o problema do modo janela. Só a tela de carregamento obedece as configurações de exibição das propriedades do atalho.

**Comment by henriquesommitz** [comment]
Vou ver se consigo solucionar o problema de não abrir maximizado e se eu conseguir, reporto aqui.

**Comment by zamitto** [comment]
Ok, to dando uma olhada também pra ver sobre esse bugzinho
