### ISSUE TITLE
[BUG]filerepmalware

### ISSUE THREAD

**Issue by anthonycxp** [hydralauncher/hydra#499]
### Describe the bug

quando abro o hydra o avast me notifica por um filerepmalware(malware em potencial) 

### Steps to Reproduce

avast information

### Expected behavior

malware em potencial

### Operating System

windows 11

### Hydra Version

latest

**Comment by thegrannychaseroperation** [comment]
I see no point in reporting how the AV of your choice reports Hydra. The code is open source, feel free to build it and scan it yourself. Closing.
