### ISSUE TITLE
[REQUEST] Splash Screen

### ISSUE THREAD

**Issue by xbozo** [hydralauncher/hydra#502]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Would like to see a splash screen similar to Discord; a logo in the center a text with some data or curiosity right below.
This would be used mainly on the launcher initiation, but could be reused for other trouleshoot/updating/loading screens.
![image](https://github.com/hydralauncher/hydra/assets/119091492/e8c7e9fa-9aad-485e-90f3-4c2df8762c95)

**Comment by zamitto** [comment]
It was done in #466
