### ISSUE TITLE
Пароли!!!!!![BUG] 

### ISSUE THREAD

**Issue by Deniska2336** [hydralauncher/hydra#507]
### Describe the bug

Скачал игру Магика2. в итоге получил Запароленый архив с игрой. Вопрос зачем скачивал 

### Steps to Reproduce

Скачай игру магика2

### Expected behavior

Я ожидал архив с игрой без пароля

### Operating System
Windows 11

### Hydra Version

v.1.1.0. Exodus

**Comment by 3misty** [comment]
Ну так это не баг. Лаунчер берет репаки с разных источников, и не возможно предусмотреть все из условия, а ты скорее всего скачал с online fix, у которых ВСЕ под под одним и тем же паролем.
