### ISSUE TITLE
[BUG] No description on the game page if open game via download list

### ISSUE THREAD

**Issue by Barraki** [hydralauncher/hydra#508]
### Describe the bug

No description on the game page if opens the game in the download list

### Steps to Reproduce

- Open the download page
- Chose the game

### Expected behavior

Expected description of the game

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/33422772/57c104de-a3db-4afd-b21c-bf94cd008405)

### Operating System

windows 11 

### Hydra Version

1.2.4

### Additional Information

Lang: RU

**Comment by zamitto** [comment]
Hydra gets the game texts and most images from Steam page. If the game is blocked in your region on Steam, Hydra won't be able to gather this information. Currently, you would need to use a VPN to load all the game info.

**Comment by Barraki** [comment]
![image](https://github.com/hydralauncher/hydra/assets/33422772/3aa7e90c-1c78-4961-a161-1fc17c0b8e06)
https://github.com/hydralauncher/hydra/assets/33422772/cfa78f7a-2890-4e1b-8ebf-cfbeb8b07d7d


Ok. But why do I have a description of an open game page from the sidebar library list?

And I don't need VPN for this game in steam
![image](https://github.com/hydralauncher/hydra/assets/33422772/a4931243-369b-4ce9-8751-c6f53b44523e)

**Comment by Barraki** [comment]
[combined.log](https://github.com/hydralauncher/hydra/files/15474905/combined.log)

Of course

**Comment by zamitto** [comment]
Sorry, I read again your issue and you mentioned that you were in the Downloads page and then navigated to the game details. This was already fixed in the code and the issue should no longer happen in the next update

**Comment by thegrannychaseroperation** [comment]
Solved in 2.0.
