### ISSUE TITLE
[BUG]  Download de Jogo Sumiu!

### ISSUE THREAD

**Issue by ManoPurple606** [hydralauncher/hydra#509]
### Describe the bug

Abaixei recentemente o jogo Ghost Of Tsushima (inclusive muito obra Hydra Group por isso).
Joguei normalmente, perfeito, após uma semana o fui jogar novamente o jogo simplesmente sumiu do meu diretório/HD.

Podem me ajudar ?

### Steps to Reproduce

Abaixei recentemente o jogo Ghost Of Tsushima (inclusive muito obra Hydra Group por isso).
Joguei normalmente, perfeito, após uma semana o fui jogar novamente o jogo simplesmente sumiu do meu diretório/HD.

Podem me ajudar ?

### Expected behavior

Abaixei recentemente o jogo Ghost Of Tsushima (inclusive muito obra Hydra Group por isso).
Joguei normalmente, perfeito, após uma semana o fui jogar novamente o jogo simplesmente sumiu do meu diretório/HD.

Podem me ajudar ?

### Operating System

Windows 10

### Hydra Version

Last

**Comment by JackEnx** [comment]
If you don't know how to report what happened, join the Telegram group, we can better check what may have happened.
