### ISSUE TITLE
Debrid services integration

### ISSUE THREAD

**Issue by Netflixyapp** [hydralauncher/hydra#51]
Hi, I want to suggest adding Debrid services such as Real-Debrid to help downloading torrents faster and most importantly in a more secured way for users in countries where torrenting is dangerous and punishable.

**Comment by hydralauncher** [comment]
Very little do I know about Debrid services. It's not a common thing in Brazil since torrenting has been freely adopted with no fear of any law intervention whatsoever. If you have any intention to start working on this, feel free to join the Discord and discuss a little bit more about it.

**Comment by nunera** [comment]
its mostly more of a convenience because if someone has downloaded the file before on real debrid, it's permanently cached and can be downloaded without needing to be torrented

**Comment by lilezek** [comment]
Real debrid is supported in https://github.com/lilezek/hydra already, but you will need to build it yourself. You can skip the python/torrent setup though, because Real Debrid overrides the torrent logic.

**Comment by hydralauncher** [comment]
Closing this since Real Debrid has been implemented on the main branch.
