### ISSUE TITLE
[BUG] Hydra doesn't open

### ISSUE THREAD

**Issue by Pamlau** [hydralauncher/hydra#510]
### Describe the bug

I installed the latest version to see if that was fixed but still nothing, I open it, it asks for admin permission to open as usual, then absolutely nothing shows up, I already tried reinstalling, already tried the -no-sandbox thing, already fully disabled kaspersky

This was happening in a different way a couple versions ago, where Hydra would open the 2nd time I executed it but with no version nor games shown, making it also impossible to use.

The client itself is still shown as running through task manager though

### Steps to Reproduce

1. Install client
2. Attempt to open
3. boom nothing

### Expected behavior

Expected client to open once executed

### Screenshots

![Screenshot_1](https://github.com/hydralauncher/hydra/assets/170785532/165004c4-0c06-47e2-b66e-b84d2f3dd1a3)

### Operating System

Windows 11

### Hydra Version

v1.2.4

**Comment by Daniel-wews** [comment]
estou com o mesmo problema do Pamlau, baixei normalmente e instalei. quando clico para ele abrir pede autorização pro adm e eu confirmo. depois nao acontece mais nada.

**Comment by Pamlau** [comment]
I really can't find any solution to this, I can't find the source of the problem that started from version 1.2.1 and beyond that doesn't let me open the launcher (on 1.2.1 it would open but not actually download anything nor show games)

**Comment by zamitto** [comment]
Hydra does not even show on system tray?
Example:
![image](https://github.com/hydralauncher/hydra/assets/167933696/3d2aa950-8095-4f75-aee2-ca4353b79fbb)

**Comment by Pamlau** [comment]
> Hydra does not even show on system tray? Example: ![image](https://private-user-images.githubusercontent.com/167933696/335708577-3d2aa950-8095-4f75-aee2-ca4353b79fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODQ3ODYsIm5iZiI6MTcxNzE4NDQ4NiwicGF0aCI6Ii8xNjc5MzM2OTYvMzM1NzA4NTc3LTNkMmFhOTUwLTgwOTUtNGY3NS1hZWUyLWNhNDM1M2I3OWZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxOTQxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDcxYTkzYmM2NmFhZjE3Njk5NDcyYzBmOTVlMWIzNzk5NDg2YzM0NjI5YjZmMTg5Y2JmNGU4ZmM1OTM1ZGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CjkiIMaXE1CTHl5KsKEbkksl_kOqkanhehJO9t1_7Bw)

doesn't show on system tray either, only in open background processes on task manager

**Comment by Pamlau** [comment]
Just installed version v2.0.1 Leviticus and now I'm back to the same situation as one of the first versions where the launcher would open but not display version number and not display any game/download options

**Comment by zamitto** [comment]
@Pamlau, some users tried the following and solved the problem:
1. Uninstall Hydra
2. go to "%appdata%/hydra" and delete everything except the hydra.db file if it exists (if you delete de .db file, you will lose your local library)
3. go to "%appdata%" and check if there are others folder with hydra in the name, like "hydralauncher" or "hydra-launcher" and delete them
4. go to "%localappdata%" and check if there are any hydra folder here and delete them too
5. Run the installer again

**Comment by Pamlau** [comment]
> @Pamlau, some users tried the following and solved the problem:
> 
> 1. Kill any Hydra process and uninstall Hydra
> 2. go to "%appdata%/hydra" and delete everything except the hydra.db file if it exists (if you delete de .db file, you will lose your local library)
> 3. go to "%appdata%" and check if there are others folder with hydra in the name, like "hydralauncher" or "hydra-launcher" and delete them
> 4. go to "%localappdata%" and check if there are any hydra folder here and delete them too
> 5. Run the installer again

IT WORKED :D

**Comment by FluffyOWP** [comment]
bro, most likely you have Dr. web or another antivirus installed, delete it and Hydra will start immediately.

**Comment by kira11x** [comment]
Hi, I have the same problem, my hydra won't open. it appears in the task manager, but does not open, it does not appear in the system tray. I already tried deleting the files and reinstalling but it didn't work for me.

**Comment by wallacerenan** [comment]
Same here

**Comment by wogerxx** [comment]
> Same here

i deleted and reinstalled but i installed to my all users in my laptop so it worked
