### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Gabuabuu** [hydralauncher/hydra#511]
### Describe the bug

Não consigo desinstalar jogo, há alguns jogos que não querem desinstalar do meu pc porque bugou o download e não aparece o arquivo unistall dos jogos! E nem mesmo nas configurações de desinstalação do proprio computador

### Steps to Reproduce

Não consigo desinstalar jogo, há alguns jogos que não querem desinstalar do meu pc porque bugou o download e não aparece o arquivo unistall dos jogos! E nem mesmo nas configurações de desinstalação do proprio computador

### Expected behavior

Não consigo desinstalar jogo, há alguns jogos que não querem desinstalar do meu pc porque bugou o download e não aparece o arquivo unistall dos jogos! E nem mesmo nas configurações de desinstalação do proprio computador

### Operating System

Windows 11

### Hydra Version

1.2.0

**Comment by JackEnx** [comment]
update to the latest version and better report your issue.
