### ISSUE TITLE
Error Downloading The New Version (1.2.4)

### ISSUE THREAD

**Issue by Xahts** [hydralauncher/hydra#512]
### Is your feature request related to a problem? Please describe.

Yea, it is cause i cant download the new version of the launcher

### Describe the solution you'd like

The solution for the issue, i really dont know what i can do to fix that

### Describe alternatives you've considered

Reinstall, Removing all the archives, etc

### Additional context

![Screenshot_1](https://github.com/hydralauncher/hydra/assets/170789718/97856b0a-76e9-4dc8-a8c1-24ad3797d9c1)

**Comment by zamitto** [comment]
We had some other users with this problem. Try this:

1. Delete current installation of hydra
2. Go to `C:\Users\YOUR_USER_NAME\AppData\Roaming`
3. Delete `hydralauncher` 
4. Go to `C:\Users\YOUR_USER_NAME\AppData\Roaming\Hydra` and delete everything except the `hydra.db` file (if you delete this you will lose you database and the games you had on library)
5. Go to `C:\Users\YOUR_USER_NAME\AppData\Local` and if it exists, delete any hydra folder that remained

**Comment by zamitto** [comment]
hey @Xahts, did you try it?
