### ISSUE TITLE
[REQUEST] add freetp.org repacks (another online fix)

### ISSUE THREAD

**Issue by 3misty** [hydralauncher/hydra#513]
### Is your feature request related to a problem? Please describe.

It would be great to add another site with online repacks. It is quite famous and has games that cannot be found on Online-fix.me

### Describe the solution you'd like

Add another source of repacks

**Comment by Gleb2372372** [comment]
[https://github.com/hydralauncher/hydra/issues/286](url)

**Comment by Gleb2372372** [comment]
https://github.com/hydralauncher/hydra/issues/286

**Comment by zamitto** [comment]
This can be done by the community since version 2.0

**Comment by Gleb2372372** [comment]
![image](https://github.com/hydralauncher/hydra/assets/76180186/201ffde2-c019-4ebd-82b6-7bb863d7d9fe)

**Comment by BadKiko** [comment]
Made in #286
