### ISSUE TITLE
[BUG] Kingdom Hearts Not Showing

### ISSUE THREAD

**Issue by The13thTimelord** [hydralauncher/hydra#514]
### Describe the bug

When searching for Kingdom Hearts no games or repacks appear even though FitGirl has them on their site

### Steps to Reproduce

Search for "Kingdom Hearts"

### Expected behavior

To display the Kingdom Hearts Games

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by zamitto** [comment]
I think that Kingdom Hearts games are not on Steam. If that's the case, Hydra won't be able to show them.
Currently Hydra indexes games based on steam. We are working on this so that won''t be a problem in the future
