### ISSUE TITLE
[BUG] Hydra is detected as trojan on Kaspersky

### ISSUE THREAD

**Issue by geraldofjunior** [hydralauncher/hydra#517]
### Describe the bug

When installing Hydra and trying to run on a PC protected with Kaspersky antivirus, it will detect it as "PDM:Trojan.Win32.Generic" just on trying to run it.

### Steps to Reproduce

1. Pull Windows installer from distribution page on this repository
2. Run setup on Windows without disabling protection from Kaspersky
3. Kaspersky will automatically detect it as a trojan.

### Expected behavior

It's expected that this launcher won't raise suspections from antivirus software.

### Screenshots

The detection window:
![image](https://github.com/hydralauncher/hydra/assets/34254843/c16fcfac-fea5-4465-9290-070c07f9003a)

### Operating System

Windows 11 (version 23H2, compilation 22635.3646)

### Hydra Version

1.2.4

**Comment by scrlkx** [comment]
So? What do you expect to be done?

**Comment by zamitto** [comment]
We can't ensure Hydra won't be seen as false positive by Anti-viruses. It is not a signed software.
If anyone is interested, in the Support chat of your Telegram channel there is a pinned message from a user about how to make Kaspersky not complain anymore (add to quarentine, etc)

**Comment by TheNikita945** [comment]
Greetings, I sent Hydra Launcher to Kaspersky Virus Labs and yesterday I got a reply from them. The reply said that it was a false positive of the behavioral analysis module, which will be fixed within 24 hours. Please check it now.
![Снимок экрана 2024-05-29 194009](https://github.com/hydralauncher/hydra/assets/171174527/28eae265-578d-4433-b3cc-63be393505f9)
