### ISSUE TITLE
[BUG] Game does not open. is directed to the original Stean's page

### ISSUE THREAD

**Issue by IrandevWolf** [hydralauncher/hydra#531]
### Describe the bug

when I go to open the game the last of us part l,,  I am directed to the original Stean page with the following message "An error occurred while trying to start: no license"

### Steps to Reproduce

1 click on the game's Laucher that is on the desktop, 2 I am directed to the original Stean's page

### Expected behavior

that the game would work.

### Screenshots

![Captura de tela 2024-05-28 062533](https://github.com/hydralauncher/hydra/assets/167035593/55a4054a-41ed-455b-8d2a-bd1e2359da46)
![Captura de tela 2024-05-28 062704](https://github.com/hydralauncher/hydra/assets/167035593/88bced08-8b9c-4c41-91c4-2f46e10d65b4)

### Operating System

Windows 11

### Hydra Version

Hydra-1.1.0.Setup.exe

### Additional Information

I downloaded Cyberpunk and it worked without any problems

**Comment by zamitto** [comment]
Ok, does not seems a Hydra issue. We are not responsible for the repacks. We just make it easier for users to download them.

I'd advise you to join the Telegram group, there are users there who are used to help with common issues regarding the installation process of games.

**Comment by Myllin** [comment]
> I'd advise you to join the Telegram group, there are users there who are used to help with common issues regarding the installation process of games.

I apologize and do not tell where to find the conversation in telegram from all the links in the repository found only the main group with updates

**Comment by zamitto** [comment]
This is a pretty old issue
We do not have a support Telegram channel anymore
Our Telegram is only for announcements
The best support channel is our chat or email support@hydralauncher.gg

**Comment by Myllin** [comment]
Thanks for the reply, I'll keep that in mind!
