### ISSUE TITLE
File .exe failure

### ISSUE THREAD

**Issue by jmferreira03** [hydralauncher/hydra#533]
I downloaded a game using Dodi repack and at the end of the installation using the Wizard, a shortcut was created on the desktop that cannot locate the file .exe . When running the game through the launcher, it opens the wizard installer again. What do I do?

![image](https://github.com/hydralauncher/hydra/assets/165291862/0d8c74f4-b96b-4973-9766-9af8780aba7b)

**Comment by zamitto** [comment]
We cannot provide support on the games you install. I suggest you join the Discord server the community created. The link is in out Telegram channel
