### ISSUE TITLE
[BUG]  Far Cry 5 Gold Edition DODI Repack Erro: Granite -2000000

### ISSUE THREAD

**Issue by Richwrs** [hydralauncher/hydra#537]
### Describe the bug

Pelo que dá a entender, o game da esse erro pois não há local de Save, qual precisaria estar logado na Uplay pra poder salvar e dar continuidade no jogo.  Al

### Steps to Reproduce

1) Instalar o arquivo baixado pelo Hydra;
3) Jogar a campanha até o carro cair da ponte que explode após um ataque de um avião (no estágio inicial).

### Expected behavior

O jogo fica numa tela escura (transparente) indicando pra você voltar ao menu. Se negar, essa tela parecerá constantemente até você aceitar, após aceitar, ele volta para o menu iniciar, se você clicar em "Continuar", ele inicia o load do save, porém ele da o "Erro: Granite -2000000".

### Operating System

Windows 12

### Hydra Version

hydra-1.2.2

### Additional Information

Já tentei buscar diversas soluções, porém nenhuma que resolveu.

**Comment by Richwrs** [comment]
@JackEnx  publiquei no local errado?
Há algum meio correto deu resolver esse problema? 
Agradeço qualquer esclarecimento.

**Comment by JackEnx** [comment]
Sorry for the delay in responding, we don't deal with game-related issues here.
