### ISSUE TITLE
[REQUEST] Add number of downloads

### ISSUE THREAD

**Issue by amintikk** [hydralauncher/hydra#539]
### Is your feature request related to a problem? Please describe.

I think adding a section in each game that indicates how many downloads the game has had can help when choosing an installer, for example, FitGirl, DODI, etc.

### Describe the solution you'd like

![Captura de pantalla 2024-05-29 113852](https://github.com/hydralauncher/hydra/assets/76745488/c2cd84df-d4f4-4091-833d-3b8ec82deb74)

**Comment by thegrannychaseroperation** [comment]
We won't compute downloads on arbitrary download options. Thanks.
