### ISSUE TITLE
Game is removed from library when you click "remove installer" in the download tab

### ISSUE THREAD

**Issue by Magrid0** [hydralauncher/hydra#54]
As the title says,  when you click "remove installer" in the download tab, the game is removed from the library

**Comment by Vhirsion** [comment]
Yep. But the game is still downloaded, just go back to the game through the catalogue, click add to library and just click the .exe of where you downloaded it.

**Comment by Magrid0** [comment]
I noticed that, I was just reporting it because I personally find it annoying so maybe other people find it annoying too, also I don’t see why the game should be removed from the library if you remove the installer
