### ISSUE TITLE
[BUG] Doesn´t download metadata on the sunset overdrive dodi repack

### ISSUE THREAD

**Issue by Seawater0876** [hydralauncher/hydra#541]
### Describe the bug

The launcher doesn´t download the sunset overdrive game metadata

### Steps to Reproduce

Go to the download section and chose the dodi repack of sunset overdrive. It puts downloading metadata and nothing downloads

### Expected behavior

Download the game metadata

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/112400373/b70804a0-b718-4df1-b767-182988df78ad)
Its been like this 1h

### Operating System

Windows 11

### Hydra Version

1.24 exodus

**Comment by daniil2327** [comment]
same problem

**Comment by raphaelkieling** [comment]
I was facing the same issue, i cancelled, closed hydra and opened it again. Just works after it for me, unfortunatelly it's a temporary solution, after some hours it will happen again.

**Comment by thegrannychaseroperation** [comment]
We do not offer any support with any issue related to download options.
