### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 14leo19** [hydralauncher/hydra#542]
### Describe the bug

REPACK-Ka0s não transfere (fica sempre no 0%)

### Steps to Reproduce

--

### Expected behavior

Esperava que transferisse e não dá download

### Screenshots

--

### Operating System

windows 10

### Hydra Version

Hydra-1.1.0.Setup

### Additional Information

--

**Comment by giwih** [comment]
windows 9?

**Comment by zamitto** [comment]
1. Please use a newer version of Hydra, latest release is 1.2.4
2. What repack? What game? Please provide more information
