### ISSUE TITLE
[PROPOSAL] Better game state management

### ISSUE THREAD

**Issue by guibzo** [hydralauncher/hydra#546]
### Is your feature request related to a problem? Please describe.

Game state management related.

### Describe the solution you'd like

I think a better game state management is needed to avoid confusion and unexpected behavior.

### Additional context

The game state management currently is pretty confuse and unclear.
I think a more clear and concise approach is needed, so there is my proposal and the comparison.

## Current
![image](https://github.com/hydralauncher/hydra/assets/119091492/69286632-3e53-4935-995e-e6a62a3adc0e)

## Proposal (new)
![image](https://github.com/hydralauncher/hydra/assets/119091492/589ab339-6b05-4477-981e-0b9d5f65d5ba)

**Comment by JackEnx** [comment]
we improved this operation on #633, make free to open another issue if you think something could be improved
