### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JordanHay23** [hydralauncher/hydra#548]
### Describe the bug

When I install games or when I add another game I get a lot of almost identical files. Here is one of them fastlist-00133615498079773738

### Steps to Reproduce

1 Choose a game
2 After downloading or adding, you may see these prompts

### Expected behavior

I expect that they will help me to get rid of these files

### Operating System

Windows 10

### Hydra Version

1.2.4

**Comment by scrlkx** [comment]
Can you give us more details? Which game has this behavior? Where this files are being created? Which OS are you using?

**Comment by JordanHay23** [comment]
I hope it's appropriate.
When I added Call of Duty Modern Warfare 2
I immediately start to see files like this. I use Windows 7 ultimate

**Comment by JordanHay23** [comment]
They appear on the desktop

пт, 31 трав. 2024 р., 18:18 користувач Daniel Freitas <
***@***.***> пише:

**Comment by JordanHay23** [comment]
Here is a photo of this file

пт, 31 трав. 2024 р., 18:19 користувач Irsa Hura ***@***.***>
пише:

**Comment by scrlkx** [comment]
You have not attached any screenshot. But this is probably related to the game itself and not Hydra. Make sure that you installing the game properly.

**Comment by JordanHay23** [comment]
пт, 31 трав. 2024 р., 20:39 користувач Daniel Freitas <
***@***.***> пише:

**Comment by scrlkx** [comment]
It's not working, there is no valid link or screenshot. You may have to attach it from a computer.

**Comment by JordanHay23** [comment]
https://ru.paste.pics/225280dd3995937f61063d6d68aa104c
I hope this link works

пт, 31 трав. 2024 р. о 20:43 Daniel Freitas ***@***.***> пише:

**Comment by scrlkx** [comment]
As I said, it's probably related to the game itself and not Hydra. Try searching online about the issue, it may help.

**Comment by JackEnx** [comment]
this issue is confused, be more clean about the problem.
