### ISSUE TITLE
para mim não aparece para istalar o jogo[BUG] 

### ISSUE THREAD

**Issue by bracinhol2** [hydralauncher/hydra#550]
### Describe the bug

os jogos tem pra instalar mas quando clica no jogo aparece que não tem downloud

### Steps to Reproduce

1 celecione o jogo que tem downloud 
2 não vai dar pra instalar

![Captura de Tela (41)](https://github.com/hydralauncher/hydra/assets/171296175/6efe86f7-9448-4043-a300-c5d8249b4771)

### Expected behavior

que desse pra instalar

### Screenshots

![Captura de Tela (41)](https://github.com/hydralauncher/hydra/assets/171296175/42f18e65-c1a1-4aaf-8395-f018f2d24d22)
![Captura de Tela (42)](https://github.com/hydralauncher/hydra/assets/171296175/f59dc14a-755e-4516-b26c-e6b5f5e105a4)

### Operating System

windows 11 

### Hydra Version

1.2.4

### Additional Information

tem solução

**Comment by davimcruz** [comment]
Olá, você leu a descrição do problema? 
Isso acontece quando não há nenhum link de download disponível para aquele jogo. O game está em catálogo mas não possui os repacks catalogados dentro do mesmo para download do usuário. 

Os issues do github não são para esse tipo de problema.

**Comment by bracinhol2** [comment]
> Olá, você leu a descrição do problema? Isso acontece quando não há nenhum link de download disponível para aquele jogo. O jogo está em catálogo mas não possui os repacks catalogados dentro do mesmo para download do usuário.
> 
> Os problemas do github não são para esse tipo de problema.

isso é com todos os jogo irm

**Comment by Richwrs** [comment]
Estou com o mesmo problema, creio que seja atualização de versão.

**Comment by Guigao4136** [comment]
Estou com o mesmo problema, alguém sabe dizer quando vão laçar versões para resolver ?

**Comment by zamitto** [comment]
Same problem as #526, we are gonna fix it for the next release

**Comment by Richwrs** [comment]
Eu consegui identificar o que ocorreu no meu caso.
Quando o jogo é adicionado na Biblioteca, ele não mostra listas de download. Pra baixar basta remover da lista e aparecerá as opções.

**Comment by zamitto** [comment]
Fixed in 2.0

**Comment by Melqui42** [comment]
Estou com o mesmo problema.

**Comment by zamitto** [comment]
@Melqui42 please describe your problem with more details

**Comment by Char434** [comment]
I have the same problem. I'm trying to use Hydra 2.0.1, but when I add the game to the library, there's only the option to play I can't download the game
![image](https://github.com/hydralauncher/hydra/assets/107639814/474fec62-9fc5-40e7-87c3-5f043b98e963)
![image](https://github.com/hydralauncher/hydra/assets/107639814/c07168d0-18f1-4179-866a-649793ea421a)

**Comment by FaKaMaKaKaSDK** [comment]
https://hydralinks.cloud
click on "Install on Hydra"

вт, 25 июн. 2024 г. в 02:59, Miguel ***@***.***>:

**Comment by Char434** [comment]
@FaKaMaKaKaSDK thank you
