### ISSUE TITLE
[BUG] Wrong game repack

### ISSUE THREAD

**Issue by chocotoneg** [hydralauncher/hydra#553]
### Describe the bug

the game i was going to download has the wrong repack in it

### Steps to Reproduce

1. go to the Oneshot page
2. click on the download button

### Expected behavior

it was supposed to have the right game re-pack in it, but it has a re-pack from a different game.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/98628957/8dbb1ba7-d985-4ac4-bf29-917d5f38ae95)
![image](https://github.com/hydralauncher/hydra/assets/98628957/122771f0-b935-4661-9b60-12a0ced242f4)

### Operating System

Windows 10

### Hydra Version

1.2.4

**Comment by JackEnx** [comment]
side effect to how hydra index the games, we will improve in the future.
