### ISSUE TITLE
[BUG] saturated flickering GUI

### ISSUE THREAD

**Issue by Bi0s-Lain** [hydralauncher/hydra#558]
### Describe the bug

When I'm on the Hydra GUI, I experience major graphical bugs: the display becomes unreadable and saturated with a predominance of yellow.

### Steps to Reproduce

The bug appears when I launch the application without doing any more manipulations.

### Expected behavior

It shouldn't have that yellow 'veil' on the display

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/154735009/df6e421a-a844-450d-a28a-05c918742304)

https://github.com/hydralauncher/hydra/assets/154735009/e8538aab-04f4-4cfa-8838-2a027c9ee59e

### Operating System

Windows 11

### Hydra Version

1.2.4

### Additional Information

Note that my graphic (and all) driver are up to date and wallpaper engine is not the cause of that issue.

**Comment by zamitto** [comment]
What is your CPU and GPU?

**Comment by Bi0s-Lain** [comment]
> What is your CPU and GPU?

A Ryzen 5 3600 and a RTX 2060 super (from MSI)

**Comment by TiagoCastilhos** [comment]
@Bi0s-Lain Is your graphics card driver updated?
Does it happen with applications that use 'electron'? (like spotify, discord, ...)
Could you disable wallpaper engine and set a static wallpaper just for testing?

**Comment by Bi0s-Lain** [comment]
@TiagoCastilhos as mentioned in my original message, my graphics drivers are up to date. Wallpaper engine is not a problem, in fact, I've already tried with WE stopped and the problem persists. Discord isn't running and neither is spotify :  

![image](https://github.com/hydralauncher/hydra/assets/154735009/bd61d422-405e-437a-9db8-6f22c44ead31)

Nvidia driver Version: 555.99

**Comment by zamitto** [comment]
Someone in the community found a solution. Could you close Hydra, disable Nvidia overlay and open hydra again?

**Comment by Bi0s-Lain** [comment]
> Someone in the community found a solution. Could you close Hydra, disable Nvidia overlay and open hydra again?

Hello, the new update seems to fix the issue. However im pretty sure that it was be caused by the Nvidia overlay (it appears after updating nvidia app ig)
