### ISSUE TITLE
[BUG] Não consigo prosseguir com o processa da instalação do jogo no explorador de arquivos ( instalção )

### ISSUE THREAD

**Issue by OliveiraSantana** [hydralauncher/hydra#563]
### Describe the bug

Não consigo prosseguir com o processa da instalação do jogo, mesmo seguindo os passos indicados, acaba acontecendo um erro inesperado.

### Steps to Reproduce

Depôs do download do jogo pelo hydra, ele indica que você prossigua para a instalação manual do jogo em sua pasta, porém, não foi possível continuar a instalação já que os arquivos não iniciam este processo. Pode-se perceber isso no jogo, minecraft dungeons, após o download, clique em ''instalar'', será redirecionado para a pasta onde se encontra os arquivos de instalação, procure pelo arquivo ''exe'' o executável do jogo, e se deparar com esta mensagem, ''couldn´t start''.

### Expected behavior

No entanto, seguindo corretamente esses passos a passos direcionados, não deveria ao menos aparecer qualquer mensagem de erro / não foi possível iniciar, mas, caso não acontecesse nenhum tipo de erro, o jogo deveria abrir somente de clicá-lo no ícone do ''aplicativo''.

### Screenshots

![Captura de tela 2024-06-03 114355](https://github.com/hydralauncher/hydra/assets/143148365/9b77d231-410e-45d0-ba17-da5795ca7bf4)
![Captura de tela 2024-06-03 114408](https://github.com/hydralauncher/hydra/assets/143148365/6c67ff5a-0613-4c1c-b735-c5b96c862062)
![Captura de tela 2024-06-03 115557](https://github.com/hydralauncher/hydra/assets/143148365/96a5d3b2-f232-47f3-a61a-3655a5963223)
![Captura de tela 2024-06-03 115608](https://github.com/hydralauncher/hydra/assets/143148365/8f61b42b-8f96-4858-a338-f46c1285296f)

### Operating System

windows 11

### Hydra Version

1.2.4 "Exodus''

### Additional Information

Espero que tenha retorno assim que possível para poder conseguir instalar e jogar os jogos corretamente, estou à espera.

**Comment by zamitto** [comment]
Does not seem an issue from Hydra.
Double check if your anti virus did not delete any file from the game
If not, try another download

Hydra is not responsible in any way about the downloaded files, whether they are working or not

**Comment by zamitto** [comment]
You can also join the community discord server (link in our telegram channel). There are people there who can help you

**Comment by OliveiraSantana** [comment]
Ok @zamitto thanks you, i go try again, and also join in community telegram
