### ISSUE TITLE
[BUG] Unable to download using Real Debrid

### ISSUE THREAD

**Issue by kumanaya** [hydralauncher/hydra#564]
### Describe the bug

I am unable to download using Real Debrid. It gets stuck at "Starting download".

### Steps to Reproduce

1 - Enable Real Debrid
2 - Insert the token
3 - Download the game

### Expected behavior

Download the game using Real Debrid

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/38965476/ef3e180d-65f1-43f4-a78f-5ca831377012)

### Operating System

Windows 10

### Hydra Version

1.2.4 Exodus

**Comment by zamitto** [comment]
Is this still an issue on 2.0.2?
