### ISSUE TITLE
[REQUEST] Novo tracker confiavel + Seed + praticidade

### ISSUE THREAD

**Issue by rybandz** [hydralauncher/hydra#569]
### Is your feature request related to a problem? Please describe.

Dando ideia sobre melhoria, fonte confiavel, aumentar o seed em torrents, praticidade pro hydra

### Describe the solution you'd like

Levando em conta que os repackers utilizam cs.rin.ru e rutracker.org como fontes pra baixar e publicar, notei que as pessoas que publicam no forum são marcadas como confiáveis, tipo aqui na imagem no rutracker
![imagem_2024-06-04_170011630](https://github.com/hydralauncher/hydra/assets/165525397/9e9117a9-f86c-44b0-9cca-b10e385deffe)
(acredito que de pra puxar só as fontes confiaveis entao)

Além disso, observei que é fácil encontrar conteúdo em formato portable. Normalmente td mundo remove a instalação de repacks e param de seedar (euu). Já baixando em formato portable, ia ficar seedando o torrent, alem de economizar espaço, tempo, ia deixar mais pratico e funcional o programa

A única ressalva é ser necessário fazer login pra buscar no forum. Como não manjo sobre programação, fico na dúvida se seria possível integrar um sistema de login automático internamente ao Hydra (um usuario pra todos que usam o programa). Ou ter um registro e login no hydra, enviando o cadastro e login pro site deles pra cada usuario ter acesso a busca

-No forum quase sempre tudo estao com a ultima atualizaçao ou uma muito recente

-Alem de ser super facil de puxar o magnet de cada pagina

-Em conjunto poderia adicionar outra fonte de portable, dentro do proprio site do dodi tem um banner que redireciona pra um site só de portable (game-repack.site)

**Comment by JackEnx** [comment]
#633
