### ISSUE TITLE
Portable version of Hydra

### ISSUE THREAD

**Issue by kalc1t** [hydralauncher/hydra#572]
### Is your feature request related to a problem? Please describe.

I heard that portable versions more stable and can work without stopping like it won't break. + i can drag it to anywhere without any problems

### Describe the solution you'd like

Is it possible to make a portable version of Hydra? If yes, pls make it 🙏

**Comment by zamitto** [comment]
I'm testing a solution, just be aware that the database won't be carried with the portable version
