### ISSUE TITLE
[BUG] Slow downloading speed 

### ISSUE THREAD

**Issue by Dis-World** [hydralauncher/hydra#577]
### Describe the bug

So after i updated hydra from 1.1.0 to 1.2.4 all games i try downloading are going extremely slow taking literally months to download, i already tried changing the versions but now the problem persists, can someone help me with this? 

its not my wifi and i've seen another post talking about torrent "seeds" i belive its not the problem either

### Steps to Reproduce

1 - Download Hydra
2 - try downloading anything

### Expected behavior

Download starts at 500kb max and start falling to bites

### Screenshots

![Captura de tela 2024-06-06 101525](https://github.com/hydralauncher/hydra/assets/171943890/100b1a0d-ec0e-4c5a-a7fa-748f5cecb2d9)
![Captura de tela 2024-06-06 100218](https://github.com/hydralauncher/hydra/assets/171943890/7bd4a66f-11aa-4320-aa39-da7a5ee50c2e)

### Operating System

Windows 10

### Hydra Version

1.2.4

**Comment by piradata** [comment]
i am on 1.2.4 and its fast as always

**Comment by OtavioSC** [comment]
same problem here

**Comment by JackEnx** [comment]
we will be changing the download system soon

**Comment by JackEnx** [comment]
fixed on #722, if the problem persist, please report it
