### ISSUE TITLE
[BUG] Spamming notification

### ISSUE THREAD

**Issue by hiroshimorowaka** [hydralauncher/hydra#579]
### Describe the bug

I recently installed Hydra Launcher and activated the “Notify when download finishes” option and when it finished downloading, it started checking the game files and kept spamming notifications until I deactivated the option. 
I use Windows 10

### Steps to Reproduce

1. install a game
2. When the download reaches 100%, click on pause and it will start checking the game files
3. After step 2, it will start spamming notifications.

### Expected behavior

I don't know what to write here, but I think the behavior I hope for is that this does NOT happen.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/82670390/88f6c4b1-ac68-4f32-9ab5-1bebca2ebc3e)

### Operating System

Windows 10 Pro (V: 22H2)

### Hydra Version

1.2.4

**Comment by apofeoziy** [comment]
Support me, I have the same situation now.
![image](https://github.com/hydralauncher/hydra/assets/154058846/fcba3e43-122a-41be-a34e-21d2f6ed60b8)

**Comment by mggd44** [comment]
SAME! I downloaded DODI Gta 5 repack and it started notificate me. but it was not installed yet.. LOL!

**Comment by mggd44** [comment]
Idk if i can trust hydra, but it says 13 hours to 62 gb game

**Comment by mggd44** [comment]
![image](https://github.com/hydralauncher/hydra/assets/172170288/e3acd3bd-1c59-4df7-8fce-c44c13eb0026)
now 17

**Comment by thegrannychaseroperation** [comment]
Solved in 2.0.
