### ISSUE TITLE
[BUG] High Memory Use/Leak

### ISSUE THREAD

**Issue by RedstoneAlmeida** [hydralauncher/hydra#580]
### Describe the bug

When I'm downloading a game, the memory usage is absurd, although it doesn't appear, doing the math with Hydra closed it shows a total of 61%, I have 32GB on my computer, but when I start downloading a game with Hydra open it starts to consume almost all the available memory. I believe it's a leak, or parts of the game are placed in the memory, I would like to know if it's just some kind of bug or if it's something more related to my hardware (I think it's unlikely to be)

### Steps to Reproduce

Start downloading, any game whatsoever

### Expected behavior

Usage around 150% or greater than the current program total (300mb to 1500mb)

### Screenshots

![Screenshot_178](https://github.com/hydralauncher/hydra/assets/15146680/990c7bb6-5cc3-4270-9b5b-6218fd130855)

### Operating System

Windows 10 Home Single Language

### Hydra Version

v1.2.4 Exodus

### Additional Information

Specifications:

DDR4 Memory - 4x8GB (32GB)
Ryzen 7 5700X - Standard configuration, no tweaks
RTX 4070 MSI
1x SSD 960GB SATA
2x SSD 512GB M.2
1x HD 512GB
1x SSD 120GB SATA
1x SSD 480GB SATA

**Comment by RedstoneAlmeida** [comment]
Sorry for not posting this earlier, but the image below is after downloading the game.
![Screenshot_179](https://github.com/hydralauncher/hydra/assets/15146680/c0ace988-017a-444a-8ae2-8865fcecb9d8)

**Comment by thegrannychaseroperation** [comment]
Most likely solved in 2.0. If the issue still persists, please open a new one.
