### ISSUE TITLE
[BUG] stuck in "downloading metadata"

### ISSUE THREAD

**Issue by thesievert** [hydralauncher/hydra#581]
### Describe the bug

when i try to download anything on hydra launcher it says "downloading metadata" and stays at 0 percent, even when the file is small

i tested many types of downloads, on many games. i've downloaded it on my chromebook (chrome OS) and i tried using many different versions of the download

i only was able to open the .deb files since it was the only one that was supported by my linux sistem.

my chrome OS is updated and i am using the version: 
125.0.6422.140 (official version) 64 bits

please tell me how to fix this

### Steps to Reproduce

i don't really know if you can reproduce this, just use the same system i am using and try it

### Expected behavior

"downloading metadata"

### Operating System

linux chrome OS

### Hydra Version

tested on 1.20.4     1.20.1      1.20    and i don't remember if i tested on 1.0.1

**Comment by goldsrc4** [comment]
had the same problem and couldnt even open the .deb files for sm reason

**Comment by Crystalbreaker76** [comment]
Just restart the PC it worked for me.

**Comment by JackEnx** [comment]
fixed on #722, if the problem persist, please report it
