### ISSUE TITLE
Open without Admin rigths on Windows 11

### ISSUE THREAD

**Issue by Vintic** [hydralauncher/hydra#588]
### Is your feature request related to a problem? Please describe.

Please,
create a possibility to open without admin privilege.
Installer allow me to install the app, but after I attempt to launch it, Admin password is requested.
What for it is done?

I am trying to use it on work laptop, and I don't have admin rights there.
I can search the web and download portable apps and games, that can be started without admin rights.
(I did it for many apps, mostly using scoop: discord, Firefox, IDEA, Xonotic, ...)

### Describe the solution you'd like

Possibility to use app without admin rights.

**Comment by expload233** [comment]
Maybe you can try to edit the [electron-builder.yml](https://github.com/hydralauncher/hydra/blob/main/electron-builder.yml) file, then modify **requestExecutionLevel** to **asInvoker** then build it. To bypass the Windows permission requirement

**Comment by zamitto** [comment]
The admin permissions are needed to keep track of the games processes, and to open and close them. These features would not work correctly without admin privileges on Windows

**Comment by 1vnt** [comment]
I do not know about all the windows internals, however other launchers like for example steam can do it just fine.

**Comment by zamitto** [comment]
Coincidentally, we use discussing this internal earlier today. We will rework how we handle it and drop the need of UAC on Windows

**Comment by zamitto** [comment]
Admin rights is needed in the latest version
