### ISSUE TITLE
[REQUEST] Add custom sources for games.

### ISSUE THREAD

**Issue by heartdeadz** [hydralauncher/hydra#589]
### Is your feature request related to a problem? Please describe.

Not at all.

### Describe the solution you'd like

I would love a way to add custom sources for games.
Whatever source you guys use for this software, it barely scrape anything relative or new.
Like, Hellblade II <--  there are tons of safe, secure releases for that game.   yet it does not show up in Hydra :D 

would love a way to add sources myself, so i can get relevant and new games added too :D

**Comment by zamitto** [comment]
First, do you mean Hellblade does not show up at all? Or that is shows with no download options?

Second, the option to add download sources is almost ready and will be on next release

**Comment by heartdeadz** [comment]
Oh! i probably should've said.

So, i just took hellblade II as a random game, but i do find the game itself on hydra yea.  there's just no available source to download from.
but there are tons of sources available for it. ( trusted sources ) 
hence why i was wondering about the download sources thingy :D  

But you answered that for me in your post there! :D

**Comment by zamitto** [comment]
Done in 2.0
