### ISSUE TITLE
Some games aren’t present

### ISSUE THREAD

**Issue by Magrid0** [hydralauncher/hydra#59]
I found that some games aren’t on hydra, for example Raft and Pc Building Simulator 2.
Maybe, this could be fixed by fetching data from IGDB like playnite does instead of steamDB or whatever is being used at the moment.

**Comment by Bartek16194** [comment]
Same for old Need for Speed games, AC Mirage, Spider Man 2

**Comment by thegrannychaseroperation** [comment]
This has been fixed in latest versions.
