### ISSUE TITLE
[REQUEST] A separate menu with all games in my library

### ISSUE THREAD

**Issue by bpavuk** [hydralauncher/hydra#594]
### Is your feature request related to a problem? Please describe.

Sometimes, scrolling through all the games in the sidebar can be inconvenient. A separate menu can be a good solution.

### Describe the solution you'd like

A separate "Library" tab that has all the games from the library collected and displayed in a way that search results and trending games are. Akin to Epic Games Store "Library" tab.

### Additional context

You can use Epic Games Store as an inspiration. The launcher's UX is quite reminiscent of EGS.

**Comment by zamitto** [comment]
We have it in 2.0, after you create an account and sign in, you will be able to see your profile with your games
