### ISSUE TITLE
[REQUEST] Add a torrent/magnet download button

### ISSUE THREAD

**Issue by Ertersilva** [hydralauncher/hydra#595]
### Is your feature request related to a problem? Please describe.

I went to download a game that wasn't a repack, I ended up downloading dozens of optional languages ​​and videos that I will never use, as we still don't have a way to choose this

### Describe the solution you'd like

They could add a button to download the .torrent directly in the Downloads folder, so I can do this job manually in my magnets app.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by TeddOravec** [comment]
Seconded. This would also allow those users who don't want to put the gaming machine on a VPN to still be able to cover their asses by using a different client to obtain the data.

**Comment by luis123456xp** [comment]
It would be quite useful if you could obtain the torrent file or the magnet of the game that is being downloaded, in case you want to use another service for the download, for example alldebrid.com

**Comment by JackEnx** [comment]
outdated by #633
