### ISSUE TITLE
PROXY

### ISSUE THREAD

**Issue by nsysp4** [hydralauncher/hydra#598]
### Is your feature request related to a problem? Please describe.

Can you incorporate the option to place a proxy?

### Describe the solution you'd like

Can you incorporate the option to place a proxy?

**Comment by JackEnx** [comment]
be more specific about what you want, don't ask questions, make proposals and specifically how you want it.

**Comment by nsysp4** [comment]
![proxy win](https://github.com/hydralauncher/hydra/assets/41489456/075b79d2-65e6-4e9b-8d9c-9f33b1df58db)

**Comment by JackEnx** [comment]
duplicated and more datalhed on #625
