### ISSUE TITLE
Automated Game Installation and Execution Enhancement

### ISSUE THREAD

**Issue by caduHD4** [hydralauncher/hydra#60]
**Automating Game Installation Process and Executable Selection**

When the game download completes, automate the installation process. For Online-fix games, where the rar files have the default password 'online-fix.me', this would enable automatic extraction and deletion of the rar file. Additionally, upon clicking 'play', automatically redirect to the folder where the game was downloaded, making it easier to select the executable. If possible, implement a feature that allows the program to find the correct executable without the need for manual selection by the user, perhaps by searching for it within the folder based on characters similar to the game's name. 

*Note:* I attempted to add 'unrar-js' to the project, but encountered issues with the game ID, so I decided to postpone this task for now.

**Comment by hydralauncher** [comment]
Please open different issues for distinct topics. Closing this and hoping for one issue per topic.
