### ISSUE TITLE
problema em iniciar o jogo

### ISSUE THREAD

**Issue by unitypng** [hydralauncher/hydra#602]
### Describe the bug

quando o jogo baixa eu tento abrir ele mais fica aparecendo para baixar o hydra sendo que ele já tá baixado e não abre o jogo

### Steps to Reproduce

eu não sei se e só no meu computador

### Expected behavior

eu só esperava que o jogo abrisse 

### Screenshots

![Captura de Tela (26)](https://github.com/hydralauncher/hydra/assets/173103232/101f17dc-f7b6-46e2-add2-05360135ba48)
![Captura de Tela (27)](https://github.com/hydralauncher/hydra/assets/173103232/61a2687a-0107-4ab3-9042-6b58c66c9b3c)
![Captura de Tela (28)](https://github.com/hydralauncher/hydra/assets/173103232/8ceb0b6d-669c-4b64-89c0-408e88b54b4b)
![Captura de Tela (29)](https://github.com/hydralauncher/hydra/assets/173103232/058539ab-569d-46f1-a60c-4b4fbdecb4d1)
![Captura de Tela (30)](https://github.com/hydralauncher/hydra/assets/173103232/416d9c51-52f0-42b1-8431-b0688ac6cb2a)

### Operating System

Windows 10/Sistema operacional de 64 bits, processador baseado em x64

### Hydra Version

1.2.4 a mais recente

### Additional Information

e ainda quando eu click para instalar ele fala para eu fechar o hydra mais quando eu fecho e ate desistalo ele ainda pede para fechar o hydra

**Comment by JackEnx** [comment]
plase, read the README
