### ISSUE TITLE
[BUG] EA FC 24 sem opcao de dowloand

### ISSUE THREAD

**Issue by Th4l3sPott3R** [hydralauncher/hydra#603]
### Describe the bug

na aba do jogo dentro do launcher não aparece nenhuma opcão de dowloand disponive

### Steps to Reproduce

1. pesquise pelo nome do jogo
2. clique sobre o icone 
3. abra a página do jogo

### Expected behavior

em tese, era para aparecer a opção de dowloand disponivel para aquele jogo

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/164954390/4684b938-6dcf-4931-bbb9-dc3bbfc6dba0)

### Operating System

windows 10

### Hydra Version

v1.2.4

**Comment by JackEnx** [comment]
plase, read the README

**Comment by dfsmarsi** [comment]
Adicionei todas as fontes de downloads disponíveis em hydralinks.cloud, mas nenhuma encontrou o jogo. Alguém sabe de alguma outra fonte que tenha?
