### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by krathack** [hydralauncher/hydra#604]
### Describe the bug

very low download speed

### Steps to Reproduce

1. logged into the launcher
2. downloading the game

### Expected behavior

fast download

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/50818254/32ede7e7-069b-41db-9d06-a69b1e4661c3)

### Operating System

windows 11

### Hydra Version

1.2.4

**Comment by JackEnx** [comment]
slow download is expected in some games, this is a torrent sistem after all
