### ISSUE TITLE
[REQUEST] Add real-debrid and other debrid support

### ISSUE THREAD

**Issue by Ragnarokkkk** [hydralauncher/hydra#607]
### Is your feature request related to a problem? Please describe.

Real debrid would make downloads faster and more efficient for those who have it.

### Describe the solution you'd like

Title is pretty self explanatory and it probably shouldn't be too hard to implement

**Comment by JackEnx** [comment]
![image](https://github.com/hydralauncher/hydra/assets/167036558/b1d58039-a84b-4742-b6d6-b8f677107065)
