### ISSUE TITLE
[BUG] Hydra confuses Hades and Hades II

### ISSUE THREAD

**Issue by kotenok2000** [hydralauncher/hydra#609]
### Describe the bug

When i open hades it lists both Hades and Hades 2 in download list.

### Steps to Reproduce

1. Search for Hades
2. Open download variants

### Expected behavior

Only hades is present in list.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/8822292/f4777d78-4ef2-4f5e-a10e-e923fc843555)

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by kotenok2000** [comment]
And why is Hades II v.0.91027 36.6 gb, but 90912 is 4.1 gb?

**Comment by bpavuk** [comment]
Dishonored/Dishonored 2. same.

**Comment by kotenok2000** [comment]
Also largest one is Warhammer 40000 Rogue Trader (2023)

**Comment by JackEnx** [comment]
the problem with hades 1 in 2 is a expected behavior, side effect to how hydra index the games, about the wrong game, this was fixed on 2.0.0

**Comment by kotenok2000** [comment]
Hydra 2.0.1 still lists it in download source list. 
36.6 GB one.
![image](https://github.com/hydralauncher/hydra/assets/8822292/bf7d209f-cef1-4133-b6bb-25237d6152d6)
