### ISSUE TITLE
[REQUEST] eta for 1.3

### ISSUE THREAD

**Issue by mithunnivas** [hydralauncher/hydra#612]
### Is your feature request related to a problem? Please describe.

What is the planned eta for the 1.3 version? 

### Describe the solution you'd like

Do we have a timeline?

**Comment by zamitto** [comment]
22.06.24, next saturday
It will be version 2.0

**Comment by mithunnivas** [comment]
Thank you for the prompt reply

**Comment by thegrannychaseroperation** [comment]
Closing.
