### ISSUE TITLE
[BUG] Monster Hunter Stories has the links of MHS 2

### ISSUE THREAD

**Issue by jorgelloret** [hydralauncher/hydra#614]
### Describe the bug

The links contained in Monster Hunter Stories are those of MHS 2.

### Steps to Reproduce

1. Search for Monster Hunter Stories
2. Click on View download options

### Expected behavior

The links of Monster Hunter Stories

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/16226783/e0a65ca3-740f-471f-b1c8-09b42a8ae400)

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by JackEnx** [comment]
side effect of to how hydra index the games, is expected, although it can be improved in the future
