### ISSUE TITLE
[BUG] Metadata Download

### ISSUE THREAD

**Issue by Kinger101** [hydralauncher/hydra#619]
### Describe the bug

I was downloading "Hogwarts Legacy", until out of curiosity I decided to pause the installation of Hogwarts to see how OnlineFix works with the game "Overcooked! 2", after some research to really be sure that how to download the game through OnlineFix I started to download it, but it didn't show the information that metadata was being downloaded, after a bit of frustration I decided to re-download Hogwarts, but when I tried to download it it returned to where it started (47.29 %), it just gets stuck on the information that the metadata was being downloaded, just like Overcooked! two. 

Note: I don't have much knowledge on this type of subject, I've had previous problems and felt that I was treated with ignorance due to my lack of knowledge. So if it was a mistake on my part, I immediately apologize.

### Steps to Reproduce

It has happened other times, but when this happened I would close Hydra completely and the game would start checking the files normally, I don't know exactly what steps have to be taken for this to happen, but a good part of what I did is in the detailed explanation of the problem. And when that didn't work, I even changed the SSD that was downloading and it started working again.

### Expected behavior

I expected the game to resume where it left off (47.29%), and not get stuck downloading metadata.

### Screenshots

![imagem_2024-06-20_211757019](https://github.com/hydralauncher/hydra/assets/169103654/1f278d6f-98a9-4b3b-aa60-78bce4840c63)

### Operating System

Windows 10

### Hydra Version

v1.2.4

**Comment by JackEnx** [comment]
fixed on #722, if the problem persist, please report it
