### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Rodrigo1589** [hydralauncher/hydra#636]
### Describe the bug

all games are appearing with no download available.

### Steps to Reproduce

open hydra and in the catalog all the games were saying no download available

### Expected behavior

download was supposed to appear so you could click and choose which one you wanted

### Operating System

Windows 11

### Hydra Version

2.0.0  It is 1.2.4

**Comment by RafaelFaiaC** [comment]
A mesma coisa está acontendo no meu windows 10.
The same thing is happening in my windows 10.

**Comment by Kinger101** [comment]
O de vocês também está com uma baixa quantidade de seeds e de peers? O meu pegava tipo uma média de 150 (peers) e 100-90 (seeds) pelo torrent mesmo.
Does yours also have a low number of seeds and peers? Mine got like an average of 150 (peers) and 100-90 (seeds) through the torrent itself.

**Comment by 007pikalonga** [comment]
aconteceu o mesmo comigo, todos o jogos estão com 0 download disponiveis.

**Comment by thegrannychaseroperation** [comment]
Please read the release notes. Closing.
