### ISSUE TITLE
[BUG] User profile doesn't load

### ISSUE THREAD

**Issue by Fairydx** [hydralauncher/hydra#637]
### Describe the bug

After creating an account the loading stay like this

### Steps to Reproduce

Create an Account and log in

### Expected behavior

To load the profile

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/8240478/0ce912ea-863c-4940-8d9d-b86a0796fec9)

### Operating System

Windows 11

### Hydra Version

2.0.0

**Comment by thegrannychaseroperation** [comment]
Solved in 2.0.1.
