### ISSUE TITLE
[BUG] Login popup open with wrong language

### ISSUE THREAD

**Issue by kaioenzo** [hydralauncher/hydra#639]
### Describe the bug

Login screen open in wrong language.

### Steps to Reproduce

1. Click on `Login` button on left menu

### Expected behavior

Open Login screen with right language

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/59144744/923ebac3-b576-4e16-93e9-d14e8f40efd0)

### Operating System

Windows 11

### Hydra Version

v2.0.0 "Levictius"

### Additional Information

As I can see, in change logs of v2, the menu opens in Portguese for a client that appears to be in English
[Example in change logs](https://hydra-launcher.gitbook.io/hydra/v/pt#sincronizacao-da-biblioteca)

**Comment by thegrannychaseroperation** [comment]
Thanks for the report. Will fix this ASAP.

**Comment by zamitto** [comment]
Fixed on latest version
