### ISSUE TITLE
[BUG]  Account creation does not work

### ISSUE THREAD

**Issue by antoxa-kms** [hydralauncher/hydra#641]
### Describe the bug

I fill in all the fields and no account is created.

### Steps to Reproduce

1. Click on the create account button.
2. Fill in all the fields and click create account
3. A window with a PIN code opens. I check the box and click confirm.
4. The pin window closes and the registration window is displayed again and nothing happens. When you click the create account button, a window with a pin code appears again.
5. If you click on "Already have an account", it throws to the login window and if you enter your username and password, it writes about the inaccuracy of entering your username or password.

### Expected behavior

So that everything would be registered

### Screenshots

![Снимок экрана 2024-06-23 141719](https://github.com/hydralauncher/hydra/assets/49340651/648cf650-6b92-4fbf-8001-ee5802b0978d)
![Снимок экрана 2024-06-23 141942](https://github.com/hydralauncher/hydra/assets/49340651/9094ea40-f625-45ba-95c3-7b9e489a2efc)
![Снимок экрана 2024-06-23 142041](https://github.com/hydralauncher/hydra/assets/49340651/5042666a-1679-4802-b124-6c8483273d6a)
![Снимок экрана 2024-06-23 142120](https://github.com/hydralauncher/hydra/assets/49340651/2c79f4b3-a705-4c0e-b4ba-0c42e44352df)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by Magrid0** [comment]
It worked fine for me, maybe something in your computer is blocking it?

**Comment by antoxa-kms** [comment]
That's what's blocking it. I don't have any third-party antiviruses (only the standard one that is preinstalled in windows 11), the firewall is turned off.

**Comment by antoxa-kms** [comment]
I've solved the problem. The problem was that the login had a dash sign (-)

**Comment by zamitto** [comment]
Sorry for it, we are already fixing it, so an error message properly shows warning you
