### ISSUE TITLE
[BUG] METADATA

### ISSUE THREAD

**Issue by DezelXI** [hydralauncher/hydra#643]
### Describe the bug

Not a single game is downloaded, from any source

### Steps to Reproduce

Not a single game is downloaded, from any source

### Expected behavior

Not a single game is downloaded, from any source

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/137102808/3ad719ae-e3c0-461d-b2d5-3e9e2c424137)
![image](https://github.com/hydralauncher/hydra/assets/137102808/aee2385b-d2eb-470b-a617-37b96785a42b)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by ItzJemm** [comment]
the same problem

**Comment by Pamlau** [comment]
same problem here

**Comment by JackEnx** [comment]
fixed on #722, if the problem persist, please report it
