### ISSUE TITLE
[BUG] All last played are replaced by "2 months ago" instead of the real value

### ISSUE THREAD

**Issue by Magrid0** [hydralauncher/hydra#644]
### Describe the bug

I just updated to 2.0.1 and before starting a game i noticed that all of my "last played" are now replaced by "last played 2 months ago" instead of the real time i last played them.

For example, i played Baldur's Gate 3 yesterday, but it say "Last played 2 months ago"

### Steps to Reproduce

1. Go to any game in your library
2. Look at the "last played" text

### Expected behavior

Show the the actual time that has passed since I last played the game
### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/73496008/7a82ff8c-d214-4cf8-987a-b1b35dd5af77)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
I will investigate it, thanks for reporting

**Comment by zamitto** [comment]
@Magrid0, to help me investigate, could you upload your logs files? They are located in "%appdata%/hydra/logs

**Comment by Magrid0** [comment]
> @Magrid0, to help me investigate, could you upload your logs files? They are located in "%appdata%/hydra/logs

[info.txt](https://github.com/user-attachments/files/15944852/info.txt)
are these the logs?
It's the only file in the folder C:\Users\<myuser>\AppData\Roaming\Hydra\logs

**Comment by zamitto** [comment]
> > @Magrid0, to help me investigate, could you upload your logs files? They are located in "%appdata%/hydra/logs
> 
> [info.txt](https://github.com/user-attachments/files/15944852/info.txt) are these the logs? It's the only file in the folder C:\Users<myuser>\AppData\Roaming\Hydra\logs

Yes, thank you. It was something when your Hydra uploaded your games. A lot of them were send with a date from April, not sure why. 

The next time you play a new game, or even a game that you have played before (and shows 2 months ago), could you tell me if that date shows correctly?

**Comment by zamitto** [comment]
> > @Magrid0, to help me investigate, could you upload your logs files? They are located in "%appdata%/hydra/logs
> 
> [info.txt](https://github.com/user-attachments/files//info.txt) are these the logs? It's the only file in the folder C:\Users<myuser>\AppData\Roaming\Hydra\logs

Yes, thank you. It was something when your Hydra uploaded your games. A lot of them were send with a date from April, not sure why. 

The next time you play a new game, or even a game that you have played before (and shows 2 months ago), could you tell me if that date shows correctly?

**Comment by Magrid0** [comment]
yes, i just finished playing a game some minutes ago and the date of that game is correct now.

All the other games are still incorrect tho
