### ISSUE TITLE
Nem um jogo está com a opção de download [BUG] 

### ISSUE THREAD

**Issue by CKarvalhais** [hydralauncher/hydra#645]
### Describe the bug

Todos os jogos disponíveis estão marcados como "Sem downloads disponíveis".
![imagem_2024-06-23_094011555](https://github.com/hydralauncher/hydra/assets/144966532/86e2cb06-d0cd-40c2-b841-23cb8b8f77bd)

### Steps to Reproduce

1.Instalar o launcher
2.Abrir
3.Nenhum jogo tem download disponivel

### Expected behavior

help me 

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/144966532/ed355a24-4442-4ba3-81ea-18a30e0d0e30)
![image](https://github.com/hydralauncher/hydra/assets/144966532/2533c69c-d690-4187-b7d4-b3f87ff8a8f9)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
Expected behaviour until you add your download sources. If you need help with it, join our telegram channel and look for the Support chat
