### ISSUE TITLE
[BUG] No games are available for download

### ISSUE THREAD

**Issue by Deivisson-dev** [hydralauncher/hydra#650]
### Describe the bug

No games in the app have a download option

### Steps to Reproduce

....

### Expected behavior

.....

### Screenshots

![Sem título](https://github.com/hydralauncher/hydra/assets/82292999/5c8c6a09-cc2c-4498-abbb-fa88b9045f82)

### Operating System

 Windows 11

### Hydra Version

2.0.1 "Leviticius"

**Comment by VladicekTraviska** [comment]
I have the same problem. I just installed this laucher opened and registered. And when I went to the end to download something I noticed that nothing can be downloaded at all.
![image](https://github.com/hydralauncher/hydra/assets/144840632/acd92c98-81ed-4426-b871-21210d4acfc9)

**Comment by EznoShurek** [comment]
na verdade pessoal, isso na verdade não é nenhum problema. Vocês não fizeram o processo pra ter a fonte de instalação, vejam esse vídeo https://www.youtube.com/watch?v=oqG5YAdozyQ

**Comment by zamitto** [comment]
Yeah, it is the expected behaviour until you add your downloads source. Above comment has a solution

**Comment by Raxstwq** [comment]
Hi. download hydra version 1,2,1
