### ISSUE TITLE
[BUG] hydra nao iniciando com o windows

### ISSUE THREAD

**Issue by rybandz** [hydralauncher/hydra#651]
### Describe the bug

desde as versoes antigas eu deixo marcado a opçao de iniciar com o windows mas nunca chegou a iniciar

![imagem_2024-06-23_145900556](https://github.com/hydralauncher/hydra/assets/165525397/d593cc50-cfc6-4537-a1fc-a9547f88fa37)

até no gerenciador ele ta ativado mas na pratica nao

### Steps to Reproduce

Marco a opçao de iniciar o hydra junto com o sistema mas nao funciona

### Expected behavior

Iniciar o hydra com o windows

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
Thanks for reporting, we will try to fix it for next release

**Comment by zamitto** [comment]
Fixed in 2.0.2
You wil just need to uncheckd and check again the option, so it takes effect
