### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Kiiraaaaaaa** [hydralauncher/hydra#652]
"Sem downloads disponíveis"

Não consigo baixar nenhum jogo.

### Steps to Reproduce

1. Abre o executável, 2. início, 3. "sem download's disponíveis"

### Expected behavior

Poder baixar os jogos.

### Screenshots

![Captura de tela 2024-06-23 150848](https://github.com/hydralauncher/hydra/assets/173629185/f682b5c6-b379-4408-8b73-f814470cecb4)

### Operating System

Windows 11

### Hydra Version

2.0.1

### Additional Information

Simplesmente não consigo baixar jogo algum, pensei que era o firewall bloqueando mas dei permissão de entrada e saída ao hydra e mesmo assim parece que está offline e não aparece os download's disponíveis.

**Comment by zamitto** [comment]
Expected behaviour until you add your download sources. If you need help with it, join our telegram channel and look for the Support chat
