### ISSUE TITLE
[BUG] meus downloads não estou iniciando

### ISSUE THREAD

**Issue by JucaGF** [hydralauncher/hydra#654]
### Describe the bug

sempre que tento colocar um jogo para baixar o download fica travado no 0% e não aumenta.
também os peers e seeds ficam sempre em 0

### Steps to Reproduce

start download

### Expected behavior

que o jogo fosse baixado

### Operating System

windows 11

### Hydra Version

2.0.1

**Comment by DaniloHub123** [comment]
Eles começam, mas como é torrent demoraria.

**Comment by soupaulodev** [comment]
Same behavior here. Download does not start. I started 30 minutes ago
![image](https://github.com/hydralauncher/hydra/assets/78260151/cd8d1e8a-9308-4c27-8cd6-e052b5ba92a6)

**Comment by zamitto** [comment]
Could you attach your logs? They are located in "%appdata/hydra/logs"

**Comment by JackEnx** [comment]
fixed on #722, if the problem persist, please report it

**Comment by slanzzz** [comment]
> fixed on [#722](https://github.com/hydralauncher/hydra/pull/722), if the problem persist, please report it

still dont workj for me
