### ISSUE TITLE
[BUG] Launcher flickando, impossível de usar

### ISSUE THREAD

**Issue by corelyoooo** [hydralauncher/hydra#657]
### Describe the bug

Launcher constantemente flickando em cores super-saturadas, principalmente amarelo. 

### Steps to Reproduce

1. Instalei e abri o launcher. 

### Expected behavior

O launcher deveria funcionar normalmente, sem esses bugs de cores. 

### Screenshots

![imagem_2024-06-23_212918598](https://github.com/hydralauncher/hydra/assets/155807492/a1d2c312-9ac6-4367-b1d0-8553c5ae46ea)

### Operating System

Windows 11

### Hydra Version

v2.0.1 "Leviticus"

**Comment by zamitto** [comment]
Nvidia GPU?

**Comment by zamitto** [comment]
Try disabling Nvidia overlay

**Comment by corelyoooo** [comment]
> Try disabling Nvidia overlay

It didn't work

**Comment by zamitto** [comment]
We had users who figure this solution in the community discord server (link is in our telegram channel), maybe you can join it and ask for help there. 100% of the users with this bug that we tracked so far are Nvidia users

**Comment by corelyoooo** [comment]
> We had users who figure this solution in the community discord server (link is in our telegram channel), maybe you can join it and ask for help there. 100% of the users with this bug that we tracked so far are Nvidia users

I see. Can you please provide the invite here or in my discord? I neither use or have Telegram.

**Comment by zamitto** [comment]
https://discord.gg/TSxymg7JTJ

**Comment by corelyoooo** [comment]
thanks man.
