### ISSUE TITLE
[BUG] Is this normal ? There's no download options 

### ISSUE THREAD

**Issue by YKDM0** [hydralauncher/hydra#658]
### Describe the bug

There's no download options 

### Steps to Reproduce

I just runned the .exe file 

### Expected behavior

It was supposed to show the download options, right ?

### Screenshots

![imagem_2024-06-23_232605684](https://github.com/hydralauncher/hydra/assets/138411085/469ae2bb-0efe-4948-aef1-5f48bd645d15)

### Operating System

Windows 11

### Hydra Version

v2.0.1

**Comment by Winnymax** [comment]
Cara, tambem estou com o mesmo problema. Baixei ontem e esta mostrando isso pra mim tambem!

**Comment by Winnymax** [comment]
![Sem título](https://github.com/hydralauncher/hydra/assets/173647800/f2c2cec7-1358-487c-8071-b71672fde370)
Cara. Também estou com o mesmo problema. Baixei ontem e esta mostrando isso pra mim!

**Comment by leomachadods** [comment]
@YKDM0 @Winnymax 

Basicamente a partir das novas versões do hydra foi adicionado uma aba chamada "Download Sources" no menu "Settings"

![image](https://github.com/hydralauncher/hydra/assets/99626076/dc99e674-a052-4bc2-b3cc-2355984cb4b2)

Para resolver esse problema basta acessar o link https://hydralinks.cloud/ e adicionar todos as fontes diretamente nessa aba

Após adicioná-los o seu launcher vai se parecer como algo assim
![Screenshot from 2024-06-24 00-39-47](https://github.com/hydralauncher/hydra/assets/99626076/23a03b79-9078-47ae-acf4-ec5b19685cee)

**Comment by Winnymax** [comment]
> @YKDM0 @Winnymax
> 
> Basicamente a partir das novas versões do hydra foi adicionada uma aba chamada "Fontes de download" no menu "Configurações"
> 
> ![imagem](https://private-user-images.githubusercontent.com/99626076/342194668-dc99e674-a052-4bc2-b3cc-2355984cb4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2MjQsIm5iZiI6MTcxOTIwMTMyNCwicGF0aCI6Ii85OTYyNjA3Ni8zNDIxOTQ2NjgtZGM5OWU2NzQtYTA1Mi00YmMyLWIzY2MtMjM1NTk4NGNiNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MzQ2NzFlZWE3MGQ5YzQ2NTlhNjBlOGM1MjYxMGM3MmM0ZTA4ZGU2ZTc0YWE4ZTdkMTQxYjM0NjkyOTE3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sgwMozyLgTh1gGu4KK0cDLIbqyTXOiTCWsMYxyCelnc)
> 
> Para resolver esse problema basta acessar o link https://hydralinks.cloud/ e adicionar todas as fontes diretamente nessa aba
> 
> Após adicioná-los, seu launcher parecerá algo assim ![Captura de tela de 2024-06-24 00-39-47](https://private-user-images.githubusercontent.com/99626076/342194495-23a03b79-9078-47ae-acf4-ec5b19685cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE2MjQsIm5iZiI6MTcxOTIwMTMyNCwicGF0aCI6Ii85OTYyNjA3Ni8zNDIxOTQ0OTUtMjNhMDNiNzktOTA3OC00N2FlLWFjZjQtZWM1YjE5Njg1Y2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZGI0ZjdmOGIyMmJkOGE4ZTE4M2JmODYzODUxMjU3YWJjOWRjNWE1ZDllNGNiOWU3OGYzMmU1NTI1MWRmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgncrpyqrXJbyinowc5LeCkaxH7cvXqeTofSP_0-OJw)

Po cara me ajudou pra caramba. Finalmente consegui! Muitissimo obg irmao
