### ISSUE TITLE
[BUG] Download won't start / Download não inicia

### ISSUE THREAD

**Issue by rafsnx** [hydralauncher/hydra#660]
### Describe the bug

Can´t download anything / Não baixa nada.

### Steps to Reproduce

Ao clicar no game e selecionar o repack fica somente baixando metadados

### Expected behavior

Na versão anterior antes da atualização atual os mesmos downloads foram feitos normalmente

### Screenshots

![printscreen](https://github.com/hydralauncher/hydra/assets/166335859/e8284369-f0a6-424b-afa9-12a0414f8b8c)

### Operating System

Windows 11

### Hydra Version

2.0.1

### Additional Information

Após adicionar manualmente os links do https://hydralinks.cloud/ na fonte de download, os downloads iniciaram.

**Comment by S3r4ph1m-S3c** [comment]
Estou com o mesmo problema no Ubuntu

**Comment by devjaizon** [comment]
Same problem here. Tested in both Fedora and Manjaro

**Comment by JackEnx** [comment]
fixed on #722, if the problem persist, please report it
