### ISSUE TITLE
[BUG] Empty login window

### ISSUE THREAD

**Issue by bUmmy1337** [hydralauncher/hydra#661]
### Describe the bug

The window where the account login should be is simply empty, there is nothing there
I tried restarting Hydra, reinstalling, but nothing helped

### Steps to Reproduce

Click login button

### Expected behavior

Fix this problem

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/92600850/1c9cc46b-7504-49cd-9928-df632e5c3a55)

### Operating System

Windows 11

### Hydra Version

2.0.1

### Additional Information

Windows 11 was reinstalled yesterday

**Comment by linquit** [comment]
Впн включи и будет окно

**Comment by zamitto** [comment]
Is it still happening in 2.0.2?

**Comment by zamitto** [comment]
Could you test it again @bUmmy1337 ?
