### ISSUE TITLE
[BUG] Loading 0 seeds

### ISSUE THREAD

**Issue by Sleyn452** [hydralauncher/hydra#665]
### Describe the bug

When I try to download any game I get 0/0. Some Fitgirl repack downloaded 4mb and froze. I'm in Russia, can you tell me if this could be a problem?

### Steps to Reproduce

1) select a game
2) select download option
3) 0 seeds 0 peers, download 0mb/s

### Expected behavior

Loading the game

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/173693491/6a23d3e5-752f-466b-a5c4-9d46016abb16)

### Operating System

windows 11

### Hydra Version

2.0.1

### Additional Information

Использую так же Qbittorent с ним все хорошо, очень сильно хочу пользовать гидрой, но не получается(

**Comment by herosh1sh** [comment]
У тебя получилось исправить всё? Или всё также

**Comment by Sleyn452** [comment]
> У тебя получилось всё исправить? Или всё также

Нет, все так же :( жду ответа от других людей

**Comment by RagingStarfire** [comment]
> > У тебя получилось всё исправить? Или всё также
> 
> Нет, все так же :( жду ответа от других людей

Кароче, как я понял, у администрации какие-то технические проблемы.
https://hydralinks.cloud/
Переходишь на этот сайт, переносишь все в гидру, смотришь у каких репакеров есть доступные загрузки, и скачиваешь репаки от них. Если для игры, которую ты хочешь скачать, нет репака от нужного автора, то жди, терпи пока админы все не пофиксят)

**Comment by Sleyn452** [comment]
> > > У тебя получилось всё исправить? Или всё также
> > 
> > 
> > Нет, все так же :( жду ответа от других людей
> 
> Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотришь, у каких репаков есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)

Уже сделал это) Тоже никакого результата.

**Comment by RagingStarfire** [comment]
> > > > У тебя получилось всё исправить? Или всё также
> > > 
> > > 
> > > Нет, все так же :( жду ответа от других людей
> > 
> > 
> > Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотришь, у каких репаков есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)
> 
> Уже сделал это) Тоже никакого результата.

У меня, кстати, все починилось. Проверь, может и у тебя

**Comment by Sleyn452** [comment]
> > > > > У тебя получилось всё исправить? Или всё также
> > > > 
> > > > 
> > > > Нет, все так же :( жду ответа от других людей
> > > 
> > > 
> > > Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотри, у каких репаков есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)
> > 
> > 
> > Уже сделал это) Тоже никакого результата.
> 
> У меня, кстати, все починилось. Проверь, может и у тебя

![image](https://github.com/hydralauncher/hydra/assets/173693491/e20e229c-0681-4301-b8e8-55479434d2ed)

**Comment by RagingStarfire** [comment]
> > > > > > У тебя получилось всё исправить? Или всё также
> > > > > 
> > > > > 
> > > > > Нет, все так же :( жду ответа от других людей
> > > > 
> > > > 
> > > > Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотри, у каких репаков есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)
> > > 
> > > 
> > > Уже сделал это) Тоже никакого результата.
> > 
> > 
> > У меня, кстати, все починилось. Проверь, может и у тебя
> 
> ![image](https://private-user-images.githubusercontent.com/173693491/342652535-e20e229c-0681-4301-b8e8-55479434d2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3NTQsIm5iZiI6MTcxOTMwNTQ1NCwicGF0aCI6Ii8xNzM2OTM0OTEvMzQyNjUyNTM1LWUyMGUyMjljLTA2ODEtNDMwMS1iOGU4LTU1NDc5NDM0ZDJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWJiMjI4ZTBlNWIxNDRmNTcwZjgwZjg2OTg4YmI5YjVlNDBiNmVkMmQ0MGYzM2JjYWI2M2EwOTFmMzBkMjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1tyJPTntmK9weybwqxs9EEyt3F2w_Ktpeiy7pB_Uay8)

![Снимок2](https://github.com/hydralauncher/hydra/assets/173739576/935a8a4b-285d-4906-91b8-c102eba8bddb)
У меня все заработало, но я вчера с впн тыкался, может это помогло. В любом случае, подожди еще день, м.б. вылечится

**Comment by Sleyn452** [comment]
> > > > > > > У тебя получилось всё исправить? Или всё также
> > > > > > 
> > > > > > 
> > > > > > Нет, все так же :( жду ответа от других людей
> > > > > 
> > > > > 
> > > > > Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотри, в каком репакове есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)
> > > > 
> > > > 
> > > > Уже сделал это) Тоже никакого результата.
> > > 
> > > 
> > > У меня, кстати, все починилось. Проверь, может и у тебя
> > 
> > 
> > ![изображение](https://private-user-images.githubusercontent.com/173693491/342652535-e20e229c-0681-4301-b8e8-55479434d2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3NTQsIm5iZiI6MTcxOTMwNTQ1NCwicGF0aCI6Ii8xNzM2OTM0OTEvMzQyNjUyNTM1LWUyMGUyMjljLTA2ODEtNDMwMS1iOGU4LTU1NDc5NDM0ZDJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWJiMjI4ZTBlNWIxNDRmNTcwZjgwZjg2OTg4YmI5YjVlNDBiNmVkMmQ0MGYzM2JjYWI2M2EwOTFmMzBkMjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1tyJPTntmK9weybwqxs9EEyt3F2w_Ktpeiy7pB_Uay8)
> 
> ![Снимок2](https://private-user-images.githubusercontent.com/173739576/342653235-935a8a4b-285d-4906-91b8-c102eba8bddb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU5NjgsIm5iZiI6MTcxOTMwNTY2OCwicGF0aCI6Ii8xNzM3Mzk1NzYvMzQyNjUzMjM1LTkzNWE4YTRiLTI4NWQtNDkwNi05MWI4LWMxMDJlYmE4YmRkYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODU0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDY2NjNhNDg5M2U1ZWJjZmZiY2FlNmYzYjBkNjhhZjhmOGM0ZTViYzljNjdiMTRlNWJmNzI5ZTdkNmUzZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uBPMIXGzET89X5sKgz4C4ptm4R2Lv3tS3oVbDcx9rHw) У меня все заработало, но я вчера с впн тыкался, может это помогло. В любом случае, подожди еще день, м.б. вылечится

Какой впн использовал? Можешь дать ссылку?

**Comment by RagingStarfire** [comment]
> > > > > > > > У тебя получилось всё исправить? Или всё также
> > > > > > > 
> > > > > > > 
> > > > > > > Нет, все так же :( жду ответа от других людей
> > > > > > 
> > > > > > 
> > > > > > Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотри, в каком репакове есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)
> > > > > 
> > > > > 
> > > > > Уже сделал это) Тоже никакого результата.
> > > > 
> > > > 
> > > > У меня, кстати, все починилось. Проверь, может и у тебя
> > > 
> > > 
> > > ![изображение](https://private-user-images.githubusercontent.com/173693491/342652535-e20e229c-0681-4301-b8e8-55479434d2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3NTQsIm5iZiI6MTcxOTMwNTQ1NCwicGF0aCI6Ii8xNzM2OTM0OTEvMzQyNjUyNTM1LWUyMGUyMjljLTA2ODEtNDMwMS1iOGU4LTU1NDc5NDM0ZDJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWJiMjI4ZTBlNWIxNDRmNTcwZjgwZjg2OTg4YmI5YjVlNDBiNmVkMmQ0MGYzM2JjYWI2M2EwOTFmMzBkMjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1tyJPTntmK9weybwqxs9EEyt3F2w_Ktpeiy7pB_Uay8)
> > 
> > 
> > ![Снимок2](https://private-user-images.githubusercontent.com/173739576/342653235-935a8a4b-285d-4906-91b8-c102eba8bddb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU5NjgsIm5iZiI6MTcxOTMwNTY2OCwicGF0aCI6Ii8xNzM3Mzk1NzYvMzQyNjUzMjM1LTkzNWE4YTRiLTI4NWQtNDkwNi05MWI4LWMxMDJlYmE4YmRkYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODU0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDY2NjNhNDg5M2U1ZWJjZmZiY2FlNmYzYjBkNjhhZjhmOGM0ZTViYzljNjdiMTRlNWJmNzI5ZTdkNmUzZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uBPMIXGzET89X5sKgz4C4ptm4R2Lv3tS3oVbDcx9rHw) У меня все заработало, но я вчера с впн тыкался, может это помогло. В любом случае, подожди еще день, м.б. вылечится
> 
> Какой впн использовал? Можешь дать ссылку?

Planet vpn из microsoft store

**Comment by RagingStarfire** [comment]
> > > > > > > > > У тебя получилось всё исправить? Или всё также
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Нет, все так же :( жду ответа от других людей
> > > > > > > 
> > > > > > > 
> > > > > > > Кароче, как я понял, у администрации какие-то технические проблемы. https://hydralinks.cloud/ Переходишь на этот сайт, переносишь все в гидру, смотри, в каком репакове есть доступные загрузки, и скачиваешь репаки с них. Если для какой игры, ты хочешь скачать, нет репака от нужного автора, то жди, терпи, пока админы все не пофиксят)
> > > > > > 
> > > > > > 
> > > > > > Уже сделал это) Тоже никакого результата.
> > > > > 
> > > > > 
> > > > > У меня, кстати, все починилось. Проверь, может и у тебя
> > > > 
> > > > 
> > > > ![изображение](https://private-user-images.githubusercontent.com/173693491/342652535-e20e229c-0681-4301-b8e8-55479434d2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU3NTQsIm5iZiI6MTcxOTMwNTQ1NCwicGF0aCI6Ii8xNzM2OTM0OTEvMzQyNjUyNTM1LWUyMGUyMjljLTA2ODEtNDMwMS1iOGU4LTU1NDc5NDM0ZDJlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWJiMjI4ZTBlNWIxNDRmNTcwZjgwZjg2OTg4YmI5YjVlNDBiNmVkMmQ0MGYzM2JjYWI2M2EwOTFmMzBkMjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1tyJPTntmK9weybwqxs9EEyt3F2w_Ktpeiy7pB_Uay8)
> > > 
> > > 
> > > ![Снимок2](https://private-user-images.githubusercontent.com/173739576/342653235-935a8a4b-285d-4906-91b8-c102eba8bddb.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDU5NjgsIm5iZiI6MTcxOTMwNTY2OCwicGF0aCI6Ii8xNzM3Mzk1NzYvMzQyNjUzMjM1LTkzNWE4YTRiLTI4NWQtNDkwNi05MWI4LWMxMDJlYmE4YmRkYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwODU0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDY2NjNhNDg5M2U1ZWJjZmZiY2FlNmYzYjBkNjhhZjhmOGM0ZTViYzljNjdiMTRlNWJmNzI5ZTdkNmUzZGYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uBPMIXGzET89X5sKgz4C4ptm4R2Lv3tS3oVbDcx9rHw) У меня все заработало, но я вчера с впн тыкался, может это помогло. В любом случае, подожди еще день, м.б. вылечится
> > 
> > 
> > Какой впн использовал? Можешь дать ссылку?
> 
> Planet vpn из microsoft store

сука у меня снова все сломалось

**Comment by s9mpus** [comment]
Решение нашли какое-нибудь?/Did u find any solution of this problem?

**Comment by Sleyn452** [comment]
Есть еще варианты решения?

**Comment by TheLuckie** [comment]
Попробуйте отключить брандмауэр, у меня с другом такая же проблема была. Только отключили брандмауэр и сразу всё пошло

**Comment by JackEnx** [comment]
> Попробуйте отключить брандмауэр, у меня с другом такая же проблема была. Только отключили брандмауэр и сразу всё пошло

ould you try 2.0.2 to see if this problem persist?

**Comment by TheLuckie** [comment]
> > Попробуйте отключить брандмауэр, у меня с другом такая же проблема была. Только отключили брандмауэр и сразу всё пошло
> 
> Could you try 2.0.2 to see if this problem persist?

![image](https://github.com/hydralauncher/hydra/assets/97118745/a516cea3-7d4c-4c2b-bd62-8cd54ddb30a3)
Great! Now it works good!

**Comment by Sleyn452** [comment]
IT WORKING! HELL YES

**Comment by zanda09** [comment]
Не знаю, актуально или нет, но я поставилв свойствах ярлыка "открывать от имени администратора". сразу помогло

**Comment by Rapter101** [comment]
Ребят, ничего не получается, отключил брендмауэр, запускал от имени администратора. Все работало, но уже неделю ничего не могу загрузить, ПОЖАЛУЙСТА ПОМОГИТЕ!
