### ISSUE TITLE
[REQUEST]  Add multiplayer support (possibly for a paid subscription) to cracked games via spacewar

### ISSUE THREAD

**Issue by kyreosu** [hydralauncher/hydra#666]
### Is your feature request related to a problem? Please describe.

Add multiplayer support (possibly for a paid subscription) to cracked games via spacewar

### Describe the solution you'd like

Add multiplayer support (possibly for a paid subscription) to cracked games via spacewar

### Additional context

thx

**Comment by bpavuk** [comment]
they already scrape from the Online-Fix

**Comment by JackEnx** [comment]
We don't deal with game cracks
