### ISSUE TITLE
Option to stop/block seeding

### ISSUE THREAD

**Issue by VELTR0** [hydralauncher/hydra#67]
Add an option to stop or block the seeding process. There are some cases where seeding can turn into a problem.

**Comment by hydralauncher** [comment]
Please elaborate this and be more technical. What exactly do you mean by "a problem"?

**Comment by VELTR0** [comment]
Legally speaking some countries like Germany (even with VPN) can track and sue you. I'm saying this out of experience :)

**Comment by AfkKun** [comment]
Not entirely sure, you are save here with a VPN, if you were "tracked" even when using VPN you didn't bind the Interface and your real IP leaked. Just have to double check everything ;) 

But yeah Having this option is important as in germany you don't receive warnings like in the US, you instantly receive a cease and desist with a hefty fine to pay

**Comment by Magrid0** [comment]
does hydra even leave the torrent seeding? I thought it automatically stopped seeding

**Comment by Bartek16194** [comment]
Options like stop seeding, bandwidth cap and pop up after downloading should be implemented in future

**Comment by axeltechtips** [comment]
I think binding to a internet profile like one that Mullvad generates when you use the VPN is also needed too.

**Comment by pedrosantayana** [comment]
It doesn't looks that hydra allows torrent seeding. It will be an option in the future? More people seeding means faster download speed for who are using the launcher.

**Comment by thegrannychaseroperation** [comment]
Yes; closing this since Hydra does not seed at all.
