### ISSUE TITLE
[BUG] Missing games on Hydra

### ISSUE THREAD

**Issue by Maiqueel** [hydralauncher/hydra#675]
### Describe the bug

Eu e meu amigo temos o Hydra instalados desde as versões anteriores. Ambos com todas as fontes de downloads adicionadas, e sincronizadas.
Ele também já tentou desinstalar e instalar novamente o Hydra.
No meu Hydra, aparece a opção de download com o onlinefix. Pra ele, não.

//

I and my friend have Hydra installed from previous versions. Both with all download sources added and synchronized.
He has also tried uninstalling and reinstalling Hydra.
On my Hydra, a download option appears with onlinefix. Not for him.

My Hydra:
![image](https://github.com/hydralauncher/hydra/assets/45471120/73a470f9-be6d-4964-aafd-b24c26faac5f)

My friend:
![image](https://github.com/hydralauncher/hydra/assets/45471120/f7086e9e-38f0-439e-b105-3db3ee20479a)

### Steps to Reproduce

1. Download Hydra
2. Put all Download Fonts
3. Synchronize
4. Missing game

### Expected behavior

^ above

### Operating System

Windows 11

### Hydra Version

v2.0.1

**Comment by otaviotm** [comment]
mine also has the same problem

**Comment by otaviotm** [comment]
![image](https://github.com/hydralauncher/hydra/assets/38588167/2d4d5ff7-cc21-42e5-8274-ce9c0ca87d36)

**Comment by zamitto** [comment]
@otaviotm you need to add a download source, by default Hydra loads with no downloads available and it's up to you to add sources

**Comment by zamitto** [comment]
@Maiqueel, strange, if you both added the same download sources you both should have them available. 

Did you and your friend had Hydra installed before or you first installed it in 2.0?

**Comment by Maiqueel** [comment]
> @otaviotm you need to add a download source, by default Hydra loads with no downloads available and it's up to you to add sources

This has already been done. As said in the post, we added the sources and synchronized them. To check if it wasn't cache or something like that, he restarted the PC and nothing changed.

We noticed that only this game was missing, other games appeared as download sources. It's probably missing from some other game as well, which we haven't checked.

**Comment by Maiqueel** [comment]
> @Maiqueel, strange, if you both added the same download sources you both should have them available.
> 
> Did you and your friend had Hydra installed before or you first installed it in 2.0?

Both with the lower version before updating to 2.0

We already had another version installed. Both the same version. We updated at the same time to the new version 2.0.1

**Comment by zamitto** [comment]
@Maiqueel your friend could try deleting his database, probably there was a conflict with old games on his database that didn't allow his Hydra to get the download for this game. If he already created an account, his library won't be lost as it is synchronized.

For this:
1. Close Hydra
2. Uninstall Hydra
3. Go to "%appdata%/hydra"
4. Delete "hydra.db"
5. Reinstall Hydra and add the download sources again
