### ISSUE TITLE
[BUG] I don't understand how to install the game

### ISSUE THREAD

**Issue by Che1tro** [hydralauncher/hydra#682]
### Describe the bug

I can't find the exe file

### Steps to Reproduce

after I click install the game is transferred to the game folder, I go to the MD5 Quick folder and file checking begins

### Expected behavior

help

### Screenshots

![2024-06-25_13-52-31](https://github.com/hydralauncher/hydra/assets/166286729/078494e5-0f2c-4f28-8fa2-a6d3625a9317)
![2024-06-25_13-52-10](https://github.com/hydralauncher/hydra/assets/166286729/63dc4794-9b55-4286-baf2-4559947e5ac1)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by Che1tro** [comment]
I hope you can help

**Comment by zamitto** [comment]
We can't give support on how to install games. Hydra is just a launcher with a download manager.
You can join the discord server managed by the community, they have more experience installing games and will be able to help you for sure.

https://discord.gg/TSxymg7JTJ
