### ISSUE TITLE
[BUG] russian translate, download source name is ambiguous

### ISSUE THREAD

**Issue by Djastas** [hydralauncher/hydra#684]
### Describe the bug

в русской локализации в меню настроек 
пункт "Donwload sources" называется "Скачать исходный код"(donwload source code) это сильно сбивает с толку
\\\
in Russian localization in the settings menu
The item "Donwload sources" is called "Скачать исходный код" (donwload source code) this is very confusing

### Steps to Reproduce

.

### Expected behavior

.

### Screenshots

.

### Operating System

windows 10

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
This will be fixed in the next version. Thanks for reporting

**Comment by Djastas** [comment]
предлагаю перевести как "источники загрузки"

**Comment by zamitto** [comment]
This exact fix was made by @01M. It is already in the main code. 
We just didn't release a new version because we are rushing to fix the downloader and then release a new version
