### ISSUE TITLE
[BUG] unable to load Steam.dll

### ISSUE THREAD

**Issue by tutubr123** [hydralauncher/hydra#685]
### Describe the bug

sempre que eu inicio um jogo nao online aparece isso

### Steps to Reproduce

1.instalo o jogo
2.extraio o jogo
3.aparece o bug

### Expected behavior

abri o jogo normalmente

### Screenshots

![Captura de Tela (1)](https://github.com/hydralauncher/hydra/assets/173808824/6ae4b11d-b3c8-4452-b738-10cec22009f5)

### Operating System

W 10

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
We can't give support on how to install games. Hydra is just a launcher with a download manager.
You can join the discord server managed by the community, they have a lot more experience installing games and will be able to help you for sure.

https://discord.gg/TSxymg7JTJ
