### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ryan013paz** [hydralauncher/hydra#688]
### Describe the bug

não ta fazewndo dowload

### Steps to Reproduce

começou dai depois parou.

### Expected behavior

sss

### Screenshots

não tem

### Operating System

windos 11

### Hydra Version

hydra 2.0

### Additional Information

faz horas que tento fazer dowaload

**Comment by JackEnx** [comment]
Please, if you are going to open an issue, describe the problem, the way you did it tells us absolutely nothing.
