### ISSUE TITLE
[BUG] failed to update hydra

### ISSUE THREAD

**Issue by Rayxmam** [hydralauncher/hydra#689]
### Describe the bug

Eu não consigo instalar a nova versão, fica pedindo para iniciar o instalador novamente mas não resolve

### Steps to Reproduce

Ele instala normalmente até a hora de abrir

### Expected behavior

Eu so queria finalizar a instalação

### Screenshots

![git](https://github.com/hydralauncher/hydra/assets/173850831/567b7ad3-97b4-4354-9e56-ffe5fdf9c359)

### Operating System

Windows 11

### Hydra Version

2.0.1

### Additional Information

Eu ja limpei tudo que havia no Pc da versão anterior que tinha mas não muda nada

**Comment by zamitto** [comment]
You removed everything Hydra related from "%appdata%",  "%localappdata%" and "%localappdata%/Programs"?

**Comment by zamitto** [comment]
Closing issue as no response in a long time.
