### ISSUE TITLE
[BUG] Wrong Russian translation

### ISSUE THREAD

**Issue by trolley813** [hydralauncher/hydra#692]
### Describe the bug

Translation of "Download sources" into Russian is "Скачать исходный код", which means "to download the sources" (e.g. of the application itself). It is completely unrelated to this tab. To mean "the sources of downloads" (which it actually is), the translation should be e.g. "Источники загрузок".

### Steps to Reproduce

1. Open Hydra
2. Set the app language to Russian
3. Open settings and see the download sources tab

### Expected behavior

A correct translation should be displayed

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/8910056/c424eb72-fe87-40b3-8fdb-6534dca0a304)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by Xxxsusx** [comment]
I don't think this is a big deal, or is it? Not being rude, just asking. The developers probably uses some Google Translator API or something like that. 
The only thing I know is that the developers are brazilian so I expected that would happen.

**Comment by zamitto** [comment]
> I don't think this is a big deal, or is it? Not being rude, just asking. The developers probably uses some Google Translator API or something like that. 
> The only thing I know is that the developers are brazilian so I expected that would happen.

Actually, there are native russians that help with the translations


But these issues should be fine in 2.0.2
Feel free to re open or open a new issue if you find improvements tha could be done
