### ISSUE TITLE
[BUG] Não existem download dos jogos (I can't download games)

### ISSUE THREAD

**Issue by spyfamoso** [hydralauncher/hydra#697]
### Describe the bug

Quando vou em "Ver opções de download" (onde deveria se encontrar o download do jogo) não aparece nada, na biblioteca aparece que não existem download dos jogos disponíveis, como baixo os jogos para jogar?

### Steps to Reproduce

/

### Expected behavior

/

### Screenshots

![Sem título](https://github.com/hydralauncher/hydra/assets/173909006/bf1746d9-2d8d-477c-8289-085dc12f46be)
![Sem título](https://github.com/hydralauncher/hydra/assets/173909006/c1c3e32d-8e5c-4c36-84dc-c7f89d5b77a0)

### Operating System

Win10

### Hydra Version

1.2.4

**Comment by SlayerSterr** [comment]
Não é bug, ainda não existem links para esse download em especifico. Tambem não tenho opção, eventualmente serão adicionados

**Comment by zamitto** [comment]
No, they won't be added. You need to add them. You can find download sources on the internet and add your own. The community can help on the Hydra Community discord server, or on our telegram

**Comment by SlayerSterr** [comment]
It's funny how the internet works. 
Got to answer with an obvious wrong answer for someone to help the guy xD

**Comment by Duduz1nh00** [comment]
Mesma coisa mano, nenhum game tem link aqui

**Comment by Xxxsusx** [comment]
Opa, mano, beleza? Isso é um bug que está ocorrendo para algumas pessoas aí após instalar a nova versão 2.0 manualmente ou automática pelo launcher. Para consertar isso, apenas vá nas configurações/ajustes do Hydra e você terá que adicionar as fontes de downloads manualmente, que deverá aparecer aqui:
![image](https://github.com/hydralauncher/hydra/assets/105179663/bebc06a0-bf65-4672-8e59-86f349542400)

Se, por outro caso, não aparecer nada, o problema pode estar relacionado nisso. Para consertar esse problema, certifique-se de que o Hydra esteja aberto antes de fazer esse processo (Isso é importante).

Após ir em ajustes e Fontes de Downloads, você terá que ir neste site adicionar todas as fontes de Downloads manualmente que estão neste site: https://hydralinks.cloud/
![image](https://github.com/hydralauncher/hydra/assets/105179663/61e1a87a-adeb-4d79-91ba-bea696ada626)

Espero ter lhe ajudado!

**Comment by Duduz1nh00** [comment]
> Opa, mano, beleza? Isso é um bug que está ocorrendo para algumas pessoas aí após instalar a nova versão 2.0 manualmente ou automática pelo launcher. Para consertar isso, apenas vá nas configurações/ajustes do Hydra e você terá que adicionar as fontes de downloads manualmente, que deverá aparecer aqui: ![image](https://private-user-images.githubusercontent.com/105179663/343588819-bebc06a0-bf65-4672-8e59-86f349542400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTQ0OTAsIm5iZiI6MTcxOTUxNDE5MCwicGF0aCI6Ii8xMDUxNzk2NjMvMzQzNTg4ODE5LWJlYmMwNmEwLWJmNjUtNDY3Mi04ZTU5LTg2ZjM0OTU0MjQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxODQ5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGY0YmYzODA3YTRiYWI4OGRiYTcxODkxZGJlOTVmYjBhNWM0MDFmYmRlMjQ0NzIyYzdhMWVhNjc4MjA5ZWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fr_Rd6UP47IW8zQAHaIeoYQYjctqodtPlnAkE_ReLao)
> 
> Se, por outro caso, não aparecer nada, o problema pode estar relacionado nisso. Para consertar esse problema, certifique-se de que o Hydra esteja aberto antes de fazer esse processo (Isso é importante).
> 
> Após ir em ajustes e Fontes de Downloads, você terá que ir neste site adicionar todas as fontes de Downloads manualmente que estão neste site: https://hydralinks.cloud/ ![image](https://private-user-images.githubusercontent.com/105179663/343589788-61e1a87a-adeb-4d79-91ba-bea696ada626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTQ0OTAsIm5iZiI6MTcxOTUxNDE5MCwicGF0aCI6Ii8xMDUxNzk2NjMvMzQzNTg5Nzg4LTYxZTFhODdhLWFkZWItNGQ3OS05MWJhLWJlYTY5NmFkYTYyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxODQ5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWVlMDA2ODE0OWM4YjY3OTBhZTAzNDFhYzRiM2EyZjVjYmFhNWFmYzFkNGQzMWI1NWFlOTJhMWVjOTMzYzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihNLMCclPSV-9yr8Zsu6zp0UcnPDy6_zL1Nk8p0KzxM)
> 
> Espero ter lhe ajudado!

Valw monstro, Resolveu aqui

**Comment by edycarlos19** [comment]
> aqui

eu fiz tudo isso mas não consgo abrir o jogo, instalo o setup e fica sempre instalando
