### ISSUE TITLE
[BUG] WHITE SCREEN ON VERSION 2.0.1

### ISSUE THREAD

**Issue by Lizard243** [hydralauncher/hydra#703]
### Describe the bug

For some reason, when i enter on the page of an game on the version 2.0.1, it turns into a white screen. In the version 1.2.1, it works perfectly normal.

### Steps to Reproduce

1. Open the launcher;
2. Search for a game;
3. Try to enter the game page;
4. See the blank white screen.

### Expected behavior

It should just enter the game page where i can see all the details and downloads and all that stuff.

### Screenshots

![erro do norman](https://github.com/hydralauncher/hydra/assets/173971917/352442b5-b79d-4103-b604-f13fa3a87375)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
This happens for every game that you try to access?

**Comment by Lizard243** [comment]
> This happens for every game that you try to access?

Yes

**Comment by zamitto** [comment]
Could you attach your logs? They are in "%appdata%/hydra/logs"
Attach all files if possible

**Comment by zamitto** [comment]
You can also try the following:

1. Kill any Hydra process and uninstall Hydra
2. go to "%appdata%/hydra" and delete everything except the hydra.db file if it exists (if you delete de .db file, you will lose your local library)
3. go to "%appdata%" and check if there are others folder with hydra in the name, like "hydralauncher" or "hydra-launcher" and delete them
4. go to "%localappdata%" and check if there are any hydra folder here and delete them too
5. Run the installer again

**Comment by Lizard243** [comment]
> You can also try the following:
> 
> 1. Kill any Hydra process and uninstall Hydra
> 2. go to "%appdata%/hydra" and delete everything except the hydra.db file if it exists (if you delete de .db file, you will lose your local library)
> 3. go to "%appdata%" and check if there are others folder with hydra in the name, like "hydralauncher" or "hydra-launcher" and delete them
> 4. go to "%localappdata%" and check if there are any hydra folder here and delete them too
> 5. Run the installer again

Sorry for not answering. The error occured with my friend, so he had to give me the files bur he didn't. Anyway, i'll tell him to do this, thanks.

**Comment by zamitto** [comment]
Closing issue as no response in a long time.
If this error still happens in 2.1.7, feel free to open a new issue
