### ISSUE TITLE
[BUG] Can't download games,always show "Downloading metadata"

### ISSUE THREAD

**Issue by diotrek** [hydralauncher/hydra#704]
### Describe the bug

When I try to download any games it show "Downloading metadata" and dont download the game. I try to use Vpn and this is dont working.

### Steps to Reproduce

Click on "Download variants" and choose any variant.

### Expected behavior

The game will download.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/88184704/e06e662e-35d3-4486-8177-1e5dfcf61820)

### Operating System

Windows 11

### Hydra Version

2.0.1

### Additional Information

Other games in library i download from torrent trackers

**Comment by JoyceeWasabi** [comment]
У меня такая же проблема
![image](https://github.com/hydralauncher/hydra/assets/174023202/f5bb15c2-fb81-45fb-bc7a-f151ec2d093d)

**Comment by JackEnx** [comment]
We are working on a solution to this problem, it is taking us a while as it requires a complete refactoring of the download system, when a new version coming out, please report if the problem persists

**Comment by itstokyon** [comment]
> We are working on a solution to this problem, it is taking us a while as it requires a complete refactoring of the download system, when a new version coming out, please report if the problem persists

i too have this problem

**Comment by Xxxsusx** [comment]
Install the new v2.0.2 version. This bug has been fixed

**Comment by JackEnx** [comment]
fixed on #722
