### ISSUE TITLE
[BUG] cant downolad any games

### ISSUE THREAD

**Issue by YARMAAA** [hydralauncher/hydra#705]
### Describe the bug

when i want to downolad any games i see on every game "no downolads avaible" and i cant downolad every game + button "surprise me" also dont work 

### Steps to Reproduce

1. katalog 2.see error

### Expected behavior

idk but i think this because i live in belarus

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/162727280/b7bf3706-f76c-425a-8403-e1c4e45e6de3)

### Operating System

windows 10

### Hydra Version

2.0.1

### Additional Information

idk what write here sorry

**Comment by YARMAAA** [comment]
not 1.catalog 2.see error 
but 1.home 2.ree error

**Comment by 2Leo1** [comment]
Я тоже из Беларуси, тебе нужно просто перейти по ссылке https://hydralinks.cloud/ и на все репаки нажать install on hydra, оно тебя перекинет в приложение и все, у тебя буду доступны для скачки репаки от тех или иных издателей
/////
I am also from Belarus, you just need to follow the link https://hydralinks.cloud/ and click install on hydra on all repacks, it will transfer you to the application and that's it, you will have repacks from certain publishers available for download
