### ISSUE TITLE
[BUG] No Downloads Available in the new update (2.0.1)

### ISSUE THREAD

**Issue by ri5o** [hydralauncher/hydra#708]
### Describe the bug

In any games that previously had download links available, they no longer exist.
![Sem título](https://github.com/hydralauncher/hydra/assets/174057488/1e5807ad-2c75-4f9d-a0b6-9fc05984ac58)

For example, Crow Country, a game that i already has installed, no longer has any link for download it again.
![image](https://github.com/hydralauncher/hydra/assets/174057488/32c55d4a-fb4c-4020-8eee-e07f9a5607e5)

### Steps to Reproduce

.

### Expected behavior

.

### Operating System

Windows 10

### Hydra Version

2.0.1

**Comment by itstokyon** [comment]
this is not bug join their discord https://discord.gg/3EsrweK4
then faq and faq 15 theres a hydra links

**Comment by zamitto** [comment]
> this is not bug join their discord https://discord.gg/3EsrweK4
> then faq and faq 15 theres a hydra links

Just a disclaimer that I have to point out, this is not our oficial discord, it is a community managed discord. 
But the rest is correct, there you will find help

**Comment by thegrannychaseroperation** [comment]
Closing this for now.
