### ISSUE TITLE
Missing Game Management Menu

### ISSUE THREAD

**Issue by caduHD4** [hydralauncher/hydra#71]
I've noticed that the game management menu is missing. It would be possible, when right-clicking on a game in the sidebar, to access various useful options such as "Play", "Install", "Create Shortcut", "Remove", "Uninstall", and "Properties" (where you can change the game path or something like this).

Having quick access to these options would save time and make the game management experience much more convenient.

* Below is the prototype I made:

![Options](https://github.com/hydralauncher/hydra/assets/69264602/817fcbc8-3210-46c8-9082-44725410780b)

**Comment by caduHD4** [comment]
I was thinking that the properties could initially have these items, and in the future add some more.
* I believe that libtorrent has something to check the integrity of files, which could be another insue.

![Captura de tela 2024-04-22 194855](https://github.com/hydralauncher/hydra/assets/69264602/fe52963a-6ac5-4ffd-9142-5451191d4c12)

**Comment by hydralauncher** [comment]
+1 such a nice feature.
@caduHD4 please join our Discord server as a collaborator so we can discuss this.

**Comment by Magrid0** [comment]
> I was thinking that the properties could initially have these items, and in the future add some more.
> 
> * I believe that libtorrent has something to check the integrity of files, which could be another insue.
> 
> ![Captura de tela 2024-04-22 194855](https://private-user-images.githubusercontent.com/69264602/324632907-fe52963a-6ac5-4ffd-9142-5451191d4c12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDY0MTIsIm5iZiI6MTcxMzg0NjExMiwicGF0aCI6Ii82OTI2NDYwMi8zMjQ2MzI5MDctZmU1Mjk2M2EtNmFjNS00ZmZkLTkxNDItNTQ1MTE5MWQ0YzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA0MjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjkzNDQ1YTMwYzEyM2YwNWJmNmNlMzA1ODg4MjMxNDE4NDUwYzZjYjljMGU0ZGI1YmNhMzQyZGU5MTZmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTah5E8ExFXhNJvNem5ADDaWMTC0TmjJQ8pn6MVKop0)

Looks good

**Comment by caduHD4** [comment]
> +1 such a nice feature. @caduHD4 please join our Discord server as a collaborator so we can discuss this.

Okk

**Comment by caduHD4** [comment]
> > I was thinking that the properties could initially have these items, and in the future add some more.
> > 
> > * I believe that libtorrent has something to check the integrity of files, which could be another insue.
> > 
> > ![Captura de tela 2024-04-22 194855](https://private-user-images.githubusercontent.com/69264602/324632907-fe52963a-6ac5-4ffd-9142-5451191d4c12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDY0MTIsIm5iZiI6MTcxMzg0NjExMiwicGF0aCI6Ii82OTI2NDYwMi8zMjQ2MzI5MDctZmU1Mjk2M2EtNmFjNS00ZmZkLTkxNDItNTQ1MTE5MWQ0YzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA0MjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZjkzNDQ1YTMwYzEyM2YwNWJmNmNlMzA1ODg4MjMxNDE4NDUwYzZjYjljMGU0ZGI1YmNhMzQyZGU5MTZmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTah5E8ExFXhNJvNem5ADDaWMTC0TmjJQ8pn6MVKop0)
> 
> Looks good

Thanksss

**Comment by caduHD4** [comment]
> +1 such a nice feature. @caduHD4 please join our Discord server as a collaborator so we can discuss this.

**I have now entered the discord server.**

_I saw that some people are wanting a login option to save the game list, I believe you can do this without directly logging in with a Hydra account. In the settings there could be a Beckup option, where there would be a button to do a backup and next to it a key to do the backup automatically or not, and a button to restore the backup._

In short: It would be an option that would have backup locally and in the cloud (optional) through the user's Google Drive and the local database, that is, the user would click to do a backup and choose whether they want it local (generate a .zip) or cloud (google drive), if it were through the cloud he would log in with his google account without being linked to any third party server other than google itself, so hydra would create a backup folder in google drive with the .zip, and if the user If he needed to format the PC he could simply log in and restore the backup.

* It also wouldn't need to be Google Drive, any other form of online storage, or just use the idea of local backup with .zip for the user to save on a pendrive for example.

**Comment by hydralauncher** [comment]
@caduHD4 please create a different issue to suggest this. Keep each issue aimed towards a single discussion.

**Comment by ramonpego** [comment]
I would love to see this feature, I face a problem now.
I downloaded a game but due to my carelessness or an error in the download list another release came, I wanted 1 and release 2 came and now I can't remove the first one to add the right version

**Comment by thegrannychaseroperation** [comment]
Solved in 2.0.
