### ISSUE TITLE
[BUG] loguin screen empty

### ISSUE THREAD

**Issue by ZedcliF** [hydralauncher/hydra#711]
### Describe the bug

При авторизации нет окна для ввода логина и пароля

### Steps to Reproduce

1) Нажимаю войти
2) Пустое окно авторизации

### Expected behavior

Окно авторизации

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/156314435/b39e2e3a-7efd-4b4d-aa1c-a8a614babfea)

### Operating System

Windows 10

### Hydra Version

2.0.1 Leviticus

**Comment by RagingStarfire** [comment]
Вруби впн и залогинься

**Comment by zamitto** [comment]
Is it still happening in version 2.0.2?

**Comment by zamitto** [comment]
Could you test it again @ZedcliF?

**Comment by zamitto** [comment]
This should be fixed by now, no need to use vpn anymore
