### ISSUE TITLE
[BUG] cant download any game on portable exe

### ISSUE THREAD

**Issue by dotRarufu** [hydralauncher/hydra#712]
### Describe the bug

games does not download when using the portable exe. Always stuck in 0%.

### Steps to Reproduce

1. Download the portable exe
2. Add hydra links
3. Download any game

### Expected behavior

It should be able to download any game

### Operating System

Windows 10

### Hydra Version

v2.0.1

### Additional Information

found out that this does not exist in with installer version

**Comment by kykovich23** [comment]
I've also faced this problem, who was able to solve this?

**Comment by dotRarufu** [comment]
install hydra launcher using setup.exe, don't use the portable

**Comment by kykovich23** [comment]
> install hydra launcher using setup.exe, don't use the portable

reinstalled launcher, but still loading speed 0. Is it because of the lack of peers and seeds?

**Comment by Xxxsusx** [comment]
Installing hydra portable or the normal version doesn't work. I've made a issue explaining why that happens and it has nothing to do with the lack of peers and seeds.
I'm currently waiting for any developer or contributor to see the issue:
https://github.com/hydralauncher/hydra/issues/723

Sadly, for now there isn't pretty much to do about it. All we can do is wait for now until a new update that fixes this comes.

**Comment by Xxxsusx** [comment]
Install the new v2.0.2 version. This bug has been fixed

**Comment by zamitto** [comment]
Closing as the bug has been fixed. If you still have issues, feel free to reopen this.
