### ISSUE TITLE
32 bits

### ISSUE THREAD

**Issue by ViniciusDadalte** [hydralauncher/hydra#713]
### Is your feature request related to a problem? Please describe.

Quando eu clico executar, aparece um erro falando que só é compativel com sistemas operacionais 64 bits e o meu windows 7 é 32 bits.

### Describe the solution you'd like

Gostaria que o hydra fosse compativel com sistemas operacionais 32 bits.

### Describe alternatives you've considered

Façam com que  hydra tambem funcione em sistemas operácionais 32 bits, como o meu windows 7 D:

**Comment by thegrannychaseroperation** [comment]
Not feasible at this moment. x86 nor Windows 7 (14 years old OS) are planned to be supported.
