### ISSUE TITLE
não aparece o setup do jogo 

### ISSUE THREAD

**Issue by unitypng** [hydralauncher/hydra#714]
### Describe the bug

quando eu baixo e instalo o jogo não aparece o setup para eu poder instalar 

### Steps to Reproduce

apenas tente instalar o cuphead ou e so para mim

### Expected behavior

>:(

### Screenshots

>:(

### Operating System

Windows 10/Sistema operacional de 64 bits, processador baseado em x64

### Hydra Version

2.0.1 a mais recente

### Additional Information

>:(

**Comment by thegrannychaseroperation** [comment]
We do not support game related issues.
