### ISSUE TITLE
[BUG] (EN) bug 126 failed to load dll from the list. Hydra launcher (POR) erro 126 falha ao carregar a dll da lista

### ISSUE THREAD

**Issue by Chkotonio** [hydralauncher/hydra#715]
### Describe the bug

(POR) o jogo não inicia e diz que é erro de dll (EN)  The game won't start and says it's DLL error

### Steps to Reproduce

(POR) baixei o jogo, fui em iniciar e deu o erro (EN)  I downloaded the game, went to start and it gave the error

### Expected behavior

(POR) esperava que o jogo iniciasse normalmente (EN) I expected the game to start normally

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/169678049/421992b2-fa88-4559-a589-c32cbc344043)

### Operating System

Windows 10

### Hydra Version

2.0.1 "Levictus"

### Additional Information

(EN)the fix not work (POR) o fix não funciona

**Comment by thegrannychaseroperation** [comment]
We do not support game related issues.
