### ISSUE TITLE
[BUG] cant download

### ISSUE THREAD

**Issue by uperedu** [hydralauncher/hydra#716]
### Describe the bug

when i try to download any game in hydra they don't have the option of download, it just appear a message "sem downloads disponiveis"

### Steps to Reproduce

1- open hydra
2- open the game i want to download
3- can't download

### Expected behavior

i expected that i can click in a botton write download

### Operating System

windows10

### Hydra Version

2.0.1

**Comment by zamitto** [comment]
It is an expected behavior since 2.0
You need to add your own sources of download. You can join the a discord server managed by the community, they have tutorials for that. 
https://discord.gg/TSxymg7JTJ
