### ISSUE TITLE
[BUG] Aria2c is completely breaking downloads (Metadata Bug)

### ISSUE THREAD

**Issue by Xxxsusx** [hydralauncher/hydra#723]
### Describe the bug

What I'm trying to say is that Aria2c that is a program that is used for multiple downloads (I guess) is breaking all my Hydra downloads and I literally cannot install any games. This started happening after the launcher automatically updated to 2.0.1 which is the version that Aria2c is included in the program's files.

### Steps to Reproduce

1. Download any game
2. Go to Downloads List
3. It will say "Downloading Metadata" forever which is being caused by Aria2c.

### Expected behavior

It's supposed to download the game normally.

The reason I know the problem may be because of Aria2c, is because Aria2c does not support HashV2 Torrent Metadata and it only supports V1. Which makes like 90% on the games in the launcher not being able to download and only stuck on "downloading metadata" since it is trying to get a HashV2 Torrent Metadata. If possible, please, stop using Aria2c and try to find another program for multiple downloads. 

This is a message for the contributors and developers of Hydra and I would hope that this issue would reach the contributors and developers attention because I literally can't download any games which makes the program completely useless since it's a launcher for torrent games but I literally cannot download any of its games.

### Operating System

Windows 10

### Hydra Version

v2.0.1 "Leviticus" (Latest)

**Comment by thegrannychaseroperation** [comment]
Fixed in 2.0.2.
