### ISSUE TITLE
[BUG] I can't create an account

### ISSUE THREAD

**Issue by GuiltHC** [hydralauncher/hydra#725]
### Describe the bug

When I try to register an account, after confirming that I have saved the PIN code and clicking on the "Confirm" button, the PIN window closes, but nothing else happens. If you click "Create Account" again, it will open the same PIN window again and so on indefinitely. If I try to login with this information, I get an error message saying "Incorrect Username or Password".

### Steps to Reproduce

When I try to register an account, after confirming that I have saved the PIN code and clicking on the "Confirm" button, the PIN window closes, but nothing else happens. If you click "Create Account" again, it will open the same PIN window again and so on indefinitely. If I try to login with this information, I get an error message saying "Incorrect Username or Password".

### Expected behavior

I was expecting to receive confirmation and log in to my account

### Operating System

Windows 11

### Hydra Version

2.0.2

**Comment by xXKillSTrEAkXx** [comment]
Same issue here on Windows 10

**Comment by zamitto** [comment]
Usernames and displayName need to be at least 4 characters long.
We had some bugs that were not showing these information.
If you have any problems creating accounts even after double checking these requirements, join the community discord and ask for help there, it will be easier to aid your exact problem

**Comment by zamitto** [comment]
Closing issue as no response in a long time

**Comment by DefomCode** [comment]
I have exactly the same problem. Will there be no solution?
