### ISSUE TITLE
[BUG] Nenhum download disponível

### ISSUE THREAD

**Issue by LarissaAngioni** [hydralauncher/hydra#727]
### Describe the bug

Todos os jogos mostram "Sem downloads disponíveis". 
![image](https://github.com/hydralauncher/hydra/assets/55850170/7f8b5b49-d4e1-4df1-a74e-2f44641528b3)

### Steps to Reproduce

No launcher todo.

### Expected behavior

Possibilidades de fazer downloads.

### Operating System

Win 10

### Hydra Version

2.0.2

**Comment by JackEnx** [comment]
this is not a bug, look into the hydra community in discord, or hydra telegram (look in README)
