### ISSUE TITLE
[BUG] CAN'T DOWNLOAD NOTHING

### ISSUE THREAD

**Issue by K4yn1xZz** [hydralauncher/hydra#728]
### Describe the bug

i'm having troubles to download, 'cause the downloads aren't avaliable to me, i don't know if there's more people that are in this trouble too, but mine's not working. Even the games that i have already installed, do not work...

### Steps to Reproduce

1. Go into the app, and there it is, i just can't download nothing

### Expected behavior

i expected to download a game that im crazy for playing, "Charlie Murder" that i have already installed, but i couldn't download it

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/174157840/bfbfdbbc-af10-4beb-a991-391ec04d15ce)

### Operating System

Windows 11

### Hydra Version

2.0.2 "Leviticus"

### Additional Information

all that i had to tell is upstairs haha

**Comment by JackEnx** [comment]
read this issue: #697, maybe can help you
