### ISSUE TITLE
[BUG] Hydra runs fastlist.exe every second

### ISSUE THREAD

**Issue by kotenok2000** [hydralauncher/hydra#730]
### Describe the bug

Hydra runs fastlist.exe every second.

### Steps to Reproduce

Launch Hydra

### Expected behavior

Hydra doesn't run fastlist.exe every second.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/8822292/684b9ca3-54db-400b-9f2a-999569e4b869)

### Operating System

Windows 11

### Hydra Version

2.0.1

**Comment by JackEnx** [comment]
Could you specify how you want this to work? how could this be improved or how specifically should it behave?

**Comment by zamitto** [comment]
Why do you see this as a problem? 
Here is the source code of fastlist: https://github.com/MarkTiedemann/fastlist
We use it as a way to get the running process and count the playtime

**Comment by Kuzuru** [comment]
> Could you specify how you want this to work? how could this be improved or how specifically should it behave?

There is probably a way to get the process time via system signals when the process is finished. It would also be a good alternative to disable game time tracking ( `fastlist` ) in the user client

**Comment by zamitto** [comment]
If what you say is a real possibility, definitely looks like a great improvement
Could you elaborate how to do this?
To see how it currently works, check `process-watcher.ts`

**Comment by zamitto** [comment]
Even if we don't actually see any problem with the current implementation

**Comment by zamitto** [comment]
PS: fastlist has been replaced by psutil (https://github.com/giampaolo/psutil) on 2.0.3
