### ISSUE TITLE
No access to download options [BUG] 

### ISSUE THREAD

**Issue by Sadakosk** [hydralauncher/hydra#738]
### Describe the bug

I can't access the options to download the games
That happens with any game

### Expected behavior

I would like to see the download options

### Screenshots

![Imagem do WhatsApp de 2024-06-29 à(s) 14 33 32_c979e160](https://github.com/hydralauncher/hydra/assets/168938288/0c9b913f-d049-444f-992c-992a85591422)

### Operating System

Windows 11

### Hydra Version

v2.0.2

**Comment by Maiqueel** [comment]
add download fonts at https://hydralinks.cloud

**Comment by zamitto** [comment]
@Sadakosk it is an expected behaviour. Since 2.0 you need to add download sources by yourself.
