### ISSUE TITLE
[BUG] Log In error

### ISSUE THREAD

**Issue by SaymonMaster14** [hydralauncher/hydra#741]
### Describe the bug

Just updated to the new 2.0.2 version and my account logged off, tried log in back again and the program said my username or password was incorrect, tried recovering with the pin, it said again the username was incorrect.

Game hours still the same, but I'm afraid that creating a new account will wipe the hours I have in the games

### Steps to Reproduce

Try log in

### Expected behavior

To be logged in

### Operating System

Windows

### Hydra Version

2.0.2

**Comment by zamitto** [comment]
Username is currently case sensitive (we will solve this soon). double check if every letter has the correct case

**Comment by SaymonMaster14** [comment]
Ok, thank you


Em sáb., 29 de jun. de 2024 às 18:05, Zamitto ***@***.***>
escreveu:

**Comment by SaymonMaster14** [comment]
I checked the case, tried to recover the password, and now it says the pin
is incorrect

Em sáb., 29 de jun. de 2024 às 18:05, Zamitto ***@***.***>
escreveu:

**Comment by zamitto** [comment]
@SaymonMaster14 sorry I took so long to see your reply. Are you still having problems logging in?

**Comment by SaymonMaster14** [comment]
bro you took so long that my GPU died and I don't play in the PC anymore 🤣
