### ISSUE TITLE
[BUG]  Downloaded 0%

### ISSUE THREAD

**Issue by MelloXT** [hydralauncher/hydra#742]
### Describe the bug

Nao consegui

### Steps to Reproduce

nao consigo baixar

### Expected behavior

Nao consigo baixar

### Screenshots

![Captura de tela 2024-06-23 082044](https://github.com/hydralauncher/hydra/assets/173607687/e21a5662-5958-41f3-b922-107466a1179b)

### Operating System

Windowns 10

### Hydra Version

2.0.2 and 2.0.1

**Comment by zamitto** [comment]
Did you try with other games from your sources?

**Comment by Xxxsusx** [comment]
Isso deve ser causado pelo torrent (arquivo de instalação). Você por acaso já fechou (completamente) o Hydra e abriu depois de baixar a nova versão? Na v2.0.2 esse bug do Metadata 0% já foi consertado e eu também estava com problemas mas isso foi na v2.0.1

Então há dois casos aqui que podem estar acontecendo, você acabou de atualizar o Hydra v2.0.1 pro v2.0.2 ou o arquivo desse jogo nessa fonte de Download está muito lento pra ser acessado/instalado.

Já tentou pausar e resumir o download? Se não, tente. Se nada for resolvido ainda, tente baixar outro jogo e veja se isso ocorre em outros jogos também. Se isso também ocorrer em outros jogos, cancele o download, reinicie o sistema, abra o Hydra e inicie o download de novo para ver se resolveu o problema.

Se você fez todas as opções e ainda não resolveu, eu recomendaria fechar o Hydra completamente, desinstalar ele e instalar. (Sua biblioteca vai voltar quando você fazer login na conta mas você provavelmente terá que localizar os arquivos .exe dos jogos pra jogar eles)

**Comment by CaioK367** [comment]
I having this issue on the 2.0.2 version

**Comment by GabrielFerraz** [comment]
Estou tendo o mesmo problema. Instalei a versão 2.0.2 e tentei baixar e não consegui. Tentei fazer download de várias fontes diferentes e não funcionou. Tentei até baixar o jogo Gris, que eu tinha baixado na 1.2.4, em todas as fontes e ainda assim ficou preso em 0%.

**Comment by zamitto** [comment]
Real Debrid or Torrent?

**Comment by GabrielFerraz** [comment]
Torrent

**Comment by MIPRUS123456** [comment]
Have you solved the problem?

**Comment by JackEnx** [comment]
long time without response, if the problem persists, open the issue again
