### ISSUE TITLE
[BUG] Can't download games

### ISSUE THREAD

**Issue by glitch65** [hydralauncher/hydra#744]
### Describe the bug

Can't download games. No download button

### Steps to Reproduce

1. Open hydra
2. Select game

### Expected behavior

download game

### Screenshots

![Hydra_LeJtdt8w7i](https://github.com/hydralauncher/hydra/assets/94213385/56ac1851-4d63-45f1-8744-6afeb61f58f6)

![image](https://github.com/hydralauncher/hydra/assets/94213385/24a68057-5a52-47fd-9a80-4a1f6ab42740)

### Operating System

Windows 11

### Hydra Version

v2.0.2

**Comment by AnmiTaliDev** [comment]
I have the same:(

**Comment by Maor-Ar** [comment]
I have the same issue I used the [hydralauncher-2.0.2-setup.exe] file (https://github.com/hydralauncher/hydra/releases/download/v2.0.2/hydralauncher-2.0.2-setup.exe)
To install Hydra I got the same behavior.

Please help )':

**Comment by Maor-Ar** [comment]
Found out the solution for the issue,
You need to install the sources of the games
you can find everything you are looking for here:
https://hydralinks.cloud/
