### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Gamse12** [hydralauncher/hydra#745]
### Describe the bug

no downloads available in all games

### Steps to Reproduce

no way

### Expected behavior

no way

### Screenshots

![Снимок экрана 2024-06-30 223925](https://github.com/hydralauncher/hydra/assets/166207313/f00da236-a6a1-4e79-9eaa-40fce6f3dff1)

### Operating System

windows 11

### Hydra Version

2.0.2

**Comment by zamitto** [comment]
Expected behavior, since 2.0 you need to add sources by yourself.
You can find help in the Discord server managed by the community https://discord.gg/TSxymg7JTJ
