### ISSUE TITLE
[BUG] No downloads available

### ISSUE THREAD

**Issue by fesper-s** [hydralauncher/hydra#746]
### Describe the bug

I dowloaded `hydralauncher_2.0.2_amd64.deb` and I can't dowload any game. It says "No downloads available"

### Steps to Reproduce

I downloaded `.deb` package at my Pop!_OS (Ubuntu based). Installed it and no downloads available..

### Expected behavior

When I dowloaded it on windows 11 it worked.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/67757208/4ed9afe9-d023-408b-90f8-fcb5656b9828)

### Operating System

Pop!_OS 22.04 (Ubuntu based)

### Hydra Version

2.0.2

**Comment by Xxxsusx** [comment]
https://github.com/hydralauncher/hydra/issues/697
