### ISSUE TITLE
[BUG] ao iniciar com o windows o duplo clique nao funciona

### ISSUE THREAD

**Issue by rybandz** [hydralauncher/hydra#749]
### Describe the bug

Ao iniciar o Windows, o Hydra é executado em segundo plano e aparece na lista de programas em segundo plano. Mas pra abrir o Hydra, é necessário clicar com o botão direito do mouse e selecionar "Abrir". O duplo clique não funciona para abrir o programa inicialmente; só é possível abri-lo dessa forma depois de tê-lo aberto uma vez com o botão direito.

### Steps to Reproduce

iniciar o windows, lista de programas segundo plano, duplo clique

### Expected behavior

acredito que seja um bug pq apos a primeira vez de abrir ele o duplo clique funciona nele atraves dos programas em segundo plano

### Operating System

Windows 11

### Hydra Version

2.0.2

**Comment by JackEnx** [comment]
Thanks for the reporter, we detected this behavior and we are working on a fix
