### ISSUE TITLE
[BUG] Download Freezing

### ISSUE THREAD

**Issue by Luscaverd** [hydralauncher/hydra#750]
### Describe the bug

Hello, i was using Hydra 2.0.2, and i got a really strange issue involving download, so, i was downloading Easy Red 2, i tried almost all the download options, and all of them was frozen on "Downloading Metadata", there is one of the options that actually works, and when im downloading, specifically on 4,04% of download counting, just freeze, and say "Calculating remaining time" the internet over here is good, downloading 40-50 Mbps, however, during dowloading Easy Red 2, firstly was on 1-2 Mbps, then reaching on 4,04% it was droping very quickly, soon got on 1 B/s, and the download would take 123 years to be done, then the message of calculating time appeared and dont get away.

### Steps to Reproduce

1- Search for Easy Red 2
2- Select the first DODI Repacks download option
3- Wait download until 4,04%
4- Error on download freezing (this may dont happen to someone also, maybe this problem happens only to me)

### Expected behavior

I expected the download started at "Downloading MetaData" for a while and then the download works well after that, but it always freezed

### Screenshots

![Captura de tela 2024-07-01 004237](https://github.com/hydralauncher/hydra/assets/174293595/67185d7a-d5fc-41de-bdba-ec22c10ab711)

### Operating System

Windows 11

### Hydra Version

2.0.2

### Additional Information

The first time that this problem happened to Easy Red it froze on 17,21%, now it stops at 4,04%

**Comment by Xxxsusx** [comment]
Either it's the torrent with lack of seeds or it is your network connection. Try downloading any other game (completely) and see if it everything goes on normally. If it does, then the problem is the torrent with Easy Red II

**Comment by JackEnx** [comment]
hydra uses a torrent system, so your internet speed is not the main factor for the download rate, this information is in the project's README itself, your case does not seem to be a problem with the hydra download system itself.

![image](https://github.com/hydralauncher/hydra/assets/167036558/a6593e6b-3f86-4566-96be-7a9299ca3b60)

if you want to know more about bittorrent protocol: https://en.wikipedia.org/wiki/BitTorrent
