### ISSUE TITLE
[BUG] No downloads available

### ISSUE THREAD

**Issue by SystemFalse** [hydralauncher/hydra#751]
### Describe the bug

I downloaded hydralauncher-2.0.2-setup.exe from releases and installed launcher (I have never installed Hydra on my PC before). After this I opened launcher and created new account. After that, "No downloads available" is written for all games.

### Steps to Reproduce

1. Download hydralauncher-2.0.2-setup.exe and run it
2. Create new account

### Expected behavior

It doesn't look like there aren't downloads for absolutely all games.

### Screenshots

![no downloads available (1)](https://github.com/hydralauncher/hydra/assets/91965802/f933962a-9c51-4650-8cec-667382055f78)
![no downloads available (2)](https://github.com/hydralauncher/hydra/assets/91965802/5b891017-5aac-48ba-a313-e79a6cb876ae)

### Operating System

Windows 10

### Hydra Version

2.0.2 "Leviticus"

**Comment by lukasd2010** [comment]
you gotta add the sources yourself using this
https://hydralinks.cloud/
