### ISSUE TITLE
[BUG] I can't download anything

### ISSUE THREAD

**Issue by xkjhon** [hydralauncher/hydra#753]
### Describe the bug

After updating to version 2.0 there is no way to download the games.

### Steps to Reproduce

1. 1. Open Hydra
2. Enter any game

### Expected behavior

A button should appear to find a list of Sources for Downloading Games.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/174385200/c83a6e32-ec10-4307-8387-8eefd32827df)
![image](https://github.com/hydralauncher/hydra/assets/174385200/a2d5a823-4420-403b-b362-efd35d9e9965)

### Operating System

Windows 11

### Hydra Version

v. 2.0.2

**Comment by JackEnx** [comment]
You will find information about this here: #697
