### ISSUE TITLE
[REQUEST] Add profile background images

### ISSUE THREAD

**Issue by LeandroV12** [hydralauncher/hydra#757]
### Is your feature request related to a problem? Please describe.

No exactly, but it would be cool to put some scene underneath to make it more fun and interesting.

### Describe the solution you'd like

There may be the option to place an image or give one to set the profile background as shown in this image.

![imagem_2024-07-02_174519569](https://github.com/hydralauncher/hydra/assets/149306476/723491b5-82fb-406c-b089-3fe221d926c3)

To simplify, put an image under my profile photo and where it says leave profile, in the black bar

**Comment by JackEnx** [comment]
implemented in update 3.0.
