### ISSUE TITLE
No Download Available

### ISSUE THREAD

**Issue by gbdacoolkid** [hydralauncher/hydra#758]
### Describe the bug

whenever I open Hydra I can't download any file because there is no download available.
![Captura de Ecrã (4)](https://github.com/hydralauncher/hydra/assets/174490291/d0efe77b-c311-4311-b9a2-76e454ad8421)

### Steps to Reproduce

![Captura de Ecrã (4)](https://github.com/hydralauncher/hydra/assets/174490291/bb49a8b5-8d84-446d-87f5-ead0b8134def)

### Expected behavior

There were supposed to be downloads available, but there aren't

### Screenshots

![Captura de Ecrã (4)](https://github.com/hydralauncher/hydra/assets/174490291/f860213b-90ad-43f8-845f-22b78cdd0c22)

### Operating System

Windows 10

### Hydra Version

v2.0.2 "Leviticus"

**Comment by korex71** [comment]
To temporarily resolve the issue, install version 1.2.4. It will automatically update to 2.0.2, so it will work...

**Comment by T3SL4A** [comment]
my friend is having the same problem, we've tried to install older versions but still didnt work... let me know if u find a way to fix it

**Comment by JackEnx** [comment]
this not a problem, read this issue #697

**Comment by kakodiel** [comment]
baixei a versão 1.2.4 e atualizei para 2.0.2, não funcionou para mim

**Comment by JackEnx** [comment]
> To temporarily resolve the issue, install version 1.2.4. It will automatically update to 2.0.2, so it will work...

Please, if you are not sure about the problem, do not have any wild ideas, it may corrupt local data
