### ISSUE TITLE
[HELP FOR COMMUNITY] put json files of download sources into this thread

### ISSUE THREAD

**Issue by Spacyaa** [hydralauncher/hydra#759]
### Is your feature request related to a problem? Please describe.

not

### Describe the solution you'd like

not

### Additional context

Please upload these links here to help other users who need more repacks

**Comment by KoTle7a** [comment]
[атфа.txt](https://github.com/user-attachments/files/16560074/default.txt)

**Comment by KoTle7a** [comment]
[ата.json](https://github.com/user-attachments/files/16560081/default.json)
