### ISSUE TITLE
[BUG] no downloads 

### ISSUE THREAD

**Issue by DianPSilva** [hydralauncher/hydra#770]
### Describe the bug

don´t have downloads my hydra 

### Steps to Reproduce

don´t have downloads my hydra 

### Expected behavior

don´t have downloads my hydra 

### Screenshots

![imagem_2024-07-03_215105326](https://github.com/hydralauncher/hydra/assets/126826651/b346c056-51b7-4983-a12b-face8d451be7)

### Operating System

windows 11

### Hydra Version

2.0.2

**Comment by raddy21** [comment]
you must have the sourde link for the download and past the links to hydra launcer https://hydralinks.cloud/
