### ISSUE TITLE
stuck metadata 0%

### ISSUE THREAD

**Issue by raddy21** [hydralauncher/hydra#771]
### Describe the bug

![Hydra 04_07_2024 02_53_23](https://github.com/hydralauncher/hydra/assets/174665941/622544f7-9f55-43ec-a1f5-23216852165d)

### Steps to Reproduce

1. i go to the site link of hydra community
2. i choose the game that have to install
3. stuck at 0% for metadati downloading

### Expected behavior

i don't know, i hope this is only  a bug

### Operating System

windows 11

### Hydra Version

2.0.2

**Comment by raddy21** [comment]
pls answer me

**Comment by fanzzxyx21** [comment]
Hello, you need to delete all the downloaded game files from that game, then you need to remove it from library and start do download again. If its not working just choose another source.

**Comment by TristisOris** [comment]
That happens for a long time before download begins.
I add same torrent to usual client at same time, and got peers instantly.
![image](https://github.com/hydralauncher/hydra/assets/1270117/57e2716e-c870-4cc5-9d70-afe8519c91cc)
