### ISSUE TITLE
[BUG] долгая загрузка

### ISSUE THREAD

**Issue by Zoma746** [hydralauncher/hydra#774]
### Describe the bug

мой интернет 3 мегабайта, но во время скачивания интернет ловит 13 килобайт

### Steps to Reproduce

1. Стал скачивать
2. медленно скачивал игру
3. проверял и больше 16 к/с не грузило

### Expected behavior

ожидал загрузку в мегабайт в секунду

### Operating System

windows 10

### Hydra Version

2.0.2

### Additional Information

скачивал с помощью торрента было также как с wi-fi

**Comment by fanzzxyx21** [comment]
Hello, u can fix it by buying real debrid for 30 days. Its an app that allows u download games with the highest speed of your internet. If you by it you need to go to setting in hydra launcher and press the API token link "here''. Copy the code and past it to hydra.

**Comment by nikita999-cyber** [comment]
> Hello, u can fix it by buying real debrid for 30 days. Its an app that allows u download games with the highest speed of your internet. If you by it you need to go to setting in hydra launcher and press the API token link "here''. Copy the code and past it to hydra.
why the fuck should we pay for normal loading, fucking idiot

**Comment by zamitto** [comment]
This is a closed issue, but just to clarify
We do have RD integrated, but they are not absolutely optional
In 3.1.0 we have reworked downloads, they should be more stable and with better speed overall
But remember that specially torrent downloads depends on other things, (seeds, peers, etc) and even direct download depends on  server distance, etc
We use a well know library for torrents: libtorrent. The same used by qBitTorrent. If you are experiencing significant different download speeds for the same torrent, at the same time when comparing Hydra and other torrent client, please, let us know and send us as much info as you can get
For direct (http) downloads, we use aria2, another well know program. If something is not stable, let us know as well

**Comment by nikita999-cyber** [comment]
> This is a closed issue, but just to clarify We do have RD integrated, but it is absolutely optional In 3.1.0 we have reworked downloads, they should be more stable and with better speed overall But remember that specially torrent downloads depends on other things, (seeds, peers, etc) and even direct download depends on server distance, etc We use a well know library for torrents: libtorrent. The same used by qBitTorrent. If you are experiencing significant different download speeds for the same torrent, at the same time when comparing Hydra and other torrent client, please, let us know and send us as much info as you can get For direct (http) downloads, we use aria2, another well know program. If something is not stable, let us know as well
there is byxatab website where loading is thousands of times faster without peers
