### ISSUE TITLE
No installation paths[BUG] 

### ISSUE THREAD

**Issue by MaruDE100S** [hydralauncher/hydra#775]
### Describe the bug

I encountered a problem where I couldn't log into the app. I "deleted" the files and reinstalled the app, and it worked—I can now log in. However, I don't have any games available for download; it says there are no installation paths.

### Steps to Reproduce

I tried both the Portable and Setup versions, but nothing changed. I can log into the app, but it just shows that there are no installation paths for any game.

### Expected behavior

Download games again

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/174747747/87205760-ab51-4248-8522-e03e9d1b177f)

### Operating System

Win 10 pro

### Hydra Version

ojk6mExQ - 2.0.2 "Leviticus"

**Comment by MaruDE100S** [comment]
And a button Random game is not working.

**Comment by GR3go240Hz** [comment]
I have the same problem

**Comment by nowt46** [comment]
Same has happend to me, maybe they dont have the cloud option right now to save users accounts games...maybe its temporary but i dont have idea

**Comment by zamitto** [comment]
As stated in a lot of other issues:
This is not a bug, you just need to add download sources so you can have downloads available
