### ISSUE TITLE
Launcher doesn't open [BUG] 

### ISSUE THREAD

**Issue by vicky-vaporub** [hydralauncher/hydra#777]
### Describe the bug

i have windows 11 on my pc and tried downloading both Setup and Portable versions of hydra, but none of them seems to work, when i try to open the app nothing happens, my mouse shows the loading icon, but Hydra doesn't open even when i run as adm

### Steps to Reproduce

1. Start Windows
2. Double click or press enter on Hydra
3. Fail

### Expected behavior

Hydra Opens

### Operating System

Windows 11

### Hydra Version

2.0.2

**Comment by zamitto** [comment]
Is it the first time you tried to install/use Hydra?

Could you also see if Hydra generated any logs and upload them here? They are located in `%appdata%/hydra`

**Comment by zamitto** [comment]
Closing issue as no response in a long time.
If this error still happens in 2.1.7, feel free to open a new issue
