### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Shinori09** [hydralauncher/hydra#779]
### Describe the bug

There is no way to download anything since there are no downloads, In all cases it appears that there is no download available.
![Hydra 04_07_2024 23_18_59](https://github.com/hydralauncher/hydra/assets/107774231/821df462-1c17-4e8b-adab-e6e9ba7018c4)

### Steps to Reproduce

...

### Expected behavior

well, hydra already comes with the bug as soon as it released 2.0.2, it doesn't show any more downloads available just this bug... I already deleted it from the pc at the root and everything, I already downloaded an old version of it and updated it to See if it worked, I've already updated my drives, I've restarted my PC... I did everything and nothing was resolved

### Screenshots

![Hydra 04_07_2024 23_18_59](https://github.com/hydralauncher/hydra/assets/107774231/76dc5264-665e-445f-9946-8a4b8cec06fb)

### Operating System

windows 10

### Hydra Version

2.0.2

**Comment by zamitto** [comment]
It is not a bug. It is an expected behaviour. Since 2.0 you add download sources by yourself.
You can join the community discord server, they have made tutorials for that
https://discord.gg/TSxymg7JTJ
