### ISSUE TITLE
Backup and Restore with Local and Cloud Options

### ISSUE THREAD

**Issue by caduHD4** [hydralauncher/hydra#78]
**I saw that some people are wanting a login option to save the game list, I believe you can do this without directly logging in with a Hydra account. In the settings there could be a Beckup option, where there would be a button to do a backup and next to it a key to do the backup automatically or not, and a button to restore the backup.**

In short: It would be an option that would have backup locally and in the cloud (optional) through the user's Google Drive and the local database, that is, the user would click to do a backup and choose whether they want it local (generate a .zip) or cloud (google drive), if it were through the cloud he would log in with his google account without being linked to any third party server other than google itself, so hydra would create a backup folder in google drive with the .zip, and if the user If he needed to format the PC he could simply log in and restore the backup.

- It also wouldn't need to be Google Drive, any other form of online storage, or just use the idea of local backup with .zip for the user to save on a pendrive for example.

- Then Hydra wouldn't store any user data on an external server, but rather, the user storing their own data in their own private cloud. 😎 It would be a bit more work than local backup, but there's the idea.

- The backup would only be updated when the user removes or adds a game to the launcher. (Or every 3 hours, for example)

![Captura de tela 2024-04-24 105234](https://github.com/hydralauncher/hydra/assets/69264602/b50241e0-1770-4589-9ad3-e11662e96a8b)

**Comment by zamitto** [comment]
I might be wrong, but I think that we'd need an API key for the Google Drive solution. We'd need to authenticate to Google to auto upload the backup.

**Comment by caduHD4** [comment]
@zamitto Yes, I would need the API Key to log in, but I could only think of it this way so that it wouldn't be necessary for hydra to store user data. 

Do you have another suggestion on how this can be done without a database with user logins?

**Comment by scrlkx** [comment]
We could just have a Export/Import feature that uses a managed format to move stuff around (including user settings and game list). How it will be stored or shared it's users business.

**Comment by zamitto** [comment]
We actually implemented it in v2.0

**Comment by perigozin** [comment]
> We actually implemented it in v2.0

Can't see it implemented anywhere. Where can I save a local backup copy of all the games and achievements? This project seems like a cash grab. Also why can't achievements be used without an account? I understand you charging for the "cloud" feature (which is already sketchy since you're making money based on piracy) but as an open source project why isn't there an option to use all the features offline? I don't need a stupid account or stupid cloud storage.
