### ISSUE TITLE
[BUG]  Problema nas fontes de todos os games.

### ISSUE THREAD

**Issue by AvilaLima** [hydralauncher/hydra#781]
### Describe the bug

Não encontro mais nenhuma fonte de nenhum jogo disponível, independente se uso a busca ou não

![image](https://github.com/hydralauncher/hydra/assets/29666613/aa75bae1-2616-4cdc-af8a-fa56c2e1517c)

### Steps to Reproduce

Ao abrir e clicar em catálogo.

### Expected behavior

Outros amigos com a mesma versão me falam que encontrar opções para download:

meu hydra:
![image](https://github.com/hydralauncher/hydra/assets/29666613/6288751b-e8c1-4669-8e01-04199235bcfa)

meu amigo:

![image](https://github.com/hydralauncher/hydra/assets/29666613/571b8a74-49cf-46cf-9b03-769a67c49c0f)

### Operating System

Win 11

### Hydra Version

2.0.2

**Comment by fanzzxyx21** [comment]
Hello, from the version 2 in hydra launcher you need to add sources by urself. Its not hard just go to https://hydralinks.cloud and download sources you need (i recommend to download every source cuz many games dont have the same download source)
