### ISSUE TITLE
[BUG] Game Search with wrong results

### ISSUE THREAD

**Issue by japolete** [hydralauncher/hydra#782]
### Describe the bug

As I search for a remake, the  client returns  with links for the original game despite showing me two separate games (2008 and 2023). 

### Steps to Reproduce

-Search for "Dead Space" 
- See multiple entries for 1, 2, 3 and  Remake
- Click Remake
- Check sources
- See that all the games are about the first edition (2008)

### Expected behavior

Expected the 2023 version of the game as a separate entry,.

### Operating System

Windows 11 and Arch Linux

### Hydra Version

2.0.2

**Comment by zamitto** [comment]
We implemented game search in our backend, it will be much more flexible now and these problems should not happen anymore
