### ISSUE TITLE
TROJAN DETECTADO EM UM JOGO 

### ISSUE THREAD

**Issue by mateso0803** [hydralauncher/hydra#784]
### Describe the bug

Baixei o jogo "No Time To Relax" pelo Hydra no OnlineFix e depois de extrair o jogo fui tentar entrar e meu antivírus detectou Trojan no arquivo, acredito que seja algum problema no link do OnlineFix, mas por favor arrumar rápido.

### Steps to Reproduce

Se você baixar e extrair o jogo, como sempre, na hora de entrar no arquivo do mesmo irá dar a notificação

### Expected behavior

Esperava apenas entrar no jogo como sempre, mas me surpreendi com a notificação de vírus

### Operating System

Windows 11

### Hydra Version

2.0.2

**Comment by thegrannychaseroperation** [comment]
WE DO NOT GIVE ANY SUPPORT FOR GAMES OR EXTERNAL SOURCES THAT YOU LINK WITH YOUR HYDRA. PLEASE DO NOT OPEN ISSUES THAT WE CANNOT DO ANYTHING ABOUT IT.
