### ISSUE TITLE
[REQUEST] Adicionar fontes manualmente

### ISSUE THREAD

**Issue by rybandz** [hydralauncher/hydra#785]
### Is your feature request related to a problem? Please describe.

A proposta do hydra parecia ser tornar tudo mais pratico, principalmente pra quem nao tem costume de jogar os jogos por outras fontes fora da steam, tem pessoas que mal sabem instalar um jogo e acho que o novo metodo de adicionar manualmente fontes acaba tornando a plataforma mt menos cômoda, pra mim é totalmente de boa. Mas to falando na perspectiva de mts usuarios, vi que tao fazendo ate videos pra ensinar oq deve ser feito e mts pessoas buscando ajuda sobre nao ter download disponivel; 

Eu ja tinha lido alguem relatando no telegram que haviam deixado mais difícil de utilizar o hydra, acho que dessa forma acaba tornando a plataforma menos pratica e menos atrativa

### Describe the solution you'd like

Se conseguiram voltar pro modelo antigo de adicionar as fontes automaticamente deixaria a plataforma mt melhor

**Comment by blkzy** [comment]
in English please.

**Comment by JackEnx** [comment]
In both cases, manual or automatic, people complain about something (there were a lot more complaints in the old way), the current way has the problem of breaking the application's behavior, but in the long run it is much better.

**Comment by nightmareghosthell** [comment]
Disagree, it became impossible to use if you don't know hwo to use properly, the moment you have to spend hours on youtube to try and make sense of how things work means you stop bothering to make your product be easier for use, the idea is quite nice but I just wanted to check some old games and a friend said here is "easier", dam freaking lie, here is way harder, I was expecting to come and just try some old games, but nope, seems you guys made impossible for me to just do that, sadly I decided to just give up, I already have to much stuff to do to have to learn to configure this :/ really sad you all dont care with the people using yoru product, if you gonna downgrade why dont even share, really disapointed.
