### ISSUE TITLE
[BUG]  Why is there no download button, only the play button, but there is no game and nothing starts.

### ISSUE THREAD

**Issue by nolihetzz** [hydralauncher/hydra#786]
### Describe the bug

Why is there no download button, only the play button, but there is no game and nothing starts.

### Steps to Reproduce

there is no download button

### Expected behavior

the download button

### Screenshots

![Hydra 05 07 2024 22_29_23](https://github.com/hydralauncher/hydra/assets/174832484/b4e00525-5cb4-4d24-9d85-8f3f5e3a29c5)

### Operating System

windows 11

### Hydra Version

hydra 2.0.3

### Additional Information

Why is there no download button, only the play button, but there is no game and nothing starts.

**Comment by nolihetzz** [comment]
this is another screenshot 
![Hydra 05 07 2024 22_29_12](https://github.com/hydralauncher/hydra/assets/174832484/353818a3-bb34-4351-8239-ab80a8cd0e6e)

**Comment by gamingeveryday** [comment]
can you do a screenshot in english?

**Comment by nolihetzz** [comment]
ok

**Comment by nolihetzz** [comment]
![Uploading Hydra 06.07.2024 0_19_29.png…]()

**Comment by nolihetzz** [comment]
![Hydra 06 07 2024 0_19_29](https://github.com/hydralauncher/hydra/assets/174832484/1b10edad-649a-468b-b926-1897b5d1a669)

**Comment by zamitto** [comment]
Have you added your Download Sources? You need to add them by yourself since v2.0
Join the community discord (https://discord.gg/TSxymg7JTJ) they have tutorials for that
