### ISSUE TITLE
[BUG] HLTB stat not loaded if no downloads available

### ISSUE THREAD

**Issue by TristisOris** [hydralauncher/hydra#789]
### Describe the bug

if no any repacks availabe, HLTB block flash for a sec then dissapear.
On site info exist for this games.

### Steps to Reproduce

open any game without avalable downloads.

### Expected behavior

show HLTB no matter why.

### Screenshots

![Animation](https://github.com/hydralauncher/hydra/assets/1270117/77bfd9bf-3e6d-41cf-b4b3-19cb86955489)

### Operating System

win11

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
I tested with games that I had no download source and they loaded HLTB correctly.
It seems that `Trials of Argolis` is not available on HLTB.

We might rethink how this pages shows the content when it is in the load state, so this does not mislead someone again

![image](https://github.com/hydralauncher/hydra/assets/167933696/7d9204cc-897d-4c47-a218-7a899134b50f)

**Comment by TristisOris** [comment]
damn. i'm sure i got search result before reporting( But it really not exist. my bad.
