### ISSUE TITLE
[BUG]  Only 1 download possible for each game

### ISSUE THREAD

**Issue by TristisOris** [hydralauncher/hydra#790]
### Describe the bug

i choose some repack, but it has no seeders or something else, so download not happens.
i can't choose another download because button is locked.
Maybe another repack have some seeders, i don't care which one will succeed.

### Steps to Reproduce

above.

### Expected behavior

above.

### Screenshots

![hydra_01](https://github.com/hydralauncher/hydra/assets/1270117/5bc16e5e-315e-460f-a8b5-c7b3ba66e8e9)

### Operating System

win11

### Hydra Version

2.0.3

**Comment by JackEnx** [comment]
cancel the current one and then download a new one, this is not a bug
