### ISSUE TITLE
[HELP] Cant find sources

### ISSUE THREAD

**Issue by logan0888** [hydralauncher/hydra#794]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I cant find where to get the sources to add to the launcher and when i clicked the discord link it said that it had expired.

**Comment by Eduardo4815162342** [comment]
Hi, it works for me: 
Go to https://hydralinks.cloud/
copy to clipboard all the sources and in Settings > Download Source, import all the files from hydra website
