### ISSUE TITLE
[BUG] Some Games request archive password

### ISSUE THREAD

**Issue by KovalskiSDK** [hydralauncher/hydra#796]
### Describe the bug

When downloading some games and trying to install them - asks for the password from the Archive.

### Steps to Reproduce

Example: Content Warning
RePack master: onlinefix

### Expected behavior

Some frame with page or parse password informations from repacker resuource
Or copy password in descriptions about game 
like "online-fix.pro"
![изображение](https://github.com/hydralauncher/hydra/assets/158568164/5ecae85a-332e-47a8-9ace-ba50e338f741)

### Screenshots

![изображение](https://github.com/hydralauncher/hydra/assets/158568164/c820a469-7e12-4702-b79a-6801e3e9a8a8)

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by NGame1** [comment]
I had the same problem with bodycam
this password worked for me: ```online-fix.me```
