### ISSUE TITLE
[REQUEST] Filter catalogue games by having download options or not

### ISSUE THREAD

**Issue by discollizard** [hydralauncher/hydra#797]
### Is your feature request related to a problem? Please describe.

Having to browse games, but having games that don't have download options showing up.

### Describe the solution you'd like

Some toggleable control that only shows catalogue games that do have download options.

**Comment by Kirihan** [comment]
+1

**Comment by zamitto** [comment]
It is a planned feature

**Comment by MilesFarber** [comment]
This, absolutely this, same thing with the Home page. I have over 10000 download links in my list and half of the Home page is games that have no download options.

**Comment by zamitto** [comment]
Done in 3.1.0
