### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by felipemartins346** [hydralauncher/hydra#801]
### Describe the bug

Ao usar o Real-Bird mesmo pago, download não cria o intalador, só por torrent

### Steps to Reproduce

Ativar o real-bird e baixar

### Expected behavior

Download mais rápido e criar o instalador

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/22746947/b83c722e-8f7a-4d16-bdbe-15ebbebf85df)

### Operating System

win 11

### Hydra Version

v2.0.3 Leviticus

**Comment by felipemartins346** [comment]
Ao aplicar o download seja pelo  real-debrid, ele não cria o instalador do jogo, quando seleciono via torrent ele cria o instalador na pasta do hydra. 

Pelo real-debridele geraria um link para baixar o zip mas, não está indo para lá

**Comment by JackEnx** [comment]
please try to explain again, but this time review what you are saying, your explanation is extremely confusing.

**Comment by zamitto** [comment]
Closing issue as no response in a long time.
