### ISSUE TITLE
[BUG] NO DOWNLOADS AVALIABLE

### ISSUE THREAD

**Issue by Andersocaeag** [hydralauncher/hydra#803]
### Describe the bug

Eu ja usei esse app antes, mas por algum motivo agora, não aparece NENHUMA forma de Download de NENHUM jogo

![image](https://github.com/hydralauncher/hydra/assets/59018905/04c9306e-1f25-4c2f-8a8e-4e8c96127549)

### Steps to Reproduce

Não tem passo a passo, é literalmente só abrir o hydra e vê que não tem downloads

### Expected behavior

Aparecer downloads disponíveis para os jogos

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/59018905/62bbc670-b6bd-49d9-b656-9795282de661)

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by JackEnx** [comment]
https://hydra-launcher.gitbook.io/hydra
