### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VovaBenzin** [hydralauncher/hydra#804]
### Describe the bug

whole games just dont have repacks where i can install it and says there is 0 instalation of every game,every game page says no downoalding available

### Steps to Reproduce

on every page i see thats theres no downoalding available

### Expected behavior

ive just wanted to install smth

### Screenshots

![изображение_2024-07-08_233043787](https://github.com/hydralauncher/hydra/assets/175056449/c5516ab5-7170-4850-a345-74539b1d9954)

### Operating System

windows11

### Hydra Version

2.0.3

**Comment by JackEnx** [comment]
https://hydra-launcher.gitbook.io/hydra

you can find sources in the closed issues
