### ISSUE TITLE
download button doesn't exist in the new version

### ISSUE THREAD

**Issue by KameXcode** [hydralauncher/hydra#805]
### Describe the bug

my friend downloaded hydra and the download button doesn't appear in any game, i thought that the problem was in his pc, but today i reboot my hd and i downloaded the new version of hydra, and now i'm with the same bug. Where can i find old hydra's version ?. (yes i added the downloads sources) 

![image](https://github.com/hydralauncher/hydra/assets/140350276/4d73ae82-a148-423f-8d94-d27e4974beb8)

### Steps to Reproduce

a

### Expected behavior

a

### Screenshots

a

### Operating System

Windows

### Hydra Version

latest 2.0.3

**Comment by zamitto** [comment]
Please, next time, be as detailed as possible.

Which download sources did you add? Please, send a screenshot of the Download sources tab like the following:
![image](https://github.com/hydralauncher/hydra/assets/167933696/8f9a5a91-900a-4af2-8653-848063aae5fd)

**Comment by contttttt** [comment]
tengo exactamente el mismo problema, no se que hacer, la ultima vez que descargue el launcher hace aproximadamente 1 mes y medio ya tenia todas las fuentes de descargas disponibles, en esta versión tengo que agregar fuentes de descargas o como?

**Comment by Deyllon** [comment]
i haved the same problem before, for me my problem has solved doing this:
1 go to settings
2 click in the download sources
3 click in button add source
4 Copy these links one at a time to gain access to all the download sources :
   1. https://hydralinks.cloud/sources/xatab.json
   2. https://hydralinks.cloud/sources/tinyrepacks.json
   3. https://hydralinks.cloud/sources/onlinefix.json
   4. https://hydralinks.cloud/sources/kaoskrew.json
   5. https://hydralinks.cloud/sources/gog.json
   6. https://hydralinks.cloud/sources/fitgirl.json
   7. https://hydralinks.cloud/sources/empress.json
   8. https://hydralinks.cloud/sources/dodi.json
   9. https://hydralinks.cloud/sources/steam-amiga.json

**Comment by DaviRezende15** [comment]
you are the guy

**Comment by narkonimi** [comment]
thank you very much, how did you find these links (I’m writing through Google translator, since I don’t know English)?
@Deyllon

**Comment by Deyllon** [comment]
Relaxa mano sou br, but i will answer in english. I Don't remember exactly where i find this but i find in another issue from this repository, btw i think this is the official repo for get the links: https://hydralinks.cloud/sources

**Comment by narkonimi** [comment]
@Deyllon it's okay, I'm not too lazy to translate, thanks for the link, have a nice day
