### ISSUE TITLE
[BUG] Hydra crashes on launch

### ISSUE THREAD

**Issue by PedroFire432** [hydralauncher/hydra#808]
### Describe the bug

I'm running Windows 8.1. It doesn't crash immediately, it stays open for a while and then crashes (as a task, it never opens a window).

GPU: NVIDIA GTX 970
CPU: Intel Core i5-3470
RAM: 8 GB

### Steps to Reproduce

1. open Hydra
2. crash

### Expected behavior

open Hydra normally

### Screenshots

![hydra screenshot](https://github.com/hydralauncher/hydra/assets/76817920/54742699-853c-4bc8-b4af-7d64a90a7f1d)

### Operating System

Windows 8.1

### Hydra Version

2.0.3

### Additional Information

also tried using the setup version but it says that this app can't run on my PC.

**Comment by JackEnx** [comment]
plase, download this program: https://github.com/pd4d10/debugtron/releases/tag/v0.5.0, windows is Debugtron-0.5.0.Setup.exe, 
![image](https://github.com/hydralauncher/hydra/assets/167036558/938f665b-826f-42a1-a931-636533f82f87)
open hydra and wait to crash, and send here the text into this box:
![image](https://github.com/hydralauncher/hydra/assets/167036558/34a37135-9c03-4a5f-9726-c9b4ae30faa1)

**Comment by PedroFire432** [comment]
the installed version of hydra doesn't even launch, and dragging the portable executable to debug displays nothing
![hydra screenshot 2](https://github.com/user-attachments/assets/be459e04-9576-4a73-a501-3167c521021c)

**Comment by JackEnx** [comment]
Have you tried running as administrator? the Debugtron

**Comment by zamitto** [comment]
@PedroFire432 any change you update to Windows 10? Electron dropped compatibility for Windows older than 10 sometime ago. This is probably why Hydra does not work for you
