### ISSUE TITLE
not downloading games, js saying "calculating download time" + prob with real-debrid[BUG] 

### ISSUE THREAD

**Issue by BOBLO123** [hydralauncher/hydra#809]
### Describe the bug

ive has this problem since V2.0.3 where no game will download, it will just have my kbs go down till the download would take around 1000 years, then it goes too "calculating download time" and the download stays at 0% for hours and never changes. along with that, i cant get the api key for real-debrid, it gives me a 404 error when i go to the website where the api key is at.

### Steps to Reproduce

(downloading games) this is real simple, just try and download a game
(real-debrid) 1: settings 2: real-debrid 3: enable real-debrid 4: get api key here

### Expected behavior

i was hoping games would download, and they did in V2.0.2 but not now 
and for real-debrid too allow me to get the api key

### Screenshots

![image_2024-07-09_220403707](https://github.com/hydralauncher/hydra/assets/130241547/7ed0f17b-dee8-4fca-be42-23ebf1e4875d)
![image_2024-07-09_220644038](https://github.com/hydralauncher/hydra/assets/130241547/f4041c98-04f9-48a9-9225-cc9fbca30891)

### Operating System

windows 11

### Hydra Version

3.0.2

**Comment by JackEnx** [comment]
real debrid is a paid service, is a optional for someone want to use it (this service is not related to Hydra, we only support it), about the download try others game, if the problem persist probably you have other torrent like qbittorrent, closed first after open hydra and try again.

**Comment by BOBLO123** [comment]
ive done that, the game still doesnt download, and that goes for all games (btw thanks, i didnt know it was a paid service)

**Comment by zamitto** [comment]
We reworked the downloads in 2.1.0
If it is still an error, feel free to open a new issue

**Comment by STUMP02** [comment]
the same problem on version 3.0.4 I tried a lot, they advised me to install version 1.2.1, but it's nowhere to be found, I just didn't find it, I tried different games, different repacks, nothing helps, the download just lasts 10,000 years and then stops at 0 and all that to do when it's fixed, the same problem I had on version 1.3.1 then I I installed 1.2.1 and it helped, and then I erased the hydra launcher from the PC, installed it again and here it is again.
Перевод на русский: 
та же проблема на версии 3.0.4, я много перепробовал, мне посоветовали установить версию 1.2.1, но ее нигде нет, я просто не нашел ее, я пробовал разные игры, разные репаки, ничего не помогает, загрузка просто длится 10 000 лет, а потом останавливается на 0, и все это для того, чтобы сделайте, когда это будет исправлено, ту же проблему, которая была у меня в версии 1.3.1, затем я установил 1.2.1, и это помогло, а затем я удалил программу запуска hydra с ПК, установил ее снова, и вот она снова здесь
