### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by snakeking021** [hydralauncher/hydra#811]
### Describe the bug

não consigo iniciar o app , sempre da esse erro.

### Steps to Reproduce

.

### Expected behavior

eu pensei que iria inicar normalmente,mas acabou dando esse erro.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/175306174/183eff61-a58b-4360-8dbb-f17828fb8237)

### Operating System

windows 8

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
Hydra uses Electron, and it only supports Windows 10 and newer.

https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
