### ISSUE TITLE
[REQUEST] Integrate Achievement Watcher

### ISSUE THREAD

**Issue by Kaminski93** [hydralauncher/hydra#813]
### Is your feature request related to a problem? Please describe.

Currently, Hydra Launcher excels at organizing and managing game downloads and installations, but it lacks a comprehensive achievement tracking system. Many gamers appreciate tracking their in-game achievements as it adds to the overall gaming experience and provides a sense of accomplishment. Without this feature, users need to rely on separate applications or manual tracking, which can be cumbersome and disrupt the seamless experience Hydra aims to provide.

### Describe the solution you'd like

I propose integrating Achievement Watcher into Hydra Launcher. Achievement Watcher is an achievement tracking tool that supports multiple game platforms, including Steam and Steam emulators. By embedding Achievement Watcher into Hydra, users would receive real-time notifications of their achievements, along with automatic screenshots or video captures of those moments. This integration would enhance the gaming experience by consolidating all relevant game-related information and milestones within Hydra.

### Describe alternatives you've considered

Manual Tracking: Users manually track their achievements using spreadsheets or notes, which is inconvenient and lacks the real-time engagement.

Third-party Applications: Users can install and run Achievement Watcher separately, but this adds complexity and fragments the gaming experience between multiple applications.

Built-in Basic Achievement Tracking: Hydra could develop its basic achievement tracking system, but it would likely be less comprehensive and robust compared to the well-established Achievement Watcher.

### Additional context

User Engagement: Integrating Achievement Watcher can increase user engagement by making Hydra a one-stop hub for game management and achievement tracking.

Community Feedback: Many users in gaming forums and communities have expressed the desire for integrated achievement tracking within their game launchers like Playnite.

Technical Feasibility: Achievement Watcher is open-source and can be integrated with proper API usage and collaboration with its developers.

Enhanced Experience: Real-time notifications, coupled with automatic screenshots and videos, provide a richer and more interactive gaming experience.

**Comment by JackEnx** [comment]
implemented in update 3.0.
