### ISSUE TITLE
[BUG] I can't delete a game

### ISSUE THREAD

**Issue by FViniciusCastro** [hydralauncher/hydra#815]
### Describe the bug

I download one game (subnautica), but when i try to delete the files (in rar) apperars this pop-up

### Steps to Reproduce

download subnautica (i used "steam amiga" as font)
try to delete (of the hydra)
the files will not be deleted

if you try to delete directly of the pc this pop-up appears, even excluding it in the hydra

### Expected behavior

files should will deteted

### Screenshots

![Captura de tela 2024-07-11 181347](https://github.com/hydralauncher/hydra/assets/133995167/fcb89f3f-304b-46ba-abd4-f4c83e6612a8)

### Operating System

windows 11

### Hydra Version

2.0.3

### Additional Information

help, i want to delete a game

**Comment by JackEnx** [comment]
if the file is being downloaded or paused, it is probably locked by hydra, remove the file through hydra or close hydra completely before deleting the file.

**Comment by Mihkalik** [comment]
i have the same issue have you find a
 solution?

**Comment by zamitto** [comment]
Closing issue as no response in a long time
This should be fixed in 2.1.7
If the error still exists, feel free to open a new issue
