### ISSUE TITLE
[BUG] after the reboot, everything does not load

### ISSUE THREAD

**Issue by 2pk1Mitrofanov** [hydralauncher/hydra#820]
### Describe the bug

I have to reinstall the launcher to make the profile work, in the trend for games, "surprise me" and displaying caps and other properties of games, is there any way to fix this? or is it a bug that will be removed with the update?

### Steps to Reproduce

install - close - run - bug

### Expected behavior

the solution to the problem

### Screenshots

![изображение_2024-07-12_163900681](https://github.com/user-attachments/assets/7af7f294-f5a7-4f35-bf13-7fc957904b29)

### Operating System

Windows 10

### Hydra Version

2.0.3

**Comment by SpaceKosti** [comment]
Same problem

**Comment by 2pk1Mitrofanov** [comment]
> Same problem

Is there really no solution?

**Comment by Rxflex** [comment]
More information is needed to identify the problem. Describe which system you are using, characteristics, hydra log files, and so on.

**Comment by 2pk1Mitrofanov** [comment]
@Rxflex, Windows 10, intel core i5-12400F, AMD RX 6600, 32 RAM
[error.old.txt](https://github.com/user-attachments/files/16286705/error.old.txt)
[error.txt](https://github.com/user-attachments/files/16286707/error.txt)
[info.txt](https://github.com/user-attachments/files/16286708/info.txt)

**Comment by Rxflex** [comment]
@2pk1Mitrofanov Looks like steam refusing your requests, try to use vpn, its might help
![image](https://github.com/user-attachments/assets/42a482b4-0b35-4fea-92cb-050dd6e82289)

**Comment by zamitto** [comment]
It seems that some firewalls blocks Hydra HTTP requests. Check if you have Kaspersky or other firewalls.

**Comment by zamitto** [comment]
Closing issue as no response in a long time
