### ISSUE TITLE
[BUG] - Data leak

### ISSUE THREAD

**Issue by BrunoBiluca** [hydralauncher/hydra#822]
### Describe the bug

This guy reported that his data leaked after download a game. Do you guys know something abouting?

https://www.youtube.com/watch?v=N1l7FRnZf1A

### Steps to Reproduce

1. Download a game

### Expected behavior

Not be hacked

### Operating System

Windows 11

### Hydra Version

2.0.0

**Comment by BrunoBiluca** [comment]
Eu também não botei confiança nesse vídeo, também não vi nada além desse vídeo com esse comportamento.

**Comment by victorsouzaleal** [comment]
> Eu também não botei confiança nesse vídeo, também não vi nada além desse vídeo com esse comportamento.

É complicado porque esses dados vazados podem vir a acontecer de várias formas, a gente também não sabe o que ele faz de download por fora e quais fontes ele usou para baixar os torrents do Hydra. Eu defendo o Hydra porque confio no projeto em si  mas os usuários e o que eles fazem, que fontes adicionam é outra história...

**Comment by GTazz** [comment]
Vi o vídeo desse cara metendo o pau no Hydra e depois vi o vídeo resposta. Acabei conhecendo o projeto por conta desse cara, propaganda gratuita kkkkkkkkk

**Comment by JackEnx** [comment]
just an uninformed person talking about things he doesn't know, he didn't want to say where he downloaded the hydra, version, which game he downloaded, the source, nothing, unfortunately we can't know for sure what he did.

**Comment by zamitto** [comment]
Kept this open for a while so people could see it.
It has been a while, so I don't think it is relevant anymore
