### ISSUE TITLE
[BUG] screen is flickering (IT'S NOT THE FAULT OF NVIDIA'S OVERLAY)

### ISSUE THREAD

**Issue by nerdmanianoob** [hydralauncher/hydra#824]
### Describe the bug

When I open Hydra, the launcher keeps blinking and it's horrible to use. This happened after the new updates

### Steps to Reproduce

open the launcher

### Expected behavior

work without blinking

### Screenshots

https://github.com/user-attachments/assets/a7020fdd-c3ec-4d57-ad95-4c546914dbe2

### Operating System

windows 11

### Hydra Version

2.0.3

### Additional Information

I've already tried disabling the NVIDIA overlay. If any word is not correct, it is Google Translate's fault.

**Comment by rafaelfmuniz** [comment]
seme problem here

**Comment by Annihl4nth** [comment]
same problem for me (I don't have Nvidia Overlay)

**Comment by tiago4171** [comment]
**Guys, disabling MPO solve the problem for me!**
There's a official documentation from NVIDIA Support that provide scripts to disable MPO or enable MPO(if nothing changes for you).
The procedure is pretty simple:
1. Download from [this page](https://nvidia.custhelp.com/app/answers/detail/a_id/5157/~/after-updating-to-nvidia-game-ready-driver-461.09-or-newer%2C-some-desktop-apps) MPO_Disable.reg
2. Execute the file to apply the registry change
3. Restart your PC
4. Re-open the Hydra to see if it's fixed

If it **didn't** work for you, you should return to the [same page](https://nvidia.custhelp.com/app/answers/detail/a_id/5157/~/after-updating-to-nvidia-game-ready-driver-461.09-or-newer%2C-some-desktop-apps) I linked before to download the MPO_Restore.reg apply and restart to restore the default Windows Behavior. 

But for me it's pretty much solved. I'm using a GTX 1650 with Windows 10 and latest drivers to date(565.90).

**Comment by nerdmanianoob** [comment]
@tiago4171 Obrigado amigo você é um amigo. Resolveu aqui cara, muito obrigado : )

**Comment by Lapokoshmala** [comment]
It's simple.
go to shortcut properties and type --disable-gpu-compositing, it should say "C:\Program Files\Hydra\Hydra.exe" --disable-gpu-compositing.
This option will be better than disabling MPO, because without MPO you won't have g-sync in many games.

**Comment by Lapokoshmala** [comment]
You should write --disable-gpu-compositing in the “object” field.
