### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JONATHATT27** [hydralauncher/hydra#828]
### Describe the bug

Dentro do app não aparece nenhuma opção de download, em todos os jogos está com esse mesmo erro.

There is no download option within the app, all games have this same error
![HYDRA](https://github.com/user-attachments/assets/b1a18d42-3868-4505-966d-ebb4213e78e6)

### Steps to Reproduce

Eu abro o aplicativo, procuro o game que estou interessado e não aparece a opção de baixar, e isso se aplica a todos os jogos que estão dentro app

### Expected behavior

Não aparece, em nenhum dos games do app a opção de realizar o download 

### Screenshots

![hydra1](https://github.com/user-attachments/assets/42908ec5-9c1d-4516-8ae1-694211a1f2ea)

### Operating System

WINDONS 10 PRO

### Hydra Version

2.0.3

### Additional Information

Não consigo realizar nenhum download como mostrado na imagem que fixei.

**Comment by yuriccosta** [comment]
Mesma coisa aqui no linux.

**Comment by yuriccosta** [comment]
Você tem que adicionar as fontes por conta própria a partir de agora. Você pode encontrar as fontes neste link: https://hydralinks.cloud/
Aperta na opção de instalar no Hydra nas fontes que desejar ou você vai em ajustes->Fontes de download->Adicionar fonte e cola os links que vão estar no site acima
