### ISSUE TITLE
very slow download speed

### ISSUE THREAD

**Issue by icwroo** [hydralauncher/hydra#829]
### Describe the bug

for some reason my download speed is really slow

### Steps to Reproduce

try to download the game

### Expected behavior

download in a normal speed

### Screenshots

![imagem_2024-07-14_020657266](https://github.com/user-attachments/assets/5703e47d-ec69-49ee-8f5d-854e95f42fd4)

### Operating System

Windows 10

### Hydra Version

2.0.3

### Additional Information

idk why but this is only happening with some corpse party games

**Comment by JackEnx** [comment]
> same issue i have fiber 1 gig speed download and upload this is what i get ![image](https://private-user-images.githubusercontent.com/128870258/348802051-edf0a134-a547-4aaa-a89e-35ef4208c1c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODY0NjIsIm5iZiI6MTcyMTA4NjE2MiwicGF0aCI6Ii8xMjg4NzAyNTgvMzQ4ODAyMDUxLWVkZjBhMTM0LWE1NDctNGFhYS1hODllLTM1ZWY0MjA4YzFjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQyMzI5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmEzMjEzODAwMWMxZGRmMTk5ZjgxNzNiZWFkMWM0MzFlM2M0NjRlZDQ2MzU3NTkzYmE3YzUyNzMzZDFkODQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XL0fXOEEwsgPZSkvHFEffU-NjYrW6RmqVVrqa-Y9l_A)

please, read the README before to saying it's a bug, this is expected behavior of torrent downloads.

**Comment by JackEnx** [comment]
you need to see if it has seeds, if you seeds is zero or lower your download will be slow.
