### ISSUE TITLE
[BUG] hydra launcher

### ISSUE THREAD

**Issue by ygorxz08** [hydralauncher/hydra#834]
### Describe the bug

quando vou abrir algum jogo ja instalado ele n abre e diz q deu system erro

### Steps to Reproduce

va no hydra launcher instale algum jogo de  preferencia dark souls 3 remastered ao iniciar o jogo ele nao abre e da system erro

### Expected behavior

que abrisse o jogo normalmente

### Operating System

win 10

### Hydra Version

2.0.3 levictus

**Comment by JackEnx** [comment]
please describe in detail the problem, steps to produce, prints and test on at least 3 games.

**Comment by ManowTheusZica** [comment]
quando eu instalo a nova versao ou a antiga nao aparece nenhuma instalaçao disponivel o que eu posso fazer?

**Comment by zamitto** [comment]
@ManowTheusZica, you need to add your Download Sources. You can join the Discord managed by the community, there you can find help and tutorials for that.
https://discord.gg/TSxymg7JTJ
