### ISSUE TITLE
Can't download from Hydra[BUG] 

### ISSUE THREAD

**Issue by ChaosInsurgencyAgent** [hydralauncher/hydra#841]
### Describe the bug

When I go on a game page, I can't seem to download any repack of it, and this happens to all of them, no matter what game.

### Steps to Reproduce

1. Go to catalogue
2. Choose any game
3. See the error

### Expected behavior

I expected for repack list to show up.

### Screenshots

![Screenshot_3](https://github.com/user-attachments/assets/513c640d-28a2-464b-b8f0-4c5fce8db302)
![Screenshot_4](https://github.com/user-attachments/assets/6d2735d2-ef57-4d6a-b5a8-169e92c9582a)

### Operating System

Windows 10

### Hydra Version

v2.0.3 "Leviticus"

**Comment by JackEnx** [comment]
you can find information about this here: https://hydra-launcher.gitbook.io/hydra

you can find sources in the closed issues

**Comment by pckcml** [comment]
Is having to add sources a new thing? Because on my old installation I've never had to do it in order to download stuff.
