### ISSUE TITLE
[BUG] 0% game load

### ISSUE THREAD

**Issue by NaviTDost** [hydralauncher/hydra#842]
### Describe the bug

i select the download option and click on download and go to the “downloads” section, it says that the game is loading, I wait 10-15 minutes and there is still 0% download although the internet is fine

### Steps to Reproduce

click on download game

### Expected behavior

I think they will help me solve the problem and I will be able to download my favorite games

### Screenshots

![Снимок](https://github.com/user-attachments/assets/f79d72b6-336e-469c-b1db-a6fed011e1f1)

### Operating System

windows 10

### Hydra Version

2.0.3 "Leviticus"

### Additional Information

the problem remains even if you click on pause and then click on continue

**Comment by JackEnx** [comment]
duplicated #836
