### ISSUE TITLE
[BUG] No downloads available

### ISSUE THREAD

**Issue by VladimirMeshcherekov** [hydralauncher/hydra#843]
### Describe the bug

No downloads available 

### Steps to Reproduce

Install app

### Expected behavior

Able to downloads game

### Screenshots

![image_2024-07-19_22-50-21](https://github.com/user-attachments/assets/1b0bbadb-bda8-4594-bb19-daab594ea801)
![image_2024-07-19_22-50-05](https://github.com/user-attachments/assets/e9d1011f-e9f2-4313-b307-dd8bba0afba0)

### Operating System

Windows 10

### Hydra Version

2.0.3

### Additional Information

I am certain that there are regional blockages in my country, because everything works fine in my friends

**Comment by Dorremy** [comment]
Привет  @VladimirMeshcherekov 
Тоже столкнулся с данной проблемой на версии 2.0.3
Скорее всего у тебя как и у меня в "Источниках загрузок" ничего нет (Настройки - Источники загрузки) 
Добавь туда ссылки на интересующие тебя источники, можешь использовать https://hydralinks.cloud/
