### ISSUE TITLE
[BUG] no downloads available

### ISSUE THREAD

**Issue by Zaier432** [hydralauncher/hydra#846]
### Describe the bug

all games are showing as "no downloads available"

### Steps to Reproduce

I just opened the app

### Expected behavior

there should be downloads for at least one game

### Screenshots

![Screenshot_1](https://github.com/user-attachments/assets/ed7e110d-4072-4f81-a35c-53fc9abaf010)

### Operating System

win 11

### Hydra Version

2.0.3

**Comment by BarBarizz** [comment]
Hi, I had the same error. You need to delete your version of the launcher, then download the very first version, the launcher will offer to update, and everything will work

**Comment by zamitto** [comment]
That is the expected behaviour, you need to add your Download Sources. You can get tutorials for that on the Community Discord server https://discord.gg/hydralaunchercommunity
