### ISSUE TITLE
[BUG] Downloads don't start

### ISSUE THREAD

**Issue by NeKola1** [hydralauncher/hydra#847]
### Describe the bug

Loading stuck at 0%

### Steps to Reproduce

I go into the Hydra launcher and try to download the game, the download gets stuck

### Expected behavior

Help me with the problem

### Operating System

Windows 10

### Hydra Version

2.0.3

### Additional Information

firewall doesn't help

**Comment by manku479** [comment]
Facing the same issue man

**Comment by Roszik** [comment]
Faz 2 semanas que estou com o mesmo problema, achei até que era minha maquina kkk

**Comment by Ender2397** [comment]
Try downgrading for an older version.

**Comment by zamitto** [comment]
Real Debrid or Torrent downloads?
If possible, upload your logs files, they are located on `%appdata%/hydra/logs`

**Comment by zamitto** [comment]
No response in a long time. Closing issue.

If any of you is still facing this issue, please open a new one after updating to 2.1.7
