### ISSUE TITLE
[REQUEST] download speed

### ISSUE THREAD

**Issue by Krasnov-Alex** [hydralauncher/hydra#849]
### Is your feature request related to a problem? Please describe.

The download speed is not displayed. It does not display how much time is left to download.

### Describe the solution you'd like

I would like to see at least one of these features when downloading.

**Comment by zamitto** [comment]
The download speed is displayed on the footer of the application.
Could you be more specific where you want it to be displayed as well? Screenshots and specific ideas are appreciated

**Comment by Krasnov-Alex** [comment]
Then this is not a suggestion, but an incorrect operation of the application, there is nothing at the bottom.
  
>Вторник, 23 июля 2024, 16:46 +03:00 от Zamitto ***@***.***>:
> 
> 
>The download speed is displayed on the footer of the application.
>Could you be more specific where you want it to be displayed as well? Screenshots and specific ideas are appreciated
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <hydralauncher/hydra/issues/849/2245305968 @ github . com> 
 
 
--
Александр Краснов
Отправлено из Почты  Mail.ru

**Comment by zamitto** [comment]
Could you send screenshots of the whole Hydra screen while downloading something?

**Comment by Krasnov-Alex** [comment]
I took screenshots to capture an area larger than the application. two screenshots in window mode and full screen mode.




вторник, 23 июля 2024 г. в 21:35 +03:00 от ***@***.***  ***@***.***>:

**Comment by JackEnx** [comment]
If the problem still exists, send the information directly via github and open the issue again.
