### ISSUE TITLE
[Docker Support] I like your repository.

### ISSUE THREAD

**Issue by dreammis** [hydralauncher/hydra#85]
I run the exe file, but I don't know where to fill the environtment.

lots of people including me, we all like docker deploy. XD

**Comment by hydralauncher** [comment]
It’s an Electron desktop application. It's very unlikely that anyone would be able to Dockerize such application since you have to run it as an app.

**Comment by dreammis** [comment]
Oh, thank u for your response. I thought it was a web app.
