### ISSUE TITLE
[BUG] There's no downloads

### ISSUE THREAD

**Issue by felipeditchum** [hydralauncher/hydra#851]
### Describe the bug

None of the games in version 2.0.3 have downloads.

### Steps to Reproduce

Enter any game.

### Expected behavior

Have downloads.

### Operating System

Windows 10

### Hydra Version

2.0.3

**Comment by Kumbbar** [comment]
Add source https://hydralinks.cloud/

**Comment by MatecrackXD13** [comment]
@Kumbbar instale todas las fuentes del enlase y todavia la gran mayoria de juegos no tienen descargas

**Comment by Kumbbar** [comment]
> @Kumbbar instale todas las fuentes del enlase y todavia la gran mayoria de juegos no tienen descargas

These links contain a few games as i understand it. There is something similar in this discussion https://www.reddit.com/r/hydralauncher/comments/1e64le2/is_hydralinkscloud_safe/ But i have enough of these games with hydralinks
