### ISSUE TITLE
When you start the game, it crashes almost immediately. Hydra [BUG] 

### ISSUE THREAD

**Issue by tasanji** [hydralauncher/hydra#853]
### Describe the bug

I downloaded the Contraband Police game. I started it, set the path to the opening and the game download window appeared. After a couple of seconds, the game crashed. I downloaded it via another torrent and the problem remained the same.
![Снимок экрана 2024-07-25 154931](https://github.com/user-attachments/assets/63c5fc10-6947-43b3-85aa-4cf40b3b30da)

### Steps to Reproduce

a

### Expected behavior

a

### Screenshots

a

### Operating System

Windows 11

### Hydra Version

v2.0.3

**Comment by zamitto** [comment]
We don't give support for the games you download
