### ISSUE TITLE
Help me, please. I can't download any game

### ISSUE THREAD

**Issue by Alex9600t** [hydralauncher/hydra#854]
What am I supposed to do?

![image](https://github.com/user-attachments/assets/b64c6c57-baa8-4eab-b252-037a0ffb592b)
![image2](https://github.com/user-attachments/assets/89faa5ff-3636-47a9-a702-179d30e24699)

**Comment by zamitto** [comment]
I need to add your download sources
You can join the community discord server, they have tutorials for that
https://discord.gg/hydralaunchercommunity
