### ISSUE TITLE
[BUG] THERE  IS NO DOWNLOAD AVAILABLE 

### ISSUE THREAD

**Issue by Robsonrs1** [hydralauncher/hydra#856]
### Describe the bug

none of the games have a download option

### Steps to Reproduce

when entering hydra and choosing a game, it is already noticeable

### Expected behavior

I wish there were download options available

### Screenshots

![Captura de tela 2024-07-26 010732](https://github.com/user-attachments/assets/51db9797-3660-49aa-8855-400afb77e264)

### Operating System

Windows 10

### Hydra Version

2.0.3

**Comment by Furinat** [comment]
o meu tbm esta assim

**Comment by Robsonrs1** [comment]
como poderia fazer isso?, sou novo no hydra
