### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Furinat** [hydralauncher/hydra#857]
### Describe the bug

nenhum jogo disponivel

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/7b7a18e5-c16a-47f7-9df6-efbfe0c87051)

### Expected behavior

jogoa para baixar

### Screenshots

![image](https://github.com/user-attachments/assets/bf1009d2-4a48-413d-80c5-5ff6bd632e31)

### Operating System

windows 10

### Hydra Version

2.0.3

### Additional Information

nenhum jogo disponivel para baixar

**Comment by root-nate** [comment]
Adicione uma fonte de download para instalar os jogos, como o rutracker
