### ISSUE TITLE
No downloads[BUG] 

### ISSUE THREAD

**Issue by Nameless-Gringo** [hydralauncher/hydra#858]
### Describe the bug

You can't download any game in this launcher
![image](https://github.com/user-attachments/assets/02dbe698-dc7b-4d9b-b6b4-ca3929cb2600)
![image](https://github.com/user-attachments/assets/facbbfff-d641-482a-9c46-f072359c7663)

### Steps to Reproduce

1. Go to any game
2. See error

### Expected behavior

Download a game...

### Screenshots

![image](https://github.com/user-attachments/assets/beb1e2b5-ccab-4b6d-8b67-f505ec01a401)

### Operating System

Windows 11

### Hydra Version

v.2.0.3

**Comment by ryandonq** [comment]
this happens because you have not added any download source

**Comment by Kumbbar** [comment]
Just add source https://hydralinks.cloud/
