### ISSUE TITLE
[BUG] I can't install games or add installation sources

### ISSUE THREAD

**Issue by AnmiTaliDev** [hydralauncher/hydra#864]
### Describe the bug

I can't add installation sources either, as they suggested not to download, I have a Check button and when I click on it, nothing goes through and the source does not appear

### Steps to Reproduce

1. I go to the website https://hydralinks.cloud/
2. I log into Hydra
3. Settings
4. Sources
5. Add a source
6. Check

### Expected behavior

Operation of sources and loading of games

### Screenshots

![Снимок экрана от 2024-07-28 13-49-42](https://github.com/user-attachments/assets/df71e5c3-fc0a-4f7b-9d7c-ac3a9b282955)

### Operating System

Linux Debian 12.5 Wayland GNOME

### Hydra Version

2.0.2

**Comment by zamitto** [comment]
Could you update hydra to the latest version?
If the error still persists, could you update your logs and db?
On Linux, they are located inside ~/.config/hydra

**Comment by JackEnx** [comment]
long time without response, if the problem still exists, open the issue again.
