### ISSUE TITLE
Downloads na lista, mas não disponíveis[BUG] 

### ISSUE THREAD

**Issue by Ender2397** [hydralauncher/hydra#865]
### Describe the bug

O problema que estou a ter é que mesmo após adicionar as fontes de download, os downloads não estão disponíveis

### Steps to Reproduce

1. Pressionar "Adicionar fonte" nas definições
2. Inserir o link da fonte
3. Aparecem downloads na lista, mas não aparecem downloads disponíveis

### Expected behavior

O suposto era aparecerem downloads disponíveis

### Screenshots

![image](https://github.com/user-attachments/assets/313ffbe0-0c36-49d8-86a7-d6edcfd51102)

### Operating System

Windows 10 Pro

### Hydra Version

2.0.3

**Comment by JackEnx** [comment]
If you come from old versions of hydra, before the 2.X.X hydra persist your old links and if you have duplicated hashs in multiples links hydra ignore the duplicated hashs, hydra show total links/new links

**Comment by zamitto** [comment]
As JackEnx said, this is just a visual thing. Will be fixed next version
