### ISSUE TITLE
ETERNAL LOADING [BUG] 

### ISSUE THREAD

**Issue by xmister23** [hydralauncher/hydra#866]
### Describe the bug

downloaded two days ago, played, today I go again and see how the game page endlessly loads
not the game itself is endlessly installing, but its page
below is a screenshot

### Steps to Reproduce

1. Launched Hydra
2. Opened the game page
3. I see the page loading forever

### Expected behavior

a request and a plea to find out what is wrong and how to fix it

### Screenshots

![Снимок экрана (5)](https://github.com/user-attachments/assets/0aee6cc2-9a46-4209-b26f-a639cdda58a2)
![Снимок экрана (6)](https://github.com/user-attachments/assets/9b997191-3f6b-4502-9c06-dce3a9676cd1)

### Operating System

Windows 10 Pro

### Hydra Version

v2.0.3 "Leviticus"

**Comment by zamitto** [comment]
Should be fixed by now. Could you confirm?
