### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Thiago4596** [hydralauncher/hydra#867]
### Describe the bug

The software has a bug that every new installation does not come with the "URL-JSON" and the user needs to enter it manually.

### Steps to Reproduce

For the bug to happen, it must be a clean installation, which with version 2.0.3 and does not have a previous version in the system, so that it does not pull the URL-JSON of the old versions.

### Expected behavior

Every installation should come with URL-JSON automatically, even if it's the first time hydra is installed on your computer.

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by Ender2397** [comment]
That's not a bug is how it works now. Here's the link for you to get them yourself: https://hydralinks.cloud

**Comment by Thiago4596** [comment]
Muito obrigado pela informação vou editar o issue e retirar da categoria bug para que outras pessoas saibam
