### ISSUE TITLE
[BUG] Install Launcher Hydra

### ISSUE THREAD

**Issue by DSoraMonkey** [hydralauncher/hydra#869]
### Describe the bug

I tried to open Hydra and got a non-existent location error, I decided to uninstall and install again, when trying to finish the installation, this error appears and it won't go any further.

(fui tentar abrir o Hydra e deu erro de local inexistente, resolvi desinstalar e instalar novamente, ao tentar finalizar a instalação, aparece tal erro e não vai mais para frente)

### Steps to Reproduce

Install Hydra

### Expected behavior

Install Hydra

### Screenshots

![image](https://github.com/user-attachments/assets/5c0fc442-ead9-4e80-871e-1814e09cf2fa)

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
Where does your Downloads folder in Windows points to?

**Comment by JackEnx** [comment]
long time without response, if the problem still exists, open the issue again.
