### ISSUE TITLE
[BUG]  Yellow Screen.

### ISSUE THREAD

**Issue by kevinsolar** [hydralauncher/hydra#870]
### Describe the bug

When I open the launcher, it starts with a buh yellow look, and does not return to the original color, tested the normal version and the portable version.

quando abro o launcher, ele inicia com buh visual amarelo, e nao volta para a cor oiriginal, testado o a versao normal e o portable

### Steps to Reproduce

Open or Install and open.

### Expected behavior

yellow screen will appear 

### Screenshots

![image](https://github.com/user-attachments/assets/c9d325f4-f758-478d-b250-b10b304ad7c9)
![Captura de tela 2024-08-01 205407](https://github.com/user-attachments/assets/bb369a1c-1dbb-44ce-aeff-f163540b7346)

### Operating System

win 11

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
Disable Nvidia overlay
There's something that conflicts with nvidia overlay and causes this bug

**Comment by GromichXCS** [comment]
You don't have to disable NVIDIA Overlay full,  you can just turn off RTX Dynamic Vibrance in NVIDIA APP and it's gone

![msedge_HWrPMO7oW6](https://github.com/user-attachments/assets/a6650308-3ab1-4b48-895b-15c8e6f37033)
![Hydra_AWu3EQlVvK](https://github.com/user-attachments/assets/02768598-a787-49d6-92b1-8848ff8ef17f)

**Comment by JackEnx** [comment]
two solutions have been reported, if the problem still exists, open the issue again
