### ISSUE TITLE
[BUG] duplicate download with Real Debrid

### ISSUE THREAD

**Issue by VicenzoConti** [hydralauncher/hydra#871]
### Describe the bug

Hello guys, i dont know why but when i download a file with Real-Debrid its download in final is duplicate 

### Steps to Reproduce

Just change to real debrid in settings
input my link to donwload and when make a download, this happen
![bug](https://github.com/user-attachments/assets/63ae02f5-cace-4d03-8239-984d50711166)

### Expected behavior

Just change to real debrid in settings
input my link to donwload and when make a download, this happen
![image](https://github.com/user-attachments/assets/094d24a8-3b18-403b-991b-7faba014fc2c)

### Operating System

Windows 10

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
Did you download it using only Real Debrid, or did you first download with torrent and then later changed to real debrid?

**Comment by Pudk** [comment]
Same problem!

**Comment by zamitto** [comment]
We identified what is happening. It will be fixed on next release

**Comment by VicenzoConti** [comment]
Sorry, i dont see this notification, but @zamitto i just download to "real debrid".  Ty
