### ISSUE TITLE
[REQUEST] Cloud saving

### ISSUE THREAD

**Issue by MidnightKittenCat** [hydralauncher/hydra#872]
### Is your feature request related to a problem? Please describe.

No, I was wondering if it's in the plans to add cloud saving for game data into hydra.

### Describe the solution you'd like

To be able to save game data on the cloud via hydra.

**Comment by zamitto** [comment]
Yes, we have plans

**Comment by MidnightKittenCat** [comment]
> Yes, we have plans

Sick! when can we expect this? and how will it work exactly?

**Comment by JackEnx** [comment]
implemented in update 3.0
