### ISSUE TITLE
[REQUEST] Social component

### ISSUE THREAD

**Issue by The-real-M1000** [hydralauncher/hydra#873]
### Is your feature request related to a problem? Please describe.

Please add a social component, friends, chat etc.

### Describe the solution you'd like

Please add a social component, friends, chat etc.

**Comment by JackEnx** [comment]
we have some componentes in WIP, like #814 and #855, If you have any ideas, it would be good to specify how they should behave.

**Comment by The-real-M1000** [comment]
> Tenemos algunos componentes en WIP, como [814](https://github.com/hydralauncher/hydra/pull/814) y [855,](https://github.com/hydralauncher/hydra/pull/855) Si tienes alguna idea, sería bueno especificar cómo deben comportarse.

The features you name are already in v2.0.3 or will they be released in a later version?

**Comment by zamitto** [comment]
WIP = work in progress, so they will be available in a later version as they are still under development

**Comment by The-real-M1000** [comment]
> WIP = work in progress, so they will be available in a later version as they are still under development

Thanks, I didn't know

**Comment by zamitto** [comment]
Friends feature was release in 2.1.0
