### ISSUE TITLE
[BUG] How long to beat its not working

### ISSUE THREAD

**Issue by The-real-M1000** [hydralauncher/hydra#876]
### Describe the bug

When entering a game's page, the How Long to Beat section appears for a few seconds (only the title) and then disappears, (in all games)

### Steps to Reproduce

1. Open a game page
2.  Bug

### Expected behavior

That it appeared

### Screenshots

![Captura de pantalla 2024-08-02 231645](https://github.com/user-attachments/assets/1e165acd-23ce-4ee3-a41a-de0a811add45)

### Operating System

windows 11 (Winter os)

### Hydra Version

2.0.3

**Comment by yash1441** [comment]
Same. Upon opening the game page, the following appears for a split second and then disappears.
![image](https://github.com/user-attachments/assets/c54f880a-6e35-416c-9fba-45af2731b461)

**Comment by zamitto** [comment]
HLTB removed the integration we used. In the latest version we removed them from the UI, so it would get odd to show is loading and failing to show later
