### ISSUE TITLE
[BUG] Some games have passwords on their files

### ISSUE THREAD

**Issue by The-real-M1000** [hydralauncher/hydra#877]
### Describe the bug

I am aware that this is not your problem but some games have a password in the files, I do not know how you can solve it but I thought it was pertinent to let you know

### Steps to Reproduce

1. Install "Oxygen Not Included"
2. Try to unzip the files

### Expected behavior

Be able to unzip the archive

### Screenshots

![Captura de pantalla 2024-08-02 232138](https://github.com/user-attachments/assets/539a91db-82ba-48ff-a9a6-cd726b854aec)

### Operating System

windows 11 (Winter os)

### Hydra Version

v2.0.3

**Comment by MidnightKittenCat** [comment]
Try using: online-fix.me
