### ISSUE TITLE
[REQUEST]  Instalar o torrent juntamente com o hydra launcher

### ISSUE THREAD

**Issue by GabrielLeite2004** [hydralauncher/hydra#880]
### Is your feature request related to a problem? Please describe.

Tenho formatado direto meu computador, e direto tenho o mesmo problema quando instalo o hydra: instalar o torrent. Sem ele, o hydra não funciona (como esperado, não estou reclamando disso)

### Describe the solution you'd like

Ao instalar o hydra, também ter uma forma de instalar o torrent ou web torrent para instalar tudo de uma vez. Caso seja possivel e simples, apenas estou dando uma ideia

### Additional context

(Estou cumprindo o trabalho de software livre, e não precisa realmente levar a sério, só quis contribuir por causa desse trabalho)

**Comment by zamitto** [comment]
What do you mean?
Hydra has an embedded torrent client, it should work without the need of installing an additional torrent client outside of Hydra

**Comment by GabrielLeite2004** [comment]
No, it's just that I had a problem where the download links on Hydra weren't appearing, but I linked the torrwnts sites and it appeared, thanks
