### ISSUE TITLE
[BUG] Downloads não disponíveis em nenhum jogo 

### ISSUE THREAD

**Issue by vicxe** [hydralauncher/hydra#881]
### Describe the bug

Todos os jogos da plataforma não possuem opções de downloads disponíveis.

### Steps to Reproduce

1. Clique em qualquer jogo para instalar

### Expected behavior

Quando entrar na página do jogo, não aparecerá nenhum link para download disponível. Espero que isso seja concertado.

### Screenshots

![image](https://github.com/user-attachments/assets/d284e78a-5d90-4739-b62e-260d94760b08)
![image](https://github.com/user-attachments/assets/5b6e8fd2-9422-40c5-92e1-c10a804416cc)

### Operating System

Windows 10

### Hydra Version

v2.0.3 "Leviticus"

**Comment by slanow** [comment]
O meu ta da mesma forma. Desintalei e instalei novamente e deu no mesmo.

**Comment by Pudk** [comment]
Boa rapaziada coloca a fonte, coloca em ajustes e fonte de downloads

https://hydralinks.cloud

so copiar e colar desse site e clica para sincronizar acredito ser isso

**Comment by M4riotto** [comment]
Eu fiz isso e estava dando 1.2kb/s ia baixar em 36 anos kkkk E esta normal minha inthernet coloquei outro jogo para baixar na epic e foi rapidinho

**Comment by Pudk** [comment]
Então, se não for via real debrid, voce vai depender do tanto de seeds disponiveis no torrent do game que esta baixando, isso que vai mandar na velocidade de download ! pode testar por exemplo com o dbz kakarot ele vai bem rapido por conta de ter mais seeds

**Comment by M4riotto** [comment]
Não entendi... tem discord pra suporte?
