### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Panch0u** [hydralauncher/hydra#888]
### Describe the bug

I cant download anything, it dosent give me the option of downloading just the option to add to library
![image_2024-08-08_141514760](https://github.com/user-attachments/assets/d229bfbb-eea5-4b40-9c42-28215c15072b)
![image_2024-08-08_141647140](https://github.com/user-attachments/assets/e49a9f5a-4bd2-4297-b6e5-efb787f9ce1c)
![image_2024-08-08_141712859](https://github.com/user-attachments/assets/8a2d7cd4-cf6a-4268-8368-1f5579da9f47)
![image_2024-08-08_141744220](https://github.com/user-attachments/assets/85fc0e0c-b97d-44fd-b93f-a26d026fd265)
![image_2024-08-08_141802593](https://github.com/user-attachments/assets/d2935a17-2c24-49b2-905e-fd9869ed7412)
![image_2024-08-08_141833924](https://github.com/user-attachments/assets/1d73a4cd-d477-4b66-bf6c-9d1e483656cb)

### Steps to Reproduce

it just dosent show me to button

### Expected behavior

to have the buttons 

### Operating System

Windows 11

### Hydra Version

2.0.3 "leviticus"

**Comment by artchsh** [comment]
Did you add download sources in settings?
If not, add them and check again

**Comment by Eduardo4815162342** [comment]
Open > https://hydralinks.cloud/
Copy the source link
Go to Hydra
Settings> Add sources > paste the link of source that you chose
>save and refresh
