### ISSUE TITLE
[BUG] Hydra crashing on start

### ISSUE THREAD

**Issue by FernandoPazCavalcante** [hydralauncher/hydra#889]
### Describe the bug

After installed the Hydra launcher 2.0.3 version it crashes on start.

### Steps to Reproduce

1. Uninstall current version
2. Download latest version
3. Install latest version
4. Launch Hydra

### Expected behavior

It should start normally.

### Screenshots

![Screenshot 2024-08-08 at 15 03 06](https://github.com/user-attachments/assets/40eef2d7-7b86-4fc2-9a0f-5f282cb808f7)

### Operating System

Windows 10

### Hydra Version

2.0.3

### Additional Information

Ryzen 5 5500
Gtx 960
16gb ram
Biostar b550m

**Comment by fzanutto** [comment]
What is the complete installation path of Hydra?

The "\\?" before the "C:\..." is strange

**Comment by zamitto** [comment]
What is the complete installation path of Hydra?

The "\?" before the "C:..." is strange

**Comment by FernandoPazCavalcante** [comment]
> What is the complete installation path of Hydra?
> 
> The "?" before the "C:..." is strange

This is the complete installation path:
`C:\Program Files\Hydra`

The games I usually keep in another folder:
`C:\Users\Bru\Desktop\Games`

Also, I attached the log files here.
[error.txt](https://github.com/user-attachments/files/16556265/error.txt)

[logs.txt](https://github.com/user-attachments/files/16556267/logs.txt)

**Comment by zamitto** [comment]
@FernandoPazCavalcante, sorry I could keep up with this issue.
Could you try installing the latest version to see if this error disappears?
As for the axios errors, they are expected, nothing to do with the error you printed

**Comment by FernandoPazCavalcante** [comment]
> @FernandoPazCavalcante, sorry I could keep up with this issue. Could you try installing the latest version to see if this error disappears? As for the axios errors, they are expected, nothing to do with the error you printed

The bug was fixed bro. I tested with the latest version and everything worked very well.
