### ISSUE TITLE
stuck on installing meta data for any game and any source

### ISSUE THREAD

**Issue by Stefma4Git** [hydralauncher/hydra#89]
0% downloading metadata...

**Comment by hydralauncher** [comment]
Please provide more context, there's no much that I can suggest with that. Are you running from the source? Which games did you try? And which repacks?

**Comment by guizaodev** [comment]
@Stefma4Git 
Are you using the dev setup? If yes, it seems like your torrent-client is down. Could you please attach a screenshot from your terminal?

**Comment by hydralauncher** [comment]
Closing this since it seems like an environment issue.

**Comment by Losyah** [comment]
![image](https://github.com/hydralauncher/hydra/assets/171322187/b69bc7ef-ec6a-48d9-9a07-7d42f1671f5d)
![image](https://github.com/hydralauncher/hydra/assets/171322187/67708094-0d6e-4ab7-b06b-b36391bceac3)
0% downloading metadata
