### ISSUE TITLE
Bug with download the game.

### ISSUE THREAD

**Issue by DarkKalkor** [hydralauncher/hydra#890]
### Describe the bug

Added the game to the library and it says: Run. Hmm, I thought it would run the game loader, but in the end it doesn't show that the download has started. I looked through System Informer and there you can see the downloader. But for some reason it doesn't show the download in active downloads.

### Steps to Reproduce

Well, I didn't do anything special, I installed a regular setup from github. Then I started looking for the game through the search, found the game and added it to the library. I wanted to install the game through the library, I choose the launch path, namely your program (for some reason it doesn't install in a separate folder for the game, only through some program it was necessary to install. I chose the exe Hydra file)

### Expected behavior

Well, just to show the game installation in active loads. Nothing else is needed.

### Screenshots

Video: https://youtu.be/OIPKL0VWFJc

### Operating System

Windows 11 23H2

### Hydra Version

 hydralauncher-2.0.3-setup.exe

**Comment by DarkKalkor** [comment]
Video: https://youtu.be/OIPKL0VWFJc

**Comment by DarkKalkor** [comment]
> ### Describe the bug
> 
> Added the game to the library and it says: Run. Hmm, I thought it would run the game loader, but in the end it doesn't show that the download has started. I looked through System Informer and there you can see the downloader. But for some reason it doesn't show the download in active downloads.
> ### Steps to Reproduce
> 
> Well, I didn't do anything special, I installed a regular setup from github. Then I started looking for the game through the search, found the game and added it to the library. I wanted to install the game through the library, I choose the launch path, namely your program (for some reason it doesn't install in a separate folder for the game, only through some program it was necessary to install. I chose the exe Hydra file)
> ### Expected behavior
> 
> Well, just to show the game installation in active loads. Nothing else is needed.
> ### Screenshots
> 
> Video: https://ru.files.fm/u/rx8qudp2zd
> ### Operating System
> 
> Windows 11 23H2
> ### Hydra Version
> 
> hydralauncher-2.0.3-setup.exe
> ### Additional Information
> 
> _No response_

**Comment by DarkKalkor** [comment]
I don't know why I can't install this game in a separate folder, it's kind of strange.

**Comment by zamitto** [comment]
You need to add download sources to have the download options. You can search in the GitHub issues, a lot of users have already commented how to get sources.

You selected the Hydra.exe like it was a game, what does not make sense, because now Hydra thinks your GTA is running. You need to select your game executable (after downloading it)

**Comment by DarkKalkor** [comment]
> You need to add download sources to have the download options. You can search in the GitHub issues, a lot of users have already commented how to get sources.
> 
> You selected the Hydra.exe like it was a game, what does not make sense, because now Hydra thinks your GTA is running. You need to select your game executable (after downloading it)

Please explain, I don't understand what you're talking about at all.

**Comment by DarkKalkor** [comment]
> You need to add download sources to have the download options. You can search in the GitHub issues, a lot of users have already commented how to get sources.
> 
> You selected the Hydra.exe like it was a game, what does not make sense, because now Hydra thinks your GTA is running. You need to select your game executable (after downloading it)
