### ISSUE TITLE
[BUG] Sem opcõs de dowloads em todos os jogos

### ISSUE THREAD

**Issue by Davi0101** [hydralauncher/hydra#893]
### Describe the bug

Nem um jogo mostra as opcões de dowload, todos os jogos estão sem dowload disponives

### Steps to Reproduce

1- intalar o hydra
2- buscar os jogos disponiveis
3- instalar o jogo 
4- jogar o jogo

### Expected behavior

realizar o  dowload apos selecionar o jogo disponivel

### Screenshots

![Captura de Tela (7)](https://github.com/user-attachments/assets/cf01b256-c4e4-4413-8c0a-62013442ff30)

### Operating System

windows 10

### Hydra Version

2.0.1 , 2.0.2 e 2.0.3 

### Additional Information

não consigo fazer o dowload.

**Comment by Ryantkh** [comment]
Faz o download de uma versão anterior a levitcus, quando iniciar o Hydra ele vai atualizar para a levitcus sem esse bug

**Comment by zamitto** [comment]
This is not a bug. It is expected to be like this until you add your download sources

**Comment by davyzera** [comment]
but how can we add a download source?

**Comment by JackEnx** [comment]
> @zamitto but how can we add a download source?

setting / download sources / add source

you can find the links in closed issues

**Comment by Eduardo4815162342** [comment]
Acessa esse site: https://hydralinks.cloud/
aí escolhe as bases, vai em copiar link, depois Configurações > Fontes de Download > adicionar fonte, e cola o link, depois vai em "atualizar fontes"
