### ISSUE TITLE
[REQUEST] Achievements

### ISSUE THREAD

**Issue by AndriyOrlov** [hydralauncher/hydra#896]
### Is your feature request related to a problem? Please describe.

There's a service that provides achievements in games, is it possible to add it to the hydra?

### Describe the solution you'd like

I found an open source program that adds achievements to all games and I think it could be used here and make our national steam completely https://github.com/xan105/Achievement-Watcher#readme

**Comment by damnkrat** [comment]
Duplicate of #813
