### ISSUE TITLE
[BUG] HLTB Integration Has Disappered

### ISSUE THREAD

**Issue by ertila007** [hydralauncher/hydra#897]
### Describe the bug

The HLTB integration has also disappeared in Hydra. This problem has been reported consistently on other platforms that use this integration, such as the Steam Deck plugin, for example.

### Steps to Reproduce

Open Hydra, enter the page of any game.

### Expected behavior

HLTB data appears above the minimum requirements.

### Screenshots

![Captura de tela 2024-08-14 153433](https://github.com/user-attachments/assets/e4346a62-8132-4965-a710-ae0ad2ed7899)

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
HLTB removed the integration we used. In the latest version we removed them from the UI, so it would get odd to show is loading and failing to show later

**Comment by zamitto** [comment]
HLTB will be working again on next release
