### ISSUE TITLE
[BUG] No available downloads on games. Only on new versions.

### ISSUE THREAD

**Issue by IcedDefect** [hydralauncher/hydra#899]
### Describe the bug

When I try to download any game, i find an issue that there's no available downloads. So I can't fix it. I saw this only on 2+ versions. How can i fix it?

### Steps to Reproduce

1st is to find any game. 2nd You click on it. And on 3rd step you see below the game title that there is no downloads available

### Expected behavior

I expected to see many types of downloads. But i got an error

### Screenshots

There is no need of it

### Operating System

Windows

### Hydra Version

2.03

**Comment by zamitto** [comment]
There are a lot of issues who already discussed this and give solutions. Like #851
Please, use the search bar before opening new issues
