### ISSUE TITLE
[BUG] only SOME downloads available 

### ISSUE THREAD

**Issue by TJx586** [hydralauncher/hydra#900]
### Describe the bug

When i add download sources only about half or less downloads are available, I'm not sure why this is happing but its very frustrating because some games on that site are not available on hydra.

### Steps to Reproduce

1. add source 
2. look in sources tab 
3. only some downloads available 
4. game download options missing

### Expected behavior

1. add source 
2. ALL downloads from source all available 

### Screenshots

![image_2024-08-17_105317827](https://github.com/user-attachments/assets/19f5150d-379e-47ff-b183-2cb6949c688e)

![Screenshot 2024-08-17 104903](https://github.com/user-attachments/assets/cc6025f7-9dba-4139-bb4c-73bd0863616f)

### Operating System

Windows 11

### Hydra Version

v2.0.3

### Additional Information

i have added ALL sources and i understand some sources don't have all the games but it is frustrating to see it on the source but not on hydra.

**Comment by zamitto** [comment]
This is a poor word choice from our part
It only means that from all 5157 items, 776 items are new. Not that only 776 are available.

We will word it better on the next update
