### ISSUE TITLE
[BUG] i cant download any game

### ISSUE THREAD

**Issue by hsl9912** [hydralauncher/hydra#905]
### Describe the bug

when i opened hydra and trying to download a game it doesnt appear like theres no downloads and this happens on any game

### Steps to Reproduce

Open hydra, on games page 

### Expected behavior

 maybe because i didnt open hydra in a long time

### Screenshots

![imagen_2024-08-22_010444740](https://github.com/user-attachments/assets/71398148-22fa-4b9f-a5fd-4eb2e732bf2f)

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
There are a lot of issues who already discussed this and give solutions. Like #851
Please, use the search bar before opening new issues
