### ISSUE TITLE
[BUG] Download with Real-Debrid doenst work / Download com o Real-Debrid não funciona

### ISSUE THREAD

**Issue by SamuelBozza** [hydralauncher/hydra#906]
### Describe the bug

<p>Downloads using Real-Debrid do not start, it get stuck at 0%</p>
<p>Downloads com o Real-Debrid não começa, só fica parado em 0%</p>

### Steps to Reproduce

<p>Download any game with Real-Debrid</p>
<p>Baixar qual quer jogo com o Real-Debrid</p>

### Expected behavior

<p>Start the download</p>
<p>Iniciar o download</p>

### Screenshots

![downloaderro](https://github.com/user-attachments/assets/28b43c23-4786-417a-b0a1-00ebda6ba27b)

### Operating System

W11

### Hydra Version

v2.0.3

**Comment by zamitto** [comment]
Is it still a issue in 2.1.4?

**Comment by SirGoldenTaco** [comment]
I can confirm that trying atm on 2.1.5 still has the issue
![image](https://github.com/user-attachments/assets/43ecf424-f713-4b36-99a4-4321a43a9349)

**Comment by SirGoldenTaco** [comment]
Oh after uninstalling everything with bulk crap uninstaller and reinstalling software, source and reassigning my real debris key It works now
