### ISSUE TITLE
"no downloads available" for all games

### ISSUE THREAD

**Issue by Dredgun** [hydralauncher/hydra#908]
since i formatted my laptop and disabled a few services in services.msc, im not able to download anuthing from hydra laucher.
![image](https://github.com/user-attachments/assets/e516cf05-15c8-42dd-b5d5-ad17e6093f51)

please do help me :)

**Comment by EvaMisery** [comment]
same here :(

**Comment by zamitto** [comment]
@Dredgun, @EvaMisery 

There are a lot of issues who already discussed this and give solutions. Like #851
Please, use the search bar before opening new issues
