### ISSUE TITLE
Error occurred in handler for 'startGameDownload': TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by DCRXGames** [hydralauncher/hydra#91]
Hello Everyone,
I got this error on try does download of any game.
Does anyone know how to resolve this error? Could this be a bug?

#######
# Error #
#######

[2380:0427/144908.404:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
Error occurred in handler for 'startGameDownload': TypeError: Cannot read properties of undefined (reading 'id')
    at D:\Users\root\Downloads\hydra\.webpack\main\index.js:325219:25
    at Generator.next (<anonymous>)
    at fulfilled (D:\Users\root\Downloads\hydra\.webpack\main\index.js:325188:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\root\Downloads\hydra\torrent-client\main.py", line 84, in listen_to_socket
    msg = read_fifo.recv(1024 * 2)
  File "D:\Users\root\Downloads\hydra\torrent-client\fifo.py", line 21, in recv
    result, data = win32file.ReadFile(self.socket_handle, bufSize)
pywintypes.error: (109, 'ReadFile', 'O pipe foi finalizado.')

#################
#  My Environment:  #
#################

#> pip list
Package           Version
----------------- -------
cx_Freeze         7.0.0
cx_Logging        3.2.0
libtorrent        2.0.9
lief              0.14.1
pip               22.0.4
pywin32           306
setuptools        69.5.1
typing_extensions 4.11.0
wheel             0.43.0

#> python3
Python 3.9.14 (main, Dec 20 2022, 23:40:07) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

#> python
Python 3.9.14 (main, Dec 20 2022, 23:40:07) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

#> yarn version
yarn version v1.22.22
info Current version: 1.1.0

#> npm version
{
  hydra: '1.1.0',
  npm: '10.5.0',
  node: '20.12.2',
  acorn: '8.11.3',
  ada: '2.7.6',
  ares: '1.27.0',
  base64: '0.5.2',
  brotli: '1.1.0',
  cjs_module_lexer: '1.2.2',
  cldr: '44.1',
  icu: '74.2',
  llhttp: '8.1.2',
  modules: '115',
  napi: '9',
  nghttp2: '1.60.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.13+quic',
  simdutf: '4.0.8',
  tz: '2024a',
  undici: '5.28.4',
  unicode: '15.1',
  uv: '1.46.0',
  uvwasi: '0.0.20',
  v8: '11.3.244.8-node.19',
  zlib: '1.3.0.1-motley-40e35a7'
}

[combined.log](https://github.com/hydralauncher/hydra/files/15139346/combined.log)
[error.log](https://github.com/hydralauncher/hydra/files/15139348/error.log)
[info.log](https://github.com/hydralauncher/hydra/files/15139349/info.log)

**Comment by hydralauncher** [comment]
Lack of SteamGridDB API key, please read the whole README.

**Comment by DCRXGames** [comment]
> Lack of SteamGridDB API key, please read the whole README.

Thank you for your response. I did go through the README documentation, but one part left me a bit confused:

Regarding the line: "If you want to have onlinefix," I interpreted this as being optional. However, after fixing the .env file, everything seems to be working fine now.
