### ISSUE TITLE
[REQUEST]  Source request 

### ISSUE THREAD

**Issue by ShankarKSH001** [hydralauncher/hydra#910]
### Is your feature request related to a problem? Please describe.

This telegram bot has all pc games available can you add this source if possible.
Link : 🖥🎮 Search for PC games to download for free and Request new games to upload. https://t.me/free_pc_games_bot

### Describe the solution you'd like

This telegram bot has all pc games available can you add this source if possible.
Link : 🖥🎮 Search for PC games to download for free and Request new games to upload. https://t.me/free_pc_games_bot

**Comment by thegrannychaseroperation** [comment]
@ShankarKSH001 please do not use our GitHub to share piracy. We do not create download sources, nor accept suggestions, they are totally up to the user to create.
