### ISSUE TITLE
[REQUEST] weekly games

### ISSUE THREAD

**Issue by KratozZ12** [hydralauncher/hydra#911]
### Is your feature request related to a problem? Please describe.

The games that appear in home are always the same or those that were recently added

### Describe the solution you'd like

They should add 3 sections, 1 of the most downloaded games on hydra, the second of the weekly games (that is, the games that have been downloaded the most in the last week), and the third of the recently added games

### Additional context

you do an amazing job keep it up

**Comment by zamitto** [comment]
We do have plans to rework this feature!

**Comment by zamitto** [comment]
Added these sections on 2.1.0
