### ISSUE TITLE
[BUG] Download stuck on 0% and cant verify archives

### ISSUE THREAD

**Issue by Raffzs** [hydralauncher/hydra#913]
### Describe the bug

It is no longer downloading and keeps checking files endlessly. The game only downloaded up to this point and then it keeps checking the files but it doesn't start and the other one doesn't even start the download

### Steps to Reproduce

1 - opened hydra in admin mode, 2 - tried to download, 3 - bug

### Expected behavior

To download it

### Screenshots

![image](https://github.com/user-attachments/assets/2652f9da-b89a-409a-84db-b018167fae40)
![image](https://github.com/user-attachments/assets/551422bd-316a-4ecb-87f3-b058a156aa83)
[error.txt](https://github.com/user-attachments/files/16738791/error.txt)
[info.txt](https://github.com/user-attachments/files/16738792/info.txt)
[logs.txt](https://github.com/user-attachments/files/16738793/logs.txt)

### Operating System

Windows 11

### Hydra Version

2.0.3

**Comment by zamitto** [comment]
Closing as 3 weeks of inactivity
