### ISSUE TITLE
[REQUEST] Add starting game with parameters

### ISSUE THREAD

**Issue by mealet** [hydralauncher/hydra#914]
### Is your feature request related to a problem? Please describe.

Recently I've downloaded **Dishonored** from your launcher and tried to translate it to Russian Language.
But there's a problem: game must be launched with specific argument and launcher cannot do it.

### Describe the solution you'd like

Just add `Launch Options` field to settings and append them after start command.

### Describe alternatives you've considered

Allow editing execute command for manually adding launch args

### Additional context

_Nothing here_

**Comment by thisisignitedoreo** [comment]
+1
running games as an argument to the other command (e.g. proxychains or prime-run for laptops with optimus on linux) would also be great to see.
