### ISSUE TITLE
 error

### ISSUE THREAD

**Issue by MarianaCarneiro34** [hydralauncher/hydra#924]
### Describe the bug

after downloading a game on hydra, my winrar asked for a password to be able to download, someone help me

### Steps to Reproduce

.

### Expected behavior

i was hoping that my winrar didn't ask for a pass

### Screenshots

![Sem Título](https://github.com/user-attachments/assets/78c67d1c-6ff7-4122-ae90-2f0655df64a8)

### Operating System

windows

### Hydra Version

2.0.3

### Additional Information

.

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
We don't give support for downloaded games.
You can find help in the community discord server https://discord.gg/hydralaunchercommunity
