### ISSUE TITLE
[BUG] THE LIBRARY HAS NO DOWNLOADS

### ISSUE THREAD

**Issue by yalx1** [hydralauncher/hydra#925]
### Describe the bug

in the new version 2.0.3, the entire library has no download avaliable. What in the url of this .json file to solve the problem?

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/2e00fc6a-c012-4323-9062-86f495d2c541)
![image](https://github.com/user-attachments/assets/fee641ee-6c49-45ab-aa1b-8738ffb34e0d)

### Screenshots

![image](https://github.com/user-attachments/assets/ee43bf6a-bd70-4eb7-8ec5-9171c7e76aff)
![image](https://github.com/user-attachments/assets/ba4d6ad5-8b78-41ed-862a-dae8cff0175a)

### Operating System

windows 10

### Hydra Version

2.0.3 "Leviticus"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Please, search before opening new issues.
See #858
