### ISSUE TITLE
[BUG] trying to launch cat goes fishing

### ISSUE THREAD

**Issue by steeepaaaan** [hydralauncher/hydra#926]
### Describe the bug

when trying to launch cat goes fishing hydra goes blank and has to be reopened

### Steps to Reproduce

1. Go to cat goes fishing 
2. click on it 
3. gray screen

### Screenshots

![Snímek obrazovky 2024-08-30 105147](https://github.com/user-attachments/assets/51d914d5-59b9-411b-a6fa-f9a29ddb65f7)
![Snímek obrazovky 2024-08-30 105157](https://github.com/user-attachments/assets/f50c053a-a97a-45a2-9e53-2c20013ee642)

### Operating System

Windows 11

### Hydra Version

2.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by fdciabdul** [comment]
try to use nightly build in action artifact

https://github.com/hydralauncher/hydra/actions/runs/10636570045

**Comment by zamitto** [comment]
Thanks for the report. It is a bug that will be fixed in the next oficial release.

**Comment by KRWCLASSIC** [comment]
its still happening, for me its with PC Building Simulator
![image](https://github.com/user-attachments/assets/ae6797d7-3d66-40c4-9a06-46020d65dc63)
![image](https://github.com/user-attachments/assets/d35c7570-ba14-4468-b231-d899ae76c55c)
