### ISSUE TITLE
[BUG] BSOD after leaving a game downloading for a while

### ISSUE THREAD

**Issue by PedroHDrawanz** [hydralauncher/hydra#927]
### Describe the bug

Nothing much to add, i start downloading ghost of tsushima from xatab or idk how it writes, and after some time my pc goes blue screen and restarts, i actually need to turn it off through the button, because once it restarts, it gets stuck in the motherboard screen(The one asking to press del or f2 to open bios).

My pc specs:
GPU - RX 6650 XT
CPU - R5 4600G
RAM - 16GB DDR4
PSU - 500W

Could it be a faulty hdd perhaps?(Yes i still use a HDD, don't have money to buy a better drive rn)

### Steps to Reproduce

Seems like somthings wrong on my side, so just starting to download a game is enough to make my pc shutdown

### Operating System

Windows 11 Compact(GhostSpectre)

### Hydra Version

2.0.3

### Additional Information

I have seen another issue like mine in here, but the guy barely spoke English and it ended up not getting any fix, so i am not even sure if it was the same thing.

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by PedroHDrawanz** [comment]
Also i'd like to add that my pc does not give any blue screen and works normally if i do not open hydra

**Comment by zamitto** [comment]
Does this happen for every download? Even for small games (less than 1 GB for instance)?

**Comment by PedroHDrawanz** [comment]
> Does this happen for every download? Even for small games (less than 1 GB for instance)?

I haven't tried that, but i believe it to be a problem caused by my faulty HDD, i tried using another drive and i'm still ok, i'll update if anything goes wrong or not.

**Comment by zamitto** [comment]
You can use Crystal Disk to help with HDD errors. It should be easy to find youtube tutorials to help you use it

**Comment by PedroHDrawanz** [comment]
> You can use Crystal Disk to help with HDD errors. It should be easy to find youtube tutorials to help you use it

I just scheduled a chkdsk with cmd to the next restart, i'll try crystal disk aswell. Thank you for the tip

**Comment by zamitto** [comment]
Glad it worked! 
Closing the issue as completed
