### ISSUE TITLE
[BUG] Sem downloads disponíveis

### ISSUE THREAD

**Issue by andersonrrss** [hydralauncher/hydra#933]
### Describe the bug

Eu instalei o Hydra e TODOS os jogos estão sem downloads disponíveis, não sei se houve algum erro na instalação ou algo assim, mas eu já desinstalei e instalei o aplicativo mais de uma vez e o erri continua

### Steps to Reproduce

1. Simplesmente entrar no Hydra e ver que nenhum jogo tem download disponível

### Screenshots

![image](https://github.com/user-attachments/assets/769d3ac5-2a2f-4259-a85c-e2c53838c566)

### Operating System

Windows 10

### Hydra Version

v2.0.3 "Leviticus"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by Ruanc1409** [comment]
o meu tambem não tem nenhum dowload disponivel

**Comment by bermarques** [comment]
https://github.com/hydralauncher/hydra/issues/858

**Comment by TioKazuma** [comment]
Voces precisam exportar fontes, talvez esse video ajude https://www.youtube.com/watch?v=Oc0_EkK4ts8

**Comment by zamitto** [comment]
It is not a bug nor an installation error. The comment above is correct, you need to add your download sources.
IF you need further help, you can join the community discord server (https://discord.gg/hydralaunchercommunity)
