### ISSUE TITLE
[BUG] I can't download

### ISSUE THREAD

**Issue by lukasfontess** [hydralauncher/hydra#937]
### Describe the bug

It keeps showing that there is no download available, I have already uninstalled and reinstalled my hydra 4 times and I can't use it

### Steps to Reproduce

I open my hydra and I can't use it

### Expected behavior

be able to download my games and run them without any difficulty.

### Screenshots

![WhatsApp Image 2024-09-09 at 18 42 18](https://github.com/user-attachments/assets/07ff86f8-fc87-4b72-af8d-8e1aa3351f40)

### Operating System

Windows 11

### Hydra Version

2.0.3 Levictus

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by JackEnx** [comment]
you can find information about this here: https://hydra-launcher.gitbook.io/hydra
you need to add download sources to hydra, you can find in closed issues like:  #851, 
there more sources in closed issues (all sources is provided by the community)
