### ISSUE TITLE
[BUG] PAGE GOES BLACK

### ISSUE THREAD

**Issue by LeandroV12** [hydralauncher/hydra#938]
### Describe the bug

When I enter hydra and type the name of the game "The Silent Age" in the search bar a black screen appears and I can only close it, I waited a long time but it continues to appear

### Steps to Reproduce

1. I entered the normal hydra
2. I put the name of the game "The Silent Age" in the search bar
3. I clicked on the game
4. Black screen appears
5. I closed Hydra and tested again but the same black screen always appears.

### Expected behavior

I thought it would go normally like other games, there wouldn't be a black screen.

### Screenshots

![image](https://github.com/user-attachments/assets/c95cd1dd-f9ac-4e16-99a6-90364dd54880)

![image](https://github.com/user-attachments/assets/cd389cc3-bd3e-4f92-8c95-1c0214fb2be5)

https://github.com/user-attachments/assets/f011fcd2-2497-4e63-9d98-a9fce3671a9b

### Operating System

Windows 10

### Hydra Version

2.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by LeandroV12** [comment]
> ### Describe the bug
> When I enter hydra and type the name of the game "The Silent Age" in the search bar a black screen appears and I can only close it, I waited a long time but it continues to appear
> 
> ### Steps to Reproduce
> 1. I entered the normal hydra
> 2. I put the name of the game "The Silent Age" in the search bar
> 3. I clicked on the game
> 4. Black screen appears
> 5. I closed Hydra and tested again but the same black screen always appears.
> 
> ### Expected behavior
> I thought it would go normally like other games, there wouldn't be a black screen.
> 
> ### Screenshots
> ![image](https://private-user-images.githubusercontent.com/149306476/365846791-c95cd1dd-f9ac-4e16-99a6-90364dd54880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MjgxNzUsIm5iZiI6MTcyNTkyNzg3NSwicGF0aCI6Ii8xNDkzMDY0NzYvMzY1ODQ2NzkxLWM5NWNkMWRkLWY5YWMtNGUxNi05OWE2LTkwMzY0ZGQ1NDg4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwMDI0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWZkNDljZDcyZmViNGZhM2QyNjRiZTFlYThjZjc5NDdlN2VlZDc1ZDgxOTk5NzM4YmJiYTA0YTgyMjE4NTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.spatWpzKQY7mqzXQNNDZtVQTd2ZAp8CAyJriixHJLhg)
> 
> ![image](https://private-user-images.githubusercontent.com/149306476/365846674-cd389cc3-bd3e-4f92-8c95-1c0214fb2be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MjgxNzUsIm5iZiI6MTcyNTkyNzg3NSwicGF0aCI6Ii8xNDkzMDY0NzYvMzY1ODQ2Njc0LWNkMzg5Y2MzLWJkM2UtNGY5Mi04Yzk1LTFjMDIxNGZiMmJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQwMDI0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTVlMTJlZWY0YjE4YzFlY2Y1MzBiMWI0OTMzOTIxMWVjMjdjMGIwNmMxM2RjZWY5OGU4MGVjNmFlNzNlZjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oCMYSmyd6YCzsjMtQggBKSyig5OIS63S6nsW3xn6XI0)
> 
> ### Operating System
> Windows 10
> 
> ### Hydra Version
> 2.0.3
> 
> ### Additional Information
> _No response_
> 
> ### Before opening this Issue
> * [x]  I have searched the issues of this repository and believe that this is not a duplicate.
> * [x]  I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Fix will be available in next update!

**Comment by LeandroV12** [comment]
There are more games with black screen

**Comment by LeandroV12** [comment]
> Fix will be available in next update!

There are more games with black screen

**Comment by zamitto** [comment]
> > Fix will be available in next update!
> 
> There are more games with black screen
> 

Yes, I'm aware. This bug affects all games that don't have a publisher info on their steam page

**Comment by LeandroV12** [comment]
ah ok 🙂 thx

**Comment by zamitto** [comment]
Fixed in the latest version
