### ISSUE TITLE
[BUG] Download links missing for release 2.0.3

### ISSUE THREAD

**Issue by carlosealves2** [hydralauncher/hydra#944]
### Describe the bug

I attempted to download the latest release (v2.0.3) from the releases page, but there are no assets available for download. The release appears to be published, but no downloadable files (e.g., binaries or source code) are attached.

### Steps to Reproduce

- Download last release
- install
- open

### Expected behavior

The release should include downloadable assets, such as binaries or source code.

### Screenshots

![Captura de tela 2024-09-11 183528](https://github.com/user-attachments/assets/a22f5ad7-4b63-4a2a-9f66-21b95f9d9f43)
![Captura de tela 2024-09-11 183600](https://github.com/user-attachments/assets/f36d76fd-6921-4a4c-b8ea-1aee676ee939)

### Operating System

Edição	Windows 11 Pro Versão	23H2 Instalado em	‎10/‎09/‎2024 Compilação do SO	22631.4169 Experiência	Windows Feature Experience Pack 1000.22700.1034.0

### Hydra Version

v2.0.3 "Leviticus

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by JackEnx** [comment]
you can find information about this here: https://hydra-launcher.gitbook.io/hydra
you need to add download sources to hydra, you can find in closed issues like: https://github.com/hydralauncher/hydra/issues/851,
there more sources in closed issues (all sources is provided by the community)
