### ISSUE TITLE
[REQUEST] Play Time Counter

### ISSUE THREAD

**Issue by hornyalcoholic** [hydralauncher/hydra#947]
### Is your feature request related to a problem? Please describe.

Not necessarily a problem but it would be helpful to have a way to track how long I've played each game in my library. 
Since there’s no way to know how much time I’ve spent on each title, which is a feature I love like on Steam 💯 

### Describe the solution you'd like

I’d love to see a Play Time Counter for each game similar to what Steam offers. 
It could be displayed in the game library or on the game's details page, showing total hours played

### Describe alternatives you've considered

There aren’t many alternatives I can think of, other than manually tracking playtime, but an integrated counter would be much more convenient

### Additional context

I think this feature would add value for users who like tracking their game time and would make the launcher even more user-friendly 👍🏻

**Comment by zamitto** [comment]
I'm not sure if I understood your request. We have a counter in the games page:

![image](https://github.com/user-attachments/assets/8a9f4ba8-24a4-4479-92ab-a40ff1c7c71b)

**Comment by hornyalcoholic** [comment]
> I'm not sure if I understood your request. We have a counter in the games page:
> 
> ![image](https://private-user-images.githubusercontent.com/167933696/366953255-8a9f4ba8-24a4-4479-92ab-a40ff1c7c71b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjI5ODMsIm5iZiI6MTcyNjE2MjY4MywicGF0aCI6Ii8xNjc5MzM2OTYvMzY2OTUzMjU1LThhOWY0YmE4LTI0YTQtNDQ3OS05MmFiLWE0MGZmMWM3YzcxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNzM4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmVlNDk3MWNjZjczNTdiOWM3NDdkZmNjMGFiODMwNjIwOTUwZmE0ZTQwZTg4YjVjOWUwZjgyZTBmZDQzZGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ijC7rawObeW2H0Qc3QXSzu4TlBCPojwhRO_jApYLO3k)

Hm weird, I might not be running the latest version then perhaps? I do not have this for some reason.

**Comment by zamitto** [comment]
You need to set the game executable path so Hydra can track the time that the game is running (you can do it in the Options button on my screenshot)
If you have already done it, could you send a screenshot of your whole Hydra window while running a game?

**Comment by zamitto** [comment]
@hornyalcoholic, any updates? Did it work?

**Comment by hornyalcoholic** [comment]
Yup, this indeed fixed the Issue. Thanks!

**Comment by myCitara** [comment]
There's a way for me to change this time manually? Example, leaving it as if I had played the game for a period of time without having actually played it?
