### ISSUE TITLE
[BUG] sometimes nothing loads up even though i have a connection

### ISSUE THREAD

**Issue by Khalylexe** [hydralauncher/hydra#962]
### Describe the bug

even though I have internet sometimes it doesn't show anything
same with search
also, it is saying "user not found" whenever I click on my profile picture

**Note**: I started doing this after updating it to 2.1.0

**Also note:** Suprise me works as intended just search and home don't work

**another Note**: so sometimes it works as intended but it loads stuff relatively slow

### Steps to Reproduce

1. update the launcher to 2.1.0
2. look for home or search something
3. nothing shows up

### Expected behavior

everything should work normally as before updating

### Screenshots

![image](https://github.com/user-attachments/assets/f6f3bb10-8057-4611-9a42-4bb3e3186621)
![image](https://github.com/user-attachments/assets/e5b47fe7-bea6-47a2-9fd8-6ae7f3e40d42)
![image](https://github.com/user-attachments/assets/0eb0926b-1c4d-4e02-850d-ee2c0fcbd411)

### Operating System

Windows 11

### Hydra Version

2.1.0

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by xjhowxjhow** [comment]
Same here, in my latest log file :
[2024-09-14 19:29:25.749] [error]                   Unhandled rejection SqliteError: table repack has no column named uris

**Comment by joaozx121** [comment]
o meu tmb esta assim

**Comment by zamitto** [comment]
Our server basically died with too many requests. We fixed, should be 100% now

**Comment by zamitto** [comment]
> Same here, in my latest log file : [2024-09-14 19:29:25.749] [error] Unhandled rejection SqliteError: table repack has no column named uris

Does this happens even in 2.1.3?

**Comment by xjhowxjhow** [comment]
> > Same here, in my latest log file : [2024-09-14 19:29:25.749] [error] Unhandled rejection SqliteError: table repack has no column named uris
> 
> Does this happens even in 2.1.3?

It has already been fixed, you can disregard it

**Comment by Aflaujat** [comment]
I'm facing the same problem. Release 3.0.5
