### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joaozx121** [hydralauncher/hydra#963]
### Describe the bug

quando vou pesquisar algum jogo não carrega nada mesmo q eu tenha inserido nome correto do jogo

### Steps to Reproduce

ir em buscar jogos e pesquisar 

### Screenshots

![image](https://github.com/user-attachments/assets/9c8f2416-176a-44df-bafe-f9eaf6d3f5df)

### Operating System

Windows10 

### Hydra Version

2.1.0

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
There was a huge server overload when we launched 2.1.0. We already fixed it
