### ISSUE TITLE
[BUG] Bugged user (Usuario Bugado)

### ISSUE THREAD

**Issue by JoaozimBr2016** [hydralauncher/hydra#964]
### Describe the bug

When I try to change my profile pic and username, it keeps throwing an "user not found" error, even though I'm on the latest version and logged in. In reality, I shouldn't even be complaining since I'm not the one coding this, right? XD 
### Steps to Reproduce

Eu clico no meu nome de usuario e vai la e da o erro 

### Expected behavior

I didn’t want that to show up, lol. 

### Screenshots

Não quero colocar e não acho preciso colocar( I don't want to put it and I don't think I need to put it)

### Operating System

Windows 10

### Hydra Version

2.1.0

### Additional Information

Oh, I forgot to mention this: I downloaded DirectX and Visual C++ to avoid errors, but it’s still not working. 

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Our servers had a huge overload when we released 2.1.0. Already fixed, it is stable and working now
