### ISSUE TITLE
[BUG] Download problem 

### ISSUE THREAD

**Issue by ShankarKSH001** [hydralauncher/hydra#966]
### Describe the bug

Can't download games via streamrip stucks on 0%

### Steps to Reproduce

Can't download games via streamrip stucks on 0%

### Operating System

Windows 

### Hydra Version

2.0.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Is it still an issue in 2.1.4? I can't help with specific download sources you added. Could you test other sources or other downloads

**Comment by JackEnx** [comment]
long time without response, if the problem persists, open the issue again
