### ISSUE TITLE
[REQUEST] please add elamigos as add on 

### ISSUE THREAD

**Issue by Justavinash09** [hydralauncher/hydra#967]
### Is your feature request related to a problem? Please describe.

https://elamigos.site/

### Describe the solution you'd like

https://elamigos.site/

### Describe alternatives you've considered

https://gamepcfull.com/

**Comment by zamitto** [comment]
We don't create or provide any download sources. That's entirely up to the community

**Comment by Justavinash09** [comment]
> We don't create or provide any download sources. That's entirely up to the community



> We don't create or provide any download sources. That's entirely up to the community

ok

**Comment by Justavinash09** [comment]
ok , is there any english  telegram chat for hydra launcher community
