### ISSUE TITLE
[BUG] Import does not work in download sources

### ISSUE THREAD

**Issue by HanzoRev** [hydralauncher/hydra#968]
### Describe the bug

Downloaded Hydra. I see that there are no download sources. I decided to add it. I wrote a link, click Import and nothing happens. Please help me.

### Steps to Reproduce

1) Downloaded
2) Entered the link in the line 
3) clicked check
4) clicked import

### Screenshots

![image](https://github.com/user-attachments/assets/587be952-bde5-4113-9798-95b27af4fc4e)

### Operating System

Windows 10

### Hydra Version

2.1.2

### Before opening this Issue

- [x] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by astral0pitek** [comment]
Same on Windows 11

**Comment by zamitto** [comment]
Could you upload your hydra.db and logs? They are located in "%appdata%/hydra"
We are trying to investigate the issue

**Comment by HanzoRev** [comment]
[Uploading info.txt…]()

**Comment by HanzoRev** [comment]
[info.txt](https://github.com/user-attachments/files/17005954/info.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17005955/pythoninstance.txt)
[error.txt](https://github.com/user-attachments/files/17005956/error.txt)

**Comment by HanzoRev** [comment]
https://drive.google.com/drive/u/0/home

**Comment by HanzoRev** [comment]
hydra.db - https://drive.google.com/file/d/1P-BmisQEasTKqcgd2-X9SGcZo-cNtmdT/view?usp=sharing

**Comment by zamitto** [comment]
Thanks, this for sure helps, will fix and release a new version ASAP

**Comment by HanzoRev** [comment]
okay

**Comment by zamitto** [comment]
@HanzoRev , could you update to 2.1.3? I just released a fix

**Comment by pe4cher** [comment]
@zamitto Now its working!!! :)

**Comment by xjhowxjhow** [comment]
> @HanzoRev , could you update to 2.1.3? I just released a fix

It worked for me, but now I'm getting the user not found error again?

any solution?

**Comment by xjhowxjhow** [comment]
Well, I already found the problem at https://api.hydralauncher.gg, it is available for some endpoints, I will wait, thank you very much

**Comment by L1me3310** [comment]
@zamitto updated to version 2.1.3 and this error has not disappeared

**Comment by zamitto** [comment]
> @zamitto updated to version 2.1.3 and this error has not disappeared

Could you upload your logs?

**Comment by L1me3310** [comment]
> > @zamitto обновлен до версии 2.1.3, и эта ошибка не исчезла
> 
> Не могли бы вы загрузить свои журналы?

there is nothing in the folder where the logs should have been

**Comment by L1me3310** [comment]
> > @zamitto updated to version 2.1.3 and this error has not disappeared
> 
> Could you upload your logs?

there is only hydra.db

**Comment by zamitto** [comment]
That's odd, from the moment Hydra opens it starts logging network requests and some database stuff.
Anyway, does the issue happens for all games? Some games? Games that fail to load the detail page?
What shows on the game options modal?

![image](https://github.com/user-attachments/assets/9b8f0ccd-50a8-4f2f-acd0-0e9c23700fa9)
![image](https://github.com/user-attachments/assets/3faea251-0e3d-4457-b003-39cf38ff1951)
![image](https://github.com/user-attachments/assets/15725240-b90f-40bb-8447-b3e6a566f71c)

**Comment by Steamables** [comment]
> @L1me3310, we found the bug. We'll release a fix as soon as possible

tqsm i also found the same problem today

**Comment by zamitto** [comment]
We've just release 2.1.4 with a fix for this error!

**Comment by pecanela** [comment]
Import button still not working in v2.1.4, no error message, nothing happens. :(

**Comment by zamitto** [comment]
> Import button still not working in v2.1.4, no error message, nothing happens. :(

Add more context about your error, it is not the same problem that was reported in this issue.
If possible, open a new issue, with your logs uploaded, prints or videos so we can trace your error

**Comment by zamitto** [comment]
> > > Кнопка импорта по-прежнему не работает в версии v2.1.4, сообщения об ошибке нет, ничего не происходит. :(
> > 
> > 
> > Добавьте больше контекста о вашей ошибке, это не та проблема, о которой сообщалось в этом выпуске. Если возможно, создайте новый выпуск с загруженными вашими журналами, распечатками или видео, чтобы мы могли отследить вашу ошибку
> 
> 1. The import button in the download source that is not working is discussed here
> 2. The import button still does not work

I need your logs or db to debug this. If this is still happening to you, please, upload your hydra.db. It will help me fix the error

**Comment by Sakamoto4L** [comment]
the same thing is happening to me, I press "import" and nothing happens
![Screenshot_3](https://github.com/user-attachments/assets/f67825a3-be9c-418f-84be-1575cae075d4)

**Comment by Sakamoto4L** [comment]
the same thing is happening to me, I press "import" and nothing happens
![image](https://github.com/user-attachments/assets/a20a2f24-2930-4828-b127-0a2263e47d54)

hydra.db + logs:
https://drive.google.com/file/d/1wjOrISrxtxVv4L6rnQ_EZ5BJZ9Z_nRzE/view?usp=sharing

**Comment by zamitto** [comment]
> the same thing is happening to me, I press "import" and nothing happens
> ![Screenshot_3](https://github.com/user-attachments/assets/f67825a3-be9c-418f-84be-1575cae075d4)
> 

If you could upload your logs and your hydra.db that would be of huge help
They are located at "%appdata%/hydra"

**Comment by zamitto** [comment]
@Sakamoto4L, thank you! 
We will release a fix tomorrow probably. But if you want to fix it right now you can: 
1) close hydra
2) delete your hydra.db, when you 
3) reopen Hydra and your hydra.db you be recreated with the correct structure.

From what I could see. You probably had an old hydra version. And some structure were not correctly migrated from that version to the current one.

**Comment by Sakamoto4L** [comment]
Thank you!

**Comment by zamitto** [comment]
@Sakamoto4L, just released a new version. Could you update and check if everything is working now?

**Comment by Steamables** [comment]
i seem to have fixed the issue!!!!

deleting db files in hydra folder seems to have worked :)

please send me ur thoughts

**Comment by Steamables** [comment]
![image](https://github.com/user-attachments/assets/812c6ad4-ea87-4129-9324-2430d06c48fb)


im fr so hppy acc :) rlly wanted to get a game nd was soo sad when i cldnt big tnx to @zamitto

**Comment by pecanela** [comment]
Thanks guys, the solution was deleting all the archives related to old hydra in "user folder"

**Comment by ZhivovOleg** [comment]
App version 3.2.3
Windows 11
deleted the specified directories, no effect
