### ISSUE TITLE
[BUG]  not visibility download options 

### ISSUE THREAD

**Issue by Maguz0** [hydralauncher/hydra#970]
### Describe the bug

The download options are still not appearing in this new version v2.1.3 "Leviticus" can you fix it?

### Steps to Reproduce

When trying to download a game, the download options do not appear, it only says that it is not available and that is the case with all games.

### Expected behavior

I was hoping that after waiting almost 2 months they could fix this big problem.

### Screenshots

![Hydra 15 sep  2024 12_54_52](https://github.com/user-attachments/assets/ecd7f2ac-83df-4d07-b054-545851efc47d)

### Operating System

windows 10 

### Hydra Version

v2.1.3 leviticus

### Additional Information

bugs option downloader

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by JackEnx** [comment]
this not a bug, you can find information about this here: https://hydra-launcher.gitbook.io/hydra
you need to add download sources to hydra, you can find in closed issues like: #851,
there more sources in closed issues (all sources is provided by the community)

**Comment by mikeydoom** [comment]
I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.

I have all the same sources I added to the previous versions.

**Comment by zamitto** [comment]
> I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.
> 
> I have all the same sources I added to the previous versions.

Could you be more specific with your error?

**Comment by zamitto** [comment]
> I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.
> 
> I have all the same sources I added to the previous versions.

In 2.1.3 we fixed a bug that was probably what was causing your error

**Comment by mikeydoom** [comment]
> > I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.
> > I have all the same sources I added to the previous versions.
> 
> In 2.1.3 we fixed a bug that was probably what was causing your error

I'm using the latest version. Download option is blocked. Even though I have all latest sources.

It worked perfectly fine in previous versions.

**Comment by zamitto** [comment]
> > > I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.
> > > I have all the same sources I added to the previous versions.
> > 
> > In 2.1.3 we fixed a bug that was probably what was causing your error
> 
> I'm using the latest version. Download option is blocked. Even though I have all latest sources.
> 
> It worked perfectly fine in previous versions.

Could you upload your logs?
They are at "%appdata%/hydra"

**Comment by mikeydoom** [comment]
> > > > I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.
> > > > I have all the same sources I added to the previous versions.
> > > 
> > > 
> > > In 2.1.3 we fixed a bug that was probably what was causing your error
> > 
> > 
> > I'm using the latest version. Download option is blocked. Even though I have all latest sources.
> > It worked perfectly fine in previous versions.
> 
> Could you upload your logs? They are at "%appdata%/hydra"

Yes give me a few minutes.

**Comment by mikeydoom** [comment]
> > > > I'm having the same issue on latest version. It worked fine in 2.1.1 and 2.1.2.
> > > > I have all the same sources I added to the previous versions.
> > > 
> > > 
> > > In 2.1.3 we fixed a bug that was probably what was causing your error
> > 
> > 
> > I'm using the latest version. Download option is blocked. Even though I have all latest sources.
> > It worked perfectly fine in previous versions.
> 
> Could you upload your logs? They are at "%appdata%/hydra"

Here's my log

[error.txt](https://github.com/user-attachments/files/17035604/error.txt)

**Comment by zamitto** [comment]
@mikeydoom could you upload all log files?

**Comment by mikeydoom** [comment]
> @mikeydoom could you upload all log files?

I use the portable version, so the other one is just empty.

**Comment by zamitto** [comment]
@mikeydoom, ok, so I'm gonna need your hydra.db, could you upload it?

**Comment by mikeydoom** [comment]
> @mikeydoom, ok, so I'm gonna need your hydra.db, could you upload it?

I deleted it and it fixed my issue.

**Comment by zamitto** [comment]
> > @mikeydoom, ok, so I'm gonna need your hydra.db, could you upload it?
> 
> I deleted it and it fixed my issue.

Oh ok, but it would help me fix without the need to delete it for other users
