### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sharik42** [hydralauncher/hydra#971]
### Describe the bug

The game does not download, although it is available in download sources

### Steps to Reproduce

1. Opening the Launcher Hydra
2. Looking for a game with sources to download
3. I open this game to download
4. I don't understand why I can't do it
(This happened with Hogwarts Legacy, Doom Eternal and other games)

### Expected behavior

A game that indicates that it is in the source should be available for download

### Screenshots

![image](https://github.com/user-attachments/assets/7b5a823c-894b-4060-85f6-fa045b44aa6d)
![image](https://github.com/user-attachments/assets/01781ab2-8afc-461c-9503-d6ec6e6429db)

![image](https://github.com/user-attachments/assets/b28e532a-ffc3-4514-887f-ffe3093a1cf2)
![image](https://github.com/user-attachments/assets/cbb3303c-ae94-4a9c-91cc-993cb640c051)

![image](https://github.com/user-attachments/assets/1ea3f4d2-f6a5-4000-903f-b90f2f90d897)
![image](https://github.com/user-attachments/assets/f4bc4522-7f72-4100-b1b9-4d2fb7928f64)

### Operating System

Windows 10

### Hydra Version

2.1.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Does this happens only for games that show the "Could not retrieve shop details." message?

**Comment by Sharik42** [comment]
Sort of like yes

**Comment by Sharik42** [comment]
Do you need any files to verify?
