### ISSUE TITLE
[BUG] Senha para descompactar jogo

### ISSUE THREAD

**Issue by lucasmoraist** [hydralauncher/hydra#973]
### Describe the bug

Após baixar o jogo quando vou tentar descompactar é pedido um senha.

### Steps to Reproduce

1. Baixar Raft (Versão `Super Raft Boat Together` ou `Raft`)
2. Tentar descompactar arquivo zipado

### Screenshots

![Screenshot 2024-09-15 200520](https://github.com/user-attachments/assets/19758845-da6e-4591-8612-200cc2ff6967)

### Operating System

Windows 10

### Hydra Version

v2.1.3 "Leviticius"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
As stated when you opened your issue, we don't provide any support or help regarding the games you download

**Comment by zamitto** [comment]
If you need further help, I'd advise you to join the discord server managed by the community (https://discord.gg/hydralaunchercommunity)
