### ISSUE TITLE
[BUG] Could not retrieve shop details breaks game downloads

### ISSUE THREAD

**Issue by Ristavor** [hydralauncher/hydra#974]
### Describe the bug

If game cannot retrieve shop details, you cannot download this game

### Steps to Reproduce

Install Hydra
Add community sources
Find a game that cannot retrieve data (regional block, idk) (for example, red dead redemtion 2)
No download button

### Expected behavior

Download button shows on oage

### Screenshots

![image](https://github.com/user-attachments/assets/cdacc52b-7454-4273-bdeb-c880e88896ea)
![image](https://github.com/user-attachments/assets/773a028d-1e6d-4a6b-b4cf-da78cc5591cb)

### Operating System

Windows 11

### Hydra Version

2.13

### Additional Information

This problem mentioned before as fixed, for me it's not

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Games without region block work as expected?

**Comment by Ristavor** [comment]
Yes. VPN fixes problem for region blocked games

**Comment by zamitto** [comment]
Thanks, I'll take a look into it

**Comment by zamitto** [comment]
@Ristavor could you update your log files? 
They are located at "%appdata%/hydra"

**Comment by Ristavor** [comment]
yesterday's files
Today checked Red Dead Redemption. Download button and game description loads. Strange situation
[error.txt](https://git
[info.txt](https://github.com/user-attachments/files/17010494/info.txt)
hub.com/user-attachments/files/17
[pythoninstance.txt](https://github.com/user-attachments/files/17010495/pythoninstance.txt)
010493/error.txt)

**Comment by Ristavor** [comment]
[error.txt](https://github.com/user-attachments/files/17010589/error.txt)
[info.txt](https://github.com/user-attachments/files/17010591/info.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17010594/pythoninstance.txt)
Here are some more logs. Yesterday, I tried to fix the launcher by reinstalling it.

**Comment by zamitto** [comment]
Thanks! We found the bug. We'll release a fix as soon as possible

**Comment by zamitto** [comment]
We've just release 2.1.4 with a fix for this error!

**Comment by Ristavor** [comment]
Very good! Download button appears and works in region blocked games!
