### ISSUE TITLE
[BUG] НЕ РАБОТАЕТ КНОПКА ЗАГРУЗКИ

### ISSUE THREAD

**Issue by VarthVader** [hydralauncher/hydra#978]
### Describe the bug

у меня банально не кликабельная кнопка загрузки.

### Steps to Reproduce

1.нажать на любую игру в библиотеке 2.нажать на кнопку скачать 3.ничего не происходит.

### Expected behavior

при нажатии это кнопки должны появится репаки

### Screenshots

![{2F32480D-469B-4F48-A1E2-11E7F40FECD9}](https://github.com/user-attachments/assets/8a5c8e61-84b6-4167-9845-703762780a97)

### Operating System

Windows 11 Pro

### Hydra Version

v2.1.3 "Leviticus"

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
1) in English, please
2) We are fixing and will soon release a new version
