### ISSUE TITLE
[BUG] Import sources does not work

### ISSUE THREAD

**Issue by esm4534** [hydralauncher/hydra#980]
### Describe the bug

download options are not added

### Steps to Reproduce

1 open hydra normally
2 go to settings
3 go to download sources
4 go to add source
5 insert a link to the download source
6 click validate
7 click import

### Expected behavior

adding a download source

### Operating System

windows 11 pro

### Hydra Version

2.1.3 leviticus

### Before opening this Issue

- [x] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Could you upload your logs? They are located at "%appdata%/hydra"

**Comment by zamitto** [comment]
We'll release a fix probably tomorrow. Meanwhile, if you want to fix it right, you can:
1) Close Hydra
2) Delete hydra.db (located at "%appdata%/hydra"
3) Reopen hydra

**Comment by zamitto** [comment]
@esm4534 just release a new version, could you update and test it?
If the error still happens after updating. Uninstall and reinstall Hydra, it will fix from now
