### ISSUE TITLE
[BUG] jogo para download n é mesmo que está na capa

### ISSUE THREAD

**Issue by joaozx121** [hydralauncher/hydra#983]
### Describe the bug

quando pesquiso pelo jogo the isle aparece mas quando fiz o Download era outro jogo 

### Steps to Reproduce

pesquise pelo jogo the isle e quando fazer o download vai ser um jogo de moto 

### Expected behavior

o download era para ser do the isle mas é de u jogo chamado tt isle of man um jogo de moto

### Screenshots

![image](https://github.com/user-attachments/assets/451b0f20-a337-4bbf-b614-2596eb0d995d)

![image](https://github.com/user-attachments/assets/51cca52e-9357-4a1d-a3e3-1ee5a060a1c8)

### Operating System

Windows10 

### Hydra Version

2.1.4

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
Not exactly a bug, but technical a limitation on how the match between the game name and the download name happens.

**Comment by joaozx121** [comment]
zamitto but is there any way to resolve this?

**Comment by zamitto** [comment]
Unfortunately, no
There is not way to do a 1:1 match with games and downloads.
