### ISSUE TITLE
[BUG] Newly released games not showing up

### ISSUE THREAD

**Issue by archonveins** [hydralauncher/hydra#986]
### Describe the bug

Some titles that were released and already have a repack are not listed on the store
is its a bug or its not added yet to hydra?

### Steps to Reproduce

.

### Operating System

win11

### Hydra Version

2.1.3

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by JackEnx** [comment]
we do not add or manipulate any games, only the library and automatic indexing process of links with the respective game (links are the responsibility of the community and the user himself).

**Comment by mikeydoom** [comment]
Are you using all the sources from https://hydralinks.cloud/ ?

**Comment by JackEnx** [comment]
this problem is not something related to hydra but to external sources
