### ISSUE TITLE
[BUG] downloads option no visualizer 

### ISSUE THREAD

**Issue by Maguz0** [hydralauncher/hydra#992]
### Describe the bug

Even in this version v2.1.5 Hydra still does not show the download options. I have been waiting for at least 3 updates for this to be fixed. This did not happen in version 2.0.2. In that version there were no problems. It was in another language, but it did work. What is happening there?

### Steps to Reproduce

Any game you search for and all say no download options or not available

### Expected behavior

After 5 updates in a row I was hoping that they had already fixed this big problem.

### Additional information and data

![Hydra 18 sep  2024 5_25_29](https://github.com/user-attachments/assets/0a6780ba-4f64-42a2-851a-ba97092a86f7)

### Screenshots

![Hydra 18 sep  2024 5_25_29](https://github.com/user-attachments/assets/504c52e3-90e9-44f4-856c-32003c40e84b)

### Operating System

windows 10 

### Hydra Version

v2.1.5 leviticus

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by Maguz0** [comment]
I have already found a solution to this problem, use the link https://hydralinks.cloud/ and open it with hydra and validate each of those options, it worked for me and I didn't know it was there, sorry for so many pings for help, I didn't know that was there

**Comment by zamitto** [comment]
Not a bug, glad you already got a solution
