### ISSUE TITLE
[REQUEST] solicitar jogos 

### ISSUE THREAD

**Issue by joaozx121** [hydralauncher/hydra#997]
### Is your feature request related to a problem? Please describe.

poder solicitar jogos para ser adicionado nas fontes de download porque tem jogos q eu queria jogar mas n tem em nenhuma fontes de download 

### Describe the solution you'd like

uma aba de votação de jogos para entrar na semana

**Comment by zamitto** [comment]
We have no connection with the download sources or who create them. They are entirely up to the community.

If you are talking about the games that are available in Hydra search. We will update the search list soon
