### ISSUE TITLE
[BUG] Error when adding a source to download from.

### ISSUE THREAD

**Issue by H2Ox39** [hydralauncher/hydra#998]
### Describe the bug

It is not possible to download files from Hydra community links at this time. When me click on "Import", nothing happens.

### Steps to Reproduce

1. I followed the link "https://hydralinks.cloud/"
2. I selected the source I needed and clicked "install on Hydra"
3. It took me to the launcher. I confirmed the source and tried to import.
4. Nothing happened.
5. I got upset.

### Expected behavior

1. I followed the link "https://hydralinks.cloud/"
2. I selected the source code I needed and clicked "install on Hydra"
3. He brought me to the startup program. Confirmed the source code and imported
4. The source has been added.
5. I am joyful

### Additional information and data

C:\Users\H2O\AppData\Local\Programs\Hydra
![Снимок экрана 2024-09-20 223446](https://github.com/user-attachments/assets/8939402c-57ca-4bc0-8ea1-af6f06d026ed)

### Operating System

Windows 10

### Hydra Version

2.1.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by andruw34ka** [comment]
I have exactly the same problem, I thought the fact is that the new version is so raw, but I checked on everyone starting with 2.1.1 and still.

**Comment by zamitto** [comment]
@andruw34ka, @H2Ox39 

Quick fix:
1) Close Hydra
2) Delete hydra.db located at "%appdata%/hydra"
3) Open Hydra again

**Comment by andruw34ka** [comment]
> @andruw34ka, @H2Ox39
> 
> Quick fix:
> 
> 1. Close Hydra
> 2. Delete hydra.db located at "%appdata%/hydra"
> 3. Open Hydra again

IT'S WORK THX

**Comment by Sentooobl** [comment]
> [@andruw34ka](https://github.com/andruw34ka), [@H2Ox39](https://github.com/H2Ox39)
> 
> Быстрое решение:
> 
> 1. Закрыть Гидру
> 2. Удалите файл hydra.db, расположенный по адресу «%appdata%/hydra»
> 3. Снова откройте Гидру

не помогло(

**Comment by Sentooobl** [comment]
VPN не помог, как и удаление папки hydra.db
